# Animaciones JS (classes/scripts/jsvideo) · Hematología. Aplicar con insert_anim.py.
OWN = 'Animación propia'
SV = 'Ilustración: Servier Medical Art, CC BY 4.0 · rótulos y animación propios'
def one(title, src, label, credit, note, say): return {'title': title, 'images': [{'src': src, 'label': label, 'credit': credit}], 'steps': [{'note': note, 'say': say}]}
S = {
    'hem-07': {'title': 'Coombs directo e indirecto',
        'images': [{'src': 'animaciones/hem-07/A1_coombs_directo_real.mp4', 'label': 'Directo', 'credit': SV},
                   {'src': 'animaciones/hem-07/A2_coombs_indirecto_real.mp4', 'label': 'Indirecto', 'credit': SV}],
        'steps': [{'note': 'El anticuerpo ya está pegado al glóbulo',
                   'say': 'En el Coombs directo, la IgG ya está pegada a los glóbulos rojos del paciente. Se agrega el reactivo antiglobulina, que hace de puente entre los glóbulos, y se aglutinan. Es la prueba de la anemia hemolítica autoinmune.'},
                  {'note': 'Anticuerpos libres en el suero',
                   'say': 'En el indirecto, los anticuerpos están libres en el suero del paciente. Se incuban con glóbulos rojos de prueba, se pegan, y el reactivo los aglutina. Es lo que se usa en las pruebas cruzadas y en la embarazada.'}]},
    'hem-10': one('Sin la tijera ADAMTS trece', 'animaciones/hem-10/A1_adamts13_real.mp4', 'PTT', SV, 'Trombos de plaquetas, coagulación normal',
        'La ADAMTS trece corta el factor von Willebrand como una tijera. En el PTT falta, y los multímeros gigantes quedan anclados al endotelio y atrapan plaquetas: se forman microtrombos, caen las plaquetas, y los glóbulos rojos se rompen al pasar, formando esquistocitos. Como no se consumen factores, el TP, el TTPK y el fibrinógeno son normales.'),
    'hem-15': one('Coagula y sangra a la vez', 'animaciones/hem-15/A1_cid_real.mp4', 'CID', SV, 'Se consumen plaquetas y factores',
        'Una sepsis, un trauma o una complicación obstétrica liberan factor tisular, y se forma fibrina en todos los vasos. Esos microtrombos dañan los órganos, y gastan las plaquetas y los factores. Por eso el paciente termina sangrando: plaquetas y fibrinógeno bajos, TP y TTPK prolongados, y dímero D muy alto.'),
    'hem-13': one('El tapón sin malla', 'animaciones/hem-13/A1_hemofilia_tenasa.mp4', 'Hemofilia', SV, 'Solo el TTPK alterado',
        'Normalmente el tapón de plaquetas se refuerza con una malla de fibrina, gracias a la tenasa que forman los factores ocho y nueve. En la hemofilia falta uno de ellos: el tapón se forma, pero no tiene malla y se desarma, y aparecen las hemartrosis. Las plaquetas y el TP son normales; solo se alarga el TTPK.'),
    'hem-22': one('Las células se vacían', 'animaciones/hem-22/A1_lisis_tumoral_real.mp4', 'Lisis tumoral', SV, 'Potasio, fósforo y ácido úrico altos; calcio bajo',
        'Con la quimioterapia, un tumor grande se rompe y vacía su contenido: sube el potasio, que es lo que mata primero, sube el fósforo, que arrastra al calcio hacia abajo, y sube el ácido úrico. Los cristales tapan el riñón. Se previene con hiperhidratación y un hipouricemiante.'),
    'hem-08': one('El disco que se vuelve esfera', 'animaciones/hem-08/A1_esferocitosis_bazo.mp4', 'Esferocitosis', SV, 'Coombs negativo, fragilidad osmótica',
        'En la esferocitosis falla el andamio de la membrana: el glóbulo pierde trozos en cada paso y se vuelve una esfera pequeña y rígida. El bazo la atrapa y la destruye. Es una hemólisis con Coombs negativo, y se confirma con la fragilidad osmótica.'),
    'hem-12': one('Plaquetas marcadas', 'animaciones/hem-12/A1_pti_bazo.mp4', 'PTI', SV, 'El bazo no crece',
        'En la PTI aparecen anticuerpos contra las propias plaquetas. Las plaquetas marcadas pasan por el bazo y los macrófagos se las comen, y además se frena su producción en la médula. El paciente tiene petequias, pero está bien, y el bazo no se palpa.'),
    'hem-16': one('La médula colapsada', 'animaciones/hem-16/A1_blastos_medula.mp4', 'Leucemia aguda', SV, 'Veinte por ciento o más de blastos',
        'En la leucemia aguda, un progenitor se queda detenido y prolifera sin control. Los blastos llenan la médula y desplazan a las células normales: aparece la anemia, la neutropenia con fiebre y la trombocitopenia con sangrado. Se confirma con veinte por ciento o más de blastos.'),
    'hem-18': one('De cadena en cadena', 'animaciones/hem-18/A1_hodgkin_contiguo.mp4', 'Hodgkin', SV, 'Contiguo en el Hodgkin, salteado en el no Hodgkin',
        'El linfoma de Hodgkin avanza ordenado, de una cadena ganglionar a la vecina, partiendo por el cuello. El no Hodgkin, en cambio, se disemina por la sangre, en forma precoz y desordenada, y compromete órganos fuera del ganglio.'),
    'hem-20': one('El receptor que no se apaga', 'animaciones/hem-20/A1_jak2_receptor.mp4', 'JAK dos', SV, 'Eritropoyetina suprimida',
        'Normalmente el receptor solo envía señal cuando llega la eritropoyetina. Con la mutación de JAK dos queda encendido siempre, y los glóbulos rojos se fabrican sin control. El riñón deja de fabricar eritropoyetina. La misma familia incluye la trombocitemia esencial y la mielofibrosis.'),
    'hem-04': one('El hierro encerrado', 'animaciones/hem-04/A1_hepcidina_ferroportina.mp4', 'Hepcidina', SV, 'Ferritina alta, hierro bajo',
        'Con la inflamación, el hígado fabrica hepcidina, que destruye la ferroportina, la única puerta de salida del hierro. El hierro queda encerrado en los macrófagos: la ferritina sube, pero el hierro de la sangre baja. Por eso darle hierro a ciegas no sirve.'),
    'hem-02': one('Ferritina y transferrina se cruzan', 'animaciones/hem-02/A1_ferritina_transferrina.mp4', 'Perfil de hierro', OWN, 'Al revés en la ferropenia y en la inflamación',
        'La ferritina refleja los depósitos y la transferrina son los camiones. En la ferropenia, la ferritina baja y la transferrina sube. En la inflamación es al revés: la ferritina sube y la transferrina baja.'),
    'hem-24': one('Quién recibe de quién', 'animaciones/hem-24/A1_compatibilidad_abo.mp4', 'ABO', OWN, 'O da a todos; AB recibe de todos',
        'Lo que destruye los glóbulos transfundidos son los anticuerpos del receptor. Los glóbulos grupo O no tienen antígenos A ni B, así que nadie los ataca. El grupo AB no tiene anticuerpos, así que recibe de cualquier grupo.'),
    'hem-21': one('La hora de oro', 'animaciones/hem-21/A1_neutropenia_hora_oro.mp4', 'Neutropenia febril', OWN, 'Antibiótico antes de sesenta minutos',
        'Los neutrófilos caen al mínimo entre el día siete y el catorce. Con menos de quinientos y fiebre, la primera dosis de antibiótico endovenoso, como el cefepime, va antes de sesenta minutos, sin esperar el foco.'),
    'hem-23': one('El balance se inclina', 'animaciones/hem-23/A1_balance_trombofilia.mp4', 'Trombofilias', OWN, 'Más acelerador o menos freno',
        'Una trombofilia inclina el balance hacia la coagulación. Puede sumar acelerador, como el factor cinco Leiden, la más frecuente, o la mutación de la protrombina. O puede quitar freno: el déficit de antitrombina, de proteína C o de proteína S, más raros y más trombogénicos.'),
    'hem-01': one('¿La médula responde?', 'animaciones/hem-01/A1_reticulocitos.mp4', 'Reticulocitos', OWN, 'Altos: se pierde afuera; bajos: falla la fábrica',
        'Si los reticulocitos están altos, la médula fabrica y la sangre se pierde afuera: hemólisis o sangrado. Si están bajos, el problema es la fábrica: falta hierro, vitamina B doce o folato, la médula está enferma o falta eritropoyetina. Y el porcentaje se corrige antes de interpretarlo.'),
}
