// Clase 1.5 — guion docente escrito a mano (ver gastro-01.cjs para el formato).
// Fuente clínica: books/scripts/dataset_endocrinologia.cjs (endo-05).

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  id: 'endo-05',
  tier: 2,
  slides: [
    {
      type: 'cover',
      subtitle: 'Duele o no duele, capta o no capta: así se separan las tiroiditis',
      say: 'Bienvenidos. Hoy vemos las tiroiditis: De Quervain, Hashimoto, la silente y postparto, y las que producen la amiodarona y el litio. Es un tema de preguntas trampa, porque todas pueden dar hormonas altas y el alumno cae en el tiamazol. Vamos a ordenar todo con dos preguntas: ¿duele la tiroides?, y ¿capta yodo? Partamos.',
    },

    {
      type: 'flow',
      kicker: 'Mecanismo',
      title: 'De Quervain: una tiroides que se rompe',
      nodes: [
        { id: 'vir', col: 0, row: 1, k: 'cause', t: 'Infección respiratoria alta', s: '1 a 3 semanas antes' },
        { id: 'inf', col: 1, row: 1, k: 'mech', t: 'Inflamación granulomatosa', s: 'Post-viral, autolimitada' },
        { id: 'dol', col: 2, row: 0, k: 'effect', t: 'Dolor cervical intenso', s: 'Irradia a mandíbula y oídos' },
        { id: 'lis', col: 2, row: 2, k: 'mech', t: 'Lisis de los folículos', s: 'Se libera hormona ya fabricada' },
        { id: 'tox', col: 3, row: 2, k: 'effect', t: 'Tirotoxicosis transitoria', s: 'TSH baja, T4L alta' },
        { id: 'cap', col: 3, row: 1, k: 'alert', t: 'Captación casi nula', s: 'Tiroides "en blanco"' },
        { id: 'tra', col: 4, row: 2, k: 'trap', t: 'Tiamazol', s: 'No sirve: no hay síntesis' },
      ],
      edges: [
        { from: 'vir', to: 'inf' },
        { from: 'inf', to: 'dol' },
        { from: 'inf', to: 'lis' },
        { from: 'lis', to: 'tox' },
        { from: 'lis', to: 'cap', label: 'no capta' },
        { from: 'tox', to: 'tra', label: 'nunca' },
      ],
      steps: [
        { show: ['vir'], note: 'El antecedente que el enunciado siempre trae',
          say: 'Empecemos por la tiroiditis subaguda de De Quervain, la más preguntada. Es un cuadro post-viral: el enunciado casi siempre te cuenta que una a tres semanas antes el paciente tuvo un resfrío o una infección de la vía aérea alta. Es más frecuente en mujeres de treinta a cincuenta años.' },
        { show: ['inf'], note: 'Inflamación que se apaga sola',
          say: 'Después de ese virus, la tiroides se inflama. Es una inflamación granulomatosa y, lo importante, autolimitada: se apaga sola.' },
        { show: ['dol'], note: 'La única tiroiditis con dolor intenso',
          say: 'Esa inflamación duele, y mucho. Dolor cervical anterior intenso que se irradia a los ángulos de la mandíbula, a los oídos o a la nuca, con una tiroides aumentada, caliente y exquisitamente dolorosa al tacto, más fiebre o febrícula. Es la causa más común de tiroides dolorosa.' },
        { show: ['lis'], note: 'La glándula no fabrica más: se vacía',
          say: 'Ahora, el punto clave. La inflamación rompe los folículos, y la hormona que estaba guardada en el coloide sale de golpe a la sangre. La glándula no está fabricando más hormona; se está vaciando.' },
        { show: ['tox'], note: 'Tirotoxicosis, no hipertiroidismo verdadero',
          say: 'Por eso el paciente tiene palpitaciones y temblor, con TSH baja y T cuatro libre alta. Pero fíjate en el nombre: es una tirotoxicosis destructiva, no un hipertiroidismo verdadero.' },
        { show: ['cap'], note: 'Folículos rotos no captan yodo',
          say: 'Y como los folículos están rotos, no pueden captar yodo. El cintigrama muestra una captación casi nula, menor al uno o dos por ciento: la tiroides en blanco. Eso la separa con certeza de la enfermedad de Graves, donde la captación está aumentada.' },
        { show: ['tra'], note: 'Si no hay síntesis, no hay nada que bloquear',
          say: 'Y de aquí sale la trampa más clásica. El tiamazol bloquea la síntesis de hormona, pero aquí no hay síntesis: hay fuga. Los antitiroideos no sirven en ninguna tiroiditis destructiva.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Diagnóstico y tratamiento',
      title: 'De Quervain: cómo se confirma y cómo se trata',
      cards: [
        { title: 'Laboratorio', tag: 'Lo que la confirma', kind: 'criteria', items: [
          { t: 'VHS muy elevada', d: 'Sobre 60 a 100 mm/h, con PCR alta',
            say: 'Para confirmarla, el marcador cardinal es la velocidad de sedimentación, que está muy elevada, sobre sesenta a cien milímetros por hora, junto a una PCR alta. Dolor tiroideo más VHS muy alta: piensa en De Quervain.' },
          { t: 'Captación de yodo casi nula', d: 'Menos de 1 a 2 % a las 24 horas',
            say: 'Y la captación de yodo radiactivo casi nula a las veinticuatro horas. Con dolor, VHS alta y captación en blanco, el diagnóstico está hecho.' },
        ] },
        { title: 'Tratamiento', tag: 'Antiinflamatorio', kind: 'pharma', items: [
          { t: 'AINE: primera línea', d: 'Ibuprofeno o naproxeno en casos leves a moderados',
            say: 'El tratamiento ataca la inflamación, no la hormona. La primera línea son los antiinflamatorios no esteroidales, como ibuprofeno o naproxeno, en los casos leves a moderados.' },
          { t: 'Prednisona si es refractario', d: '30 a 40 mg/día, reducir en 4 a 6 semanas',
            say: 'Si el dolor es muy intenso o no cede con AINE, se pasa a prednisona oral, treinta a cuarenta miligramos al día, con reducción progresiva en cuatro a seis semanas. Ojo: la prednisona es el segundo escalón, no el primero.' },
          { t: 'Propranolol para los síntomas', d: 'Palpitaciones y temblor de la fase tóxica',
            say: 'Y si hay palpitaciones o temblor, se agrega propranolol. Pero el betabloqueo solo alivia síntomas; lo que trata la enfermedad es el antiinflamatorio.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Evolución',
      title: 'Las tres fases de una tiroiditis destructiva',
      nodes: [
        { id: 'f1', col: 0, row: 1, k: 'risk', t: 'Fase tirotóxica', s: 'Semanas 1 a 6 · TSH baja, T4L alta' },
        { id: 'f2', col: 2, row: 1, k: 'alert', t: 'Fase hipotiroidea', s: 'Semanas 6 a 16 · TSH alta, T4L baja' },
        { id: 'f3', col: 4, row: 1, k: 'good', t: 'Recuperación', s: 'Meses 4 a 6 · eutiroidismo en más del 90 %' },
        { id: 'pro', col: 0, row: 3, k: 'good', t: 'Propranolol', s: 'Solo síntomas' },
        { id: 'lt4', col: 2, row: 3, k: 'good', t: 'Levotiroxina transitoria', s: 'Si hay síntomas' },
      ],
      edges: [
        { from: 'f1', to: 'f2', label: 'se agota la reserva' },
        { from: 'f2', to: 'f3', label: 'se regeneran los folículos' },
        { from: 'f1', to: 'pro' },
        { from: 'f2', to: 'lt4' },
      ],
      steps: [
        { show: ['f1'], note: 'Válido para De Quervain y para la silente o postparto',
          say: 'Este patrón vale para De Quervain y también para la tiroiditis silente y la postparto. Primera fase, tirotóxica: durante las primeras seis semanas, los folículos rotos liberan su hormona y la TSH cae.' },
        { show: ['pro'], note: 'Se trata el síntoma, no la glándula',
          say: 'En esta fase se usa propranolol para los síntomas adrenérgicos, y nada más para la hormona.' },
        { show: ['f2'], note: 'La reserva se vació antes de regenerarse',
          say: 'Segunda fase, hipotiroidea: entre la semana seis y la dieciséis. La glándula ya vació su reserva y todavía no se regenera, así que ahora la TSH sube y la T cuatro libre baja. Es el mismo paciente, con el perfil al revés.' },
        { show: ['lt4'], note: 'Transitoria, no de por vida',
          say: 'Si hay síntomas, puede requerir levotiroxina, pero transitoria.' },
        { show: ['f3'], note: 'La gran mayoría vuelve a lo normal',
          say: 'Tercera fase, recuperación: entre el cuarto y el sexto mes, en más del noventa por ciento de los pacientes la tiroides se repara y la función vuelve a la normalidad. Por eso un examen tiroideo alterado en una tiroiditis se interpreta según la fase en que lo tomaste.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Tiroiditis indoloras',
      title: 'Hashimoto, silente y la que supura',
      cards: [
        { title: 'Hashimoto', tag: 'Crónica autoinmune', kind: 'key', items: [
          { t: 'Indolora, bocio firme y elástico', d: 'VHS normal',
            say: 'Pasemos a las tiroiditis que no duelen. La primera es Hashimoto, la tiroiditis crónica autoinmune: bocio firme y elástico, indoloro, con VHS normal.' },
          { t: 'Anti-TPO positivos en más del 90 %', d: 'Levotiroxina de por vida según TSH (GES)',
            say: 'Los anticuerpos antiperoxidasa son positivos en más del noventa por ciento. Y a diferencia de las destructivas, aquí el problema es permanente: se trata con levotiroxina de por vida, guiada por la TSH, con cobertura GES.' },
        ] },
        { title: 'Silente o postparto', tag: 'Destructiva sin dolor', kind: 'normal', items: [
          { t: 'Totalmente indolora', d: 'Anti-TPO positivos en 50 a 70 %',
            say: 'La silente y la postparto se parecen a De Quervain en su evolución de tres fases, pero sin dolor y sin VHS muy alta. Los antiperoxidasa son positivos en la mitad a dos tercios de los casos.' },
          { t: 'Captación casi nula en la fase tóxica', d: 'Propranolol; levotiroxina transitoria si hay hipotiroidismo',
            say: 'En la fase tirotóxica la captación también es casi nula, porque también es destructiva. Se maneja con propranolol, y con levotiroxina transitoria si cae en hipotiroidismo.' },
        ] },
        { title: 'Infecciosa supurada', tag: 'La excepción', kind: 'alert', items: [
          { t: 'Eritema, calor y fluctuación', d: 'Leucocitosis; captación normal con defecto focal',
            say: 'Y ojo con la excepción: la tiroiditis infecciosa supurada también duele, pero es un absceso. Hay eritema, calor local, fluctuación y leucocitosis, y la captación es normal con un defecto focal.' },
          { t: 'Drenaje + antibióticos EV', d: 'No es De Quervain',
            say: 'Esa no se trata con antiinflamatorios: requiere drenaje quirúrgico y antibióticos endovenosos.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Fármacos',
      title: 'Amiodarona: exceso de yodo, dos tirotoxicosis distintas',
      nodes: [
        { id: 'ami', col: 0, row: 2, k: 'cause', t: 'Amiodarona', s: '200 mg aportan 75 mg de yodo' },
        { id: 'hip', col: 1, row: 0, k: 'effect', t: 'Hipotiroidismo', s: 'Wolff-Chaikoff sin escape' },
        { id: 'q', col: 1, row: 2, k: 'q', t: '¿Tiroides previa?', s: 'Bocio o Graves latente vs normal' },
        { id: 't1', col: 2, row: 1, k: 'risk', t: 'Tipo 1: Jod-Basedow', s: 'Doppler hipervascular, capta' },
        { id: 't1x', col: 3, row: 1, k: 'good', t: 'Tiamazol a dosis altas', s: 'Hay síntesis que bloquear' },
        { id: 't2', col: 2, row: 3, k: 'risk', t: 'Tipo 2: destructiva', s: 'Doppler avascular, captación nula' },
        { id: 't2x', col: 3, row: 3, k: 'good', t: 'Prednisona 40 mg/día', s: 'Como toda destructiva' },
      ],
      edges: [
        { from: 'ami', to: 'hip' },
        { from: 'ami', to: 'q', label: 'tirotoxicosis' },
        { from: 'q', to: 't1', label: 'bocio previo' },
        { from: 'q', to: 't2', label: 'tiroides normal' },
        { from: 't1', to: 't1x' },
        { from: 't2', to: 't2x' },
      ],
      steps: [
        { show: ['ami'], note: 'Cien veces el requerimiento diario de yodo',
          say: 'Ahora los fármacos. La amiodarona es un antiarrítmico cargado de yodo: cada comprimido de doscientos miligramos aporta setenta y cinco miligramos de yodo, cien veces lo que necesitamos al día. Con esa carga, la tiroides puede fallar hacia cualquiera de los dos lados.' },
        { show: ['hip'], note: 'La glándula se frena y no logra escapar',
          say: 'Hacia abajo: el exceso de yodo frena la glándula, el efecto Wolff-Chaikoff, y si la tiroides no logra escapar de ese freno, el paciente queda hipotiroideo.' },
        { show: ['q'], note: 'Lo que decide el tipo es la glándula de base',
          say: 'Hacia arriba, puede dar tirotoxicosis, y aquí viene la diferencia que se pregunta. Hay dos tipos, y lo que los separa es cómo estaba la tiroides antes.' },
        { show: ['t1', 't1x'], note: 'Tipo 1: el yodo es combustible',
          say: 'Tipo uno, o Jod-Basedow: el paciente ya tenía un bocio multinodular o un Graves latente, y el yodo le sirve de combustible para fabricar más hormona. Por eso el Doppler está hipervascular y la captación es detectable. Si hay síntesis, se bloquea: tiamazol a dosis altas.' },
        { show: ['t2', 't2x'], note: 'Tipo 2: igual que De Quervain, se trata con corticoide',
          say: 'Tipo dos: tiroides previamente normal, y la amiodarona la destruye directamente. Es una tiroiditis destructiva, con Doppler avascular y captación nula. Y como en toda destructiva, el antitiroideo no sirve: se trata con corticoides, prednisona cuarenta miligramos al día.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Fármacos',
      title: 'Litio: bocio e hipotiroidismo',
      cards: [
        { title: 'Mecanismo', tag: 'Frena la liberación', kind: 'key', items: [
          { t: 'Inhibe la salida de T3 y T4', d: 'Bloquea la proteólisis del coloide',
            say: 'El litio actúa distinto: impide que la hormona salga del coloide folicular. La tiroides la fabrica, pero no la puede liberar.' },
          { t: 'Bocio e hipotiroidismo en 20 a 30 %', d: 'Subclínico o clínico, en uso crónico',
            say: 'El resultado es bocio e hipotiroidismo, subclínico o clínico, en el veinte a treinta por ciento de los pacientes que lo usan en forma crónica.' },
        ] },
        { title: 'Conducta', tag: 'Se pregunta', kind: 'pharma', items: [
          { t: 'No suspender el litio', d: 'Es un estabilizador muy eficaz',
            say: 'Y la conducta es la que el examen busca: no se suspende el litio. Es un estabilizador del ánimo muy eficaz, y el problema tiroideo se maneja fácil.' },
          { t: 'Agregar levotiroxina', d: 'Hasta normalizar la TSH',
            say: 'Se mantiene el litio y se agrega levotiroxina hasta normalizar la TSH. Cambiar el litio por otro fármaco es el distractor clásico.' },
        ] },
      ],
    },

    {
      type: 'pathway',
      intro: 'Juntemos todo en un árbol de decisión, con las dos preguntas de la clase: si duele, y si capta.',
    },

    {
      type: 'table',
      kicker: 'Trampas EUNACOM',
      title: 'Cada tiroiditis con su pista y su tratamiento',
      head: ['Tiroiditis', 'Pista clave', 'Tratamiento'],
      rows: [
        { cells: ['De Quervain', 'Dolor irradiado + VHS > 60 + captación < 1 %', 'AINE; prednisona si es refractaria + propranolol'],
          say: 'Repasemos. De Quervain: dolor irradiado, VHS muy alta y captación en blanco. AINE, prednisona si no cede, y propranolol para los síntomas.' },
        { cells: ['Hashimoto', 'Bocio indoloro + anti-TPO alto', 'Levotiroxina de por vida según TSH'],
          say: 'Hashimoto: bocio indoloro y antiperoxidasa muy positivos. Levotiroxina de por vida según la TSH.' },
        { cells: ['Silente o postparto', 'Indolora + tres fases', 'Propranolol; levotiroxina transitoria'],
          say: 'Silente o postparto: indolora, con las mismas tres fases. Propranolol y, si hace falta, levotiroxina transitoria.' },
        { cells: ['Amiodarona tipo 1', 'Bocio previo + Doppler vascular', 'Tiamazol a dosis altas'],
          say: 'Amiodarona tipo uno: bocio previo y Doppler vascular. Tiamazol a dosis altas.' },
        { cells: ['Amiodarona tipo 2', 'Tiroides normal + captación nula', 'Prednisona 40 mg/día'],
          say: 'Amiodarona tipo dos: tiroides normal, destrucción y captación nula. Prednisona. Confundir estos dos tipos es el error más frecuente.' },
        { cells: ['Litio', 'Bocio + TSH alta', 'Mantener litio + levotiroxina'],
          say: 'Litio: bocio con TSH alta. Se mantiene el litio y se agrega levotiroxina.' },
        { cells: ['Supurada aguda', 'Eritema, fluctuación, leucocitosis', 'Drenaje + antibióticos EV'],
          say: 'Y la supurada: eritema, fluctuación y leucocitosis. Drenaje y antibióticos endovenosos.' },
      ],
    },

    {
      type: 'quiz',
      kicker: 'Caso clínico',
      title: 'Caso clínico',
      stem: 'Hombre de 68 años con fibrilación auricular, usuario de amiodarona hace 2 años, sin bocio ni enfermedad tiroidea previa. Consulta por palpitaciones y baja de 4 kg. TSH 0,02 mUI/L, T4 libre 2,8 ng/dL. Eco-Doppler: tiroides de tamaño normal, sin vascularización. Captación de yodo nula.',
      question: '¿Cuál es el tratamiento de elección?',
      options: [
        { letter: 'A', text: 'Tiamazol a dosis altas' },
        { letter: 'B', text: 'Prednisona 40 mg al día' },
        { letter: 'C', text: 'Radioyodo en dosis terapéutica' },
        { letter: 'D', text: 'Levotiroxina 50 µg al día' },
        { letter: 'E', text: 'Tiroidectomía total de urgencia' },
      ],
      correct: 'B',
      explanation: 'Tiroides previamente normal, Doppler avascular y captación nula: tirotoxicosis por amiodarona tipo 2, una tiroiditis destructiva. Se trata con corticoides (prednisona 40 mg/día). El tiamazol a dosis altas es el tratamiento del tipo 1 (Jod-Basedow, con bocio previo y glándula hipervascular).',
      say: {
        stem: 'Vamos a un caso. Hombre de sesenta y ocho años con fibrilación auricular, que usa amiodarona hace dos años, sin bocio ni enfermedad tiroidea previa. Consulta por palpitaciones y baja de cuatro kilos. Tiene la TSH suprimida y la T cuatro libre alta. El Doppler muestra una tiroides de tamaño normal y sin vascularización, y la captación de yodo es nula.',
        question: '¿Cuál es el tratamiento de elección?',
        options: 'Las alternativas: tiamazol a dosis altas, prednisona, radioyodo, levotiroxina, o tiroidectomía de urgencia. Piénsalo.',
        answer: 'Es la B, prednisona. Busca las dos pistas: la tiroides era normal, y ahora está avascular y no capta. Eso es destrucción, la amiodarona tipo dos, y la destrucción se trata con corticoides. El distractor tentador es el tiamazol a dosis altas, que es correcto en el tipo uno, cuando hay bocio previo y la glándula está fabricando hormona. Aquí no hay nada que bloquear. Y el radioyodo no tiene sentido en una glándula que no capta.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2019 · Pregunta 30',
      stem: 'Una paciente de 23 años, consulta por malestar general y sensación febril de una semana de evolución, asociado a artralgias y palpitaciones. Al examen físico destaca glándula tiroides del doble del tamaño normal, muy dolorosa a la palpación, frecuencia cardiaca de 90 latidos por minuto y presión arterial de 120/80 mm Hg. Se solicitan exámenes que muestran TSH: 0,01 UI/L (valor normal: 0,3-4,5 UI/L), T4L: 1,9 ng/mL (valor normal: 0,6-1,7 ng/mL), captación de yodo radioactivo de 2% (valor normal: 20% a 30%).',
      question: '¿Cuál es el tratamiento de elección en esta paciente?',
      options: [
        { letter: 'A', text: 'Tiamazol' },
        { letter: 'B', text: 'AINEs' },
        { letter: 'C', text: 'Propiltiouracilo' },
        { letter: 'D', text: 'Bloqueadores beta' },
        { letter: 'E', text: 'Yodo radioactivo en dosis terapéutica' },
      ],
      correct: 'B',
      explanation: 'Tiroides dolorosa, febrícula, tirotoxicosis y captación del 2 %: tiroiditis subaguda de De Quervain. Se trata con AINE. Los antitiroideos no sirven y el radioyodo no capta. El betabloqueo alivia los síntomas, pero no es el tratamiento de la enfermedad.',
      say: {
        stem: 'Ahora preguntas reales. La primera es del EUNACOM de diciembre de dos mil diecinueve. Mujer de veintitrés años con una semana de malestar, sensación febril, artralgias y palpitaciones. La tiroides está del doble de su tamaño y muy dolorosa. TSH suprimida, T cuatro libre alta, y una captación de yodo de apenas dos por ciento.',
        question: '¿Cuál es el tratamiento de elección?',
        options: 'Las opciones: tiamazol, antiinflamatorios no esteroidales, propiltiouracilo, betabloqueadores, o radioyodo. Piénsalo.',
        answer: 'Es la B, los AINE. Dolor tiroideo, fiebre y captación casi nula: De Quervain. El tiamazol y el propiltiouracilo no sirven, porque no hay síntesis que bloquear, y el radioyodo no tiene dónde entrar. El distractor más fino es el betabloqueador: sí se usa, pero solo para los síntomas. El tratamiento de la enfermedad es el antiinflamatorio.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2017 · Pregunta 10',
      stem: 'Una paciente de 33 años, consulta por dolor cervical intenso de una semana de evolución asociado a sensación febril. Al examen físico destaca glándula tiroides del doble del tamaño normal, muy dolorosa a la palpación, frecuencia cardiaca de 90 latidos por minuto y presión arterial de 120/80 mm Hg. Se solicitan exámenes que muestran TSH: 0,2 UI/L, T4L: 1,9 ng/mL (Valor normal: 0,6-1,7 ng/mL), captación de yodo radioactivo de 2% (Valor normal: mayor a 3%).',
      question: '¿Cuál es el tratamiento de elección en esta paciente?',
      options: [
        { letter: 'A', text: 'Propiltiouracilo' },
        { letter: 'B', text: 'Ibuprofeno' },
        { letter: 'C', text: 'Prednisona' },
        { letter: 'D', text: 'Levotiroxina' },
        { letter: 'E', text: 'Yodo radioactivo' },
      ],
      correct: 'B',
      explanation: 'Tiroiditis subaguda de De Quervain: la primera línea es un AINE como el ibuprofeno. La prednisona se reserva para el dolor muy intenso o refractario a AINE. No se usan antitiroideos ni radioyodo.',
      say: {
        stem: 'La siguiente es del EUNACOM de julio de dos mil diecisiete. Mujer de treinta y tres años con una semana de dolor cervical intenso y sensación febril. Tiroides del doble del tamaño normal, muy dolorosa. TSH baja, T cuatro libre alta, y captación de yodo de dos por ciento.',
        question: '¿Cuál es el tratamiento de elección?',
        options: 'Las opciones: propiltiouracilo, ibuprofeno, prednisona, levotiroxina, o yodo radiactivo. Piénsalo.',
        answer: 'Es la B, ibuprofeno. Es el mismo De Quervain de la pregunta anterior, pero ahora el distractor es la prednisona. Y aquí está la regla: el corticoide es el segundo escalón, para el dolor muy intenso o que no responde. De entrada, AINE. Esta pregunta se repite casi igual, así que el orden de los escalones vale puntos.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2013 · Pregunta 114',
      stem: 'Una paciente de 30 años, usuaria de anticonceptivos orales, consulta por cuadro de 8 días de sudoración, palpitaciones e insomnio, que durante los últimos días se ha asociado a dolor en región cervical anterior. Al examen físico se aprecia con frecuencia cardiaca de 100 por minuto, presión arterial 140/90, dolor a la palpación cervical. Se solicitan exámenes donde destaca T4 y T4L aumentadas y TSH suprimida, electrocardiograma normal.',
      question: 'El tratamiento de elección en este caso es:',
      options: [
        { letter: 'A', text: 'Propiltiouracilo' },
        { letter: 'B', text: 'Paracetamol' },
        { letter: 'C', text: 'Metimazol' },
        { letter: 'D', text: 'Ketoprofeno' },
        { letter: 'E', text: 'Enalapril' },
      ],
      correct: 'D',
      explanation: 'Tirotoxicosis con dolor cervical anterior: tiroiditis subaguda de De Quervain. Se trata con un AINE (ketoprofeno). El paracetamol no tiene efecto antiinflamatorio suficiente y los antitiroideos no están indicados.',
      say: {
        stem: 'Una más, del EUNACOM de julio de dos mil trece. Mujer de treinta años, usuaria de anticonceptivos, con ocho días de sudoración, palpitaciones e insomnio, y en los últimos días dolor cervical anterior. Taquicárdica, con dolor a la palpación del cuello, T cuatro libre alta y TSH suprimida.',
        question: '¿Cuál es el tratamiento de elección?',
        options: 'Las opciones: propiltiouracilo, paracetamol, metimazol, ketoprofeno, o enalapril. Piénsalo.',
        answer: 'Es la D, ketoprofeno, porque es un AINE. Tirotoxicosis más dolor cervical es De Quervain hasta que se demuestre lo contrario. Fíjate en el distractor nuevo: el paracetamol. Quita el dolor, pero no desinflama, y lo que se trata aquí es la inflamación. Y el metimazol, que es el mismo tiamazol, y el propiltiouracilo, otra vez no sirven.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2024 · Pregunta 115',
      stem: 'Una paciente usuaria de anticonceptivos y con antecedentes familiares de hipotiroidismo, consulta por aumento de volumen en el cuello. Al examen físico, la tiroides se palpa aumentada de tamaño, sin nódulos. Los exámenes revelan una TSH: 2,0 UI/L, T4: 14,0 ug/dl (valor normal: 4,5 a 9,5), anticuerpos antitiroglobulina: 48 UI/ml (valor normal: <35) y anticuerpos antiperoxidasa tiroidea: 320 UI/ml (valor normal: <35).',
      question: '¿Cuál es la conducta más adecuada?',
      options: [
        { letter: 'A', text: 'Solicitar T4 libre' },
        { letter: 'B', text: 'Solicitar ecografía tiroidea' },
        { letter: 'C', text: 'Solicitar una cintigrafía tiroidea' },
        { letter: 'D', text: 'Realizar control de TSH y T4 en un año' },
        { letter: 'E', text: 'Realizar biopsia tiroidea por punción' },
      ],
      correct: 'D',
      explanation: 'Bocio difuso con antiperoxidasa muy elevados y TSH normal: tiroiditis de Hashimoto eutiroidea. La T4 total alta se explica por los anticonceptivos, que elevan la proteína transportadora; la TSH normal descarta hipertiroidismo. Se controla la función tiroidea en forma anual para pesquisar el hipotiroidismo.',
      say: {
        stem: 'Y la última, del EUNACOM de julio de dos mil veinticuatro, que nos lleva a Hashimoto. Mujer usuaria de anticonceptivos, con familiares hipotiroideos, que consulta por aumento de volumen del cuello. Tiroides aumentada, sin nódulos. TSH normal, una T cuatro total alta, y anticuerpos antitiroglobulina y antiperoxidasa elevados, estos últimos muy altos.',
        question: '¿Cuál es la conducta más adecuada?',
        options: 'Las opciones: pedir T cuatro libre, ecografía tiroidea, cintigrafía, control de TSH y T cuatro en un año, o punción tiroidea. Piénsalo.',
        answer: 'Es la D, control anual. Bocio indoloro con antiperoxidasa muy altos es Hashimoto, y con TSH normal está eutiroidea, así que hoy no hay nada que tratar: se controla para pescar a tiempo el hipotiroidismo. ¿Y la T cuatro total alta? Es la trampa: los anticonceptivos suben la proteína que transporta la hormona, y la total sube sin que el paciente esté hipertiroideo. La TSH normal manda.',
      },
    },

    {
      type: 'points',
      kicker: 'Cierre',
      title: 'Reglas de oro para el examen',
      cards: [
        { title: 'Diagnóstico', tag: 'Dolor y captación', kind: 'key', items: [
          { t: 'Dolor + VHS alta + captación nula', d: 'De Quervain',
            say: 'Cerremos con las reglas de oro. Tiroides dolorosa, VHS muy alta y captación en blanco: De Quervain.' },
          { t: 'Captación nula = destrucción', d: 'Captación alta = Graves',
            say: 'La captación separa la destrucción del hipertiroidismo verdadero. Nula en las tiroiditis, alta en Graves, que es justamente la próxima clase.' },
        ] },
        { title: 'Tratamiento', tag: 'Según el mecanismo', kind: 'pharma', items: [
          { t: 'De Quervain: AINE primero', d: 'Prednisona si es refractaria',
            say: 'De Quervain se trata con AINE, y prednisona solo si no responde.' },
          { t: 'Nunca tiamazol en una destructiva', d: 'Salvo amiodarona tipo 1',
            say: 'Nunca antitiroideos en una tiroiditis destructiva. La única de este grupo que lleva tiamazol es la amiodarona tipo uno.' },
        ] },
        { title: 'Fármacos', tag: 'Se pregunta', kind: 'alert', items: [
          { t: 'Amiodarona 1 tiamazol, 2 corticoide', d: 'Lo decide la tiroides previa',
            say: 'Amiodarona: tipo uno, tiamazol; tipo dos, corticoide.' },
          { t: 'Litio: mantener + levotiroxina', d: 'No suspender',
            say: 'Y con el litio, no se suspende: se agrega levotiroxina. Si te llevas una sola idea de hoy: antes de bloquear la tiroides, pregúntate si está fabricando hormona o si se está rompiendo. Nos vemos en la próxima clase.' },
        ] },
      ],
    },
  ],

  pathway: {
    title: 'Tiroiditis: ¿duele y capta?',
    root: N('start', 'Sospecha de tiroiditis', 'Tirotoxicosis, bocio o fármaco',
      'Paciente con alteración tiroidea y sospecha de tiroiditis. La primera pregunta es si toma amiodarona o litio, porque cambia todo el razonamiento.',
      ['', N('q', '¿Usa amiodarona o litio?', 'Fármaco sospechoso',
        '¿Hay un fármaco de por medio?',
        ['Litio', N('do', 'Mantener litio + levotiroxina', 'Bocio e hipotiroidismo',
          'Si es litio, con bocio e hipotiroidismo: se mantiene el litio y se agrega levotiroxina.')],
        ['Amiodarona', N('q', '¿Tiroides previa enferma?', 'Doppler y captación',
          'Si es amiodarona con tirotoxicosis, pregunta cómo estaba la tiroides antes, y mira el Doppler y la captación.',
          ['Bocio previo', N('do', 'Tipo 1: tiamazol a dosis altas', 'Doppler vascular, capta',
            'Con bocio previo, Doppler vascular y captación detectable: tipo uno, tiamazol a dosis altas.')],
          ['Tiroides normal', N('do', 'Tipo 2: prednisona 40 mg/día', 'Avascular, no capta',
            'Con tiroides previa normal, avascular y sin captación: tipo dos, prednisona.')])],
        ['No', N('q', '¿Duele la tiroides?', 'Dolor cervical anterior',
          'Sin fármacos, la pregunta es si la tiroides duele.',
          ['Sí, con fluctuación', N('refer', 'Supurada: drenaje + antibióticos', 'Eritema y leucocitosis',
            'Si duele con eritema, fluctuación y leucocitosis, es un absceso: drenaje y antibióticos endovenosos.')],
          ['Sí, post-viral', N('ok', 'De Quervain: AINE', 'VHS alta, captación nula',
            'Si duele después de un cuadro viral, con VHS alta y captación nula: De Quervain. AINE, prednisona si es refractaria, y propranolol para los síntomas.')],
          ['No', N('ok', 'Hashimoto o silente', 'Anti-TPO y evolución',
            'Si no duele: Hashimoto, con bocio y anticuerpos altos, que se trata con levotiroxina según la TSH; o la silente y postparto, que pasa por tres fases y se maneja con propranolol y levotiroxina transitoria.')])])]),
  },
};
