// Clase 7.20 — guion docente escrito a mano (ver gastro-01.cjs para el formato).
// Fuente clínica: books/scripts/dataset_endocrinologia.cjs (endo-20).

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  id: 'endo-20',
  tier: 2,
  slides: [
    {
      type: 'cover',
      subtitle: 'Hemianopsia bitemporal, el estudio triple y la hidrocortisona que salva en la apoplejía',
      say: 'Bienvenidos. Dejamos el hueso y subimos a la hipófisis, con las masas selares. Es un tema de frecuencia alta, y el examen lo pregunta de tres formas: un paciente que choca con las cosas porque no ve hacia los lados, una masa que se descubre por casualidad, y una cefalea brutal que termina en shock. Hoy vamos a ordenar las tres. Partamos.',
    },

    {
      type: 'points',
      kicker: 'Etiología',
      title: '¿Qué hay en la silla turca?',
      cards: [
        { title: 'Adenomas hipofisarios', tag: 'Los más frecuentes', kind: 'key', items: [
          { t: 'Tumores benignos de la adenohipófisis', d: '10–15 % de las neoplasias intracraneales',
            say: 'Partamos por lo que puede haber en la silla turca. Lo más frecuente en el adulto son los adenomas hipofisarios: tumores epiteliales benignos de la adenohipófisis, que son del diez al quince por ciento de todas las neoplasias intracraneales.' },
          { t: 'Prolactinoma 40 %, no funcionante 30–35 %', d: 'Somatotropo 15 %, corticotropo 10 %',
            say: 'El más común es el prolactinoma, con cuarenta por ciento. Le siguen los no funcionantes, con treinta a treinta y cinco; los productores de hormona de crecimiento, con quince; y los productores de ACTH, con diez.' },
          { t: 'Micro < 10 mm · Macro ≥ 10 mm', d: 'El tamaño cambia la conducta',
            say: 'Y se clasifican por tamaño: bajo diez milímetros es un microadenoma, y desde diez milímetros, un macroadenoma. Ese corte de diez milímetros lo vas a usar en la conducta.' },
        ] },
        { title: 'Otras masas selares', tag: 'Diferencial', kind: 'criteria', items: [
          { t: 'Craneofaringioma', d: 'Quístico, calcificado, de la bolsa de Rathke',
            say: 'Pero no todo es adenoma. El craneofaringioma deriva de la bolsa de Rathke: es supraselar, quístico y con calcificaciones, y aparece en niños y en adultos mayores.' },
          { t: 'Meningioma y quiste de Rathke', d: 'También aneurisma carotídeo y metástasis',
            say: 'Además están el meningioma del tubérculo selar, el quiste de la hendidura de Rathke, el aneurisma de la carótida interna, y las metástasis de mama, pulmón o próstata.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Fisiopatología',
      title: 'Efecto de masa: hacia dónde crece',
      nodes: [
        { id: 'mac', col: 0, row: 2, k: 'cause', t: 'Macroadenoma', s: '10 mm o más' },
        { id: 'dia', col: 1, row: 0, k: 'mech', t: 'Distiende el diafragma selar', s: 'Crece dentro de la silla' },
        { id: 'cef', col: 2, row: 0, k: 'effect', t: 'Cefalea sorda', s: 'Retroocular o bifrontal' },
        { id: 'sup', col: 1, row: 2, k: 'mech', t: 'Extensión supraselar', s: 'Comprime el centro del quiasma' },
        { id: 'fib', col: 2, row: 2, k: 'mech', t: 'Fibras nasales decusadas', s: 'Ven el campo temporal' },
        { id: 'hem', col: 3, row: 2, k: 'risk', t: 'Hemianopsia bitemporal', s: 'Visión central conservada' },
        { id: 'cav', col: 1, row: 4, k: 'mech', t: 'Invasión del seno cavernoso', s: 'Pares III, IV, VI, V1–V2' },
        { id: 'oft', col: 2, row: 4, k: 'risk', t: 'Oftalmoplejía', s: 'Diplopía, ptosis' },
      ],
      edges: [
        { from: 'mac', to: 'dia', label: 'dentro' }, { from: 'dia', to: 'cef' },
        { from: 'mac', to: 'sup', label: 'arriba' }, { from: 'sup', to: 'fib' }, { from: 'fib', to: 'hem' },
        { from: 'mac', to: 'cav', label: 'lateral' }, { from: 'cav', to: 'oft' },
      ],
      steps: [
        { show: ['mac'], note: 'Los síntomas dependen de hacia dónde crece',
          say: 'Ahora, ¿cómo da síntomas un macroadenoma? Por efecto de masa, y los síntomas dependen de hacia dónde crece. Si entiendes la anatomía, deduces la clínica.' },
        { show: ['dia', 'cef'], note: 'Cefalea por distensión',
          say: 'Mientras crece dentro de la silla, estira el diafragma selar, y eso da una cefalea sorda, retroocular o bifrontal.' },
        { show: ['sup'], note: 'Justo arriba está el quiasma',
          say: 'Si crece hacia arriba, se encuentra con el quiasma óptico, que está justo encima de la silla, y lo comprime por abajo, en su centro.' },
        { show: ['fib'], note: 'En el centro cruzan las fibras nasales',
          say: 'Y en el centro del quiasma cruzan las fibras que vienen de la mitad nasal de cada retina. Esas fibras son las que ven el campo visual temporal, el de los lados.' },
        { show: ['hem'], note: 'El paciente que no ve a los lados',
          say: 'El resultado es la hemianopsia bitemporal: el paciente pierde la visión de ambos lados, pero conserva la visión central. Por eso choca con los muebles o no ve los autos en los cruces, aunque lea perfecto la cartilla. Esta es la imagen clásica del examen.' },
        { show: ['cav', 'oft'], note: 'Lateral: pares craneales del seno cavernoso',
          say: 'Y si crece hacia los lados, invade los senos cavernosos, por donde pasan los pares tres, cuatro y seis, y las primeras ramas del trigémino. Aparece la oftalmoplejía: diplopía, ptosis, estrabismo.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'Diagnóstico',
      title: 'Estudio triple obligatorio',
      nodes: [
        { id: 'mas', col: 0, row: 2, k: 'start', t: 'Masa selar', s: 'Incidental, cefalea o defecto visual' },
        { id: 'rm', col: 1, row: 0, k: 'good', t: 'RM de silla turca', s: 'T1/T2 con y sin gadolinio' },
        { id: 'cv', col: 1, row: 2, k: 'good', t: 'Campimetría computarizada', s: 'Documenta el daño quiasmático' },
        { id: 'hor', col: 1, row: 4, k: 'good', t: 'Perfil hormonal completo', s: 'Todos los ejes' },
        { id: 'exc', col: 2, row: 4, k: 'mech', t: '¿Hipersecreta?', s: 'Prolactina, IGF-1, cortisol + ACTH' },
        { id: 'def', col: 3, row: 4, k: 'alert', t: '¿Hay déficit?', s: 'TSH + T4L, FSH/LH + esteroides sexuales' },
      ],
      edges: [
        { from: 'mas', to: 'rm' }, { from: 'mas', to: 'cv' }, { from: 'mas', to: 'hor' },
        { from: 'hor', to: 'exc' }, { from: 'exc', to: 'def' },
      ],
      steps: [
        { show: ['mas'], note: 'Tres estudios, siempre',
          say: 'Frente a cualquier masa selar, sea un hallazgo, una cefalea o un defecto visual, hay un estudio triple obligatorio. No uno: los tres.' },
        { show: ['rm'], note: 'La imagen de elección es la resonancia',
          say: 'Primero, la resonancia magnética de silla turca, con y sin gadolinio. Es el examen de imagen de elección; la radiografía y la TAC quedan atrás.' },
        { show: ['cv'], note: 'Objetiva el daño visual',
          say: 'Segundo, la campimetría computarizada, que documenta formalmente si hay daño de las fibras del quiasma.' },
        { show: ['hor', 'exc'], note: 'Primero, qué produce de más',
          say: 'Y tercero, el perfil hormonal completo. Buscas si el tumor produce algo: prolactina para el prolactinoma, IGF uno para la acromegalia, y cortisol con ACTH para el Cushing.' },
        { show: ['def'], note: 'Después, qué dejó de producir',
          say: 'Y buscas si la masa aplastó a la hipófisis sana: TSH con T cuatro libre para el hipotiroidismo central, gonadotropinas con testosterona o estradiol, y el cortisol matinal para una insuficiencia suprarrenal. Además, la prolactina puede subir solo porque la masa desconecta el tallo, sin ser un prolactinoma.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Conducta',
      title: '¿Qué se hace con la masa?',
      cards: [
        { title: 'Prolactinoma', tag: 'Regla de oro', kind: 'pharma', items: [
          { t: 'Cabergolina, no cirugía', d: 'Aunque dé hemianopsia bitemporal',
            say: 'Con el estudio listo, decides la conducta. Y la regla de oro va primero: si la masa es un prolactinoma, el tratamiento de entrada es médico, con un agonista dopaminérgico, la cabergolina. Incluso si ya produce hemianopsia bitemporal. Es el único adenoma que se trata primero con pastillas, y lo vemos a fondo en la próxima clase.' },
        ] },
        { title: 'Cirugía transesfenoidal', tag: 'Neurocirugía', kind: 'alert', items: [
          { t: 'Macroadenoma no funcionante compresivo', d: 'Descomprimir el quiasma, salvar la visión',
            say: 'El macroadenoma no funcionante que comprime el quiasma se opera: resección transesfenoidal endoscópica, para descomprimir la vía visual antes de que la atrofia óptica sea irreversible. La cabergolina aquí no sirve.' },
          { t: 'Adenomas de GH o ACTH', d: 'Previa evaluación corticotropa y tirotropa',
            say: 'Los adenomas que secretan hormona de crecimiento o ACTH también van a cirugía. Y antes de operar, se evalúan los ejes corticotropo y tirotropo.' },
        ] },
        { title: 'Incidentaloma', tag: 'Observar', kind: 'normal', items: [
          { t: 'No funcionante < 10 mm, asintomático', d: 'Sin cirugía: RM a los 12 meses',
            say: 'Y el incidentaloma: un microadenoma no funcionante, bajo diez milímetros y sin síntomas, no se opera. Se controla con resonancia a los doce meses y evaluación hormonal periódica.' },
          { t: 'Seguimiento después de operar', d: 'RM anual, campimetría, ejes hormonales',
            say: 'Y después de una cirugía, el seguimiento es con resonancia anual, campimetría periódica y control hormonal, para pesquisar un hipopituitarismo que puede aparecer en forma diferida.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Urgencia',
      title: 'Apoplejía hipofisaria',
      nodes: [
        { id: 'ade', col: 0, row: 1, k: 'cause', t: 'Adenoma previo', s: 'A menudo desconocido' },
        { id: 'gat', col: 0, row: 3, k: 'cause', t: 'Gatillantes', s: 'Anticoagulantes, cirugía, embarazo' },
        { id: 'inf', col: 1, row: 2, k: 'mech', t: 'Infarto o hemorragia', s: 'Del adenoma' },
        { id: 'cli', col: 2, row: 1, k: 'risk', t: 'Cefalea en trueno', s: 'Pérdida visual, III par, meningismo' },
        { id: 'acth', col: 2, row: 3, k: 'alert', t: 'Cae la ACTH', s: 'Insuficiencia suprarrenal aguda' },
        { id: 'hc', col: 3, row: 2, k: 'good', t: 'Hidrocortisona 100 mg EV', s: 'Inmediata, en bolo' },
        { id: 'qx', col: 4, row: 2, k: 'refer', t: 'Descompresión urgente', s: 'Si pierde visión o conciencia' },
      ],
      edges: [
        { from: 'ade', to: 'inf' }, { from: 'gat', to: 'inf' },
        { from: 'inf', to: 'cli' }, { from: 'inf', to: 'acth' },
        { from: 'acth', to: 'hc', label: 'primero' }, { from: 'hc', to: 'qx', label: 'RM urgente' },
      ],
      steps: [
        { show: ['ade', 'gat'], note: 'Un adenoma que nadie conocía',
          say: 'Ahora la emergencia del tema: la apoplejía hipofisaria. Parte con un adenoma que muchas veces nadie conocía, y un gatillante: un cambio hemodinámico brusco, una cirugía cardiovascular mayor, anticoagulantes, el embarazo, o una prueba de estimulación hipofisaria.' },
        { show: ['inf'], note: 'El tumor se infarta o sangra',
          say: 'El adenoma sufre un infarto fulminante o una hemorragia masiva dentro de él, y crece de golpe.' },
        { show: ['cli'], note: 'Simula una hemorragia subaracnoidea',
          say: 'La clínica es brutal: cefalea súbita en estallido, en trueno, pérdida visual súbita, oftalmoplejía dolorosa con ptosis y diplopía por el tercer par, y meningismo. Por eso se confunde con una hemorragia subaracnoidea.' },
        { show: ['acth'], note: 'Lo que mata es la falta de cortisol',
          say: 'Pero lo que mata no es la cefalea. La hemorragia destruye la hipófisis sana, se corta la ACTH, y aparece una insuficiencia suprarrenal aguda secundaria: compromiso de conciencia y shock. Conecta con la clase de crisis suprarrenal.' },
        { show: ['hc'], note: 'Primera medida: hidrocortisona',
          say: 'Por eso, la primera medida, la que salva la vida, es hidrocortisona cien miligramos endovenosa en bolo, de inmediato. No esperas la imagen para darla.' },
        { show: ['qx'], note: 'La cirugía decide la visión',
          say: 'Luego, resonancia urgente. Y descompresión transesfenoidal de urgencia si la visión se deteriora, hay defectos campimétricos severos o compromiso de conciencia profundo. La hidrocortisona salva la vida; la cirugía salva la visión.' },
      ],
    },

    {
      type: 'table',
      kicker: 'Diagnóstico diferencial',
      title: 'Masas de la región selar',
      head: ['Lesión', 'A quién', 'Imagen', 'Conducta'],
      rows: [
        { cells: ['Adenoma hipofisario', 'Adultos de 20–60 años', 'Intraselar, realce homogéneo', 'Cabergolina si prolactinoma; si no, cirugía'],
          say: 'Repasemos el diferencial. El adenoma es del adulto de veinte a sesenta años, intraselar, con o sin extensión hacia arriba, y con realce homogéneo. Cabergolina si es prolactinoma, cirugía si es otro.' },
        { cells: ['Craneofaringioma', 'Bimodal: 5–14 y > 50 años', 'Supraselar, quístico, calcificado en TC', 'Resección ± radioterapia'],
          say: 'El craneofaringioma tiene dos picos, entre los cinco y los catorce años y después de los cincuenta. Supraselar, quístico, con calcificaciones gruesas en la TAC. Si ves un niño con una masa calcificada sobre la silla, es este.' },
        { cells: ['Meningioma selar', 'Mujeres de edad media', 'Base dural con cola dural', 'Cirugía si da síntomas'],
          say: 'El meningioma selar, en mujeres de edad media, se reconoce por su base dural y la cola dural.' },
        { cells: ['Quiste de Rathke', 'Hallazgo incidental', 'Quístico intraselar, sin realce', 'Observar salvo compresión visual'],
          say: 'El quiste de Rathke es un hallazgo frecuente: quístico, intraselar, bien delimitado y sin realce. Se observa, salvo que comprima la vía visual.' },
        { cells: ['Apoplejía hipofisaria', 'Crisis sobre adenoma previo', 'Hiperintensidad T1 por sangrado', 'Hidrocortisona EV ± descompresión'],
          say: 'Y la apoplejía, con sangrado agudo en la resonancia: hidrocortisona endovenosa y, según la visión, descompresión.' },
      ],
    },

    {
      type: 'pathway',
      intro: 'Juntemos todo en un árbol de decisión, tal como lo vas a razonar en el examen.',
    },

    {
      type: 'table',
      kicker: 'Trampas EUNACOM',
      title: 'Las decisiones que más se preguntan',
      head: ['Escenario', 'Conducta correcta', 'Error frecuente'],
      rows: [
        { cells: ['Hemianopsia bitemporal', 'Pensar en quiasma: macroadenoma', 'Buscar la lesión en el occipital'],
          say: 'Repasemos las trampas. Hemianopsia bitemporal es quiasma, y en el adulto, macroadenoma. Una lesión occipital da hemianopsia homónima, no bitemporal.' },
        { cells: ['Sospecha de masa selar', 'RM de silla turca', 'Radiografía de silla turca o TAC'],
          say: 'La imagen de elección es la resonancia de silla turca. La radiografía de silla turca es la alternativa anticuada que aparece como distractor.' },
        { cells: ['Prolactinoma con hemianopsia', 'Cabergolina', 'Cirugía de entrada'],
          say: 'Prolactinoma, aunque comprima el quiasma: cabergolina. Operar de entrada es el error.' },
        { cells: ['Macroadenoma no funcionante compresivo', 'Cirugía transesfenoidal', 'Cabergolina u observar'],
          say: 'Macroadenoma no funcionante que comprime: cirugía transesfenoidal. Ni cabergolina, ni observación.' },
        { cells: ['Microadenoma incidental no funcionante', 'RM de control a los 12 meses', 'Operar'],
          say: 'Microadenoma incidental no funcionante y sin síntomas: resonancia de control. No se opera.' },
        { cells: ['Cefalea en trueno, III par, hipotensión', 'Hidrocortisona 100 mg EV', 'Manitol o esperar la cirugía'],
          say: 'Y cefalea en trueno con tercer par e hipotensión: apoplejía. Lo primero es hidrocortisona. El manitol o correr a pabellón sin corticoide es la trampa.' },
      ],
    },

    {
      type: 'quiz',
      kicker: 'Caso clínico',
      title: 'Caso clínico',
      stem: 'Hombre de 45 años, con cefaleas esporádicas previas, consulta por 3 horas de cefalea holocraneana súbita "en estallido", vómitos, ptosis derecha, diplopía y somnolencia. PA 85/50 mmHg. Parálisis completa del III par derecho con midriasis y defecto campimétrico bitemporal severo. TC: masa selar con focos de hemorragia aguda.',
      question: '¿Cuál es la medida inicial de máxima prioridad?',
      options: [
        { letter: 'A', text: 'Manitol al 20 % en infusión rápida' },
        { letter: 'B', text: 'Hidrocortisona 100 mg EV en bolo' },
        { letter: 'C', text: 'Cabergolina por sonda nasogástrica' },
        { letter: 'D', text: 'Heparina de bajo peso molecular subcutánea' },
        { letter: 'E', text: 'Somatostatina EV continua' },
      ],
      correct: 'B',
      explanation: 'Apoplejía hipofisaria: la hemorragia destruye la hipófisis, cae la ACTH y aparece una insuficiencia suprarrenal aguda secundaria (hipotensión). La primera medida es hidrocortisona 100 mg EV inmediata; luego RM y descompresión transesfenoidal urgente por el compromiso visual.',
      say: {
        stem: 'Vamos con un caso. Hombre de cuarenta y cinco años con cefalea súbita en estallido hace tres horas, vómitos, ptosis derecha, diplopía y somnolencia. Presión de ochenta y cinco sobre cincuenta. Tiene el tercer par derecho paralizado, con midriasis, y un defecto bitemporal. La TAC muestra una masa selar con sangrado agudo.',
        question: '¿Cuál es la medida inicial de máxima prioridad?',
        options: 'Las opciones: manitol, hidrocortisona endovenosa, cabergolina por sonda, heparina, o somatostatina. Piénsalo.',
        answer: 'La respuesta es la B. Es una apoplejía hipofisaria, y la hipotensión te dice que ya cayó el cortisol. Lo primero es hidrocortisona cien miligramos endovenosa. El manitol tienta porque hay una masa y compromiso de conciencia, pero no trata lo que lo está matando. Después vendrá la descompresión, porque está perdiendo la visión.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2019 · Pregunta 138',
      stem: 'Una paciente cefalea de 4 semanas de evolución, mayor en las mañanas, que se asocia a vómitos y, además, refiere alteraciones visuales. Al examen físico tiene fuerzas y sensibilidad conservada en las 4 extremidades y en el campo visual se constata hemianopsia bitemporal.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Tumor de la glándula pineal' },
        { letter: 'B', text: 'Glioma del nervio óptico' },
        { letter: 'C', text: 'Tumor de la base del lóbulo frontal' },
        { letter: 'D', text: 'Hiperprolactinemia' },
        { letter: 'E', text: 'Macroadenoma hipofisiario' },
      ],
      correct: 'E',
      explanation: 'Cefalea con vómitos y hemianopsia bitemporal: masa que comprime el quiasma desde abajo. El diagnóstico es un macroadenoma hipofisario.',
      say: {
        stem: 'Ahora las preguntas reales. Esta es del EUNACOM de diciembre de dos mil diecinueve. Paciente con cefalea de cuatro semanas, peor en las mañanas, con vómitos y alteraciones visuales. Fuerza y sensibilidad normales, y en el campo visual, hemianopsia bitemporal.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones: tumor pineal, glioma del nervio óptico, tumor de la base del lóbulo frontal, hiperprolactinemia, o macroadenoma hipofisario. Piénsalo.',
        answer: 'Es la E, macroadenoma hipofisario. La palabra clave es bitemporal: eso es el centro del quiasma, y lo que lo comprime desde abajo es una masa de la silla turca. El glioma del nervio óptico tienta, pero dañaría un solo ojo. Y la hiperprolactinemia es un laboratorio, no un tumor que comprime.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2024 · Pregunta 80',
      stem: 'Una mujer de 55 años consulta por cefalea progresiva, de localización interciliar y occipital, asociada a alteraciones visuales. Al examen físico, tiene hemianopsia heterónima, sin alteraciones motoras ni de la sensibilidad.',
      question: '¿En qué estructura anatómica se encuentra con mayor probabilidad la lesión?',
      options: [
        { letter: 'A', text: 'En las retinas' },
        { letter: 'B', text: 'En ambos nervios ópticos' },
        { letter: 'C', text: 'En el lóbulo occipital' },
        { letter: 'D', text: 'En la radiación óptica' },
        { letter: 'E', text: 'En el quiasma óptimo' },
      ],
      correct: 'E',
      explanation: 'Hemianopsia heterónima (bitemporal): lesión del quiasma óptico, típicamente por un tumor hipofisario. El nervio óptico da amaurosis de un ojo; el lóbulo occipital, la radiación y la cintilla dan hemianopsia homónima contralateral.',
      say: {
        stem: 'La siguiente es del EUNACOM de julio de dos mil veinticuatro. Mujer de cincuenta y cinco años con cefalea progresiva y alteraciones visuales. Al examen, hemianopsia heterónima, sin alteraciones motoras ni sensitivas.',
        question: '¿Dónde está la lesión?',
        options: 'Las opciones: las retinas, ambos nervios ópticos, el lóbulo occipital, la radiación óptica, o el quiasma. Piénsalo.',
        answer: 'Es la E, el quiasma óptico. Aquí te cambian la palabra: heterónima significa que se pierden lados opuestos en cada ojo, y la bitemporal es la heterónima clásica. Solo el quiasma, donde cruzan las fibras nasales, produce eso. El lóbulo occipital y la radiación óptica dan hemianopsia homónima, el mismo lado en ambos ojos.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2018 · Pregunta 111',
      stem: 'Un paciente consulta por disminución del deseo sexual y de las erecciones. Además, presenta astenia y debilidad, que ha ido aumentando, desde hace algunos meses. También, refiere haber chocado con un mueble, por no haberlo visto, resultado con lesiones. Al examen físico se aprecia pálido, con disminución del vello corporal, tiene edema de extremidades inferiores y disminución de la visión en la zona temporal del campo visual.',
      question: '¿Cuál es el examen de elección para iniciar el estudio de este paciente?',
      options: [
        { letter: 'A', text: 'Radiografía de silla turca' },
        { letter: 'B', text: 'Prolactinemia' },
        { letter: 'C', text: 'Resonancia magnética de silla turca' },
        { letter: 'D', text: 'Fondo de ojo' },
        { letter: 'E', text: 'TAC de cerebro' },
      ],
      correct: 'C',
      explanation: 'Compresión del quiasma (choca con un mueble, pérdida del campo temporal) más hipopituitarismo (libido, astenia, pérdida de vello): tumor hipofisario. El examen de elección es la RM de silla turca.',
      say: {
        stem: 'Esta es del EUNACOM de diciembre de dos mil dieciocho. Paciente con menos deseo sexual y menos erecciones, astenia y debilidad progresivas, y que chocó con un mueble porque no lo vio. Está pálido, con menos vello corporal, edema de piernas, y pérdida de la visión temporal.',
        question: '¿Cuál es el examen de elección para iniciar el estudio?',
        options: 'Las opciones: radiografía de silla turca, prolactinemia, resonancia de silla turca, fondo de ojo, o TAC de cerebro. Piénsalo.',
        answer: 'Es la C, resonancia magnética de silla turca. Fíjate que el caso junta las dos caras del macroadenoma: el efecto de masa sobre el quiasma, que lo hace chocar con el mueble, y la hipófisis sana aplastada, que explica la baja libido y la pérdida de vello. La radiografía de silla turca es el distractor anticuado.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2024 · Pregunta 24',
      stem: 'Una paciente de 32 años, consulta por un cuadro de 6 meses de amenorrea, asociado a secreción mamaria bilateral. No utiliza método anticonceptivo y es sexualmente activa. Además, ha presentado cefalea que ha aumentado en las últimas semanas, de predominio matinal. Al examen mamario se objetiva escasa galactorrea y al examen neurológico se constata presencia de una hemianopsia bitemporal.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Craneofaringioma' },
        { letter: 'B', text: 'Macroadenoma hipofisiario' },
        { letter: 'C', text: 'Glioma cerebral' },
        { letter: 'D', text: 'Apoplejía hipofisiaria' },
        { letter: 'E', text: 'Accidente vascular encefálico' },
      ],
      correct: 'B',
      explanation: 'Amenorrea-galactorrea (hiperprolactinemia) más hemianopsia bitemporal (compresión del quiasma): macroadenoma hipofisario. La apoplejía sería un cuadro agudo con cefalea en trueno.',
      say: {
        stem: 'Y la última, del EUNACOM de julio de dos mil veinticuatro. Mujer de treinta y dos años con seis meses de amenorrea y galactorrea bilateral, y una cefalea matinal que ha ido aumentando. Al examen, hemianopsia bitemporal.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones: craneofaringioma, macroadenoma hipofisario, glioma, apoplejía hipofisaria, o accidente vascular. Piénsalo.',
        answer: 'Es la B, macroadenoma hipofisario. Amenorrea con galactorrea habla de prolactina alta, y la hemianopsia bitemporal, de un tumor grande que comprime el quiasma. La apoplejía tienta, pero es súbita, con cefalea en trueno; esto lleva semanas. Y el craneofaringioma es más propio de niños y mayores de cincuenta. Este cuadro es justo el puente a la próxima clase.',
      },
    },

    {
      type: 'points',
      kicker: 'Cierre',
      title: 'Reglas de oro para el examen',
      cards: [
        { title: 'Clínica', tag: 'Quiasma', kind: 'key', items: [
          { t: 'Hemianopsia bitemporal = quiasma', d: 'Macroadenoma hasta demostrar lo contrario',
            say: 'Cerremos con las reglas de oro. Hemianopsia bitemporal significa quiasma, y en el adulto, macroadenoma hasta demostrar lo contrario.' },
          { t: 'Estudio triple', d: 'RM + campimetría + perfil hormonal',
            say: 'Toda masa selar lleva el estudio triple: resonancia, campimetría y perfil hormonal completo.' },
        ] },
        { title: 'Conducta', tag: 'Según el tipo', kind: 'pharma', items: [
          { t: 'Prolactinoma: cabergolina', d: 'El único que no va a cirugía de entrada',
            say: 'El prolactinoma se trata con cabergolina, aunque comprima el quiasma.' },
          { t: 'No funcionante compresivo: cirugía', d: 'Incidentaloma < 10 mm: RM de control',
            say: 'El no funcionante que comprime se opera por vía transesfenoidal; el incidentaloma pequeño se controla.' },
        ] },
        { title: 'Apoplejía', tag: 'Emergencia', kind: 'alert', items: [
          { t: 'Hidrocortisona 100 mg EV primero', d: 'Luego descompresión si pierde visión',
            say: 'Y en la apoplejía, primero hidrocortisona endovenosa, después la cirugía. Si te llevas una sola idea de hoy: la hemianopsia bitemporal es quiasma, y en la apoplejía lo que mata es la falta de cortisol. En la próxima clase vemos el adenoma más frecuente, el prolactinoma. Nos vemos en la próxima clase.' },
        ] },
      ],
    },
  ],

  pathway: {
    title: 'Masa selar: de la urgencia a la conducta',
    root: N('start', 'Masa selar', 'Incidental, cefalea o defecto visual',
      'Paciente con una masa selar, descubierta por casualidad, por cefalea o por un defecto visual. La primera pregunta es si es una urgencia.',
      ['', N('q', '¿Apoplejía?', 'Cefalea en trueno, colapso',
        '¿Tiene cefalea en trueno, pérdida visual súbita, oftalmoplejía o colapso hemodinámico?',
        ['SÍ', N('alert', 'Hidrocortisona 100 mg EV', 'Luego RM y descompresión si pierde visión',
          'Si la tiene, es una apoplejía: hidrocortisona cien miligramos endovenosa de inmediato, resonancia urgente, y descompresión si la visión o la conciencia se deterioran.')],
        ['NO', N('do', 'Estudio triple', 'RM + campimetría + perfil hormonal',
          'Si está estable, haces el estudio triple: resonancia, campimetría y perfil hormonal completo.',
          ['', N('q', '¿Es prolactinoma?', 'Prolactina elevada',
            '¿El perfil muestra que es un prolactinoma?',
            ['SÍ', N('do', 'Cabergolina', 'Aunque haya hemianopsia',
              'Si lo es, cabergolina, aunque haya compresión del quiasma.')],
            ['NO', N('q', '¿Comprime o hipersecreta?', 'Quiasma, GH o ACTH',
              'Si no lo es, ¿comprime el quiasma o secreta hormona de crecimiento o ACTH?',
              ['SÍ', N('refer', 'Cirugía transesfenoidal', 'Neurocirugía',
                'Entonces va a cirugía transesfenoidal, por neurocirugía.')],
              ['NO', N('ok', 'Incidentaloma < 10 mm', 'RM a los 12 meses',
                'Si es un incidentaloma no funcionante, bajo diez milímetros y sin síntomas, se observa con resonancia a los doce meses.')])])])])]),
  },
};
