// Clase 7.24 — guion docente escrito a mano (ver gastro-01.cjs para el formato).
// Fuente clínica: books/scripts/dataset_endocrinologia.cjs (endo-24).

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  id: 'endo-24',
  tier: 2,
  slides: [
    {
      type: 'cover',
      subtitle: 'Falta de ADH, exceso de ADH, y los tumores que vienen en familia',
      say: 'Bienvenidos. Cerramos el bloque de hipófisis con su parte posterior y con la hormona que maneja el agua: la hormona antidiurética. Cuando falta, tenemos diabetes insípida; cuando sobra, el síndrome de secreción inadecuada de ADH. Y al final vemos las neoplasias endocrinas múltiples. Partamos.',
    },

    {
      type: 'flow',
      kicker: 'Mecanismo',
      title: 'Una hormona, dos enfermedades opuestas',
      nodes: [
        { id: 'hip', col: 0, row: 1, k: 'start', t: 'ADH hipotalámica', s: 'Vasopresina' },
        { id: 'v2', col: 1, row: 1, k: 'mech', t: 'Receptor V2', s: 'Túbulo colector renal' },
        { id: 'agu', col: 2, row: 1, k: 'good', t: 'Reabsorbe agua libre', s: 'Orina concentrada' },
        { id: 'di', col: 3, row: 0, k: 'effect', t: 'Falta o resistencia', s: 'Diabetes insípida: poliuria diluida' },
        { id: 'sia', col: 3, row: 2, k: 'effect', t: 'Exceso autónomo', s: 'SIADH: hiponatremia' },
      ],
      edges: [
        { from: 'hip', to: 'v2' },
        { from: 'v2', to: 'agu' },
        { from: 'agu', to: 'di', label: 'poca ADH' },
        { from: 'agu', to: 'sia', label: 'mucha ADH' },
      ],
      steps: [
        { show: ['hip', 'v2'], note: 'El hipotálamo la fabrica, el riñón la usa',
          say: 'Partamos por la fisiología, porque con ella se deducen las dos enfermedades. La hormona antidiurética, o vasopresina, se fabrica en el hipotálamo y actúa en el riñón, sobre los receptores V dos del túbulo colector.' },
        { show: ['agu'], note: 'Su función: guardar agua',
          say: 'Su función es una sola: abrir la puerta para que el túbulo recupere agua libre. Con ADH, la orina sale concentrada y el agua se queda en el cuerpo.' },
        { show: ['di'], note: 'Sin ADH: el agua se pierde',
          say: 'Si la ADH falta, o el riñón no le hace caso, el agua se pierde: litros de orina diluida. Eso es la diabetes insípida.' },
        { show: ['sia'], note: 'Con ADH de sobra: el agua se retiene',
          say: 'Y si hay ADH de sobra, sin que el cuerpo la pida, se retiene agua y el sodio se diluye. Eso es el síndrome de secreción inadecuada de ADH, o SIADH. Una hormona, dos caras opuestas.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Diabetes insípida',
      title: 'Mucha orina y muy diluida',
      cards: [
        { title: 'Clínica', tag: 'Poliuria hipotónica', kind: 'key', items: [
          { t: 'Más de 3 a 5 L/día', d: 'Hasta 15–20 L, con polidipsia y nicturia',
            say: 'La diabetes insípida se reconoce por la poliuria masiva: más de tres a cinco litros al día, y puede llegar a quince o veinte. Con sed intensa y el paciente levantándose toda la noche a orinar.' },
          { t: 'Osm urinaria bajo 300', d: 'Densidad menor de 1.005',
            say: 'La orina es diluida: osmolaridad urinaria bajo doscientos a trescientos miliosmoles por kilo y densidad menor de uno coma cero cero cinco.' },
          { t: 'Sodio normal si puede tomar agua', d: 'Hipernatremia si no accede al agua',
            say: 'Y un detalle fino: si el paciente tiene la sed intacta y acceso al agua, compensa tomando, y el sodio queda normal alto. Pero si le restringes el agua, o tiene compromiso de conciencia, se deshidrata y cae en una hipernatremia severa.' },
        ] },
        { title: 'Central', tag: 'No hay ADH', kind: 'criteria', items: [
          { t: 'Daño hipotalámico o del tallo', d: 'TEC, neurocirugía, histiocitosis, sarcoidosis',
            say: '¿Por qué ocurre? En la diabetes insípida central no se fabrica o no se libera ADH, por daño del hipotálamo o del tallo: traumatismo encéfalo craneano, neurocirugía transesfenoidal, histiocitosis, sarcoidosis, o idiopática. La causa típica del examen es el postoperatorio de una cirugía de la silla turca.' },
        ] },
        { title: 'Nefrogénica', tag: 'El riñón no responde', kind: 'alert', items: [
          { t: 'Litio: causa número 1', d: 'También hipercalcemia e hipokalemia',
            say: 'En la nefrogénica, la ADH está, pero el túbulo no responde. La causa farmacológica número uno es el carbonato de litio, y las metabólicas, la hipercalcemia severa y la hipokalemia crónica. Paciente bipolar con poliuria: piensa en litio.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Diagnóstico',
      title: 'Test de Miller: restricción y desmopresina',
      nodes: [
        { id: 'pol', col: 0, row: 1, k: 'start', t: 'Poliuria hipotónica', s: 'Osm urinaria baja' },
        { id: 'res', col: 1, row: 1, k: 'q', t: 'Restricción hídrica', s: 'La Osm urinaria no sube' },
        { id: 'dda', col: 2, row: 1, k: 'q', t: 'Desmopresina', s: '2–4 mcg SC o 20 mcg nasal' },
        { id: 'cen', col: 3, row: 0, k: 'good', t: 'DI central', s: 'Osm urinaria sube más de 50–100 %' },
        { id: 'nef', col: 3, row: 2, k: 'alert', t: 'DI nefrogénica', s: 'Osm urinaria sube menos de 50 %' },
        { id: 'txc', col: 4, row: 0, k: 'good', t: 'Desmopresina', s: 'Nasal u oral' },
        { id: 'txn', col: 4, row: 2, k: 'good', t: 'Hidroclorotiazida + amilorida', s: 'Y retirar la causa' },
      ],
      edges: [
        { from: 'pol', to: 'res' },
        { from: 'res', to: 'dda' },
        { from: 'dda', to: 'cen', label: 'responde' },
        { from: 'dda', to: 'nef', label: 'no responde' },
        { from: 'cen', to: 'txc' },
        { from: 'nef', to: 'txn' },
      ],
      steps: [
        { show: ['pol', 'res'], note: 'Fase 1: se quita el agua',
          say: 'Para confirmar y distinguir las dos, se usa el test de deprivación hídrica y desmopresina, o test de Miller. Primero se restringe el agua. Una persona sana concentraría la orina; en la diabetes insípida la osmolaridad urinaria no sube de trescientos.' },
        { show: ['dda'], note: 'Fase 2: se da la ADH desde afuera',
          say: 'Luego se administra desmopresina, que es ADH sintética: dos a cuatro microgramos subcutáneos, o veinte microgramos nasales. Y aquí está la pregunta clave: ¿el riñón responde a la hormona que le das?' },
        { show: ['cen'], note: 'Si responde, lo que faltaba era la hormona',
          say: 'Si la osmolaridad urinaria sube más de cincuenta a cien por ciento y el volumen de orina cae, el riñón funcionaba bien; lo que faltaba era la hormona. Es diabetes insípida central.' },
        { show: ['nef'], note: 'Si no responde, el problema es el riñón',
          say: 'Si la osmolaridad casi no sube, menos de cincuenta por ciento, el riñón no escucha a la ADH aunque se la des. Es diabetes insípida nefrogénica.' },
        { show: ['txc', 'txn'], note: 'El tratamiento sigue la misma lógica',
          say: 'Y el tratamiento sale solo. La central se trata reponiendo la hormona: desmopresina nasal u oral. La nefrogénica no responde a la desmopresina, así que se usan hidroclorotiazida más amilorida, y se retira la causa, como el litio si es posible.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'SIADH',
      title: '¿Por qué la hiponatremia es euvolémica?',
      nodes: [
        { id: 'adh', col: 0, row: 1, k: 'cause', t: 'ADH autónoma', s: 'Sin estímulo osmótico ni hipovolemia' },
        { id: 'ret', col: 1, row: 1, k: 'mech', t: 'Retiene agua libre', s: 'Túbulo colector' },
        { id: 'hna', col: 2, row: 0, k: 'effect', t: 'Hiponatremia hipotónica', s: 'Por dilución' },
        { id: 'anp', col: 2, row: 2, k: 'mech', t: 'Leve expansión: ANP y BNP', s: 'Péptidos natriuréticos' },
        { id: 'nau', col: 3, row: 2, k: 'effect', t: 'Natriuresis', s: 'Sodio urinario alto' },
        { id: 'euv', col: 4, row: 1, k: 'alert', t: 'Euvolemia clínica', s: 'Sin edema ni deshidratación' },
      ],
      edges: [
        { from: 'adh', to: 'ret' },
        { from: 'ret', to: 'hna' },
        { from: 'ret', to: 'anp' },
        { from: 'anp', to: 'nau' },
        { from: 'nau', to: 'euv' },
        { from: 'hna', to: 'euv' },
      ],
      steps: [
        { show: ['adh', 'ret'], note: 'ADH que nadie pidió',
          say: 'Ahora la otra cara. En el SIADH se secreta ADH de forma autónoma, sin que la osmolaridad esté alta y sin hipovolemia. Es decir, sin ningún motivo. Y el túbulo colector obedece: retiene agua libre.' },
        { show: ['hna'], note: 'El sodio se diluye',
          say: 'Esa agua de más diluye el sodio, y aparece una hiponatremia hipotónica.' },
        { show: ['anp', 'nau'], note: 'El cuerpo se defiende botando sodio',
          say: 'Pero el cuerpo se defiende. La leve expansión de volumen libera péptidos natriuréticos, que obligan al riñón a botar sodio por la orina. Por eso el sodio urinario sale alto, a pesar de que el sodio en sangre está bajo.' },
        { show: ['euv'], note: 'Resultado: volemia normal',
          say: 'El resultado es un paciente con volemia clínicamente normal: sin edema, sin yugulares ingurgitadas, sin signos de deshidratación. Hiponatremia euvolémica: esa es la firma del SIADH.' },
      ],
    },

    {
      type: 'points',
      kicker: 'SIADH',
      title: 'Criterios y causas',
      cards: [
        { title: 'Criterios obligatorios', tag: 'Los cinco', kind: 'criteria', items: [
          { t: 'Na bajo 135 y Osm plasmática bajo 275', d: 'Hiponatremia hipotónica',
            say: 'Para diagnosticarlo se exigen cinco criterios. Uno: hiponatremia hipotónica, con sodio bajo ciento treinta y cinco y osmolaridad plasmática bajo doscientos setenta y cinco.' },
          { t: 'Osm urinaria sobre 100', d: 'Inapropiadamente concentrada, a menudo sobre 300',
            say: 'Dos: una orina inapropiadamente concentrada, con osmolaridad urinaria sobre cien, y a menudo sobre trescientos. Con el sodio tan bajo, el riñón debería estar botando agua, y no lo hace.' },
          { t: 'Na urinario sobre 30–40', d: 'Pese a la hiponatremia',
            say: 'Tres: sodio urinario elevado, sobre treinta a cuarenta, pese a la hiponatremia.' },
          { t: 'Euvolemia y TSH, cortisol y riñón normales', d: 'Descartar hipotiroidismo e insuficiencia suprarrenal',
            say: 'Cuatro: euvolemia clínica estricta. Y cinco: función renal, tiroidea y suprarrenal normales. Esto conecta con la clase anterior: el hipotiroidismo y el déficit de cortisol también dan hiponatremia, y hay que descartarlos antes.' },
        ] },
        { title: 'Causas', tag: 'Las del examen', kind: 'alert', items: [
          { t: 'Cáncer pulmonar de células pequeñas', d: 'Más del 70 % de los ectópicos',
            say: 'La causa que más se pregunta es el cáncer pulmonar de células pequeñas, u oat cell, que secreta ADH ectópica. Fumador con hiponatremia: piensa en él.' },
          { t: 'Pulmón y sistema nervioso', d: 'Neumonía, TBC, meningitis, TEC, ACV',
            say: 'También la patología pulmonar benigna, como neumonía o tuberculosis, y la del sistema nervioso central: meningitis, traumatismo o accidente cerebrovascular.' },
          { t: 'Fármacos', d: 'ISRS, carbamazepina, ciclofosfamida',
            say: 'Y los fármacos: los inhibidores selectivos de la recaptación de serotonina, la carbamazepina y la ciclofosfamida.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Tratamiento del SIADH',
      title: 'Restringir agua y corregir despacio',
      nodes: [
        { id: 'sia', col: 0, row: 1, k: 'start', t: 'SIADH', s: 'Hiponatremia euvolémica' },
        { id: 'gra', col: 1, row: 1, k: 'q', t: '¿Convulsiones o coma?', s: 'Gravedad neurológica' },
        { id: 'res', col: 2, row: 0, k: 'good', t: 'Restricción hídrica', s: '500–1000 mL/día' },
        { id: 'hip', col: 2, row: 2, k: 'refer', t: 'Salino hipertónico al 3 %', s: 'Infusión lenta y controlada' },
        { id: 'lim', col: 3, row: 2, k: 'alert', t: 'Máximo 8–10 mEq/L en 24 h', s: 'Monitoreo estricto del sodio' },
        { id: 'mie', col: 4, row: 2, k: 'trap', t: 'Desmielinización osmótica', s: 'Mielinólisis pontina central' },
      ],
      edges: [
        { from: 'sia', to: 'gra' },
        { from: 'gra', to: 'res', label: 'no' },
        { from: 'gra', to: 'hip', label: 'sí' },
        { from: 'hip', to: 'lim' },
        { from: 'lim', to: 'mie', label: 'si se excede' },
      ],
      steps: [
        { show: ['sia', 'gra'], note: 'La gravedad decide',
          say: 'El tratamiento depende de una pregunta: ¿el paciente tiene síntomas neurológicos graves, como convulsiones o coma?' },
        { show: ['res'], note: 'Si el problema es agua de más, se quita agua',
          say: 'Si no los tiene, la lógica es simple: el problema es agua de más, así que se restringe el agua. Restricción hídrica estricta, quinientos a mil mililitros al día de líquidos totales. Ese es el tratamiento inicial de elección.' },
        { show: ['hip'], note: 'Grave: suero hipertónico',
          say: 'Si tiene convulsiones o coma, se usa suero salino hipertónico al tres por ciento, en infusión lenta y controlada.' },
        { show: ['lim', 'mie'], note: 'Corregir rápido también daña',
          say: 'Y aquí está la trampa de seguridad. La corrección no puede superar los ocho a diez miliequivalentes por litro en las primeras veinticuatro horas. Si subes el sodio demasiado rápido, provocas el síndrome de desmielinización osmótica, la mielinólisis pontina central. Por eso el sodio se monitorea de forma estricta.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Neoplasia endocrina múltiple',
      title: 'Tumores que vienen en familia',
      cards: [
        { title: 'NEM 1 · Wermer', tag: 'Gen MEN1, menina', kind: 'key', items: [
          { t: 'Las 3 P', d: 'Paratiroides, páncreas, pituitaria',
            say: 'Cambiamos de tema: las neoplasias endocrinas múltiples, trastornos hereditarios autosómicos dominantes con tumores en varias glándulas. La tipo uno, o síndrome de Wermer, se debe al gen MEN uno, que codifica la menina, y se recuerda con las tres P.' },
          { t: 'Paratiroides: 95–100 %', d: 'Hiperplasia de las 4 glándulas, lo más precoz',
            say: 'Primera P, paratiroides: hiperparatiroidismo primario por hiperplasia de las cuatro glándulas, en el noventa y cinco a cien por ciento, y es lo primero que aparece. Por eso se opera con paratiroidectomía subtotal.' },
          { t: 'Páncreas y pituitaria', d: 'Gastrinoma 60 %, insulinoma; prolactinoma 60 %',
            say: 'Segunda P, páncreas: tumores neuroendocrinos, sobre todo gastrinomas con síndrome de Zollinger Ellison, en el sesenta por ciento, e insulinomas. Tercera P, pituitaria: adenomas, sobre todo prolactinomas, en el sesenta por ciento.' },
        ] },
        { title: 'NEM 2A · Sipple', tag: 'Protooncogén RET', kind: 'alert', items: [
          { t: 'Carcinoma medular de tiroides', d: 'Penetrancia 100 %, bilateral',
            say: 'La tipo dos se debe al protooncogén RET. En la dos A, o síndrome de Sipple, el carcinoma medular de tiroides aparece en el cien por ciento, multicéntrico y bilateral.' },
          { t: 'Feocromocitoma 50 % + HPT 20–30 %', d: 'Operar el feocromocitoma primero',
            say: 'Se suman el feocromocitoma, en la mitad de los casos y bilateral, y el hiperparatiroidismo primario en el veinte a treinta por ciento. Y la regla quirúrgica: antes de operar el tiroides se descarta y se opera el feocromocitoma. Si no, la crisis de catecolaminas en la anestesia puede ser fatal.' },
        ] },
        { title: 'NEM 2B · Gorlin', tag: 'Protooncogén RET', kind: 'criteria', items: [
          { t: 'Medular precoz + feocromocitoma', d: 'Neuromas mucosos, hábito marfanoide',
            say: 'En la dos B, o síndrome de Gorlin, el carcinoma medular es muy precoz y agresivo, con feocromocitoma en el cincuenta por ciento, neuromas mucosos en lengua, labios y conjuntivas, hábito marfanoide y ganglioneuromatosis intestinal.' },
          { t: 'Sin hiperparatiroidismo', d: 'Tiroidectomía profiláctica el primer año',
            say: 'Y la diferencia que se pregunta: la dos B no tiene hiperparatiroidismo. Por lo agresivo del cáncer, se indica tiroidectomía profiláctica en el primer año de vida.' },
        ] },
      ],
    },

    {
      type: 'pathway',
      intro: 'Juntemos la parte del agua en un árbol de decisión.',
    },

    {
      type: 'table',
      kicker: 'Trampas EUNACOM',
      title: 'Lo que se pregunta y cómo se cae',
      head: ['Escenario', 'Respuesta correcta', 'Error frecuente'],
      rows: [
        { cells: ['Poliuria e hipernatremia tras cirugía selar', 'DI central', 'SIADH'],
          say: 'Repasemos las trampas. Poliuria con hipernatremia después de una cirugía de la silla turca: diabetes insípida central. El SIADH da lo contrario, hiponatremia.' },
        { cells: ['Usuario de litio con poliuria', 'DI nefrogénica', 'Polidipsia psicógena'],
          say: 'Paciente con litio y poliuria: diabetes insípida nefrogénica. No lo atribuyas a su enfermedad psiquiátrica.' },
        { cells: ['DI que no responde a desmopresina', 'Tiazida + amilorida', 'Subir la desmopresina'],
          say: 'Si no responde a la desmopresina, es nefrogénica, y se trata con tiazida y amilorida. Subir la desmopresina no sirve.' },
        { cells: ['Hiponatremia euvolémica, Na urinario alto', 'SIADH: restricción hídrica', 'Suero fisiológico'],
          say: 'Hiponatremia euvolémica con sodio urinario alto: SIADH, y se restringe el agua. Dar suero fisiológico es el error, porque el problema es el agua, no la falta de sal.' },
        { cells: ['Hiponatremia con convulsiones', 'Salino 3 %, máx. 8–10 mEq/L en 24 h', 'Corregir rápido a la normalidad'],
          say: 'Con convulsiones, salino hipertónico, pero sin pasar de ocho a diez miliequivalentes en veinticuatro horas.' },
        { cells: ['NEM 2A antes de tiroidectomía', 'Operar primero el feocromocitoma', 'Operar primero el tiroides'],
          say: 'Y en la NEM dos A, primero el feocromocitoma y después el tiroides.' },
      ],
    },

    {
      type: 'quiz',
      kicker: 'Caso clínico',
      title: 'Caso clínico',
      stem: 'Hombre de 62 años con carcinoma pulmonar de células pequeñas en tratamiento, traído por astenia, náuseas, marcha inestable y confusión progresiva. Sin edema, mucosas húmedas, yugulares normales, PA 130/80 mmHg. Na 118 mEq/L, K 4,0 mEq/L, Osm plasmática 245 mOsm/kg, Osm urinaria 480 mOsm/kg, Na urinario 54 mEq/L. Función renal, TSH y cortisol normales. No ha convulsionado.',
      question: '¿Cuál es la base del tratamiento?',
      options: [
        { letter: 'A', text: 'Suero fisiológico 0,9 % a chorro' },
        { letter: 'B', text: 'Restricción hídrica a 500–1000 mL/día' },
        { letter: 'C', text: 'Desmopresina intranasal' },
        { letter: 'D', text: 'Furosemida y albúmina' },
        { letter: 'E', text: 'Corregir el sodio a 135 mEq/L en las primeras 24 horas' },
      ],
      correct: 'B',
      explanation: 'SIADH paraneoplásico por oat cell: hiponatremia hipotónica euvolémica, Osm urinaria sobre 100, Na urinario sobre 30, con renal, tiroides y suprarrenal normales. La base es la restricción hídrica. Si convulsiona o entra en coma, salino al 3 % sin superar 8–10 mEq/L en 24 h, para evitar la mielinólisis pontina.',
      say: {
        stem: 'Vamos al caso. Hombre de sesenta y dos años con cáncer pulmonar de células pequeñas, que llega con astenia, náuseas, marcha inestable y confusión. No tiene edema, las mucosas están húmedas y las yugulares normales. El sodio es ciento dieciocho, la osmolaridad plasmática baja, la urinaria de cuatrocientos ochenta, y el sodio urinario de cincuenta y cuatro. Riñón, TSH y cortisol normales. No ha convulsionado.',
        question: '¿Cuál es la base del tratamiento?',
        options: 'Las alternativas: suero fisiológico a chorro, restricción hídrica, desmopresina, furosemida con albúmina, o corregir el sodio a ciento treinta y cinco en veinticuatro horas. Piénsalo.',
        answer: 'Es la B, restricción hídrica. Cumple todos los criterios de SIADH y tiene la causa clásica, el oat cell. La A es la trampa: el problema es agua de más, y el suero fisiológico no corrige la hiponatremia. La desmopresina empeoraría todo, porque es más ADH. Y la E es peligrosa: subir diecisiete puntos en un día arriesga una mielinólisis pontina.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Enero 2023 · Pregunta 124',
      stem: 'Niño operado de cirugía cerebral, luego presenta hipernatremia y poliuria.',
      question: '¿Diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Síndrome de secreción inadecuada de ADH (SIADH)' },
        { letter: 'B', text: 'Diabetes mellitus tipo 1' },
        { letter: 'C', text: 'Hiperaldosteronismo secundario' },
        { letter: 'D', text: 'Diabetes insípida central' },
        { letter: 'E', text: 'Polidipsia psicogénica' },
      ],
      correct: 'D',
      explanation: 'Poliuria con hipernatremia tras una neurocirugía: falta de ADH por daño hipotalámico o del tallo. El SIADH, por exceso de ADH, retiene agua y causa hiponatremia.',
      say: {
        stem: 'Ahora las preguntas reales. Esta es del EUNACOM de enero de dos mil veintitrés. Un niño operado de una cirugía cerebral que luego presenta hipernatremia y poliuria.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones: SIADH, diabetes mellitus tipo uno, hiperaldosteronismo secundario, diabetes insípida central, o polidipsia psicogénica. Piénsalo.',
        answer: 'Es la D, diabetes insípida central. Neurocirugía, más poliuria, más hipernatremia: el daño del hipotálamo o del tallo dejó al paciente sin ADH. El SIADH es la trampa, porque también aparece después de cirugías cerebrales, pero da lo contrario: retiene agua e hiponatremia. Y la polidipsia psicogénica tendría el sodio bajo, no alto.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Enero 2023 · Pregunta 125',
      stem: 'Paciente usuaria de lamotrigina, ácido valproico y litio, presenta diuresis de 12.600 mL/día, deshidratación e hipernatremia.',
      question: '¿Cuál es la causa más probable?',
      options: [
        { letter: 'A', text: 'Ácido valproico' },
        { letter: 'B', text: 'Carbonato de litio (diabetes insípida nefrogénica)' },
        { letter: 'C', text: 'Lamotrigina' },
        { letter: 'D', text: 'Polidipsia psicogénica inducida por antipsicóticos' },
        { letter: 'E', text: 'Hiperglicemia osmótica' },
      ],
      correct: 'B',
      explanation: 'El carbonato de litio es la causa farmacológica número uno de diabetes insípida nefrogénica: el túbulo colector no responde a la ADH.',
      say: {
        stem: 'La siguiente, del mismo examen de enero de dos mil veintitrés. Paciente que usa lamotrigina, ácido valproico y litio, con una diuresis de doce mil seiscientos mililitros al día, deshidratación e hipernatremia.',
        question: '¿Cuál es la causa más probable?',
        options: 'Las alternativas: ácido valproico, carbonato de litio, lamotrigina, polidipsia psicogénica, o hiperglicemia osmótica. Piénsalo.',
        answer: 'Es la B, el litio, que causa diabetes insípida nefrogénica. El distractor es la polidipsia psicogénica, que suena lógica en un paciente psiquiátrico. Pero el que toma agua de más diluye el sodio; aquí el sodio está alto y el paciente deshidratado. Eso es pérdida de agua por el riñón, no exceso de ingesta.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2024 · Pregunta 92',
      stem: 'Un paciente de 72 años, fumador de 40 paquetes/año, con diagnóstico de cáncer pulmonar de células pequeñas sin tratamiento actual, presenta un cuadro de 7 días de evolución de cefalea y tendencia a la desorientación. En sus exámenes destaca una concentración sérica de sodio de 121 mEq/L, sin focalidad neurológica.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'SIADH (Síndrome de secreción inapropiada de hormona antidiurética)' },
        { letter: 'B', text: 'Metástasis cerebrales' },
        { letter: 'C', text: 'Síndrome carcinoide' },
        { letter: 'D', text: 'Accidente vascular encefálico' },
        { letter: 'E', text: 'Hipercalcemia' },
      ],
      correct: 'A',
      explanation: 'SIADH clásico por cáncer pulmonar de células pequeñas, con hiponatremia y compromiso neurológico. Con síntomas neurológicos se usa salino hipertónico lento; si no, restricción de agua libre.',
      say: {
        stem: 'Una del EUNACOM de julio de dos mil veinticuatro. Paciente de setenta y dos años, fumador de cuarenta paquetes año, con cáncer pulmonar de células pequeñas sin tratamiento, que lleva siete días con cefalea y tendencia a la desorientación. El sodio es ciento veintiuno, sin focalidad neurológica.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones: SIADH, metástasis cerebrales, síndrome carcinoide, accidente vascular, o hipercalcemia. Piénsalo.',
        answer: 'Es la A, SIADH. Cáncer de células pequeñas más hiponatremia es la asociación que tienes que tener automática. Las metástasis cerebrales son el distractor tentador, porque también dan cefalea y confusión, pero no explican el sodio de ciento veintiuno. Y el enunciado ya te dice que no hay focalidad neurológica.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2017 · Pregunta 49',
      stem: 'Una paciente de 60 años, con antecedente de hipotiroidismo, hipertensión y depresión, en tratamiento con levotiroxina, enalapril y citalopram se realiza exámenes de control, entre los que destacan sodio plasmático de 127 mEq/L, potasio plasmático de 4,1 mEq/L, creatinina plasmática de 0,9 mg/dl y sodio urinario de 60 mEq/L.',
      question: '¿Cuál es la causa más probable de su hiponatremia?',
      options: [
        { letter: 'A', text: 'Uso del enalapril' },
        { letter: 'B', text: 'Reacción secundaria al citalopram' },
        { letter: 'C', text: 'Síndrome paraneoplásico' },
        { letter: 'D', text: 'Insuficiencia suprarrenal' },
        { letter: 'E', text: 'Hipotiroidismo descompensado' },
      ],
      correct: 'B',
      explanation: 'Probable SIADH (hiponatremia con sodio urinario alto) inducido por citalopram, un ISRS.',
      say: {
        stem: 'La última del banco, del EUNACOM de diciembre de dos mil diecisiete. Paciente de sesenta años con hipotiroidismo, hipertensión y depresión, que toma levotiroxina, enalapril y citalopram. En su control tiene sodio de ciento veintisiete, potasio y creatinina normales, y sodio urinario de sesenta.',
        question: '¿Cuál es la causa más probable de su hiponatremia?',
        options: 'Las alternativas: enalapril, citalopram, síndrome paraneoplásico, insuficiencia suprarrenal, o hipotiroidismo descompensado. Piénsalo.',
        answer: 'Es la B, el citalopram. Hiponatremia con sodio urinario alto sugiere SIADH, y los inhibidores de la recaptación de serotonina están en la lista de fármacos que lo causan. El hipotiroidismo es el distractor, porque también da hiponatremia, pero está tratado con levotiroxina; por eso mismo se exige función tiroidea normal para diagnosticar SIADH.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta del banco EUNACOM',
      title: 'Banco EUNACOM · Caso representativo',
      stem: 'Una paciente de 32 años consulta para asesoramiento genético. Su madre tuvo hiperparatiroidismo primario por compromiso de múltiples glándulas paratiroides, y a su hermano le extirparon un prolactinoma hipofisario y un gastrinoma pancreático.',
      question: '¿Cuál de los siguientes genes es el responsable más probable de esta agregación familiar?',
      options: [
        { letter: 'A', text: 'Protooncogén RET' },
        { letter: 'B', text: 'Gen supresor de tumores MEN1 (menina)' },
        { letter: 'C', text: 'Gen supresor tumoral VHL' },
        { letter: 'D', text: 'Gen NF1' },
        { letter: 'E', text: 'Gen del receptor de TSH' },
      ],
      correct: 'B',
      explanation: 'Paratiroides + páncreas (gastrinoma) + pituitaria (prolactinoma): las 3 P de la NEM 1 o síndrome de Wermer, por mutación del gen MEN1, que codifica la menina. El RET causa NEM 2A y 2B.',
      say: {
        stem: 'Para las neoplasias endocrinas múltiples, un caso representativo del banco. Paciente de treinta y dos años que pide consejo genético. Su madre tuvo hiperparatiroidismo por compromiso de varias paratiroides, y a su hermano le sacaron un prolactinoma y un gastrinoma pancreático.',
        question: '¿Qué gen es el responsable más probable?',
        options: 'Las opciones: protooncogén RET, gen MEN uno, gen VHL, gen NF uno, o gen del receptor de TSH. Piénsalo.',
        answer: 'Es la B, el gen MEN uno. Cuenta las P: paratiroides, páncreas con el gastrinoma, y pituitaria con el prolactinoma. Es una NEM uno. El RET es el distractor, porque también es un síndrome de neoplasia endocrina múltiple, pero causa la tipo dos, que se reconoce por el carcinoma medular de tiroides y el feocromocitoma.',
      },
    },

    {
      type: 'points',
      kicker: 'Cierre',
      title: 'Reglas de oro para el examen',
      cards: [
        { title: 'Diabetes insípida', tag: 'Falta ADH', kind: 'key', items: [
          { t: 'Poliuria diluida ± hipernatremia', d: 'Desmopresina distingue central de nefrogénica',
            say: 'Cerremos con las reglas de oro. Diabetes insípida: poliuria diluida, con hipernatremia si falta el agua. Si responde a desmopresina es central; si no, nefrogénica.' },
          { t: 'Litio: nefrogénica', d: 'Neurocirugía: central',
            say: 'La neurocirugía da la central, y el litio, la nefrogénica.' },
        ] },
        { title: 'SIADH', tag: 'Sobra ADH', kind: 'alert', items: [
          { t: 'Hiponatremia euvolémica', d: 'Osm urinaria sobre 100, Na urinario sobre 30',
            say: 'SIADH: hiponatremia euvolémica con orina concentrada y sodio urinario alto; piensa en el oat cell. Se trata con restricción de agua.' },
          { t: 'Máximo 8–10 mEq/L en 24 h', d: 'Evita la mielinólisis pontina',
            say: 'Y nunca corrijas más de ocho a diez miliequivalentes en veinticuatro horas.' },
        ] },
        { title: 'NEM', tag: 'Hereditarias', kind: 'criteria', items: [
          { t: 'NEM 1: las 3 P', d: 'NEM 2: medular + feocromocitoma',
            say: 'NEM uno son las tres P; NEM dos, carcinoma medular y feocromocitoma, y el feocromocitoma se opera primero. Si te llevas una sola idea de hoy: la ADH guarda agua; si falta, se pierde agua y sube el sodio; si sobra, se retiene agua y el sodio baja. Nos vemos en la próxima clase.' },
        ] },
      ],
    },
  ],

  pathway: {
    title: 'Trastornos de la ADH: poliuria o hiponatremia',
    root: N('start', 'Trastorno del agua', 'Evaluar volemia, Osm plasmática y urinaria',
      'Ante un trastorno del agua, se evalúa la volemia clínica y se miden la osmolaridad plasmática y la urinaria.',
      ['Poliuria', N('q', 'Poliuria hipotónica', 'Osm urinaria bajo 300',
        'Si hay poliuria de orina diluida, pensamos en diabetes insípida, y se hace el test de restricción hídrica con desmopresina.',
        ['Responde', N('do', 'DI central', 'Desmopresina nasal u oral',
          'Si la osmolaridad urinaria sube más de cincuenta por ciento con desmopresina, es central, y se trata con desmopresina.')],
        ['No responde', N('do', 'DI nefrogénica', 'Tiazida + amilorida; buscar litio',
          'Si no responde, es nefrogénica: se busca el litio, la hipercalcemia o la hipokalemia, y se trata con hidroclorotiazida y amilorida.')])],
      ['Na bajo', N('q', 'Hiponatremia euvolémica', 'Osm urinaria sobre 100, Na urinario sobre 30',
        'Si hay hiponatremia euvolémica con orina concentrada y sodio urinario alto, y la tiroides, el cortisol y el riñón están normales, es un SIADH.',
        ['Sin síntomas graves', N('ok', 'Restricción hídrica', '500–1000 mL/día',
          'Sin síntomas graves, se restringe el agua a quinientos a mil mililitros al día y se busca la causa.')],
        ['Convulsiones o coma', N('alert', 'Salino hipertónico al 3 %', 'Máximo 8–10 mEq/L en 24 h',
          'Con convulsiones o coma, salino hipertónico al tres por ciento, sin superar ocho a diez miliequivalentes en veinticuatro horas.')])]),
  },
};
