// Clase 7.14 — guion docente escrito a mano (ver gastro-01.cjs para el formato).
// Fuente clínica: books/scripts/dataset_endocrinologia.cjs (endo-14).

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  id: 'endo-14',
  tier: 2,
  slides: [
    {
      type: 'cover',
      subtitle: 'Aldosterona alta con renina suprimida: a quién buscar, cómo confirmar y quién se opera',
      say: 'Bienvenidos. Hoy vemos el hiperaldosteronismo primario, el síndrome de Conn, la causa endocrinológica más frecuente de hipertensión secundaria. En las dos clases anteriores la suprarrenal fallaba; hoy pasa lo contrario: la corteza fabrica aldosterona de más y sin freno. Es un tema muy preguntado, y casi todo se responde con una sola idea: aldosterona alta con renina suprimida.',
    },

    {
      type: 'flow',
      kicker: 'Fisiopatología',
      title: 'Aldosterona sin freno',
      nodes: [
        { id: 'sup', col: 0, row: 1, k: 'cause', t: 'Suprarrenal autónoma', s: 'No obedece a la angiotensina II' },
        { id: 'enac', col: 1, row: 1, k: 'mech', t: 'Canal ENaC activado', s: 'Túbulo colector cortical' },
        { id: 'na', col: 2, row: 0, k: 'effect', t: 'Retiene sodio y volumen', s: 'Hipertensión arterial' },
        { id: 'k', col: 2, row: 2, k: 'effect', t: 'Pierde potasio e H+', s: 'Hipokalemia y alcalosis' },
        { id: 'ren', col: 3, row: 0, k: 'mech', t: 'Renina suprimida', s: 'El volumen frena al riñón' },
        { id: 'sel', col: 4, row: 1, k: 'alert', t: 'Aldosterona alta + renina baja', s: 'Sello del hiperaldosteronismo primario' },
        { id: 'cal', col: 3, row: 2, k: 'effect', t: 'Calambres y debilidad', s: 'Síntomas de la hipokalemia' },
      ],
      edges: [
        { from: 'sup', to: 'enac' },
        { from: 'enac', to: 'na' }, { from: 'enac', to: 'k' },
        { from: 'na', to: 'ren', label: 'suprime' },
        { from: 'k', to: 'cal' },
        { from: 'ren', to: 'sel' },
      ],
      steps: [
        { show: ['sup'], note: 'La corteza produce aldosterona sin control',
          say: 'Partamos por el mecanismo. Normalmente la aldosterona obedece a la renina y a la angiotensina dos. En el hiperaldosteronismo primario, la corteza suprarrenal la produce de forma autónoma, y no la frena ni siquiera una sobrecarga de sodio.' },
        { show: ['enac'], note: 'Actúa en el túbulo colector',
          say: 'Esa aldosterona actúa en el túbulo colector cortical del riñón, donde deja encendido todo el tiempo el canal epitelial de sodio, el ENaC.' },
        { show: ['na'], note: 'Más sodio, más volumen, más presión',
          say: 'El riñón retiene sodio, con el sodio viene el agua, se expande el volumen intravascular y sube la presión. Por eso el paciente llega como un hipertenso.' },
        { show: ['k', 'cal'], note: 'El precio del sodio es el potasio',
          say: 'Pero para retener sodio, el túbulo intercambia y elimina potasio e hidrogeniones. De ahí la hipokalemia y la alcalosis metabólica, y de ahí los calambres, la debilidad muscular y la cefalea que aparecen en las preguntas.' },
        { show: ['ren'], note: 'El volumen expandido apaga la renina',
          say: 'Y aquí está lo más importante. Ese volumen expandido llega al riñón con buena presión de perfusión, y las células yuxtaglomerulares dejan de fabricar renina. La renina queda suprimida.' },
        { show: ['sel'], note: 'Esta dupla es el diagnóstico',
          say: 'Entonces el sello bioquímico es este: aldosterona elevada con renina suprimida. Guárdalo, porque es la base del examen de tamizaje y de la diferencia con el hiperaldosteronismo secundario, que viene más adelante.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Sospecha',
      title: '¿A qué hipertenso hay que estudiar?',
      cards: [
        { title: 'Los clásicos del examen', tag: 'Sospecha formal', kind: 'alert', items: [
          { t: 'HTA resistente', d: 'No controla con 3 fármacos, uno diurético',
            say: 'El hiperaldosteronismo primario está en el ocho a diez por ciento de los hipertensos, y hasta en el veinte por ciento de los resistentes. Por eso el primer grupo a estudiar es la hipertensión resistente: la que no se controla con tres antihipertensivos a dosis plenas, incluyendo un diurético.' },
          { t: 'HTA con hipokalemia', d: 'Espontánea o con tiazida en dosis baja',
            say: 'El segundo, la hipertensión con hipokalemia, ya sea espontánea o provocada por una tiazida en dosis baja. Una tiazida en dosis baja no debería bajar tanto el potasio; si lo hace, sospecha.' },
          { t: 'HTA en el joven', d: 'Inicio antes de los 35 a 40 años',
            say: 'El tercero, la hipertensión que empieza temprano, antes de los treinta y cinco a cuarenta años. Un joven hipertenso sin explicación se estudia.' },
        ] },
        { title: 'Otros escenarios', tag: 'También se estudian', kind: 'criteria', items: [
          { t: 'Incidentaloma suprarrenal', d: 'En un paciente hipertenso',
            say: 'Además, el incidentaloma suprarrenal en un paciente hipertenso: esa masa puede ser justamente un adenoma productor de aldosterona.' },
          { t: 'Apnea del sueño o familia', d: 'HTA precoz o ACV antes de los 40',
            say: 'Y la hipertensión asociada a apnea obstructiva del sueño, o con historia familiar de hipertensión precoz o de accidente cerebrovascular antes de los cuarenta años.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Diagnóstico bioquímico',
      title: 'Primero la RAR, después la confirmación',
      nodes: [
        { id: 'pre', col: 0, row: 1, k: 'start', t: 'Preparar al paciente', s: 'Corregir K+ · suspender espironolactona' },
        { id: 'rar', col: 1, row: 1, k: 'q', t: 'Relación aldosterona / renina', s: 'Examen de tamizaje' },
        { id: 'pos', col: 2, row: 0, k: 'risk', t: 'RAR > 20–30 + aldosterona > 15', s: 'Sospecha positiva' },
        { id: 'neg', col: 2, row: 2, k: 'good', t: 'RAR normal o renina alta', s: 'Hiperaldosteronismo primario improbable' },
        { id: 'sal', col: 3, row: 0, k: 'mech', t: 'Sobrecarga salina', s: '2 L de SF en 4 h u oral por 3 días' },
        { id: 'con', col: 4, row: 0, k: 'alert', t: 'Aldosterona no se suprime', s: 'Confirmado' },
      ],
      edges: [
        { from: 'pre', to: 'rar' },
        { from: 'rar', to: 'pos', label: 'elevada' }, { from: 'rar', to: 'neg', label: 'normal' },
        { from: 'pos', to: 'sal', label: 'confirmar' }, { from: 'sal', to: 'con' },
      ],
      steps: [
        { show: ['pre'], note: 'Dos condiciones antes de medir',
          say: 'Pasemos al diagnóstico. Antes de medir hay dos condiciones. Primero, corregir la hipokalemia, porque la hipokalemia frena la secreción de aldosterona y da falsos negativos. Segundo, suspender la espironolactona o la eplerenona al menos cuatro a seis semanas antes.' },
        { show: ['rar'], note: 'Tamizaje de elección: la RAR',
          say: 'El examen de tamizaje de elección es la relación aldosterona renina, la RAR: aldosterona plasmática dividida por la actividad de renina plasmática, medidas al mismo tiempo. Fíjate que no se pide la aldosterona sola: lo que la delata es la aldosterona alta frente a una renina apagada.' },
        { show: ['pos'], note: 'Los dos números que se preguntan',
          say: 'Es fuertemente sugerente una RAR sobre veinte a treinta, con una aldosterona plasmática sobre quince nanogramos por decilitro. Se necesitan las dos cosas.' },
        { show: ['neg'], note: 'Renina alta: pensar en otra causa',
          say: 'Si la RAR es normal, o la renina está alta, el hiperaldosteronismo primario es improbable, y piensas en hipertensión renovascular o esencial.' },
        { show: ['sal', 'con'], note: 'Lo sano se suprime; lo autónomo, no',
          say: 'Una RAR positiva se confirma con sobrecarga de sal: dos litros de suero fisiológico endovenoso en cuatro horas, o sal oral por tres días. En una persona sana la aldosterona se suprime bajo cinco a diez nanogramos por decilitro. En el hiperaldosteronismo primario no baja, porque es autónoma. Y recién ahí se piden imágenes.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'Etiología y tratamiento',
      title: '¿Adenoma o hiperplasia? Eso decide la conducta',
      nodes: [
        { id: 'tc', col: 0, row: 1, k: 'start', t: 'TC suprarrenal de corte fino', s: 'Solo con diagnóstico bioquímico' },
        { id: 'mv', col: 1, row: 1, k: 'q', t: 'Muestreo venoso suprarrenal', s: 'Estándar de oro de lateralización' },
        { id: 'ade', col: 2, row: 0, k: 'risk', t: 'Adenoma unilateral · Conn', s: '30–35 %' },
        { id: 'hip', col: 2, row: 2, k: 'risk', t: 'Hiperplasia bilateral', s: '60–65 %, la más frecuente' },
        { id: 'cir', col: 3, row: 0, k: 'good', t: 'Suprarrenalectomía laparoscópica', s: 'Unilateral y curativa' },
        { id: 'esp', col: 3, row: 2, k: 'good', t: 'Espironolactona 25–100 mg/día', s: 'Tratamiento médico indefinido' },
        { id: 'epl', col: 4, row: 2, k: 'refer', t: 'Eplerenona', s: 'Si ginecomastia o disfunción sexual' },
      ],
      edges: [
        { from: 'tc', to: 'mv', label: 'si va a cirugía' },
        { from: 'mv', to: 'ade', label: 'unilateral' }, { from: 'mv', to: 'hip', label: 'bilateral' },
        { from: 'ade', to: 'cir' }, { from: 'hip', to: 'esp' },
        { from: 'esp', to: 'epl', label: 'efecto antiandrogénico' },
      ],
      steps: [
        { show: ['tc'], note: 'La imagen va después de la bioquímica',
          say: 'Con el diagnóstico bioquímico confirmado, buscamos la causa. La localización parte con una tomografía computarizada de suprarrenales de corte fino. Ojo con el orden: la imagen nunca va primero.' },
        { show: ['mv'], note: 'Confirma que el exceso viene de un solo lado',
          say: 'Si el paciente es candidato a cirugía, el estándar de oro para confirmar que el exceso viene de un solo lado es el muestreo venoso suprarrenal, que compara el gradiente de aldosterona sobre cortisol de cada glándula.' },
        { show: ['hip'], note: 'Lo más frecuente es la hiperplasia',
          say: 'Y aquí hay un dato que se pregunta: la causa más frecuente no es el adenoma. Es la hiperplasia suprarrenal bilateral idiopática, con el sesenta a sesenta y cinco por ciento de los casos.' },
        { show: ['ade'], note: 'El Conn clásico: un nódulo en un lado',
          say: 'El adenoma productor de aldosterona, el síndrome de Conn propiamente tal, es un tumor benigno, unilateral y bien delimitado, y explica el treinta a treinta y cinco por ciento.' },
        { show: ['cir'], note: 'Unilateral: se opera y se cura',
          say: 'Si es un adenoma unilateral, el tratamiento curativo es la suprarrenalectomía laparoscópica de ese lado. Normaliza el potasio y cura o mejora mucho la presión.' },
        { show: ['esp'], note: 'Bilateral: tratamiento médico de por vida',
          say: 'Si es bilateral, o el paciente no es quirúrgico, el tratamiento es médico e indefinido, con un antagonista del receptor mineralocorticoide: espironolactona, veinticinco a cien miligramos al día. Sacar las dos suprarrenales dejaría al paciente con un Addison de por vida, lo que vimos hace dos clases.' },
        { show: ['epl'], note: 'Cambio por efecto antiandrogénico',
          say: 'La espironolactona tiene efecto antiandrogénico. Si el hombre presenta ginecomastia dolorosa o disfunción sexual, se cambia a eplerenona, que bloquea el receptor mineralocorticoide de forma selectiva. En el seguimiento controlas presión, potasio y función renal.' },
      ],
    },

    {
      type: 'pathway',
      intro: 'Ahora juntemos todo en un solo árbol de decisión, tal como lo vas a razonar en el examen.',
    },

    {
      type: 'table',
      kicker: 'Trampas EUNACOM',
      title: 'Hiperaldosteronismo primario frente a secundario',
      head: ['Parámetro', 'Primario (Conn o hiperplasia)', 'Secundario (estenosis renal)'],
      rows: [
        { cells: ['Mecanismo', 'Suprarrenal autónoma', 'Hipoperfusión renal activa el SRAA'],
          say: 'La trampa clásica es confundir el primario con el secundario, porque los dos tienen aldosterona alta, hipertensión e hipokalemia. La diferencia está en el origen: en el primario manda la suprarrenal; en el secundario, un riñón mal perfundido que activa todo el eje renina angiotensina aldosterona.' },
        { cells: ['Renina plasmática', 'Suprimida (< 0,6 ng/mL/h)', 'Francamente elevada (> 5 ng/mL/h)'],
          say: 'Por eso el dato que separa es la renina: suprimida en el primario, bajo cero coma seis, y francamente elevada en el secundario, sobre cinco.' },
        { cells: ['Aldosterona', 'Elevada', 'Elevada (por angiotensina II)'],
          say: 'La aldosterona está alta en ambos, así que por sí sola no sirve para distinguirlos.' },
        { cells: ['RAR', 'Muy elevada (> 20–30)', 'Baja o normal (< 10)'],
          say: 'Y la relación aldosterona renina lo resume: muy elevada en el primario, baja o normal en el secundario, porque ahí la renina sube junto con la aldosterona.' },
        { cells: ['Causas', 'Adenoma de Conn, hiperplasia bilateral', 'Estenosis de arteria renal, coartación, insuficiencia cardíaca'],
          say: 'Las causas del secundario son la estenosis de la arteria renal, la coartación aórtica y la insuficiencia cardíaca. Un soplo abdominal o un adulto mayor con aterosclerosis te inclinan a lo renovascular.' },
        { cells: ['Tratamiento', 'Cirugía si Conn / espironolactona', 'Angioplastia con stent / tratar la cardiopatía'],
          say: 'Y el tratamiento sigue a la causa: cirugía o espironolactona en el primario; angioplastia con stent renal o manejo de la cardiopatía en el secundario.' },
      ],
    },

    {
      type: 'quiz',
      kicker: 'Caso clínico',
      title: 'Caso clínico',
      stem: 'Hombre de 52 años con hiperaldosteronismo primario confirmado por RAR elevada y test de sobrecarga salina. La TC muestra hiperplasia suprarrenal bilateral. Inició espironolactona 50 mg/día con buen control de presión y potasio normal, pero a los 4 meses consulta por aumento de volumen mamario doloroso bilateral.',
      question: '¿Cuál es la conducta más adecuada?',
      options: [
        { letter: 'A', text: 'Suprarrenalectomía laparoscópica bilateral' },
        { letter: 'B', text: 'Cambiar espironolactona por eplerenona' },
        { letter: 'C', text: 'Aumentar espironolactona a 100 mg/día' },
        { letter: 'D', text: 'Suspender espironolactona e indicar hidroclorotiazida' },
        { letter: 'E', text: 'Solicitar muestreo venoso suprarrenal' },
      ],
      correct: 'B',
      explanation: 'La hiperplasia bilateral se trata de por vida con un antagonista mineralocorticoide. La ginecomastia es el efecto antiandrogénico de la espironolactona: se rota a eplerenona, selectiva. La cirugía bilateral dejaría una insuficiencia suprarrenal permanente, y una tiazida empeoraría la hipokalemia.',
      say: {
        stem: 'Vamos con un caso. Hombre de cincuenta y dos años con hiperaldosteronismo primario confirmado, con RAR elevada y test de sobrecarga salina. La tomografía muestra hiperplasia suprarrenal bilateral. Empezó espironolactona cincuenta miligramos al día, con buen control de la presión y potasio normal, pero a los cuatro meses consulta por aumento de volumen mamario doloroso en ambos lados.',
        question: '¿Cuál es la conducta más adecuada?',
        options: 'Las alternativas: suprarrenalectomía bilateral, cambiar a eplerenona, subir la espironolactona a cien miligramos, suspenderla e indicar hidroclorotiazida, o pedir un muestreo venoso. Piénsalo.',
        answer: 'Es la B. La hiperplasia bilateral necesita un antagonista mineralocorticoide de por vida, y la ginecomastia es el efecto antiandrogénico de la espironolactona: se cambia a eplerenona. El distractor tentador es la cirugía, pero sacar las dos suprarrenales deja un Addison permanente. Y la tiazida sola empeoraría el potasio sin tratar la causa.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2019 · Pregunta 45',
      stem: 'Una paciente de 60 años presenta cefalea, astenia, debilidad muscular y calambres en extremidades inferiores. Al examen físico se observa obeso, con PA: 170/100 mmHg, FC: 70 lpm y en sus exámenes destaca Na: 150 mEq/L, K: 2.6 mEq/L, Cl:100 mEq/L y TSH: 4.0 UI/L.',
      question: 'La causa más probable de la hipertensión es:',
      options: [
        { letter: 'A', text: 'Hipertensión renovascular' },
        { letter: 'B', text: 'Feocromocitoma' },
        { letter: 'C', text: 'Hipotiroidismo' },
        { letter: 'D', text: 'Hiperaldosteronismo primario' },
        { letter: 'E', text: 'Hipertensión esencial' },
      ],
      correct: 'D',
      explanation: 'Hipertensión con hipokalemia marcada y síntomas de hipokalemia (calambres, debilidad, cefalea): hiperaldosteronismo primario clásico. La renovascular también puede dar hipokalemia por hiperaldosteronismo secundario, pero se sospecha con soplo abdominal o antecedente cardiovascular.',
      say: {
        stem: 'Ahora preguntas reales. Esta es del EUNACOM de diciembre de dos mil diecinueve. Paciente de sesenta años con cefalea, astenia, debilidad muscular y calambres en las piernas. Presión de ciento setenta sobre cien, sodio ciento cincuenta, potasio dos coma seis y TSH normal.',
        question: '¿Cuál es la causa más probable de la hipertensión?',
        options: 'Las opciones son: hipertensión renovascular, feocromocitoma, hipotiroidismo, hiperaldosteronismo primario o hipertensión esencial. Piénsalo.',
        answer: 'Es la D, hiperaldosteronismo primario. Hipertensión con potasio bajo, sodio en el límite alto y los síntomas de la hipokalemia: calambres y debilidad. El distractor tentador es la renovascular, porque también puede bajar el potasio por el hiperaldosteronismo secundario; pero para elegirla necesitarías un soplo abdominal o antecedentes cardiovasculares.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2022 · Pregunta 121',
      stem: 'Un paciente de 37 años es diagnosticado de hipertensión hace un año, en tratamiento con enalapril, atenolol e hidroclorotiazida, a pesar de lo cual ha presentado valores tensionales sobre el objetivo, con varias tomas sobre 160/110 mmHg. Además, aqueja astenia, debilidad de las extremidades inferiores y cefalea frecuente. Se solicitan exámenes generales, que muestran TSH: 6,0 UI/L, creatinina: 1,2 mg/dl, sodio: 142 mEq/L, potasio: 3,1 mEq/L, hemograma normal y glicemia de ayuno: 72 mg/dl. Se solicita TAC de abdomen, que muestra un tumor suprarrenal derecho, de 2 cm de diámetro, sólido y homogéneo.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Feocromocitoma' },
        { letter: 'B', text: 'Hipertensión esencial' },
        { letter: 'C', text: 'Hipertensión renovascular' },
        { letter: 'D', text: 'Hipertensión asociada a insuficiencia renal' },
        { letter: 'E', text: 'Hiperaldosteronismo primario' },
      ],
      correct: 'E',
      explanation: 'Joven, HTA resistente a tres fármacos con diurético, hipokalemia con síntomas y un nódulo suprarrenal pequeño y homogéneo: adenoma productor de aldosterona (Conn). El feocromocitoma daría crisis paroxísticas, no hipokalemia.',
      say: {
        stem: 'Otra real, del EUNACOM de diciembre de dos mil veintidós. Hombre de treinta y siete años, hipertenso hace un año, con enalapril, atenolol e hidroclorotiazida, y aun así con presiones sobre ciento sesenta sobre ciento diez. Tiene astenia, debilidad de las piernas y cefalea. El potasio es tres coma uno, y el scanner muestra un tumor suprarrenal derecho de dos centímetros, sólido y homogéneo.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones son: feocromocitoma, hipertensión esencial, renovascular, asociada a insuficiencia renal, o hiperaldosteronismo primario. Piénsalo.',
        answer: 'Es la E. Suma los criterios de sospecha: joven, hipertensión resistente a tres fármacos con un diurético, e hipokalemia con síntomas. Y el nódulo pequeño y homogéneo calza con un adenoma de Conn. El distractor es el feocromocitoma, porque también hay un tumor suprarrenal, pero el feocromocitoma da crisis paroxísticas, no hipokalemia. Ese es el tema de la próxima clase.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2025 · Pregunta 171',
      stem: 'Un paciente de 37 años acude a chequeo médico en el que destaca presión arterial de 170/110 mmHg. No tiene obesidad ni antecedentes familiares de hipertensión. Se solicita un monitoreo ambulatorio de presión arterial de 24 horas, confirmándose el diagnóstico de hipertensión arterial, por lo que se inicia losartán 50 mg al día y amlodipino 5 mg al día. Se controla un mes después y el paciente refiere que ha mantenido presiones arteriales cercanas a 160/100 mmHg. Los exámenes de laboratorio muestran creatininemia: 0,9 mg/dL, BUN: 12 mg/dL, sodio plasmático: 140 mEq/L y potasio plasmático: 4,4 mEq/L.',
      question: '¿Cuál es la conducta más adecuada?',
      options: [
        { letter: 'A', text: 'Aumentar la dosis de los fármacos' },
        { letter: 'B', text: 'Agregar un diurético al tratamiento' },
        { letter: 'C', text: 'Solicitar ecografía Doppler renal' },
        { letter: 'D', text: 'Solicitar niveles plasmáticos de aldosterona' },
        { letter: 'E', text: 'Solicitar metanefrinas y catecolaminas en orina' },
      ],
      correct: 'D',
      explanation: 'HTA severa en un joven sin obesidad ni antecedentes familiares: sospecha de HTA secundaria. Por la edad, la causa más probable es el hiperaldosteronismo primario, que se estudia con aldosterona (idealmente como RAR). El potasio normal no lo descarta, sobre todo si usa ARA II.',
      say: {
        stem: 'Del EUNACOM de diciembre de dos mil veinticinco. Hombre de treinta y siete años, sin obesidad ni antecedentes familiares, con presión de ciento setenta sobre ciento diez confirmada por monitoreo. Con losartán y amlodipino sigue cerca de ciento sesenta sobre cien. La creatinina y el sodio son normales, y el potasio es cuatro coma cuatro.',
        question: '¿Cuál es la conducta más adecuada?',
        options: 'Las opciones: subir las dosis, agregar un diurético, pedir ecografía Doppler renal, pedir aldosterona plasmática, o pedir metanefrinas y catecolaminas en orina. Piénsalo.',
        answer: 'Es la D. Un joven con hipertensión severa y sin factores que la expliquen tiene sospecha de hipertensión secundaria, y a esta edad la causa más probable es el hiperaldosteronismo primario, idealmente con la RAR. Esta pregunta enseña algo nuevo: el potasio normal no lo descarta, y menos si toma losartán, que tiende a subir el potasio. El feocromocitoma cae porque no hay crisis paroxísticas.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2022 · Pregunta 51',
      stem: 'Un paciente de 40 años, con antecedente de hipertensión arterial diagnosticada hace 6 meses, de difícil manejo, acude a control. Toma hidroclorotiazida 50 mg/día, losartán 100 mg/día y amlodipino 10 mg/día. Refiere varias crisis hipertensivas, a pesar de una buena adherencia a su tratamiento farmacológico. En el examen físico, su presión arterial actual es 158/97, que es similar a los valores que habitualmente presenta en su casa; su frecuencia cardíaca es 65x’ y su examen cardiopulmonar muestra ritmo regular en dos tiempos, sin soplos y murmullo pulmonar presente, sin ruidos agregados. Trae un monitoreo de presión arterial con presión arterial promedio de 160/101 mmHg, con que muestra cargas tensionales diurnas de 77% sistólica y 63% diastólica y cargas tensionales nocturnas de 67% sistólica y 56% diastólica.',
      question: '¿Cuál es la conducta más adecuada?',
      options: [
        { letter: 'A', text: 'Reemplazar el losartán por un IECA' },
        { letter: 'B', text: 'Reemplazar la hidroclorotiazida por un diurético antialdosterónico' },
        { letter: 'C', text: 'Agregar doxazosina al tratamiento' },
        { letter: 'D', text: 'Agregar espironolactona y solicitar exámenes para descartar una hipertensión secundaria' },
        { letter: 'E', text: 'Reemplazar el amlodipino por diltiazem' },
      ],
      correct: 'D',
      explanation: 'Tres fármacos a dosis plenas, uno de ellos diurético, con buena adherencia y monitoreo que confirma presiones altas: HTA resistente. Se agrega espironolactona como cuarto fármaco y se estudia una causa secundaria, partiendo por el hiperaldosteronismo primario.',
      say: {
        stem: 'La última real, también del EUNACOM de diciembre de dos mil veintidós. Hombre de cuarenta años, con hidroclorotiazida, losartán y amlodipino a dosis plenas, buena adherencia, y un monitoreo de veinticuatro horas con promedio de ciento sesenta sobre ciento uno.',
        question: '¿Cuál es la conducta más adecuada?',
        options: 'Las opciones: cambiar el losartán por un IECA, reemplazar la tiazida por un antialdosterónico, agregar doxazosina, agregar espironolactona y estudiar hipertensión secundaria, o cambiar amlodipino por diltiazem. Piénsalo.',
        answer: 'Es la D. Tres fármacos a dosis plenas, uno diurético, con buena adherencia y el monitoreo confirmando: es una hipertensión resistente, el primer criterio de sospecha que vimos. Se agrega espironolactona como cuarto fármaco y se busca la causa secundaria. El distractor es la B: reemplazar la tiazida le quita un fármaco al esquema en vez de sumar, y no estudia la causa.',
      },
    },

    {
      type: 'points',
      kicker: 'Cierre',
      title: 'Reglas de oro para el examen',
      cards: [
        { title: 'Sospecha y tamizaje', tag: 'La puerta de entrada', kind: 'key', items: [
          { t: 'Resistente, hipokalemia o joven', d: 'Son los tres gatillos clásicos',
            say: 'Cerremos con las reglas de oro. Se estudia al hipertenso resistente, al que tiene hipokalemia y al joven. Y recuerda: el potasio normal no descarta.' },
          { t: 'RAR primero, imagen después', d: 'Corregir K+ y suspender espironolactona',
            say: 'El tamizaje es la relación aldosterona renina, con el potasio corregido y sin espironolactona. La tomografía viene solo después de confirmar.' },
        ] },
        { title: 'La diferencia clave', tag: 'Se pregunta', kind: 'alert', items: [
          { t: 'Primario: renina suprimida', d: 'Secundario: renina elevada',
            say: 'Primario y secundario tienen aldosterona alta; lo que los separa es la renina: suprimida en el primario, alta en el secundario.' },
        ] },
        { title: 'Tratamiento', tag: 'Según la causa', kind: 'pharma', items: [
          { t: 'Adenoma unilateral', d: 'Suprarrenalectomía laparoscópica',
            say: 'El adenoma unilateral se opera y se cura con suprarrenalectomía laparoscópica.' },
          { t: 'Hiperplasia bilateral', d: 'Espironolactona; eplerenona si ginecomastia',
            say: 'La hiperplasia bilateral, que es la más frecuente, va con espironolactona de por vida, y eplerenona si aparece ginecomastia. Si te llevas una sola idea de hoy: aldosterona alta con renina suprimida es hiperaldosteronismo primario, y lo que decide la conducta es si es uno o dos lados. Nos vemos en la próxima clase.' },
        ] },
      ],
    },
  ],

  pathway: {
    title: 'Hiperaldosteronismo primario: de la sospecha al tratamiento',
    root: N('start', 'Hipertenso con sospecha', 'Resistente, hipokalemia o joven',
      'Hipertenso resistente, con hipokalemia, joven, o con un incidentaloma. La pregunta no es la imagen: es la bioquímica.',
      ['', N('q', '¿RAR elevada con aldosterona alta?', 'Con K+ corregido y sin espironolactona',
        'Con el potasio corregido y sin espironolactona, pides la relación aldosterona renina. ¿Está sobre veinte a treinta, con aldosterona sobre quince?',
        ['No', N('refer', 'Primario improbable', 'Pensar en renovascular o esencial',
          'Si la RAR es normal o la renina está alta, el primario es improbable. Piensas en hipertensión renovascular o esencial.')],
        ['Sí', N('q', '¿Se suprime y de qué lado viene?', 'Sobrecarga salina · TC · muestreo venoso',
          'Si es positiva, confirmas con sobrecarga de sal, y si la aldosterona no se suprime, buscas la causa con tomografía y, si va a cirugía, muestreo venoso. ¿Se suprime? ¿Viene de uno o de los dos lados?',
          ['Se suprime', N('refer', 'Primario descartado', 'Reevaluar la causa',
            'Si la aldosterona se suprime con la sal, el eje funciona y no es un hiperaldosteronismo primario.')],
          ['No · unilateral', N('ok', 'Suprarrenalectomía laparoscópica', 'Adenoma de Conn: curativa',
            'Si no se suprime y el exceso viene de un lado, es el adenoma de Conn: suprarrenalectomía laparoscópica, que es curativa.')],
          ['No · bilateral', N('do', 'Espironolactona de por vida', 'Eplerenona si ginecomastia',
            'Si viene de los dos lados, es la hiperplasia: espironolactona indefinida, controlando presión, potasio y función renal. Y si aparece ginecomastia o disfunción sexual, cambias a eplerenona.')])])]),
  },
};
