// Clase 7.16 — guion docente escrito a mano (ver gastro-01.cjs para el formato).
// Fuente clínica: books/scripts/dataset_endocrinologia.cjs (endo-16).

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  id: 'endo-16',
  tier: 3,
  slides: [
    {
      type: 'cover',
      subtitle: 'Corregir por albúmina, pedir PTH y, en la crisis, suero fisiológico antes que todo',
      say: 'Bienvenidos. Hoy abrimos el bloque de calcio y hueso con la hipercalcemia y el hiperparatiroidismo primario, un tema de frecuencia muy alta en el examen. Más del noventa por ciento se debe a dos causas: el hiperparatiroidismo primario, la más frecuente en el ambulatorio, y la hipercalcemia maligna, la más frecuente en el hospitalizado. Casi todas las preguntas se responden con tres pasos: corregir el calcio, medir la PTH y, si hay crisis, hidratar.',
    },

    {
      type: 'points',
      kicker: 'Fisiología',
      title: 'Primero, ¿el calcio está realmente alto?',
      cards: [
        { title: 'Tres fracciones', tag: 'Calcio total', kind: 'key', items: [
          { t: '50 % iónico libre', d: 'El activo, regulado por la PTH',
            say: 'Partamos por lo básico, porque aquí está la primera trampa. El calcio de la sangre tiene tres fracciones. La mitad es calcio iónico libre, que es el biológicamente activo y el que regula la PTH.' },
          { t: '40 % unido a albúmina', d: '10 % unido a aniones',
            say: 'El cuarenta por ciento viaja unido a proteínas, sobre todo a la albúmina, y el diez por ciento restante unido a aniones como el citrato y el fosfato. El laboratorio informa el total, las tres fracciones juntas.' },
        ] },
        { title: 'Corrección por albúmina', tag: 'Obligatoria', kind: 'alert', items: [
          { t: 'Ca corregido = Ca + 0,8 × (4 − albúmina)', d: 'En mg/dL, con albúmina en g/dL',
            say: 'Entonces, si la albúmina está baja, el calcio total baja aunque el iónico esté normal o incluso alto. Por eso se corrige siempre: al calcio medido le sumas cero coma ocho por cada gramo que la albúmina esté bajo cuatro.' },
          { t: 'Albúmina baja oculta hipercalcemia', d: 'Desnutrición, hepatopatía, sepsis',
            say: 'Un ejemplo que se ha preguntado: calcio de nueve coma ocho con albúmina de tres. Parece normal, pero corregido es diez coma seis: hay hipercalcemia. Piensa en esto en el desnutrido, el cirrótico o el séptico.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Fisiopatología',
      title: '¿Qué hace la PTH?',
      nodes: [
        { id: 'pth', col: 0, row: 1, k: 'cause', t: 'PTH', s: 'Hormona paratiroidea' },
        { id: 'hue', col: 1, row: 0, k: 'mech', t: 'Resorción ósea', s: 'Libera calcio y fósforo' },
        { id: 'dis', col: 1, row: 1, k: 'mech', t: 'Túbulo distal', s: 'Reabsorbe calcio' },
        { id: 'pro', col: 1, row: 2, k: 'mech', t: 'Túbulo proximal', s: 'Bota fosfato' },
        { id: 'vd', col: 1, row: 3, k: 'mech', t: '1-alfa-hidroxilasa renal', s: 'Activa el calcitriol' },
        { id: 'int', col: 2, row: 3, k: 'effect', t: 'Absorción intestinal', s: 'Más calcio desde el intestino' },
        { id: 'hca', col: 3, row: 1, k: 'alert', t: 'Hipercalcemia', s: 'Con hipofosfatemia' },
      ],
      edges: [
        { from: 'pth', to: 'hue' }, { from: 'pth', to: 'dis' }, { from: 'pth', to: 'pro' }, { from: 'pth', to: 'vd' },
        { from: 'vd', to: 'int' },
        { from: 'hue', to: 'hca' }, { from: 'dis', to: 'hca' }, { from: 'int', to: 'hca' },
        { from: 'pro', to: 'hca', label: 'fósforo bajo' },
      ],
      steps: [
        { show: ['pth'], note: 'Una hormona, cuatro acciones',
          say: 'Ahora el mecanismo, porque explica los exámenes. La PTH tiene una sola meta, subir el calcio, y lo hace por cuatro caminos.' },
        { show: ['hue'], note: 'Saca calcio del hueso',
          say: 'Primero, estimula a los osteoclastos a reabsorber hueso, y así libera calcio y fósforo a la sangre.' },
        { show: ['dis'], note: 'Ahorra calcio en el riñón',
          say: 'Segundo, en el túbulo distal aumenta la reabsorción de calcio.' },
        { show: ['pro'], note: 'Bota fósforo por la orina',
          say: 'Tercero, en el túbulo proximal inhibe la reabsorción de fosfato, y el fósforo se va por la orina. Esto es clave: por eso el hiperparatiroidismo primario tiene el fósforo bajo.' },
        { show: ['vd', 'int'], note: 'Activa la vitamina D',
          say: 'Y cuarto, activa la uno alfa hidroxilasa del riñón, que convierte la vitamina D en calcitriol, la forma activa, y el calcitriol aumenta la absorción de calcio en el intestino.' },
        { show: ['hca'], note: 'La firma del exceso de PTH',
          say: 'Si la PTH está en exceso, el resultado es predecible: calcio alto con fósforo bajo. Guarda esa dupla, porque junto con la PTH elevada es la tríada del hiperparatiroidismo primario.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'Diagnóstico etiológico',
      title: 'La PTH divide el camino',
      nodes: [
        { id: 'hc', col: 0, row: 1, k: 'start', t: 'Hipercalcemia confirmada', s: 'Calcio corregido > 10,5 mg/dL' },
        { id: 'pth', col: 1, row: 1, k: 'q', t: 'PTH intacta', s: 'El primer examen obligatorio' },
        { id: 'alt', col: 2, row: 0, k: 'risk', t: 'Alta o inapropiadamente normal', s: 'PTH dependiente' },
        { id: 'hpt', col: 3, row: 0, k: 'alert', t: 'Hiperparatiroidismo primario', s: 'Adenoma único 85 %' },
        { id: 'sup', col: 2, row: 2, k: 'risk', t: 'Suprimida (< 10 pg/mL)', s: 'PTH independiente' },
        { id: 'neo', col: 3, row: 2, k: 'alert', t: 'Neoplasia o vitamina D', s: 'PTHrP, osteólisis, calcitriol' },
      ],
      edges: [
        { from: 'hc', to: 'pth' },
        { from: 'pth', to: 'alt', label: 'no suprimida' }, { from: 'alt', to: 'hpt' },
        { from: 'pth', to: 'sup', label: 'suprimida' }, { from: 'sup', to: 'neo' },
      ],
      steps: [
        { show: ['hc', 'pth'], note: 'Ante toda hipercalcemia: PTH',
          say: 'Con la hipercalcemia confirmada, el primer examen obligatorio es la PTH intacta. No la vitamina D, no la cintigrafía: la PTH. Y esto vale incluso si el paciente tiene un cáncer conocido.' },
        { show: ['alt'], note: 'Normal no es normal si el calcio está alto',
          say: 'Si el calcio está alto, la paratiroides sana debería apagarse. Entonces una PTH elevada, o una PTH en rango normal, que en este contexto es inapropiadamente normal, significa que la paratiroides no se está frenando. Ojo con esa palabra, inapropiadamente: se pregunta.' },
        { show: ['hpt'], note: 'Adenoma, hiperplasia o carcinoma',
          say: 'Eso es hiperparatiroidismo primario. En el ochenta y cinco por ciento es un adenoma único benigno; en el doce a quince por ciento, hiperplasia de las cuatro glándulas, asociada a las neoplasias endocrinas múltiples uno y dos A, esta última la vimos con el feocromocitoma; y en menos del uno por ciento, un carcinoma paratiroideo.' },
        { show: ['sup'], note: 'La paratiroides se frenó: la causa está afuera',
          say: 'Si en cambio la PTH está intensamente suprimida, bajo diez, la paratiroides está haciendo lo correcto, y el calcio viene de otro lado.' },
        { show: ['neo'], note: 'Pensar en cáncer',
          say: 'Lo más frecuente es una neoplasia. Y lo que tienes que retener es el contraste: PTH alta o normal, hiperparatiroidismo; PTH suprimida, cáncer o vitamina D.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Hipercalcemia PTH independiente',
      title: 'Cuatro mecanismos con la PTH suprimida',
      cards: [
        { title: 'Neoplasias', tag: 'La más frecuente', kind: 'alert', items: [
          { t: 'PTHrP · 80 %', d: 'Epidermoide de pulmón, esófago, cabeza y cuello, cérvix, riñón',
            say: 'Veamos los mecanismos cuando la PTH está suprimida. El más frecuente, en el ochenta por ciento de las neoplasias, es la secreción del péptido relacionado con la PTH, que imita a la PTH pero no se mide como PTH. Piensa en los carcinomas epidermoides de pulmón, esófago, cabeza y cuello o cérvix, y en el cáncer renal.' },
          { t: 'Metástasis osteolíticas', d: 'Mama, mieloma múltiple',
            say: 'El segundo son las metástasis osteolíticas, que destruyen hueso localmente mediante citoquinas: el cáncer de mama y el mieloma múltiple.' },
        ] },
        { title: 'Exceso de calcitriol', tag: 'Responde a corticoides', kind: 'criteria', items: [
          { t: 'Linfomas', d: 'Producen calcitriol',
            say: 'El tercero es el exceso de calcitriol: algunos linfomas, Hodgkin y no Hodgkin, fabrican su propia vitamina D activa.' },
          { t: 'Granulomas', d: 'Sarcoidosis, tuberculosis',
            say: 'Y el cuarto, las enfermedades granulomatosas, como la sarcoidosis y la tuberculosis, cuyos macrófagos tienen uno alfa hidroxilasa propia. Estos dos últimos grupos son los que responden a corticoides, y eso lo vamos a usar en el tratamiento.' },
        ] },
      ],
    },

    {
      type: 'table',
      kicker: 'Diagnóstico diferencial',
      title: 'Cómo separar las hipercalcemias',
      head: ['Entidad', 'PTH intacta', 'Fósforo · calciuria', 'Causa'],
      rows: [
        { cells: ['Hiperparatiroidismo primario', 'Alta o inapropiadamente normal', 'Bajo (< 2,5) · normal o alta', 'Adenoma único (85 %)'],
          say: 'Pongamos las causas lado a lado. Hiperparatiroidismo primario: calcio leve a moderadamente alto, PTH alta o inapropiadamente normal, fósforo bajo, bajo dos coma cinco, y calciuria normal o alta.' },
        { cells: ['Maligna por PTHrP', 'Suprimida', 'Bajo o normal · muy alta', 'Epidermoide, mama, riñón'],
          say: 'Hipercalcemia maligna por PTHrP: calcio muy alto, sobre trece a catorce, con la PTH suprimida. El fósforo puede estar bajo o normal, así que el fósforo solo no la separa del hiperparatiroidismo: la separa la PTH.' },
        { cells: ['Maligna por osteólisis', 'Suprimida', 'Alto o normal · muy alta', 'Mieloma, metástasis'],
          say: 'Por osteólisis: PTH suprimida, y el fósforo normal o alto, porque sale del hueso destruido junto con el calcio.' },
        { cells: ['Hipercalcemia hipocalciúrica familiar', 'Normal o levemente alta', 'Normal · muy baja (FE Ca < 1 %)', 'Mutación del CaSR: no operar'],
          say: 'La hipercalcemia hipocalciúrica familiar es la gran imitadora: calcio levemente alto, bajo once coma cinco, y PTH normal o apenas alta, igual que un hiperparatiroidismo. Lo que la delata es la calciuria muy baja, con excreción fraccionada de calcio bajo uno por ciento. Es una mutación benigna del receptor sensor de calcio, y no se opera.' },
        { cells: ['Toxicidad por vitamina D', 'Suprimida', 'Alto · alta', 'Exceso de ingesta o granulomas'],
          say: 'Y la toxicidad por vitamina D, por exceso de ingesta o granulomas: PTH suprimida y, a diferencia del hiperparatiroidismo, fósforo alto, porque el calcitriol aumenta también la absorción de fósforo.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Clínica',
      title: 'Huesos, cálculos, quejidos y gemidos',
      cards: [
        { title: 'Riñón', tag: 'Stones', kind: 'key', items: [
          { t: 'Poliuria y polidipsia', d: 'Diabetes insípida nefrogénica',
            say: 'La clínica se recuerda con la frase en inglés bones, stones, groans and moans. Parte por el riñón: el calcio alto bloquea la acción de la hormona antidiurética en el túbulo colector, una diabetes insípida nefrogénica. Por eso poliuria, polidipsia, y un paciente que se deshidrata.' },
          { t: 'Litiasis cálcica recurrente', d: 'Nefrocalcinosis, falla renal',
            say: 'Y la litiasis cálcica recurrente, de oxalato o fosfato de calcio, con nefrocalcinosis y falla renal progresiva. Fíjate: un paciente con cálculos a repetición es un candidato clásico a medir calcio y PTH.' },
        ] },
        { title: 'Hueso y abdomen', tag: 'Bones · groans', kind: 'criteria', items: [
          { t: 'Dolor óseo, osteoporosis cortical', d: 'Radio distal; osteítis fibrosa quística',
            say: 'En el hueso, dolores difusos y osteoporosis de predominio cortical, típicamente en el radio distal. En casos avanzados, osteítis fibrosa quística con tumores pardos.' },
          { t: 'Constipación, náuseas, vómitos', d: 'Pancreatitis y úlcera péptica',
            say: 'En el abdomen, constipación pertinaz, náuseas, vómitos y anorexia, además de pancreatitis aguda y úlcera péptica.' },
        ] },
        { title: 'Neuro y corazón', tag: 'Moans', kind: 'alert', items: [
          { t: 'Fatiga, depresión, letargia', d: 'Hiporreflexia, hasta el coma',
            say: 'En lo neuropsiquiátrico, fatiga, debilidad, hiporreflexia, depresión, y en los casos graves psicosis, letargia y coma.' },
          { t: 'QT corto', d: 'HTA y arritmias ventriculares',
            say: 'Y en el electrocardiograma, un dato que se pregunta: el intervalo QT acortado, además de hipertensión y arritmias ventriculares.' },
        ] },
      ],
    },

    {
      type: 'table',
      kicker: 'Severidad',
      title: 'El número del calcio decide dónde se trata',
      head: ['Severidad', 'Calcio corregido', 'Clínica', 'Conducta'],
      rows: [
        { cells: ['Leve', '< 12 mg/dL', 'Asintomático, astenia, constipación', 'Hidratación oral, suspender tiazidas y litio'],
          say: 'La severidad se gradúa por el calcio corregido. Leve, bajo doce: el paciente suele estar asintomático o con astenia y constipación. Se hidrata por boca, se suspenden las tiazidas y el litio, que suben el calcio, y se estudia en forma ambulatoria.' },
        { cells: ['Moderada', '12 a 13,9 mg/dL', 'Poliuria, náuseas, debilidad, deshidratación', 'Hospitalizar, SF EV, bifosfonato según clínica'],
          say: 'Moderada, de doce a trece coma nueve: aparecen la poliuria, las náuseas y la deshidratación. Se hospitaliza, suero fisiológico endovenoso y bifosfonato según la clínica.' },
        { cells: ['Crisis hipercalcémica', '≥ 14 mg/dL', 'Estupor, arritmias, falla renal', 'UCI: SF + zoledronato + calcitonina'],
          say: 'Y la crisis hipercalcémica, desde catorce: deshidratación masiva, colapso hemodinámico, falla renal aguda, estupor o coma. Es una emergencia, va a una unidad de paciente crítico, con suero fisiológico, zoledronato y calcitonina.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'Manejo de urgencia',
      title: 'Crisis hipercalcémica: el orden importa',
      nodes: [
        { id: 'sf', col: 0, row: 1, k: 'good', t: 'Suero fisiológico 0,9 %', s: '200–300 mL/h · 2 a 4 L en 24 h' },
        { id: 'fur', col: 0, row: 3, k: 'trap', t: 'Furosemida de entrada', s: 'Solo si euvolémico y sobrecargado' },
        { id: 'cal', col: 1, row: 0, k: 'mech', t: 'Calcitonina de salmón', s: 'Puente: actúa en 4–6 h' },
        { id: 'zol', col: 1, row: 2, k: 'good', t: 'Ácido zoledrónico 4 mg EV', s: 'En 15 min · efecto en 48–72 h' },
        { id: 'cor', col: 2, row: 1, k: 'refer', t: 'Corticoides', s: 'Linfoma, mieloma, sarcoidosis' },
        { id: 'hd', col: 3, row: 1, k: 'alert', t: 'Hemodiálisis', s: 'Falla renal anúrica o refractaria' },
      ],
      edges: [
        { from: 'sf', to: 'cal', label: 'puente' }, { from: 'sf', to: 'zol' },
        { from: 'sf', to: 'fur', label: 'no antes de hidratar' },
        { from: 'zol', to: 'cor', label: 'si exceso de calcitriol' },
        { from: 'cor', to: 'hd', label: 'si refractario' },
      ],
      steps: [
        { show: ['sf'], note: 'Pilar 1: volumen, antes que todo',
          say: 'Vamos al manejo de la crisis, lo más preguntado del tema. El pilar uno, de máxima prioridad, es el suero fisiológico al cero coma nueve por ciento. Este paciente tiene un déficit de tres a cinco litros por la poliuria y los vómitos. Se infunden doscientos a trescientos mililitros por hora, dos a cuatro litros en las primeras veinticuatro horas.' },
        { show: ['sf'], note: 'El volumen además bota calcio',
          say: '¿Por qué funciona? Porque restaura la filtración glomerular y, al entregar sodio al túbulo proximal, arrastra calcio hacia la orina. Hidratar ya es bajar el calcio.' },
        { show: ['fur'], note: 'La trampa clásica',
          say: 'Y la trampa: la furosemida no es de primera línea. Solo se usa si el paciente ya está euvolémico y aparece sobrecarga de volumen o insuficiencia cardíaca. Dársela a un paciente deshidratado lo empeora.' },
        { show: ['zol'], note: 'Pilar 2: el que controla el calcio',
          say: 'El pilar dos es el bifosfonato endovenoso: ácido zoledrónico cuatro miligramos en quince minutos, o pamidronato sesenta a noventa miligramos en dos a cuatro horas. Frena a los osteoclastos, pero demora: empieza a actuar a las cuarenta y ocho a setenta y dos horas, con el máximo efecto entre los cuatro y siete días. Requiere hidratación previa, y se ajusta si la filtración está bajo treinta.' },
        { show: ['cal'], note: 'Pilar 3: el puente rápido',
          say: 'Mientras tanto, la calcitonina de salmón, cuatro a ocho unidades por kilo subcutánea o intramuscular cada doce horas, baja el calcio en cuatro a seis horas. Es el puente mientras actúa el bifosfonato, porque a las cuarenta y ocho horas pierde efecto por taquifilaxia.' },
        { show: ['cor'], note: 'Pilar 4: solo si hay exceso de calcitriol',
          say: 'Los corticoides, prednisona cuarenta a sesenta miligramos al día o hidrocortisona endovenosa, se reservan para la hipercalcemia por exceso de calcitriol: linfomas, mieloma y sarcoidosis. Demoran dos a cuatro días.' },
        { show: ['hd'], note: 'El último recurso',
          say: 'Y si hay falla renal anúrica severa o refractariedad extrema, hemodiálisis con un baño bajo en calcio.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Hiperparatiroidismo primario',
      title: '¿Quién va a paratiroidectomía?',
      cards: [
        { title: 'Sintomático', tag: 'Cirugía mandatoria', kind: 'alert', items: [
          { t: 'Litiasis, osteoporosis, fracturas', d: 'Paratiroidectomía: única cura',
            say: 'Volvamos al hiperparatiroidismo primario. La paratiroidectomía es el único tratamiento curativo, y en el paciente sintomático, con litiasis, osteoporosis o fracturas, es mandatoria.' },
          { t: 'Localizar antes de operar', d: 'Cintigrama sestamibi y ecografía cervical',
            say: 'Antes de operar se localiza el adenoma con cintigrama con sestamibi y ecografía cervical, lo que permite una cirugía focalizada. Ojo: la localización es para planificar la cirugía, no para diagnosticar. El diagnóstico ya lo hizo la bioquímica.' },
        ] },
        { title: 'Asintomático', tag: 'Basta un criterio', kind: 'criteria', items: [
          { t: 'Menor de 50 años', d: 'O calcio > 1 mg/dL sobre el límite',
            say: 'En el asintomático, se opera si cumple cualquiera de estos criterios. Edad menor de cincuenta años, o un calcio más de uno sobre el límite superior normal, típicamente sobre once coma cinco.' },
          { t: 'Hueso: T-score < −2,5', d: 'Columna, cadera o radio; o fractura vertebral',
            say: 'Compromiso óseo: densitometría con T score bajo menos dos coma cinco en columna, cadera o radio distal, o una fractura vertebral por fragilidad.' },
          { t: 'Riñón: VFG < 60', d: 'Calciuria > 400 mg/día o litiasis en imagen',
            say: 'Y compromiso renal: filtración glomerular bajo sesenta, calciuria de veinticuatro horas sobre cuatrocientos miligramos al día, o litiasis o nefrocalcinosis asintomática en la imagen.' },
        ] },
        { title: 'Después de operar', tag: 'Hueso hambriento', kind: 'pharma', items: [
          { t: 'Hipocalcemia e hipofosfatemia graves', d: 'Calcio y calcitriol agresivos',
            say: 'Y un riesgo postoperatorio que se pregunta: el síndrome del hueso hambriento. Al sacar el adenoma, el hueso desmineralizado capta calcio y fósforo con avidez, y el paciente cae en hipocalcemia severa sintomática con hipofosfatemia profunda. Se trata con calcio y calcitriol agresivos, y se vigilan calcio, fósforo y función renal. De la hipocalcemia hablamos en la próxima clase.' },
        ] },
      ],
    },

    {
      type: 'pathway',
      intro: 'Ahora juntemos todo en un solo árbol de decisión, tal como lo vas a razonar en el examen.',
    },

    {
      type: 'table',
      kicker: 'Trampas EUNACOM',
      title: 'Las decisiones que más se preguntan',
      head: ['Escenario', 'Conducta correcta', 'Error frecuente'],
      rows: [
        { cells: ['Calcio "normal" con albúmina baja', 'Corregir por albúmina', 'Darlo por normal'],
          say: 'Repasemos las trampas. Calcio aparentemente normal con albúmina baja: corriges, y muchas veces aparece la hipercalcemia.' },
        { cells: ['Hipercalcemia, con o sin cáncer conocido', 'PTH intacta', 'Cintigrafía ósea o vitamina D'],
          say: 'Toda hipercalcemia se estudia primero con PTH, aunque el paciente tenga un cáncer o metástasis a la vista. El error es partir por la cintigrafía o la vitamina D.' },
        { cells: ['Crisis hipercalcémica', 'Suero fisiológico primero', 'Furosemida, zoledronato o calcitonina solos'],
          say: 'Crisis hipercalcémica: suero fisiológico primero. La furosemida, el zoledronato o la calcitonina como primera medida son los distractores clásicos.' },
        { cells: ['Crisis en hiperparatiroidismo', 'Hidratar y estabilizar', 'Paratiroidectomía de urgencia'],
          say: 'Si la crisis es de un hiperparatiroidismo, igual se hidrata primero. La cirugía y el cintigrama vienen después, de forma electiva.' },
        { cells: ['PTH normal, calciuria muy baja', 'Hipocalciúrica familiar: no operar', 'Paratiroidectomía'],
          say: 'PTH normal con calciuria muy baja: hipercalcemia hipocalciúrica familiar, y no se opera.' },
        { cells: ['Linfoma, mieloma o sarcoidosis', 'Agregar corticoides', 'Usarlos en toda hipercalcemia'],
          say: 'Y los corticoides son para el exceso de calcitriol: linfoma, mieloma y sarcoidosis, no para cualquier hipercalcemia.' },
      ],
    },

    {
      type: 'quiz',
      kicker: 'Caso clínico',
      title: 'Caso clínico',
      stem: 'Mujer de 56 años con astenia, constipación de 3 meses, dolores óseos difusos y 2 cólicos renales en los últimos 2 años. Lúcida, hidratada, PA 135/85 mmHg. Calcio 11,6 mg/dL con albúmina 4,0 g/dL, fósforo 2,1 mg/dL, creatinina 0,9 mg/dL, PTH intacta 145 pg/mL (VN 15–65). Ecografía renal: microlitiasis bilateral.',
      question: '¿Cuál es la conducta más adecuada?',
      options: [
        { letter: 'A', text: 'Ácido zoledrónico 4 mg EV' },
        { letter: 'B', text: 'Control anual de calcio y densitometría' },
        { letter: 'C', text: 'Localizar con cintigrama sestamibi y ecografía cervical, y paratiroidectomía' },
        { letter: 'D', text: 'Furosemida oral y restricción de lácteos' },
        { letter: 'E', text: 'Electroforesis de proteínas para descartar mieloma' },
      ],
      correct: 'C',
      explanation: 'Hipercalcemia + hipofosfatemia + PTH elevada: hiperparatiroidismo primario. Es sintomática (litiasis recurrente), así que la cirugía es mandatoria: se localiza el adenoma con sestamibi y ecografía y se hace paratiroidectomía. La observación solo cabe en el asintomático sin criterios; con PTH elevada, el mieloma no explica el cuadro.',
      say: {
        stem: 'Vamos con un caso. Mujer de cincuenta y seis años con astenia, constipación, dolores óseos y dos cólicos renales en dos años. Está lúcida e hidratada. Calcio once coma seis con albúmina de cuatro, fósforo dos coma uno, creatinina normal y PTH de ciento cuarenta y cinco, sobre el máximo de sesenta y cinco. La ecografía muestra microlitiasis bilateral.',
        question: '¿Cuál es la conducta más adecuada?',
        options: 'Las alternativas: ácido zoledrónico, control anual, localizar con sestamibi y ecografía y operar, furosemida con restricción de lácteos, o electroforesis de proteínas. Piénsalo.',
        answer: 'Es la C. Calcio alto, fósforo bajo y PTH alta: la tríada del hiperparatiroidismo primario. Y no es asintomática: tiene litiasis a repetición, así que la cirugía es mandatoria, previa localización. El distractor tentador es el control anual, pero eso solo cabe en el asintomático sin criterios. El zoledronato es de la crisis, y el mieloma daría PTH suprimida.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2019 · Pregunta 175',
      stem: 'Un paciente de 32 años, con antecedente de litiasis renal a repetición se realiza exámenes, que muestran calcio plasmático: 9,8 mg/dl, albúmina: 3,0 g/dl, creatinina plasmática: 0,7 mg/dl, PTH: 90 UI/L (VN: 10 a 55 pg/ml) y calciuria de 200 mg/día (VN: 50 a 150 mg/día).',
      question: 'El diagnóstico más probable es:',
      options: [
        { letter: 'A', text: 'Hiperparatiroidismo primario' },
        { letter: 'B', text: 'Hiperparatiroidismo secundario' },
        { letter: 'C', text: 'Hiperparatiroidismo terciario' },
        { letter: 'D', text: 'Hipercalciuria primaria' },
        { letter: 'E', text: 'Hipercalciuria familiar' },
      ],
      correct: 'A',
      explanation: 'Calcio corregido = 9,8 + 0,8 × (4 − 3) = 10,6 mg/dL: hay hipercalcemia. Con PTH elevada e hipercalciuria que explica la litiasis, es un hiperparatiroidismo primario. El secundario tiene calcio bajo o normal (típico de la IRC); en la hipercalciuria primaria la calcemia y la PTH son normales.',
      say: {
        stem: 'Vamos a las preguntas reales. Esta es del EUNACOM de julio de dos mil diecinueve. Paciente de treinta y dos años con litiasis renal a repetición. Calcio nueve coma ocho, albúmina tres, creatinina normal, PTH noventa, sobre el máximo de cincuenta y cinco, y calciuria de doscientos miligramos al día, elevada.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones: hiperparatiroidismo primario, secundario o terciario, hipercalciuria primaria, o hipercalciuria familiar. Piénsalo.',
        answer: 'Es la A. La clave es corregir: nueve coma ocho más cero coma ocho da diez coma seis. Hay hipercalcemia con PTH alta: hiperparatiroidismo primario, y la hipercalciuria explica los cálculos. El distractor tentador es el secundario, porque si no corriges el calcio parece normal; pero el secundario tiene calcio bajo o normal, típicamente por insuficiencia renal, y aquí la creatinina es normal.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2025 · Pregunta 167',
      stem: 'Hombre de 55 años asintomático con calcio sérico 11.2 mg/dL, fósforo 2.1 mg/dL (bajo) y PTH 145 pg/mL (elevada). Sin otros hallazgos.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Hiperparatiroidismo primario' },
        { letter: 'B', text: 'Hipercalcemia hipocalciúrica familiar' },
        { letter: 'C', text: 'Hipercalcemia de malignidad' },
        { letter: 'D', text: 'Intoxicación por vitamina D' },
        { letter: 'E', text: 'Sarcoidosis' },
      ],
      correct: 'A',
      explanation: 'Hipercalcemia + hipofosfatemia + PTH elevada en un paciente ambulatorio asintomático: hiperparatiroidismo primario, la causa más frecuente en este contexto. Malignidad, vitamina D y sarcoidosis tienen la PTH suprimida.',
      say: {
        stem: 'Del EUNACOM de julio de dos mil veinticinco. Hombre de cincuenta y cinco años, asintomático, con calcio once coma dos, fósforo bajo de dos coma uno y PTH elevada de ciento cuarenta y cinco.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones: hiperparatiroidismo primario, hipercalcemia hipocalciúrica familiar, hipercalcemia maligna, intoxicación por vitamina D o sarcoidosis. Piénsalo.',
        answer: 'Es la A. Es la tríada completa, calcio alto, fósforo bajo y PTH alta, en un paciente ambulatorio. Malignidad, vitamina D y sarcoidosis caen de inmediato, porque tienen la PTH suprimida. El distractor más fino es la hipocalciúrica familiar, que también tiene PTH normal o alta; para elegirla necesitarías una calciuria muy baja, y aquí no te la dan.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Agosto 2021 · Pregunta 121',
      stem: 'Un paciente de 67 años consulta por dolores óseos en múltiples zonas. Se realiza exámenes, entre los que destaca calcemia corregida de 14,4 mg/dl, con pruebas de función renal normales. Además, se solicitan radiografías que muestran imágenes sugerentes de metástasis óseas.',
      question: '¿Cuál es la conducta más adecuada para proseguir el estudio?',
      options: [
        { letter: 'A', text: 'Calciuria de 24 horas' },
        { letter: 'B', text: 'Niveles plasmáticos de 25-OH vitamina D' },
        { letter: 'C', text: 'Niveles plasmáticos de paratohormona' },
        { letter: 'D', text: 'Cintigrafía ósea' },
        { letter: 'E', text: 'Niveles plasmáticos de calcio iónico' },
      ],
      correct: 'C',
      explanation: 'Toda hipercalcemia se estudia con PTH: si está elevada es hiperparatiroidismo primario; si está suprimida, apoya el origen neoplásico. Las lesiones óseas también pueden deberse a hiperparatiroidismo (tumores pardos). La cintigrafía es inespecífica y aquí las lesiones ya se vieron.',
      say: {
        stem: 'Del EUNACOM de agosto de dos mil veintiuno. Paciente de sesenta y siete años con dolores óseos en múltiples zonas, calcio corregido de catorce coma cuatro, función renal normal, y radiografías que sugieren metástasis óseas.',
        question: '¿Cuál es la conducta más adecuada para proseguir el estudio?',
        options: 'Las opciones: calciuria de veinticuatro horas, vitamina D, paratohormona, cintigrafía ósea, o calcio iónico. Piénsalo.',
        answer: 'Es la C. Aunque las metástasis parezcan evidentes, la hipercalcemia se estudia siempre con PTH, porque el hiperparatiroidismo también da lesiones óseas, los tumores pardos. Si la PTH está suprimida, apoya el cáncer; si está alta, es un hiperparatiroidismo. El distractor es la cintigrafía, que es inespecífica y busca lesiones que aquí ya se vieron. En la práctica, con catorce de calcio, además hidratas mientras estudias.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2022 · Pregunta 123',
      stem: 'Un paciente de 76 años, con antecedente de cáncer de próstata avanzado, presenta un cuadro de 2 días de evolución de debilidad y malestar general, al que se agrega obnubilación de conciencia y tendencia al sopor. Al examen físico se aprecia desorientado, con sopor profundo, sin focalidad neurológica, tiene FC: 80x’, PA: 150/100 mmHg y FR: 16x’. El examen torácico y abdominal no aporta mayor información. Se solicitan electrolitos plasmáticos que muestran sodio: 148 mEq/L, potasio: 5 mEq/L, calcio: 14,8 mg/dl y otros exámenes de sangre que muestran creatinina: 1,4 mg/dl, GOT: 50 UI/l, 2, APE: 200 ng/ml.',
      question: '¿Cuál es la conducta inicial más adecuada?',
      options: [
        { letter: 'A', text: 'Administrar calcitonina endovenosa' },
        { letter: 'B', text: 'Realizar hemodiálisis de urgencia' },
        { letter: 'C', text: 'Administrar ácido zolendrónico endovenoso' },
        { letter: 'D', text: 'Administrar gluconato de calcio endovenoso' },
        { letter: 'E', text: 'Administrar suero fisiológico endovenoso' },
      ],
      correct: 'E',
      explanation: 'Calcio de 14,8 mg/dL con sopor: crisis hipercalcémica maligna. La primera medida es la expansión de volumen con suero fisiológico, que restaura la filtración e induce calciuresis. El zoledronato va después (demora 48–72 h y requiere hidratación previa); la calcitonina es puente; la hemodiálisis se reserva para falla renal anúrica o refractariedad.',
      say: {
        stem: 'Del EUNACOM de diciembre de dos mil veintidós. Hombre de setenta y seis años con cáncer de próstata avanzado, dos días de debilidad y luego sopor profundo, sin focalidad. Sodio ciento cuarenta y ocho, calcio catorce coma ocho, creatinina uno coma cuatro, y antígeno prostático de doscientos.',
        question: '¿Cuál es la conducta inicial más adecuada?',
        options: 'Las opciones: calcitonina, hemodiálisis de urgencia, ácido zoledrónico, gluconato de calcio, o suero fisiológico. Piénsalo.',
        answer: 'Es la E, suero fisiológico. Calcio sobre catorce con compromiso de conciencia es una crisis hipercalcémica, y el primer paso siempre es el volumen. El distractor tentador es el zoledrónico, porque es el fármaco que controla el calcio, pero demora dos a tres días y necesita al paciente hidratado. La hemodiálisis es para la falla renal anúrica, y el gluconato de calcio es de la hipocalcemia, la clase que viene.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2025 · Pregunta 79',
      stem: 'Hombre de 55 años con hipercalcemia severa (Ca 13.5 mg/dL), náuseas, poliuria, confusión y deshidratación. PTH elevada.',
      question: '¿Cuál es el tratamiento inicial de urgencia?',
      options: [
        { letter: 'A', text: 'Resonancia magnética' },
        { letter: 'B', text: 'Cintigrafía con sestamibi (localización de adenoma paratiroideo)' },
        { letter: 'C', text: 'Hidratación EV con solución salina 0.9%' },
        { letter: 'D', text: 'Paratiroidectomía de urgencia' },
        { letter: 'E', text: 'Carbonato de calcio oral' },
      ],
      correct: 'C',
      explanation: 'Hipercalcemia sintomática con deshidratación: el tratamiento de urgencia es la hidratación EV con suero fisiológico al 0,9 %, aunque la causa sea un hiperparatiroidismo. El sestamibi y la paratiroidectomía se planifican de forma electiva, una vez estabilizado.',
      say: {
        stem: 'La última, del EUNACOM de julio de dos mil veinticinco. Hombre de cincuenta y cinco años con calcio de trece coma cinco, náuseas, poliuria, confusión y deshidratación. La PTH está elevada.',
        question: '¿Cuál es el tratamiento inicial de urgencia?',
        options: 'Las opciones: resonancia magnética, cintigrafía con sestamibi, hidratación con suero fisiológico, paratiroidectomía de urgencia, o carbonato de calcio. Piénsalo.',
        answer: 'Es la C. Esta pregunta enseña algo distinto a la anterior: aunque la PTH alta ya te diga que es un hiperparatiroidismo, la urgencia es la misma, hidratar con suero fisiológico. El distractor es el sestamibi, o la cirugía, porque tratan la causa; pero la localización y la paratiroidectomía son electivas, una vez que el paciente está estable.',
      },
    },

    {
      type: 'points',
      kicker: 'Cierre',
      title: 'Reglas de oro para el examen',
      cards: [
        { title: 'Diagnóstico', tag: 'Tres pasos', kind: 'key', items: [
          { t: 'Corregir por albúmina', d: 'Ca + 0,8 × (4 − albúmina)',
            say: 'Cerremos con las reglas de oro. Primero, corrige siempre el calcio por la albúmina.' },
          { t: 'PTH intacta divide', d: 'Alta o normal: HPT 1° · suprimida: neoplasia',
            say: 'Segundo, la PTH intacta divide el camino: alta o inapropiadamente normal es hiperparatiroidismo primario; suprimida es neoplasia o vitamina D.' },
          { t: 'Tríada del HPT 1°', d: 'Calcio alto, fósforo bajo, PTH alta',
            say: 'Y la tríada del hiperparatiroidismo primario es calcio alto, fósforo bajo y PTH alta.' },
        ] },
        { title: 'Crisis', tag: 'Sobre 14 mg/dL', kind: 'alert', items: [
          { t: 'Suero fisiológico primero', d: 'Luego zoledronato; calcitonina de puente',
            say: 'En la crisis, suero fisiológico primero, luego zoledronato, con calcitonina de puente. La furosemida solo si ya está hidratado y sobrecargado.' },
        ] },
        { title: 'Cirugía', tag: 'Única cura', kind: 'pharma', items: [
          { t: 'Sintomático o con criterios', d: 'Menor de 50, Ca > 1 sobre límite, hueso, riñón',
            say: 'La paratiroidectomía es mandatoria en el sintomático, y en el asintomático con cualquier criterio: menor de cincuenta años, calcio más de uno sobre el límite, compromiso óseo o renal. Y vigila el hueso hambriento después.' },
          { t: 'Calciuria muy baja: no operar', d: 'Hipocalciúrica familiar',
            say: 'Con calciuria muy baja, piensa en la hipocalciúrica familiar, que no se opera. Si te llevas una sola idea de hoy: ante una hipercalcemia, corrige y pide PTH; ante una crisis, suero fisiológico antes que todo. Nos vemos en la próxima clase.' },
        ] },
      ],
    },
  ],

  pathway: {
    title: 'Hipercalcemia: de la cifra a la conducta',
    root: N('start', 'Calcio alto', 'Corregido por albúmina',
      'Tienes un calcio alto. Antes de todo, lo corriges por la albúmina para confirmar que la hipercalcemia es real.',
      ['', N('q', '¿Crisis? Calcio ≥ 14 o compromiso', 'Deshidratación, sopor, arritmias',
        '¿Es una crisis? Calcio de catorce o más, o un paciente deshidratado, con compromiso de conciencia o arritmias.',
        ['Sí', N('alert', 'Suero fisiológico + zoledronato', 'Calcitonina puente · corticoides si calcitriol',
          'Si es crisis, primero suero fisiológico, doscientos a trescientos mililitros por hora, luego zoledronato, con calcitonina de puente, y corticoides si es un linfoma, un mieloma o una sarcoidosis. Una vez estable, estudias la causa con PTH.')],
        ['No', N('q', '¿Cómo está la PTH intacta?', 'El examen que divide',
          'Si no es crisis, o una vez estabilizado, mides la PTH intacta. ¿Está alta, normal o suprimida?',
          ['Suprimida', N('refer', 'Neoplasia o vitamina D', 'PTHrP, osteólisis, calcitriol, granulomas',
            'Suprimida: la causa está fuera de la paratiroides. Buscas una neoplasia, por PTHrP u osteólisis, o un exceso de vitamina D por linfoma, granulomas o ingesta.')],
          ['Alta o normal', N('q', '¿Calciuria muy baja?', 'FE de calcio < 1 %',
            'Alta o inapropiadamente normal: es PTH dependiente. Antes de operar, mira la calciuria: ¿es muy baja?',
            ['Sí', N('ok', 'Hipocalciúrica familiar', 'Benigna: no operar',
              'Si es muy baja, con excreción fraccionada bajo uno por ciento, es la hipercalcemia hipocalciúrica familiar, y no se opera.')],
            ['No', N('do', 'Hiperparatiroidismo primario', 'Paratiroidectomía si síntomas o criterios',
              'Si no, es hiperparatiroidismo primario. Paratiroidectomía, previa localización con sestamibi y ecografía, si es sintomático o cumple algún criterio; si no, control.')])])])]),
  },
};
