// Clase 7.9 — guion docente escrito a mano (ver gastro-01.cjs para el formato).
// Fuente clínica: books/scripts/dataset_endocrinologia.cjs (endo-09).

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  id: 'endo-09',
  tier: 3,
  slides: [
    {
      type: 'cover',
      subtitle: 'Qué pedir primero, qué nódulo se punciona y qué hacer con cada Bethesda',
      say: 'Bienvenidos. Hoy vemos el nódulo tiroideo, un tema de frecuencia muy alta en el EUNACOM. Venimos de las urgencias tirotóxicas, y el hilo sigue: vas a ver que la misma TSH que usamos para el hipertiroidismo es el primer paso ante cualquier nódulo. Al final vas a saber qué examen pedir primero, qué nódulo se punciona, cuál solo se vigila, y qué conducta corresponde a cada resultado de la citología.',
    },

    {
      type: 'points',
      kicker: 'El problema',
      title: 'Muy frecuente, rara vez maligno',
      cards: [
        { title: 'Epidemiología', tag: 'La misión', kind: 'key', items: [
          { t: 'Nódulos en 50–60 % de mujeres', d: 'Detectables por ecografía, casi siempre asintomáticos',
            say: 'Partamos por entender el problema. Hasta un cincuenta a sesenta por ciento de las mujeres adultas sin síntomas tiene nódulos que se ven en una ecografía. Es decir, vas a ver nódulos todas las semanas.' },
          { t: 'Solo 5–10 % son malignos', d: 'Sobre todo carcinoma papilar',
            say: 'Pero solo un cinco a diez por ciento son malignos, y la mayoría de esos son carcinomas papilares. Entonces tu misión es doble: no puncionar ni operar nódulos benignos que nunca iban a molestar, y no dejar pasar el cáncer.' },
        ] },
        { title: 'Factores de alto riesgo', tag: 'Suben la sospecha', kind: 'alert', items: [
          { t: 'Radioterapia de cuello en la infancia', d: 'O en la adolescencia',
            say: 'Hay antecedentes que suben la sospecha, y conviene tenerlos a mano. El primero es haber recibido radioterapia de cabeza y cuello en la infancia o en la adolescencia.' },
          { t: 'Familiar con carcinoma medular o NEM 2', d: 'Historia familiar de alto riesgo',
            say: 'El segundo, la historia familiar de carcinoma medular de tiroides o de neoplasia endocrina múltiple tipo dos, que veremos en la próxima clase.' },
          { t: 'Crecimiento rápido y disfonía', d: 'Parálisis de cuerda vocal ipsilateral',
            say: 'Luego, el nódulo que crece rápido y sin dolor, y la disfonía por parálisis de la cuerda vocal del mismo lado: significa que algo está infiltrando el nervio laríngeo recurrente.' },
          { t: 'Adenopatías duras y fijas', d: 'Laterocervicales, adheridas a planos profundos',
            say: 'Y las adenopatías laterocervicales duras, adheridas a planos profundos. Guarda estas pistas, porque cambian la conducta incluso en nódulos chicos.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Primer paso',
      title: 'Antes que cualquier imagen: la TSH',
      nodes: [
        { id: 'nod', col: 0, row: 2, k: 'start', t: 'Nódulo de 1 cm o sospechoso', s: 'Palpado o incidental' },
        { id: 'tsh', col: 1, row: 2, k: 'q', t: '¿Cómo está la TSH?', s: 'Primer examen obligatorio' },
        { id: 'sup', col: 2, row: 1, k: 'mech', t: 'TSH suprimida', s: 'Menor de 0,4 mUI/L' },
        { id: 'cin', col: 3, row: 1, k: 'effect', t: 'Cintigrama tiroideo', s: 'Tc-99m o I-131' },
        { id: 'cal', col: 4, row: 0, k: 'good', t: 'Nódulo caliente', s: 'Malignidad bajo 1 %: no PAAF' },
        { id: 'nor', col: 2, row: 3, k: 'mech', t: 'TSH normal o elevada', s: 'Glándula no hiperfuncionante' },
        { id: 'eco', col: 3, row: 3, k: 'good', t: 'Ecografía con TI-RADS', s: 'Alta resolución' },
        { id: 'tra', col: 4, row: 4, k: 'trap', t: 'Cintigrama con TSH normal', s: 'Nunca' },
      ],
      edges: [
        { from: 'nod', to: 'tsh' },
        { from: 'tsh', to: 'sup', label: 'baja' },
        { from: 'sup', to: 'cin' },
        { from: 'cin', to: 'cal', label: 'hipercaptante' },
        { from: 'tsh', to: 'nor', label: 'normal o alta' },
        { from: 'nor', to: 'eco' },
        { from: 'eco', to: 'tra', label: 'no' },
      ],
      steps: [
        { show: ['nod'], note: 'Nódulo de 1 cm o más, o con aspecto sospechoso',
          say: 'Vamos al algoritmo, que es lo que más se pregunta. Llega un paciente con un nódulo de un centímetro o más, o con algo sospechoso, ya sea que se lo palpó o que apareció de casualidad en una imagen.' },
        { show: ['tsh'], note: 'Lo primero es saber cómo funciona la glándula',
          say: 'El primer examen obligatorio no es la ecografía ni la punción: es la TSH. ¿Por qué? Porque antes de preguntarte si el nódulo es maligno, necesitas saber si está fabricando hormona por su cuenta.' },
        { show: ['sup', 'cin'], note: 'TSH suprimida: el nódulo podría ser autónomo',
          say: 'Si la TSH está suprimida, bajo cero coma cuatro, hay hiperfunción. Y como vimos en Graves, cuando hay hiperfunción la pregunta la responde el cintigrama: queremos saber si el nódulo capta más que el resto.' },
        { show: ['cal'], note: 'Caliente = autónomo = prácticamente nunca maligno',
          say: 'Si el nódulo es caliente, es autónomo, y su riesgo de cáncer es menor al uno por ciento. Por eso no se punciona: se deriva a tratar el hipertiroidismo. Esa es la gran excepción del tema.' },
        { show: ['nor', 'eco'], note: 'TSH normal o alta: la ecografía estratifica el riesgo',
          say: 'Si la TSH es normal, o incluso elevada, el siguiente paso es la ecografía tiroidea de alta resolución, con la clasificación TI-RADS. Fíjate que dije normal o elevada: una TSH alta tampoco te lleva al cintigrama.' },
        { show: ['tra'], note: 'Con TSH normal, el cintigrama no aporta',
          say: 'Y ojo con la trampa. Con TSH normal nunca se pide cintigrama. Un nódulo frío es lo esperable en casi todos, y no te dice nada que la ecografía no te diga mejor.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Ecografía',
      title: 'Lo que hace sospechoso a un nódulo',
      cards: [
        { title: 'Alta sospecha', tag: 'Muy evaluado', kind: 'alert', items: [
          { t: 'Sólido', d: 'O casi completamente sólido',
            say: 'La ecografía es la imagen de elección, y el sistema TI-RADS le asigna puntos a cinco características: composición, ecogenicidad, forma, márgenes y focos ecogénicos. Veamos los signos de alta sospecha. El primero: el nódulo sólido o casi completamente sólido.' },
          { t: 'Marcadamente hipoecogénico', d: 'Más oscuro que el músculo pretiroideo',
            say: 'El segundo, la marcada hipoecogenicidad: el nódulo se ve más oscuro que la musculatura que está por delante de la tiroides.' },
          { t: 'Más alto que ancho', d: 'Eje anteroposterior mayor que el transversal',
            say: 'El tercero, la forma más alto que ancho en el corte transversal. Un nódulo benigno crece empujando los tejidos en el plano; uno maligno los atraviesa.' },
          { t: 'Márgenes irregulares o espiculados', d: 'O extensión extratiroidea',
            say: 'El cuarto, los márgenes irregulares, espiculados o microlobulados, o la extensión fuera de la tiroides.' },
          { t: 'Microcalcificaciones', d: 'Menores de 1 mm, sin sombra acústica',
            say: 'Y el quinto, las microcalcificaciones: puntos brillantes de menos de un milímetro, sin sombra acústica. Son los cuerpos de psamoma del carcinoma papilar vistos por ecografía.' },
        ] },
        { title: 'Benignidad', tag: 'Tranquiliza', kind: 'normal', items: [
          { t: 'Aspecto espongiforme', d: 'Más del 50 % en microquistes',
            say: 'Del otro lado, hay imágenes que tranquilizan. El nódulo espongiforme, con más de la mitad de su volumen en microquistes, como un panal de abejas.' },
          { t: 'Quiste simple anecoico', d: 'O iso-hiperecoico con halo fino',
            say: 'El quiste simple, completamente anecoico. Y el nódulo isoecoico o hiperecoico rodeado de un halo fino y continuo.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Indicación de PAAF',
      title: 'El umbral depende del TI-RADS',
      nodes: [
        { id: 'eco', col: 0, row: 2, k: 'start', t: 'Ecografía clasificada', s: 'Categoría TI-RADS' },
        { id: 'tr12', col: 1, row: 0, k: 'good', t: 'TR1 y TR2', s: 'No PAAF en ningún tamaño' },
        { id: 'tr3', col: 2, row: 1, k: 'mech', t: 'TR3: leve sospecha', s: 'PAAF desde 2,5 cm' },
        { id: 'tr4', col: 2, row: 2, k: 'risk', t: 'TR4: sospecha moderada', s: 'PAAF desde 1,5 cm' },
        { id: 'tr5', col: 2, row: 3, k: 'alert', t: 'TR5: alta sospecha', s: 'PAAF desde 1 cm' },
        { id: 'seg', col: 3, row: 2, k: 'good', t: 'Bajo el umbral', s: 'Seguimiento ecográfico' },
        { id: 'sub', col: 3, row: 4, k: 'trap', t: 'Subcentimétrico sin riesgo', s: 'No se punciona' },
      ],
      edges: [
        { from: 'eco', to: 'tr12' }, { from: 'eco', to: 'tr3' }, { from: 'eco', to: 'tr4' }, { from: 'eco', to: 'tr5' },
        { from: 'tr3', to: 'seg', label: 'desde 1,5 cm' },
        { from: 'tr4', to: 'seg', label: 'desde 1 cm' },
        { from: 'tr5', to: 'seg', label: 'desde 0,5 cm' },
        { from: 'tr5', to: 'sub', label: 'menor de 1 cm' },
      ],
      steps: [
        { show: ['eco'], note: 'La PAAF no se indica en todos los nódulos',
          say: 'Ahora, la pregunta clave: ¿a quién le hago una punción aspirativa con aguja fina, la PAAF? No a todos. La decisión cruza dos datos: la categoría TI-RADS y el tamaño.' },
        { show: ['tr12'], note: 'Sin sospecha: nunca PAAF',
          say: 'TR uno y TR dos, benigno y no sospechoso, no se puncionan en ningún tamaño. Aunque midan varios centímetros.' },
        { show: ['tr3'], note: 'Leve sospecha: umbral alto',
          say: 'TR tres, levemente sospechoso: PAAF solo si mide dos coma cinco centímetros o más.' },
        { show: ['tr4'], note: 'Sospecha moderada: umbral intermedio',
          say: 'TR cuatro, moderadamente sospechoso: PAAF desde uno coma cinco centímetros.' },
        { show: ['tr5'], note: 'Alta sospecha: umbral más bajo',
          say: 'Y TR cinco, altamente sospechoso: PAAF desde un centímetro. Fíjate en la lógica: mientras más sospechoso el nódulo, más chico es el tamaño que te obliga a puncionar.' },
        { show: ['seg'], note: 'Bajo el umbral, pero sobre el mínimo: vigilar',
          say: 'Y si el nódulo no alcanza el umbral, no se olvida: se vigila con ecografía. TR tres desde uno coma cinco centímetros, TR cuatro desde un centímetro, y TR cinco desde medio centímetro.' },
        { show: ['sub'], note: 'La regla que más se pregunta',
          say: 'Y la regla que más se pregunta: sin adenopatías sospechosas ni antecedentes familiares o de radiación, un nódulo de menos de un centímetro no se punciona, aunque sea TR cinco. Se vigila, para no sobrediagnosticar microcarcinomas que casi nunca dan problemas.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'Citología',
      title: 'Bethesda: cada categoría tiene su conducta',
      nodes: [
        { id: 'paaf', col: 0, row: 2, k: 'start', t: 'Resultado de la PAAF', s: 'Sistema Bethesda I a VI' },
        { id: 'b1', col: 1, row: 0, k: 'mech', t: 'I: no diagnóstica', s: 'Repetir PAAF guiada' },
        { id: 'b2', col: 2, row: 0, k: 'good', t: 'II: benigno', s: 'Control eco en 12 a 24 meses' },
        { id: 'b3', col: 3, row: 1, k: 'q', t: 'III: atipia indeterminada', s: 'Repetir PAAF o test molecular' },
        { id: 'b4', col: 3, row: 3, k: 'refer', t: 'IV: neoplasia folicular', s: 'Hemitiroidectomía diagnóstica' },
        { id: 'b5', col: 2, row: 4, k: 'risk', t: 'V: sospechoso de malignidad', s: 'Tiroidectomía total o lobectomía' },
        { id: 'b6', col: 1, row: 4, k: 'alert', t: 'VI: maligno', s: 'Tiroidectomía total ± vaciamiento' },
      ],
      edges: [
        { from: 'paaf', to: 'b1' }, { from: 'b1', to: 'b2', label: 'si se repite' },
        { from: 'paaf', to: 'b3' }, { from: 'paaf', to: 'b4' },
        { from: 'paaf', to: 'b5' }, { from: 'paaf', to: 'b6' },
      ],
      steps: [
        { show: ['paaf'], note: 'Seis categorías, cada una con su riesgo',
          say: 'Ya puncionaste. El informe de la citología viene con el sistema Bethesda, que tiene seis categorías. Cada una trae su riesgo de cáncer, y lo importante es que cada una tiene una conducta distinta.' },
        { show: ['b1'], note: 'Muestra insuficiente: no es un resultado',
          say: 'Bethesda uno es una muestra no diagnóstica, insuficiente. No es benigno ni maligno: simplemente no sirve. Se repite la PAAF guiada por ecografía.' },
        { show: ['b2'], note: 'Benigno: riesgo de 0 a 3 %',
          say: 'Bethesda dos es benigno: un nódulo coloide o una tiroiditis, con un riesgo de cáncer de cero a tres por ciento. Conducta expectante, con control ecográfico en doce a veinticuatro meses. No se opera.' },
        { show: ['b3'], note: 'Atipia: la zona gris',
          say: 'Bethesda tres es la atipia de significado indeterminado, con un riesgo de diez a treinta por ciento. Es la zona gris: se repite la PAAF a los tres a seis meses o se piden paneles moleculares.' },
        { show: ['b4'], note: 'La citología no ve la cápsula',
          say: 'Bethesda cuatro es la neoplasia folicular, y es la que más se pregunta. La citología ve células foliculares, pero no puede distinguir un adenoma de un carcinoma folicular, porque esa diferencia es la invasión de la cápsula o de los vasos, y eso solo se ve en la pieza completa. Por eso la conducta es una hemitiroidectomía diagnóstica.' },
        { show: ['b5', 'b6'], note: 'Sospechoso o maligno: cirugía',
          say: 'Bethesda cinco, sospechoso de malignidad, va a cirugía resectiva, tiroidectomía total o lobectomía. Y Bethesda seis, maligno, a cirugía oncológica definitiva: tiroidectomía total, con vaciamiento ganglionar si hay adenopatías.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Conducta en APS',
      title: 'Qué haces tú como médico general',
      cards: [
        { title: 'Derivación GES', tag: 'Cáncer de tiroides', kind: 'criteria', items: [
          { t: 'Bethesda IV, V o VI', d: 'Sospecha fundada: acceso GES desde los 15 años',
            say: 'Aterricemos esto a tu consulta. Cualquier paciente con citología Bethesda cuatro, cinco o seis tiene una sospecha fundada de cáncer de tiroides, con acceso garantizado por el GES de cáncer en personas de quince años y más.' },
          { t: 'Adenopatías sospechosas', d: 'Derivar con prioridad',
            say: 'Lo mismo si hay adenopatías sospechosas: derivación prioritaria a endocrinología y a cirugía de cabeza y cuello.' },
        ] },
        { title: 'Lo que ya no se hace', tag: 'Distractores', kind: 'alert', items: [
          { t: 'Levotiroxina supresora', d: 'En desuso: ineficaz y riesgosa',
            say: 'Y descarta un distractor antiguo: dar levotiroxina para achicar el nódulo. Está en desuso, porque no sirve y expone al paciente a un hipertiroidismo iatrogénico.' },
          { t: 'Radioyodo sin cintigrama', d: 'Solo para nódulos calientes',
            say: 'El radioyodo tampoco es una opción para un nódulo cualquiera. Queda para el nódulo caliente con hipertiroidismo, que ya definimos con el cintigrama.' },
        ] },
      ],
    },

    {
      type: 'pathway',
      intro: 'Juntemos todo en un árbol de decisión, desde el nódulo recién encontrado hasta la conducta final.',
    },

    {
      type: 'table',
      kicker: 'Trampas EUNACOM',
      title: 'Las decisiones que más se preguntan',
      head: ['Escenario', 'Conducta correcta', 'Error frecuente'],
      rows: [
        { cells: ['Nódulo + TSH menor de 0,4', 'Cintigrama tiroideo', 'PAAF de entrada'],
          say: 'Repasemos las trampas. Nódulo con TSH suprimida: cintigrama. El error es puncionar de entrada, porque si es caliente, no se punciona.' },
        { cells: ['Nódulo + TSH normal o alta', 'Ecografía con TI-RADS', 'Pedir cintigrama'],
          say: 'Nódulo con TSH normal o elevada: ecografía. El error es pedir cintigrama.' },
        { cells: ['TR5 de 1,4 cm', 'PAAF guiada por ecografía', 'Solo controlar'],
          say: 'Un TR cinco de uno coma cuatro centímetros supera el umbral: PAAF guiada por ecografía. Controlar sin puncionar retrasa el diagnóstico.' },
        { cells: ['TR5 de 0,7 cm, sin adenopatías', 'Seguimiento ecográfico en 6 a 12 meses', 'Puncionar por sospechoso'],
          say: 'Un TR cinco de siete milímetros, sin adenopatías: seguimiento ecográfico a los seis a doce meses. Aquí el error es el contrario, puncionar solo porque se ve feo.' },
        { cells: ['Bethesda II', 'Control ecográfico en 12 a 24 meses', 'Operar'],
          say: 'Bethesda dos: control ecográfico. No se opera.' },
        { cells: ['Bethesda IV', 'Hemitiroidectomía diagnóstica', 'Repetir PAAF u observar'],
          say: 'Y Bethesda cuatro: hemitiroidectomía diagnóstica. Repetir la punción no sirve, porque ninguna aguja va a mostrarte la cápsula.' },
      ],
    },

    {
      type: 'quiz',
      kicker: 'Caso clínico',
      title: 'Caso clínico',
      stem: 'Hombre de 39 años, sin antecedentes familiares ni de radiación. Nódulo tiroideo de 2 cm, TSH normal, clasificado como TI-RADS 4. Se realiza PAAF guiada por ecografía, cuyo informe concluye: Bethesda IV, neoplasia folicular.',
      question: '¿Cuál es la conducta más adecuada?',
      options: [
        { letter: 'A', text: 'Control ecográfico en 6 meses' },
        { letter: 'B', text: 'Hemitiroidectomía (lobectomía más istmectomía) diagnóstica' },
        { letter: 'C', text: 'Tiroidectomía total con vaciamiento ganglionar bilateral' },
        { letter: 'D', text: 'Radioyodo I-131 en dosis ablativa' },
        { letter: 'E', text: 'Repetir la PAAF con aguja de mayor calibre' },
      ],
      correct: 'B',
      explanation: 'Bethesda IV tiene un riesgo de cáncer de 25–40 %, y la citología no distingue adenoma de carcinoma folicular: eso exige ver invasión capsular o vascular en la pieza completa. La conducta es la hemitiroidectomía diagnóstica; si la histología confirma carcinoma, se completa la tiroidectomía.',
      say: {
        stem: 'Vamos a un caso. Hombre de treinta y nueve años, sin antecedentes familiares ni de radiación. Tiene un nódulo de dos centímetros, TSH normal, clasificado como TI-RADS cuatro. Se le hace una PAAF guiada, y el informe dice Bethesda cuatro, neoplasia folicular.',
        question: '¿Cuál es la conducta más adecuada?',
        options: 'Las alternativas: control ecográfico en seis meses, hemitiroidectomía diagnóstica, tiroidectomía total con vaciamiento, radioyodo, o repetir la PAAF con una aguja más gruesa. Piénsalo.',
        answer: 'Es la B, hemitiroidectomía diagnóstica. La citología vio células foliculares, pero la diferencia entre adenoma y carcinoma está en la cápsula y en los vasos, y eso solo lo muestra la pieza completa. El distractor tentador es repetir la punción: da lo mismo el calibre de la aguja, nunca vas a ver la cápsula. Y la tiroidectomía total con vaciamiento se adelanta a un cáncer que todavía no está demostrado.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2019 · Pregunta 167',
      stem: 'Un paciente de 30 años, presenta un nódulo tiroideo, que en el examen físico se palpa de consistencia elástica, indoloro, sin adenopatías cervicales. Se solicita TSH: 0,2 UI/L (VN: 0,3 a 5,0 UI/L), con T4 y T3 normales. Se solicita ecografía cervical, que muestra un nódulo tiroideo sólido, redondo, de aspecto homogéneo, sin microcalcificaciones, de 3 cm de diámetro.',
      question: '¿Cuál es la conducta más adecuada?',
      options: [
        { letter: 'A', text: 'Realizar cintigrafía tiroidea' },
        { letter: 'B', text: 'Realizar punción con aguja fina' },
        { letter: 'C', text: 'Controlar con pruebas tiroideas en 6 meses' },
        { letter: 'D', text: 'Solicitar niveles de tiroglobulina' },
        { letter: 'E', text: 'Realizar cirugía' },
      ],
      correct: 'A',
      explanation: 'La TSH está suprimida (hipertiroidismo subclínico con T4 y T3 normales). Con TSH baja, antes de puncionar se pide cintigrama: si el nódulo es caliente, es autónomo, casi nunca maligno y no requiere PAAF.',
      say: {
        stem: 'Ahora, preguntas reales. La primera es del EUNACOM de julio de dos mil diecinueve. Paciente de treinta años con un nódulo tiroideo elástico, indoloro, sin adenopatías. La TSH está en cero coma dos, bajo el rango normal, con T cuatro y T tres normales. La ecografía muestra un nódulo sólido, homogéneo, sin microcalcificaciones, de tres centímetros.',
        question: '¿Cuál es la conducta más adecuada?',
        options: 'Las opciones: cintigrafía tiroidea, punción con aguja fina, controlar pruebas tiroideas en seis meses, tiroglobulina, o cirugía. Piénsalo.',
        answer: 'Es la A, la cintigrafía. El detalle que decide todo es la TSH baja, aunque las hormonas sean normales. Con TSH suprimida, primero hay que saber si el nódulo es caliente. El distractor tentador es la punción, porque el nódulo mide tres centímetros; pero si es caliente, puncionarlo no tiene sentido. Y la tiroglobulina no sirve para estudiar un nódulo.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2024 · Pregunta 65',
      stem: 'Un paciente de 50 años consulta porque notó aumento de volumen en la zona anterior de su cuello. Al examen físico se palpa un nódulo de 2 cm de diámetro y consistencia dura. Se solicitan exámenes, entre los que destaca una TSH: 6,2 UI/L.',
      question: '¿Cuál es el examen más adecuado para proseguir con el estudio?',
      options: [
        { letter: 'A', text: 'T4 libre' },
        { letter: 'B', text: 'Ecografía cervical' },
        { letter: 'C', text: 'Cintigrafía tiroidea' },
        { letter: 'D', text: 'Estudio citológico por punción' },
        { letter: 'E', text: 'Anticuerpos antitiroideos' },
      ],
      correct: 'B',
      explanation: 'Con TSH normal o elevada, el siguiente paso ante un nódulo es la ecografía cervical con clasificación TI-RADS, que define si corresponde PAAF. El cintigrama solo se pide con TSH suprimida.',
      say: {
        stem: 'La segunda es del EUNACOM de julio de dos mil veinticuatro. Paciente de cincuenta años que nota un aumento de volumen en el cuello. Se palpa un nódulo duro de dos centímetros, y la TSH está en seis coma dos, elevada.',
        question: '¿Cuál es el examen más adecuado para proseguir con el estudio?',
        options: 'Las opciones: T cuatro libre, ecografía cervical, cintigrafía, punción para citología, o anticuerpos antitiroideos. Piénsalo.',
        answer: 'Es la B, la ecografía. Aquí la TSH está alta, y eso te puede despistar hacia el hipotiroidismo. Pero recuerda la regla: TSH normal o elevada lleva a la ecografía. El distractor tentador es la punción directa, porque el nódulo es duro y mide dos centímetros; pero sin ecografía no sabes su categoría ni su umbral. Y el cintigrama queda solo para la TSH suprimida.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2017 · Pregunta 38',
      stem: 'Un paciente se realiza una ecografía de cuello, como parte del estudio de un nódulo cervical, que visualiza un tumor sólido y redondeado, localizado en el istmo, de 4 mm de diámetro, sin presencia de adenopatías. Sus pruebas tiroideas muestran TSH y T4 libre dentro de rangos normales.',
      question: '¿Cuál es la conducta más adecuada?',
      options: [
        { letter: 'A', text: 'Iniciar tratamiento levotiroxina' },
        { letter: 'B', text: 'Iniciar levotiroxina en dosis de supresión' },
        { letter: 'C', text: 'Realizar punción con aguja fina' },
        { letter: 'D', text: 'Solicitar cintigrafía con yodo radiactivo' },
        { letter: 'E', text: 'Realizar seguimiento ecográfico' },
      ],
      correct: 'E',
      explanation: 'Un nódulo de 4 mm, sin adenopatías y con función tiroidea normal, no alcanza ningún umbral de PAAF: se vigila con ecografía. La levotiroxina supresora está en desuso y el cintigrama no se pide con TSH normal.',
      say: {
        stem: 'La tercera es del EUNACOM de diciembre de dos mil diecisiete. Una ecografía de cuello muestra un nódulo sólido, redondeado, en el istmo, de cuatro milímetros, sin adenopatías. La TSH y la T cuatro libre son normales.',
        question: '¿Cuál es la conducta más adecuada?',
        options: 'Las opciones: levotiroxina, levotiroxina en dosis de supresión, punción con aguja fina, cintigrafía, o seguimiento ecográfico. Piénsalo.',
        answer: 'Es la E, seguimiento ecográfico. Cuatro milímetros, sin adenopatías: no llega a ningún umbral de punción, ni siquiera el del TR cinco. El distractor más tentador es la levotiroxina supresora, que suena a tratamiento, pero está en desuso. Y el cintigrama sobra, porque la TSH es normal.',
      },
    },

    {
      type: 'points',
      kicker: 'Cierre',
      title: 'Reglas de oro para el examen',
      cards: [
        { title: 'Primer paso', tag: 'Siempre TSH', kind: 'key', items: [
          { t: 'TSH suprimida: cintigrama', d: 'Nódulo caliente: no se punciona',
            say: 'Cerremos con las reglas de oro. Ante un nódulo, primero TSH. Si está suprimida, cintigrama, y el nódulo caliente no se punciona.' },
          { t: 'TSH normal o alta: ecografía', d: 'Nunca cintigrama con TSH normal',
            say: 'Si la TSH es normal o alta, ecografía con TI-RADS, y nunca cintigrama.' },
        ] },
        { title: 'PAAF', tag: 'Tamaño y sospecha', kind: 'criteria', items: [
          { t: 'TR5 desde 1 cm, TR4 desde 1,5, TR3 desde 2,5', d: 'TR1 y TR2: nunca',
            say: 'La punción depende de la sospecha y el tamaño: TR cinco desde un centímetro, TR cuatro desde uno coma cinco, TR tres desde dos coma cinco, y los TR uno y dos nunca.' },
          { t: 'Menor de 1 cm sin riesgo: vigilar', d: 'Aunque sea TR5',
            say: 'Y bajo un centímetro, sin adenopatías ni antecedentes, se vigila aunque se vea sospechoso.' },
        ] },
        { title: 'Bethesda', tag: 'Conducta', kind: 'alert', items: [
          { t: 'II: control; IV: hemitiroidectomía', d: 'V y VI: cirugía y GES',
            say: 'Bethesda dos se controla, Bethesda cuatro va a hemitiroidectomía diagnóstica, y cinco y seis van a cirugía por el GES. Si te llevas una sola idea de hoy: ante un nódulo, la primera pregunta no es si es cáncer, sino cómo está la TSH. En la próxima clase vemos qué pasa cuando la citología confirma el cáncer. Nos vemos en la próxima clase.' },
        ] },
      ],
    },
  ],

  pathway: {
    title: 'Nódulo tiroideo: de la TSH a la citología',
    root: N('start', 'Nódulo de 1 cm o sospechoso', 'Primer examen: TSH',
      'Llega un paciente con un nódulo de un centímetro o más, o con algo sospechoso. El primer examen, siempre, es la TSH.',
      ['TSH suprimida', N('do', 'Cintigrama tiroideo', '¿El nódulo es caliente?',
        'Si la TSH está suprimida, pide un cintigrama para saber si el nódulo capta más que el resto de la glándula.',
        ['Caliente', N('ok', 'No se punciona', 'Tratar el hipertiroidismo',
          'Si es caliente, es autónomo y casi nunca maligno: no se punciona y se trata el hipertiroidismo.')])],
      ['TSH normal o alta', N('q', 'Ecografía con TI-RADS', '¿Supera el umbral de PAAF?',
        'Si la TSH es normal o alta, pide una ecografía, clasifica el nódulo con TI-RADS y compara su tamaño con el umbral de su categoría.',
        ['No', N('ok', 'Seguimiento ecográfico', 'TR1 y TR2 o bajo el umbral',
          'Si no alcanza el umbral, o es TR uno o dos, no se punciona: se vigila con ecografía cuando corresponde.')],
        ['Sí', N('q', 'PAAF guiada', '¿Qué categoría Bethesda?',
          'Si lo supera, PAAF guiada por ecografía, y la conducta la define la categoría Bethesda.',
          ['I o III', N('do', 'Repetir PAAF', 'III: o test molecular',
            'Bethesda uno o tres: se repite la punción, y en el tres también sirven los paneles moleculares.')],
          ['II', N('ok', 'Benigno', 'Control eco en 12 a 24 meses',
            'Bethesda dos: benigno, control ecográfico en doce a veinticuatro meses.')],
          ['IV', N('refer', 'Hemitiroidectomía diagnóstica', 'Ver cápsula y vasos',
            'Bethesda cuatro: hemitiroidectomía diagnóstica, porque la cápsula solo se ve en la pieza completa.')],
          ['V o VI', N('alert', 'Cirugía oncológica', 'Derivación GES',
            'Bethesda cinco o seis: cirugía, con derivación por el GES de cáncer de tiroides.')])])]),
  },
};
