// Clase 6.3 — guion docente escrito a mano (ver gastro-01.cjs para el formato).
// Fuente clínica: books/scripts/dataset_gastroenterologia.cjs (gastro-25).

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  id: 'gastro-25',
  tier: 3,
  slides: [
    {
      type: 'cover',
      subtitle: 'Una imagen clave por diagnóstico: del prematuro que se distiende al niño que sangra',
      say: 'Bienvenidos. Hoy vemos cirugía pediátrica digestiva: las urgencias y las malformaciones del tubo digestivo en el niño. No ha salido en los exámenes de los últimos años, pero es foco prioritario del nuevo perfil EUNACOM. Y la buena noticia es que cada diagnóstico tiene una imagen clave, un dato único que resuelve la pregunta. Hoy vamos a aprender a reconocer esas imágenes.',
    },

    {
      type: 'flow',
      kicker: 'Recién nacido prematuro',
      title: 'Enterocolitis necrotizante',
      nodes: [
        { id: 'pre', col: 0, row: 1, k: 'cause', t: 'Prematuro', s: 'Factor de riesgo principal' },
        { id: 'tri', col: 1, row: 1, k: 'effect', t: 'Tríada clínica', s: 'Retención gástrica, distensión, hematoquecia' },
        { id: 'rx', col: 2, row: 1, k: 'mech', t: 'Radiografía de abdomen', s: 'Neumatosis intestinal: patognomónica' },
        { id: 'med', col: 3, row: 0, k: 'good', t: 'Tratamiento médico', s: 'Régimen cero + NPT + antibióticos EV' },
        { id: 'neu', col: 3, row: 2, k: 'alert', t: 'Neumoperitoneo', s: 'Perforación' },
        { id: 'cir', col: 4, row: 2, k: 'alert', t: 'Cirugía', s: 'Perforación, necrosis o falla médica' },
      ],
      edges: [
        { from: 'pre', to: 'tri', label: 'días a semanas' }, { from: 'tri', to: 'rx' },
        { from: 'rx', to: 'med', label: 'neumatosis' }, { from: 'rx', to: 'neu', label: 'aire libre' },
        { from: 'neu', to: 'cir' }, { from: 'med', to: 'cir', label: 'si falla' },
      ],
      steps: [
        { show: ['pre'], note: 'El paciente lo dice todo: un prematuro',
          say: 'Partamos por el recién nacido. La primera urgencia es la enterocolitis necrotizante, y el dato que la gatilla está en el paciente: es un prematuro. La prematurez es el factor de riesgo principal. Si el enunciado te dice treinta semanas, ya tienes media respuesta.' },
        { show: ['tri'], note: 'Retención gástrica o vómitos + distensión + sangre en deposiciones',
          say: 'Aparece en los primeros días o semanas de vida, con una tríada: retención gástrica o vómitos, distensión abdominal y hematoquecia, es decir, sangre en las deposiciones. Aprende la tríada, porque el examen la describe tal cual.' },
        { show: ['rx'], note: 'Aire en la pared del intestino = enterocolitis',
          say: 'El examen es la radiografía de abdomen, y aquí está la imagen clave: la neumatosis intestinal, que es aire dentro de la pared del intestino. Es patognomónica. Si ves aire en la pared, no hay nada más que discutir.' },
        { show: ['med'], note: 'Primero se trata sin cirugía',
          say: 'El tratamiento es médico: régimen cero, nutrición parenteral total, sonda para descomprimir y antibióticos endovenosos. Fíjate que la neumatosis por sí sola no es indicación de operar.' },
        { show: ['neu', 'cir'], note: 'Neumatosis: tratamiento médico. Neumoperitoneo: pabellón',
          say: 'Lo que cambia la conducta es el neumoperitoneo, porque significa que el intestino se perforó. Ahí se opera. También se opera si hay necrosis o si el niño se deteriora pese al tratamiento médico. En resumen: aire en la pared, tratamiento médico; aire libre en el peritoneo, cirugía.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'Lactante',
      title: 'Invaginación intestinal',
      nodes: [
        { id: 'lac', col: 0, row: 1, k: 'start', t: 'Lactante de 6–12 meses', s: 'Previamente sano' },
        { id: 'cri', col: 1, row: 0, k: 'effect', t: 'Llanto en crisis', s: 'Hiperflexión de piernas, van y vienen' },
        { id: 'mer', col: 1, row: 2, k: 'effect', t: '"Mermelada de grosella"', s: 'Sangre y moco; masa "en salchicha"' },
        { id: 'eco', col: 2, row: 1, k: 'mech', t: 'Ecografía abdominal', s: 'Signo de la dona o diana' },
        { id: 'red', col: 3, row: 1, k: 'good', t: 'Reducción neumática', s: 'O hidrostática, guiada por imagen' },
        { id: 'cir', col: 4, row: 1, k: 'alert', t: 'Cirugía', s: 'Si falla, perfora o hay causa anatómica' },
      ],
      edges: [
        { from: 'lac', to: 'cri' }, { from: 'lac', to: 'mer' },
        { from: 'cri', to: 'eco' }, { from: 'mer', to: 'eco' },
        { from: 'eco', to: 'red' }, { from: 'red', to: 'cir', label: 'última opción' },
      ],
      steps: [
        { show: ['lac'], note: 'Otra edad, otra urgencia',
          say: 'Subamos un poco la edad. Si el paciente ya no es un recién nacido, sino un lactante de seis a doce meses, previamente sano, la urgencia que tienes que pensar es la invaginación intestinal: un segmento del intestino que se mete dentro del siguiente.' },
        { show: ['cri'], note: 'Crisis de dolor que van y vienen',
          say: 'La clínica es muy característica. Crisis de llanto inconsolable con hiperflexión de las piernas, que van y vienen. Entre una crisis y otra, el niño queda decaído. Ese ritmo intermitente es el que te pone en la pista.' },
        { show: ['mer'], note: 'La imagen clave: "mermelada de grosella"',
          say: 'Y la imagen clave: deposiciones en mermelada de grosella, que es sangre mezclada con moco. A veces además palpas una masa alargada, en salchicha. Lactante, crisis de llanto y mermelada de grosella: con eso ya tienes el diagnóstico.' },
        { show: ['eco'], note: 'Ecografía: signo de la dona',
          say: 'Se confirma con ecografía abdominal, que muestra el signo de la dona, o de la diana: los anillos del intestino metido dentro del intestino, vistos en corte.' },
        { show: ['red'], note: 'Primera línea: reducción, no cirugía',
          say: 'Y aquí está lo que se pregunta. El tratamiento de primera línea no es la cirugía: es la reducción neumática, o hidrostática, guiada por imagen. Se empuja el segmento invaginado de vuelta desde abajo, con aire o con líquido.' },
        { show: ['cir'], note: 'Cirugía: fracaso, perforación o causa anatómica',
          say: 'La cirugía es la última opción, y queda para tres situaciones: cuando la reducción fracasa, cuando hay perforación, o cuando sospechas una causa anatómica de fondo. Si en una alternativa te ofrecen laparotomía de entrada en un lactante estable, desconfía.' },
      ],
    },

    {
      type: 'points',
      kicker: 'El niño que sangra',
      title: 'Divertículo de Meckel y pólipos juveniles',
      cards: [
        { title: 'Divertículo de Meckel', tag: 'Sangra sin dolor', kind: 'alert', items: [
          { t: 'Resto onfalomesentérico en el íleon', d: 'Con mucosa gástrica ectópica',
            say: 'Pasemos al niño que sangra. El divertículo de Meckel es un resto del conducto onfalomesentérico en el íleon. Lo importante es lo que tiene dentro: mucosa gástrica ectópica. Esa mucosa secreta ácido, ulcera el íleon vecino, y sangra.' },
          { t: 'HDB indolora y abundante', d: 'Niño pequeño; o diverticulitis que imita apendicitis',
            say: 'Por eso se presenta como una hemorragia digestiva baja indolora y abundante en un niño pequeño, que puede llegar pálido y taquicárdico. Como vimos en la clase de hemorragia digestiva, es la causa que hay que pensar en el niño. Y a veces se inflama y da una diverticulitis que imita una apendicitis.' },
          { t: 'Cintigrafía con Tc-99m', d: 'Capta la mucosa gástrica ectópica',
            say: 'El examen es la cintigrafía con pertecnetato de tecnecio, que capta justamente la mucosa gástrica ectópica. La colonoscopía sale normal, porque no llega al íleon donde está el divertículo. Ojo con esa trampa.' },
        ] },
        { title: 'Regla de los "2"', tag: 'Para recordarlo', kind: 'criteria', items: [
          { t: '2 % · 2 pies · 2 pulgadas · 2 años', d: 'Población · de la válvula ileocecal · largo · edad',
            say: 'Para recordarlo, la regla de los dos: lo tiene el dos por ciento de la población, está a dos pies de la válvula ileocecal, mide dos pulgadas de largo, y se presenta hacia los dos años.' },
        ] },
        { title: 'Pólipos juveniles', tag: 'Escolar sano', kind: 'normal', items: [
          { t: 'Rectorragia escasa e intermitente', d: 'Hamartomas benignos',
            say: 'El contraste son los pólipos juveniles. Aquí el paciente es un escolar sano, con rectorragia escasa e intermitente. Son hamartomas, es decir, lesiones benignas.' },
          { t: 'Colonoscopía con polipectomía', d: 'Diagnostica y trata en el mismo acto',
            say: 'Y el examen sí es la colonoscopía, porque el pólipo está en el colon: con ella se diagnostica y se saca en el mismo acto, con polipectomía.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'La diferencia que más se pregunta',
      title: 'Sangre por el recto: la edad y el dolor deciden',
      nodes: [
        { id: 'san', col: 0, row: 2, k: 'start', t: 'Niño con sangre en deposiciones', s: '¿Qué edad? ¿Duele?' },
        { id: 'ecn', col: 1, row: 0, k: 'risk', t: 'Prematuro + distensión', s: 'Enterocolitis necrotizante' },
        { id: 'inv', col: 1, row: 1, k: 'risk', t: 'Lactante con crisis de llanto', s: 'Invaginación' },
        { id: 'mec', col: 1, row: 3, k: 'risk', t: 'Niño pequeño, indolora, abundante', s: 'Divertículo de Meckel' },
        { id: 'pol', col: 1, row: 4, k: 'effect', t: 'Escolar, escasa, intermitente', s: 'Pólipo juvenil' },
        { id: 'xrx', col: 2, row: 0, k: 'good', t: 'Radiografía', s: 'Neumatosis' },
        { id: 'xec', col: 2, row: 1, k: 'good', t: 'Ecografía', s: 'Signo de la dona' },
        { id: 'xci', col: 2, row: 3, k: 'good', t: 'Cintigrafía Tc-99m', s: 'Mucosa gástrica ectópica' },
        { id: 'xco', col: 2, row: 4, k: 'good', t: 'Colonoscopía', s: 'Y polipectomía' },
      ],
      edges: [
        { from: 'san', to: 'ecn' }, { from: 'san', to: 'inv' }, { from: 'san', to: 'mec' }, { from: 'san', to: 'pol' },
        { from: 'ecn', to: 'xrx' }, { from: 'inv', to: 'xec' }, { from: 'mec', to: 'xci' }, { from: 'pol', to: 'xco' },
      ],
      steps: [
        { show: ['san'], note: 'Cuatro diagnósticos, dos preguntas',
          say: 'Ahora juntemos todo, porque el examen te va a mostrar un niño con sangre en las deposiciones y te va a pedir que elijas. Hazte dos preguntas: qué edad tiene, y si le duele.' },
        { show: ['ecn', 'xrx'], note: 'Prematuro: radiografía',
          say: 'Si es un prematuro de días, distendido y con retención gástrica, es enterocolitis necrotizante, y el examen es la radiografía buscando neumatosis.' },
        { show: ['inv', 'xec'], note: 'Lactante con dolor: ecografía',
          say: 'Si es un lactante de seis a doce meses con crisis de llanto, es decir, con dolor, y mermelada de grosella, es invaginación, y el examen es la ecografía.' },
        { show: ['mec', 'xci'], note: 'Niño pequeño sin dolor: cintigrafía',
          say: 'Si es un niño pequeño, con un sangrado abundante y sin dolor, es un Meckel, y el examen es la cintigrafía. La ausencia de dolor es lo que lo separa de la invaginación.' },
        { show: ['pol', 'xco'], note: 'Escolar con sangrado escaso: colonoscopía',
          say: 'Y si es un escolar sano con un sangrado escaso que va y viene, es un pólipo juvenil, y se resuelve con colonoscopía. Cuatro edades, cuatro diagnósticos, cuatro exámenes distintos.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Malformaciones que obstruyen',
      title: 'El recién nacido que vomita o no traga',
      cards: [
        { title: 'Atresia duodenal', tag: 'Doble burbuja', kind: 'key', items: [
          { t: 'Vómitos biliosos desde el día 1', d: 'Obstrucción desde el nacimiento',
            say: 'Vamos ahora a las malformaciones. La primera es la atresia duodenal: el duodeno está cerrado desde el nacimiento, así que el recién nacido vomita, y vomita bilioso, desde el primer día de vida.' },
          { t: 'Radiografía: "doble burbuja"', d: 'Asociada a síndrome de Down',
            say: 'La imagen clave es la doble burbuja en la radiografía: una burbuja de aire en el estómago y otra en el duodeno, y nada más allá. Y un dato asociado que se pregunta: el síndrome de Down. El tratamiento es quirúrgico.' },
        ] },
        { title: 'Atresia esofágica', tag: 'No traga', kind: 'alert', items: [
          { t: 'Sialorrea desde el nacimiento', d: 'La saliva no tiene por dónde bajar',
            say: 'La atresia esofágica es más arriba: el esófago termina en fondo de saco. Por eso el recién nacido tiene sialorrea desde el nacimiento, la saliva no tiene por dónde bajar.' },
          { t: 'La sonda no progresa al estómago', d: 'Ese es el signo clave',
            say: 'Y el signo clave: intentas pasar una sonda y no progresa al estómago.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Malformaciones que obstruyen',
      title: 'Hernia diafragmática congénita: primero el aire',
      nodes: [
        { id: 'def', col: 0, row: 1, k: 'cause', t: 'Defecto del diafragma', s: 'Congénito' },
        { id: 'asa', col: 1, row: 1, k: 'mech', t: 'Asas en el tórax', s: 'El abdomen queda vacío' },
        { id: 'res', col: 2, row: 0, k: 'effect', t: 'Dificultad respiratoria grave', s: 'Ruidos hidroaéreos en el tórax' },
        { id: 'exc', col: 2, row: 2, k: 'effect', t: 'Abdomen excavado', s: 'La imagen clave al examen físico' },
        { id: 'ven', col: 3, row: 1, k: 'alert', t: 'Intubar y ventilar', s: 'Lo urgente' },
        { id: 'cir', col: 4, row: 1, k: 'good', t: 'Cirugía diferida', s: 'Con el niño estabilizado' },
      ],
      edges: [
        { from: 'def', to: 'asa' }, { from: 'asa', to: 'res' }, { from: 'asa', to: 'exc' },
        { from: 'res', to: 'ven' }, { from: 'exc', to: 'ven' }, { from: 'ven', to: 'cir', label: 'después' },
      ],
      steps: [
        { show: ['def', 'asa'], note: 'Las asas suben por el defecto',
          say: 'La tercera malformación es la hernia diafragmática congénita. Hay un defecto en el diafragma, y por ese defecto las asas intestinales suben al tórax.' },
        { show: ['res'], note: 'El intestino ocupa el lugar del pulmón',
          say: 'El mecanismo explica la clínica. Con el intestino ocupando el tórax, el recién nacido tiene una dificultad respiratoria grave, y al auscultarlo escuchas ruidos hidroaéreos en el tórax, donde deberías escuchar murmullo pulmonar.' },
        { show: ['exc'], note: 'Abdomen excavado: el contenido no está ahí',
          say: 'Y al mirar el abdomen, lo encuentras excavado, vacío, porque su contenido se fue al tórax. Distrés respiratorio con abdomen excavado: esa es la imagen clave.' },
        { show: ['ven'], note: 'La trampa: lo urgente no es operar',
          say: 'Aquí está la trampa. Frente a un defecto anatómico uno piensa en cirugía, pero lo urgente es intubar y ventilar. Primero el aire.' },
        { show: ['cir'], note: 'Cirugía diferida',
          say: 'La reparación quirúrgica es diferida, cuando el niño ya está estabilizado. Y no la confundas con la hernia diafragmática traumática del adulto que vimos en la clase de hiato y diafragma: esa aparece después de un trauma toracoabdominal.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'El recién nacido que no evacua',
      title: 'Enfermedad de Hirschsprung y ano imperforado',
      nodes: [
        { id: 'mec', col: 0, row: 1, k: 'start', t: 'Meconio que no sale', s: 'Más de 48 horas' },
        { id: 'dis', col: 1, row: 1, k: 'effect', t: 'Distensión y constipación', s: 'Obstrucción funcional' },
        { id: 'bio', col: 2, row: 1, k: 'mech', t: 'Biopsia rectal', s: 'Sin células ganglionares' },
        { id: 'res', col: 3, row: 1, k: 'good', t: 'Resección', s: 'Del segmento agangliónico' },
        { id: 'ano', col: 0, row: 3, k: 'alert', t: 'Ano imperforado', s: 'Diagnóstico por inspección' },
        { id: 'exa', col: 1, row: 3, k: 'good', t: 'Examinar siempre el ano', s: 'En todo recién nacido' },
      ],
      edges: [
        { from: 'mec', to: 'dis' }, { from: 'dis', to: 'bio', label: 'confirma' }, { from: 'bio', to: 'res' },
        { from: 'ano', to: 'exa' },
      ],
      steps: [
        { show: ['mec'], note: 'La imagen clave: el meconio que no sale',
          say: 'Ahora el recién nacido que no evacua. La imagen clave de la enfermedad de Hirschsprung es el retraso en la eliminación del meconio: más de cuarenta y ocho horas sin que salga.' },
        { show: ['dis'], note: 'Luego: distensión y constipación',
          say: 'Después vienen la distensión abdominal y la constipación. Conecta esto con la clase de constipación en el niño: allá dijimos que siempre hay que descartar organicidad, y la pregunta que lo descarta es justamente si hubo retraso en la eliminación del meconio.' },
        { show: ['bio'], note: 'Se confirma con biopsia, no con la clínica',
          say: 'El diagnóstico se confirma con biopsia rectal, que muestra la ausencia de células ganglionares. Ese segmento sin ganglios no se relaja, y funciona como un tapón.' },
        { show: ['res'], note: 'Se saca el segmento sin ganglios',
          say: 'Por eso el tratamiento es sacar ese segmento: la resección del segmento agangliónico.' },
        { show: ['ano', 'exa'], note: 'Lo más simple: mirar',
          say: 'Y el ano imperforado, que es lo más simple de todo: se diagnostica por inspección. La lección es que al recién nacido siempre hay que examinarle el ano. Si en un caso nadie lo miró, esa es la respuesta.' },
      ],
    },

    {
      type: 'pathway',
      intro: 'Ahora pongamos todo en un solo árbol de decisión.',
    },

    {
      type: 'table',
      kicker: 'Trampas EUNACOM',
      title: 'Una clave diagnóstica por entidad',
      head: ['Entidad', 'Clave', 'Conducta'],
      rows: [
        { cells: ['Enterocolitis necrotizante', 'Prematuro + neumatosis en la Rx', 'Régimen cero + NPT + antibióticos; cirugía si perfora'],
          say: 'Repasemos en una tabla. Enterocolitis necrotizante: prematuro con neumatosis en la radiografía. Régimen cero, nutrición parenteral y antibióticos, y cirugía solo si perfora.' },
        { cells: ['Invaginación intestinal', 'Lactante 6–12 m + "mermelada de grosella" + dona', 'Reducción neumática (cirugía si falla)'],
          say: 'Invaginación: lactante de seis a doce meses, mermelada de grosella y signo de la dona. Reducción neumática, y cirugía solo si falla.' },
        { cells: ['Divertículo de Meckel', 'HDB indolora y abundante en niño pequeño', 'Cintigrafía con Tc-99m → resección'],
          say: 'Divertículo de Meckel: sangrado indoloro y abundante en un niño pequeño. Cintigrafía con tecnecio, y luego resección.' },
        { cells: ['Atresia duodenal', 'Vómito bilioso día 1 + doble burbuja', 'Cirugía'],
          say: 'Atresia duodenal: vómito bilioso desde el primer día y doble burbuja. Cirugía.' },
        { cells: ['Enfermedad de Hirschsprung', 'Meconio > 48 h + constipación', 'Biopsia rectal → resección'],
          say: 'Hirschsprung: meconio que no sale en cuarenta y ocho horas y constipación. Biopsia rectal, y resección.' },
        { cells: ['Hernia diafragmática congénita', 'Distrés respiratorio + abdomen excavado', 'Intubar y ventilar; cirugía diferida'],
          say: 'Y la hernia diafragmática congénita: distrés respiratorio con abdomen excavado. Primero intubar y ventilar; la cirugía, después.' },
      ],
    },

    {
      type: 'quiz',
      kicker: 'Caso clínico',
      title: 'Caso clínico',
      stem: 'Lactante de 9 meses, previamente sano, con episodios de llanto inconsolable y flexión de las piernas cada 15–20 minutos, decaído entre las crisis. En el pañal hay deposiciones con sangre y moco. La ecografía abdominal muestra el signo de la dona. Está hemodinámicamente estable y sin signos peritoneales.',
      question: '¿Cuál es el tratamiento de primera línea?',
      options: [
        { letter: 'A', text: 'Laparotomía exploradora de urgencia' },
        { letter: 'B', text: 'Reducción neumática guiada por imagen' },
        { letter: 'C', text: 'Colonoscopía con polipectomía' },
        { letter: 'D', text: 'Régimen cero, nutrición parenteral y antibióticos, sin otra intervención' },
        { letter: 'E', text: 'Cintigrafía con pertecnetato de Tc-99m' },
      ],
      correct: 'B',
      explanation: 'Lactante de 6–12 meses con crisis de llanto, "mermelada de grosella" y signo de la dona: invaginación intestinal. La primera línea es la reducción neumática (o hidrostática) guiada por imagen; la cirugía queda para el fracaso de la reducción, la perforación o una causa anatómica.',
      say: {
        stem: 'Vamos al caso. Lactante de nueve meses, previamente sano, con episodios de llanto inconsolable y flexión de las piernas cada quince a veinte minutos, decaído entre las crisis. En el pañal hay deposiciones con sangre y moco, y la ecografía muestra el signo de la dona. Está estable y sin signos peritoneales.',
        question: '¿Cuál es el tratamiento de primera línea?',
        options: 'Las alternativas: laparotomía de urgencia, reducción neumática guiada por imagen, colonoscopía con polipectomía, régimen cero con nutrición parenteral y antibióticos, o cintigrafía con tecnecio. Piénsalo.',
        answer: 'Es la B. La edad, las crisis de llanto, la mermelada de grosella y la dona te dan la invaginación sin ninguna duda. Y la primera línea es la reducción neumática. El distractor tentador es la laparotomía, porque suena a urgencia quirúrgica, pero en un lactante estable y sin peritonitis la cirugía es la última opción. Las demás alternativas son el tratamiento de otras entidades de esta clase.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2025 · Pregunta 146',
      stem: 'Recién nacido de 10 días de vida, con antecedente de haber nacido prematuro a las 27 semanas, alimentado con fórmula láctea para prematuros por sonda nasogástrica, presenta un cuadro de 2 días de evolución de distensión abdominal y aumento de la retención láctea, objetivada por la sonda. Se solicita radiografía simple de abdomen, que muestra dilatación de asas intestinales, con zonas de engrosamiento de la pared intestinal y visualización de burbujas en algunos segmentos.',
      question: 'Además de suspender la fórmula láctea y asegurar una adecuada hidratación por vía endovenosa, ¿cuál es la conducta más adecuada?',
      options: [
        { letter: 'A', text: 'Realizar resolución quirúrgica inmediata' },
        { letter: 'B', text: 'Iniciar alimentación con fórmula hidrolizada de proteínas por sonda nasoenteral' },
        { letter: 'C', text: 'Administrar antibióticos de amplio espectro por vía endovenosa' },
        { letter: 'D', text: 'Realizar endoscopía digestiva alta' },
        { letter: 'E', text: 'Alimentar con suero glucosado por vía oral' },
      ],
      correct: 'C',
      explanation: 'Prematuro con distensión abdominal y retención láctea, más burbujas de aire en la pared intestinal en la radiografía: enterocolitis necrotizante. Ya con régimen cero e hidratación endovenosa en marcha, el paso siguiente es agregar antibióticos de amplio espectro. La cirugía se reserva a la perforación, la necrosis o la falla del tratamiento médico; no se alimenta al niño, ni por sonda ni por boca.',
      say: {
        stem: 'Ahora una pregunta real del examen, de diciembre de dos mil veinticinco. Recién nacido de diez días, que nació prematuro a las veintisiete semanas, alimentado por sonda nasogástrica. Hace dos días tiene distensión abdominal y le aumentó la retención de la leche en la sonda. La radiografía de abdomen muestra asas dilatadas, con zonas de la pared engrosadas y burbujas de aire en algunos segmentos.',
        question: 'Además de suspender la fórmula láctea y asegurar hidratación endovenosa, ¿cuál es la conducta más adecuada?',
        options: 'Las opciones: cirugía inmediata, alimentar con fórmula hidrolizada por sonda, antibióticos de amplio espectro endovenosos, endoscopía digestiva alta, o suero glucosado por boca. Piénsalo.',
        answer: 'Es la C. El cuadro completo, el prematuro, la distensión, y la imagen clave, aire en la pared intestinal, es la enterocolitis necrotizante. Ya suspendieron la alimentación y están hidratando, así que lo que falta es agregar antibióticos de amplio espectro. Nada de alimentar, por ninguna vía, y la cirugía se reserva para cuando el tratamiento médico falla o hay perforación.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2022 · Pregunta 40',
      stem: 'Paciente de 19 años que acude al servicio de urgencia por un cuadro de rectorragia de 2 días de evolución, que el día de hoy se volvió mucho más abundante. Al examen físico tiene frecuencia cardíaca de 117 por minuto, presión arterial de 90/60 mm Hg, palidez de piel y mucosas, y examen abdominal con dolor difuso a la palpación, sin signos de irritación peritoneal. Al preguntar dirigidamente, refiere antecedente de varios episodios de dolor periumbilical recurrente, de tipo urente, que había cedido de manera espontánea. El hemograma muestra hematocrito 27 por ciento y hemoglobina 8,1 gramos por decilitro. La colonoscopía de urgencia muestra abundante sangre en todo el trayecto colónico, que fluye, además, por la válvula ileocecal.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Enfermedad de Crohn' },
        { letter: 'B', text: 'Pólipo juvenil' },
        { letter: 'C', text: 'Infección por Shigella' },
        { letter: 'D', text: 'Divertículo de Meckel' },
        { letter: 'E', text: 'Adenitis mesentérica' },
      ],
      correct: 'D',
      explanation: 'Hemorragia digestiva baja masiva, con sangre que fluye desde el íleon a través de la válvula ileocecal, en un paciente con episodios previos de dolor periumbilical urente que cedían solos (la diverticulitis que imita apendicitis, ya resuelta espontáneamente): divertículo de Meckel. El examen que lo confirma es la cintigrafía con pertecnetato de Tc-99m, que capta la mucosa gástrica ectópica que sangra.',
      say: {
        stem: 'Otra pregunta real, de diciembre de dos mil veintidós. Paciente de diecinueve años con rectorragia de dos días, que hoy se volvió mucho más abundante. Está taquicárdico, con la presión baja y pálido. Antes había tenido varios episodios de dolor periumbilical urente que cedían solos. La colonoscopía de urgencia muestra sangre en todo el colon, que además fluye desde la válvula ileocecal.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones: enfermedad de Crohn, pólipo juvenil, infección por Shigella, divertículo de Meckel, o adenitis mesentérica. Piénsalo.',
        answer: 'Es la D. La sangre entra al colon desde la válvula ileocecal, es decir, viene del íleon, que es justo donde está el Meckel. Y los episodios previos de dolor periumbilical que cedían solos son esos brotes de diverticulitis que imitan una apendicitis leve. El diagnóstico se confirmaría con la cintigrafía con tecnecio, que aquí ni siquiera hizo falta pedir porque la colonoscopía ya dio la pista.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Agosto 2021 · Pregunta 175',
      stem: 'Niño de 48 horas de vida, con antecedente de síndrome de Down, presenta vómitos alimentarios explosivos, asociados a irritabilidad y decaimiento. Al examen abdominal se palpa abdomen blando, doloroso, con distensión epigástrica, que desaparece después de vomitar.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Atresia esofágica' },
        { letter: 'B', text: 'Hiperplasia suprarrenal congénita' },
        { letter: 'C', text: 'Enterocolitis necrotizante' },
        { letter: 'D', text: 'Atresia duodenal' },
        { letter: 'E', text: 'Estenosis hipertrófica del píloro' },
      ],
      correct: 'D',
      explanation: 'Vómitos explosivos desde las primeras horas de vida, con distensión epigástrica que cede al vomitar, en un recién nacido con síndrome de Down: atresia duodenal. La radiografía mostraría la doble burbuja. La estenosis del píloro aparece más tarde, entre la segunda y la sexta semana, no a las cuarenta y ocho horas.',
      say: {
        stem: 'Y una pregunta real más, de agosto de dos mil veintiuno. Niño de cuarenta y ocho horas de vida, con síndrome de Down, con vómitos explosivos, irritable y decaído. El abdomen está blando, doloroso, con distensión en el epigastrio que desaparece después de vomitar.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones: atresia esofágica, hiperplasia suprarrenal congénita, enterocolitis necrotizante, atresia duodenal, o estenosis hipertrófica del píloro. Piénsalo.',
        answer: 'Es la D. Vómito bilioso explosivo desde las primeras horas de vida, con síndrome de Down: atresia duodenal. La trampa es la estenosis del píloro, porque también da vómitos explosivos, pero esa aparece entre la segunda y la sexta semana, no a las cuarenta y ocho horas.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2019 · Pregunta 19',
      stem: 'Recién nacido presenta marcada dificultad respiratoria. Al examen físico tiene abolición del murmullo pulmonar izquierdo y se auscultan los ruidos cardíacos desplazados hacia el lado derecho. Su abdomen está excavado.',
      question: '¿Cuál es la conducta inicial?',
      options: [
        { letter: 'A', text: 'Cirugía de urgencia' },
        { letter: 'B', text: 'Realizar intubación orotraqueal' },
        { letter: 'C', text: 'Realizar toracostomía de urgencia' },
        { letter: 'D', text: 'Administrar prostaglandinas y oxígeno al 100 por ciento' },
        { letter: 'E', text: 'Ventilación a presión positiva por mascarilla' },
      ],
      correct: 'B',
      explanation: 'Dificultad respiratoria grave, murmullo pulmonar ausente de un lado, ruidos cardíacos desplazados y abdomen excavado: hernia diafragmática congénita. La conducta inicial es intubar y ventilar; la reparación quirúrgica es diferida. La mascarilla con presión positiva está contraindicada, porque distiende más las asas dentro del tórax.',
      say: {
        stem: 'Y otra pregunta real, de julio de dos mil diecinueve. Recién nacido con dificultad respiratoria marcada. Al examen no se escucha el murmullo pulmonar del lado izquierdo, y los ruidos del corazón están desplazados hacia el lado derecho. El abdomen está excavado.',
        question: '¿Cuál es la conducta inicial?',
        options: 'Las opciones: cirugía de urgencia, intubación orotraqueal, toracostomía de urgencia, prostaglandinas con oxígeno al cien por ciento, o ventilación a presión positiva por mascarilla. Piénsalo.',
        answer: 'Es la B. Abdomen excavado, con el pulmón y el corazón desplazados: hernia diafragmática congénita. Lo urgente es asegurar la vía aérea, intubando; la cirugía viene después, con el niño estabilizado. Y ojo con la mascarilla con presión positiva: mete aire al intestino que está en el tórax, y empeora todo.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2013 · Pregunta 11',
      stem: 'Niño de 6 años, sin antecedentes, es traído por presentar sangrado rectal fresco en gotas al final de las deposiciones, no asociado a dolor ni a otros síntomas. Al examen físico se encuentra con índice de masa corporal adecuado para su edad, abdomen blando, depresible y no doloroso, con ruidos hidroaéreos presentes.',
      question: '¿Cuál es el diagnóstico más probable en este caso?',
      options: [
        { letter: 'A', text: 'Úlcera rectal solitaria' },
        { letter: 'B', text: 'Hemorroides' },
        { letter: 'C', text: 'Divertículo de Meckel' },
        { letter: 'D', text: 'Pólipo juvenil' },
        { letter: 'E', text: 'Fisura anal' },
      ],
      correct: 'D',
      explanation: 'Escolar sano, sin ninguna otra alteración, con sangrado rectal escaso, en gotas y sin dolor: pólipo juvenil, un hamartoma benigno. Se confirma y se trata en el mismo acto con colonoscopía y polipectomía. El divertículo de Meckel sangra de forma más abundante y en niños más pequeños; la fisura anal duele.',
      say: {
        stem: 'Y la última pregunta real de esta clase, de julio de dos mil trece. Niño de seis años, sin antecedentes, con sangrado rectal fresco en gotas al final de las deposiciones, sin dolor ni ningún otro síntoma. El examen físico es completamente normal.',
        question: '¿Cuál es el diagnóstico más probable en este caso?',
        options: 'Las opciones: úlcera rectal solitaria, hemorroides, divertículo de Meckel, pólipo juvenil, o fisura anal. Piénsalo.',
        answer: 'Es la D. Escolar sano, con un sangrado escaso e intermitente, sin dolor: es el pólipo juvenil. La fisura anal duele, y el divertículo de Meckel sangra mucho más y en niños más pequeños. Se confirma y se trata con colonoscopía y polipectomía, en el mismo procedimiento.',
      },
    },

    {
      type: 'points',
      kicker: 'Cierre',
      title: 'Reglas de oro para el examen',
      cards: [
        { title: 'Recién nacido', tag: 'Imagen clave', kind: 'key', items: [
          { t: 'Prematuro + neumatosis', d: 'Enterocolitis: tratamiento médico, cirugía si perfora',
            say: 'Cerremos con las reglas de oro. Prematuro con neumatosis es enterocolitis necrotizante: tratamiento médico, y cirugía si perfora.' },
          { t: 'Vómito bilioso día 1 + doble burbuja', d: 'Atresia duodenal',
            say: 'Vómito bilioso desde el primer día con doble burbuja es atresia duodenal.' },
          { t: 'Meconio > 48 h', d: 'Hirschsprung: biopsia rectal',
            say: 'Meconio que no sale en cuarenta y ocho horas es Hirschsprung, y se confirma con biopsia rectal.' },
          { t: 'Hernia diafragmática congénita', d: 'Intubar y ventilar primero',
            say: 'Y en la hernia diafragmática congénita, primero intubar y ventilar.' },
        ] },
        { title: 'Lactante y niño', tag: 'Sangre por el recto', kind: 'alert', items: [
          { t: 'Crisis de llanto + "mermelada de grosella"', d: 'Invaginación: reducción neumática',
            say: 'Lactante con crisis de llanto y mermelada de grosella es invaginación, y la primera línea es la reducción neumática, no la cirugía.' },
          { t: 'Sangrado indoloro y abundante', d: 'Meckel: cintigrafía con Tc-99m',
            say: 'Sangrado abundante y sin dolor en un niño pequeño es Meckel, y se busca con cintigrafía. Si te llevas una sola idea de hoy: en cirugía pediátrica, cada diagnóstico tiene su imagen clave, y la edad del niño te dice cuál buscar. Nos vemos en la próxima clase.' },
        ] },
      ],
    },
  ],

  pathway: {
    title: 'Urgencias quirúrgicas digestivas del RN y el lactante',
    root: N('start', 'Urgencia digestiva en el niño', 'La edad y la imagen clave deciden',
      'Partimos de un niño con una urgencia digestiva. Lo primero que miramos es la edad, porque cada etapa tiene sus propios diagnósticos.',
      ['', N('q', '¿Recién nacido o lactante?', 'Días de vida vs meses',
        '¿Es un recién nacido de días, o un lactante o niño mayor?',
        ['Recién nacido', N('q', '¿Qué predomina?', 'Distensión, vómito o meconio',
          'En el recién nacido, preguntamos qué predomina: distensión con sangre, vómito bilioso, o meconio que no sale.',
          ['Prematuro + sangre', N('alert', 'Rx: neumatosis', 'Enterocolitis necrotizante',
            'Prematuro con distensión, retención gástrica y hematoquecia: radiografía de abdomen buscando neumatosis. Es enterocolitis necrotizante: régimen cero, nutrición parenteral y antibióticos, y cirugía si hay neumoperitoneo.')],
          ['Vómito bilioso día 1', N('refer', 'Rx: doble burbuja', 'Atresia duodenal → cirugía',
            'Vómitos biliosos desde el primer día con doble burbuja en la radiografía: atresia duodenal, asociada a síndrome de Down. Se deriva a cirugía.')],
          ['Meconio > 48 h', N('refer', 'Biopsia rectal', 'Hirschsprung → resección',
            'Si el meconio no sale en cuarenta y ocho horas, pensamos en Hirschsprung. Se confirma con biopsia rectal, sin células ganglionares, y se reseca el segmento agangliónico.')])],
        ['Lactante o niño', N('q', '¿Sangrado con dolor?', 'Crisis de llanto vs indoloro',
          'En el lactante o el niño que sangra, la pregunta es si le duele.',
          ['Con crisis de llanto', N('do', 'Ecografía: signo de la dona', 'Invaginación intestinal',
            'Lactante de seis a doce meses con crisis de llanto y mermelada de grosella: ecografía con signo de la dona.',
            ['', N('ok', 'Reducción neumática', 'Cirugía solo si falla o perfora',
              'La primera línea es la reducción neumática o hidrostática guiada por imagen. La cirugía queda para el fracaso, la perforación o una causa anatómica.')])],
          ['Indoloro', N('do', 'Cintigrafía con Tc-99m', 'Divertículo de Meckel → resección',
            'Sangrado abundante e indoloro en un niño pequeño: divertículo de Meckel. El examen es la cintigrafía con pertecnetato de tecnecio, y el tratamiento, la resección.')])])]),
  },
};
