// Clase 1.4 — guion docente escrito a mano (ver gastro-01.cjs para el formato).
// Fuente clínica: books/scripts/dataset_gastroenterologia.cjs (gastro-04).

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  id: 'gastro-04',
  tier: 3,
  slides: [
    {
      type: 'cover',
      subtitle: 'Cuándo la endoscopía se prohíbe y cuándo es lo primero',
      say: 'Bienvenidos. Hoy vemos tres urgencias del tubo digestivo alto: la úlcera perforada, la perforación del esófago y la ingesta de cáustico. El examen las pone juntas a propósito, porque comparten una regla que va contra la intuición. Si entiendes esa regla, respondes las tres. Y además aparece una cuarta, el Mallory-Weiss, que el examen usa como distractor. Partamos por la regla.',
    },

    {
      type: 'flow',
      kicker: 'La regla de la clase',
      title: 'Endoscopía: prohibida o primera medida',
      nodes: [
        { id: 'urg', col: 0, row: 1, k: 'start', t: 'Urgencia digestiva alta', s: '¿Hay un agujero o una quemadura?' },
        { id: 'per', col: 1, row: 0, k: 'risk', t: 'Perforación', s: 'Úlcera o esófago' },
        { id: 'aire', col: 2, row: 0, k: 'mech', t: 'El aire agranda la fuga', s: 'La endoscopía insufla aire' },
        { id: 'no', col: 3, row: 0, k: 'alert', t: 'Endoscopía contraindicada', s: 'Imagen y cirugía' },
        { id: 'cau', col: 1, row: 2, k: 'risk', t: 'Ingesta de cáustico', s: 'El daño ya ocurrió' },
        { id: 'eda', col: 2, row: 2, k: 'good', t: 'Endoscopía precoz', s: 'Define el daño y la conducta' },
        { id: 'trap', col: 3, row: 2, k: 'trap', t: 'Carbón activado o lavado', s: 'Prohibidos: agravan el daño' },
      ],
      edges: [
        { from: 'urg', to: 'per' }, { from: 'per', to: 'aire' }, { from: 'aire', to: 'no' },
        { from: 'urg', to: 'cau' }, { from: 'cau', to: 'eda' }, { from: 'eda', to: 'trap', label: 'nunca' },
      ],
      steps: [
        { show: ['urg'], note: 'La endoscopía parece el examen natural',
          say: 'Frente a una urgencia del tubo digestivo alto, lo intuitivo es pensar en la endoscopía. Es el examen natural de esa zona. Pero en esta clase, esa intuición te puede hacer perder puntos.' },
        { show: ['per'], note: 'Úlcera perforada y perforación esofágica',
          say: 'Si lo que hay es una perforación, ya sea de una úlcera o del esófago, la pared tiene un agujero, y por ese agujero el contenido digestivo ya está saliendo hacia donde no debe.' },
        { show: ['aire'], note: 'Insuflar aire a presión empuja contenido afuera',
          say: 'Y la endoscopía necesita insuflar aire para ver. Ese aire a presión sale por el agujero y agranda la fuga hacia el peritoneo o el mediastino.' },
        { show: ['no'], note: 'En toda perforación: imagen y cirugía',
          say: 'Por eso, en toda perforación, la endoscopía está contraindicada. El diagnóstico se hace con imagen, y el tratamiento es quirúrgico.' },
        { show: ['cau'], note: 'Aquí el daño es químico e inmediato',
          say: 'La ingesta de cáustico es la excepción. Aquí no partimos de un agujero, sino de una quemadura química que ocurre en el mismo momento en que el paciente traga.' },
        { show: ['eda'], note: 'Aquí la endoscopía es lo primero',
          say: 'Y lo que necesitamos saber es qué tan profunda es esa quemadura. Por eso aquí la endoscopía precoz es la primera medida: gradúa el daño y define la conducta.' },
        { show: ['trap'], note: 'La trampa: carbón activado y lavado gástrico',
          say: 'Y la trampa de este cuadro: el carbón activado y el lavado gástrico están prohibidos. Suenan a manejo de intoxicación, pero el daño ya ocurrió, y ambos lo empeoran. Con esta regla en mente, veamos cada cuadro.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'Úlcera perforada',
      title: 'Del síndrome ulceroso al abdomen en tabla',
      nodes: [
        { id: 'ant', col: 0, row: 1, k: 'cause', t: 'Síndrome ulceroso previo', s: 'Epigastralgia de meses' },
        { id: 'per', col: 1, row: 1, k: 'mech', t: 'La úlcera atraviesa la pared', s: 'Gástrica o duodenal' },
        { id: 'aci', col: 2, row: 1, k: 'mech', t: 'Ácido al peritoneo', s: 'Contenido muy irritante' },
        { id: 'dol', col: 3, row: 0, k: 'effect', t: 'Dolor en puñalada', s: 'Epigástrico, brusco, se generaliza' },
        { id: 'tab', col: 3, row: 2, k: 'effect', t: 'Abdomen en tabla', s: 'Blumberg +, RHA abolidos' },
      ],
      edges: [
        { from: 'ant', to: 'per' }, { from: 'per', to: 'aci' },
        { from: 'aci', to: 'dol' }, { from: 'aci', to: 'tab' },
      ],
      steps: [
        { show: ['ant'], note: 'El antecedente es la primera pista',
          say: 'Primer cuadro, la úlcera perforada. Ya la mencionamos en la clase de úlcera péptica, y ahora la vemos en detalle. La primera pista está en el antecedente: un paciente con síndrome ulceroso, con epigastralgia de meses.' },
        { show: ['per'], note: 'La complicación: la úlcera atraviesa toda la pared',
          say: 'En algún momento, esa úlcera profundiza hasta atravesar toda la pared del estómago o del duodeno.' },
        { show: ['aci'], note: 'Lo que se vierte es ácido',
          say: 'Y lo que se vierte al peritoneo es contenido ácido. Eso es clave para entender la clínica, porque el ácido es muy irritante para el peritoneo.' },
        { show: ['dol'], note: 'Brusco, epigástrico, y en minutos a todo el abdomen',
          say: 'Por eso el dolor es tan característico: brusco, epigástrico, como una puñalada, y que en poco tiempo se generaliza a todo el abdomen, a medida que el ácido se distribuye.' },
        { show: ['tab'], note: 'Peritonitis química difusa',
          say: 'Y al examen, un peritoneo irritado: abdomen en tabla, Blumberg positivo y ruidos hidroaéreos abolidos. Síndrome ulceroso más dolor en puñalada más abdomen en tabla: úlcera perforada.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Úlcera perforada',
      title: 'Cómo se confirma y cómo se trata',
      cards: [
        { title: 'Examen inicial', tag: 'Buscar aire libre', kind: 'criteria', items: [
          { t: 'Radiografía de tórax de pie', d: 'Neumoperitoneo bajo el hemidiafragma derecho',
            say: '¿Cómo lo confirmas? Con una radiografía de tórax de pie. Buscamos neumoperitoneo: el aire que escapó sube y queda bajo el diafragma, sobre todo bajo el hemidiafragma derecho, donde el hígado lo hace más visible.' },
          { t: 'Sin Rx de tórax: abdomen de pie', d: 'Alternativa si no está disponible',
            say: 'Si no tienes radiografía de tórax disponible, sirve la radiografía de abdomen de pie.' },
        ] },
        { title: 'Tratamiento', tag: 'Cirugía de urgencia', kind: 'pharma', items: [
          { t: 'Sutura + parche de epiplón', d: 'Parche de Graham',
            say: 'El tratamiento es la cirugía de urgencia: se sutura la perforación y se cubre con un parche de epiplón, el parche de Graham.' },
          { t: 'Suero, IBP ev, antibióticos', d: 'Complementos, no reemplazo',
            say: 'Suero, IBP endovenoso y antibióticos de amplio espectro se indican, pero son complementos. Acompañan a la cirugía; no la reemplazan.' },
        ] },
        { title: 'Trampas', tag: 'Se preguntan', kind: 'alert', items: [
          { t: 'Endoscopía contraindicada', d: 'El aire aumenta la filtración',
            say: 'Y las dos trampas. La primera ya la conoces: la endoscopía está contraindicada, porque el aire insuflado aumenta la filtración al peritoneo.' },
          { t: 'Si ofrecen todo: cirugía', d: 'Suero + ATB + IBP + cirugía → cirugía',
            say: 'La segunda: si el enunciado te ofrece suero, antibióticos, IBP y cirugía como alternativas separadas, la respuesta es siempre la cirugía. Es lo único que cierra el agujero. Los fármacos ganan tiempo, pero el paciente sigue con una peritonitis mientras la perforación esté abierta.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Perforación esofágica',
      title: 'El esófago también se perfora',
      nodes: [
        { id: 'iat', col: 0, row: 0, k: 'cause', t: 'Iatrogenia endoscópica', s: 'La causa más frecuente' },
        { id: 'vom', col: 0, row: 2, k: 'cause', t: 'Vómitos intensos', s: 'Síndrome de Boerhaave' },
        { id: 'per', col: 1, row: 1, k: 'mech', t: 'Perforación transmural', s: 'Aire y contenido al mediastino' },
        { id: 'tri', col: 2, row: 1, k: 'effect', t: 'Dolor torácico + vómitos + enfisema', s: 'La tríada' },
        { id: 'med', col: 3, row: 1, k: 'risk', t: 'Mediastinitis aguda', s: 'La complicación temida' },
      ],
      edges: [
        { from: 'iat', to: 'per' }, { from: 'vom', to: 'per', label: 'espontánea' },
        { from: 'per', to: 'tri' }, { from: 'tri', to: 'med', label: 'si progresa' },
      ],
      steps: [
        { show: ['iat'], note: 'Primero: la endoscopía misma',
          say: 'Segundo cuadro, la perforación del esófago. ¿Cuál es la causa más frecuente? No es la que uno piensa: es iatrogénica, por la propia endoscopía.' },
        { show: ['vom'], note: 'Boerhaave: perforación espontánea tras vomitar',
          say: 'Pero la que más se pregunta es el síndrome de Boerhaave: la perforación espontánea después de vómitos intensos. El típico enunciado es una comida abundante con alcohol, seguida de varios vómitos.' },
        { show: ['per'], note: 'Se rompe toda la pared',
          say: 'Con el esfuerzo del vómito, la presión rompe toda la pared del esófago. Es una perforación transmural, y el aire y el contenido pasan al mediastino.' },
        { show: ['tri'], note: 'El aire se hace palpable en el cuello',
          say: 'Eso explica la tríada: dolor torácico, o cervical, más el antecedente de vómitos, más enfisema subcutáneo. Ese aire del mediastino sube y se palpa como crepitación en el cuello.' },
        { show: ['med'], note: 'Fiebre y taquicardia: mediastinitis',
          say: 'Y si el cuadro progresa, aparece la complicación temida: la mediastinitis aguda. Por eso, si el paciente además está febril y taquicárdico, ya estás frente a un cuadro séptico. Y ojo, un dolor torácico intenso en un adulto siempre te hace pensar en el corazón o la aorta; lo que te lleva al esófago es el antecedente de vómitos y el enfisema.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'La diferencia que más se pregunta',
      title: 'Boerhaave vs Mallory-Weiss',
      nodes: [
        { id: 'vom', col: 0, row: 1, k: 'start', t: 'Vómitos intensos', s: 'Mismo antecedente' },
        { id: 'hem', col: 1, row: 0, k: 'effect', t: 'Hematemesis', s: 'Sin enfisema ni sepsis' },
        { id: 'mw', col: 2, row: 0, k: 'mech', t: 'Mallory-Weiss', s: 'Desgarro de la mucosa' },
        { id: 'mwt', col: 3, row: 0, k: 'good', t: 'EDA; suele ceder solo', s: 'Hemostasia si sangra' },
        { id: 'enf', col: 1, row: 2, k: 'effect', t: 'Dolor torácico + enfisema', s: 'Fiebre, taquicardia' },
        { id: 'boe', col: 2, row: 2, k: 'risk', t: 'Boerhaave', s: 'Perforación transmural' },
        { id: 'boet', col: 3, row: 2, k: 'alert', t: 'Endoscopía contraindicada', s: 'Imagen y cirugía' },
      ],
      edges: [
        { from: 'vom', to: 'hem' }, { from: 'hem', to: 'mw' }, { from: 'mw', to: 'mwt' },
        { from: 'vom', to: 'enf' }, { from: 'enf', to: 'boe' }, { from: 'boe', to: 'boet' },
      ],
      steps: [
        { show: ['vom'], note: 'Dos cuadros que parten igual',
          say: 'Y aquí está la diferencia que más se pregunta. Hay dos cuadros que parten exactamente igual: un paciente que vomita con fuerza. Lo que decide es qué viene después.' },
        { show: ['hem'], note: 'Si después sangra: Mallory-Weiss',
          say: 'Si después de los vómitos aparece hematemesis, sin enfisema ni fiebre, piensa en Mallory-Weiss. Es una causa de hemorragia digestiva alta que vas a volver a ver en la clase de hemorragia digestiva.' },
        { show: ['mw'], note: 'Solo se rompe la mucosa',
          say: 'Es un desgarro que compromete solo la mucosa. La pared queda entera, así que no hay aire que escape.' },
        { show: ['mwt'], note: 'Aquí sí se endoscopia',
          say: 'Por eso aquí la endoscopía sí se hace: es el examen de elección. Suele ceder solo, y si sigue sangrando, se hace hemostasia endoscópica.' },
        { show: ['enf'], note: 'Si después duele y crepita: Boerhaave',
          say: 'Si en cambio, después de los vómitos, aparece dolor torácico, enfisema subcutáneo y signos de sepsis, piensa en Boerhaave.' },
        { show: ['boe', 'boet'], note: 'Vómitos → sangre: mucosa. Vómitos → aire: pared completa',
          say: 'Aquí la rotura es de toda la pared, y la endoscopía está contraindicada. Resumen: vómitos seguidos de sangre es Mallory-Weiss; vómitos seguidos de aire y dolor es Boerhaave.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Perforación esofágica',
      title: 'Cómo se confirma y cómo se trata',
      cards: [
        { title: 'Diagnóstico', tag: 'Buscar neumomediastino', kind: 'criteria', items: [
          { t: 'Radiografía de tórax', d: 'Neumomediastino y enfisema',
            say: 'Volvamos al Boerhaave. El examen inicial es la radiografía de tórax, buscando neumomediastino y enfisema subcutáneo.' },
          { t: 'TAC de tórax', d: 'Si la Rx es negativa y la sospecha alta',
            say: 'Si la radiografía sale negativa, pero la sospecha clínica es alta, no te quedas tranquilo: pides un TAC de tórax.' },
          { t: 'Endoscopía contraindicada', d: 'Igual que en la úlcera perforada',
            say: 'Y la endoscopía, igual que en la úlcera perforada, está contraindicada.' },
        ] },
        { title: 'Tratamiento', tag: 'Cirugía de urgencia', kind: 'pharma', items: [
          { t: 'Cirugía de urgencia', d: 'Para evitar la mediastinitis',
            say: 'El tratamiento es la cirugía de urgencia, para cerrar la perforación antes de que se instale la mediastinitis.' },
          { t: 'Conservador: la excepción', d: 'Pequeña, contenida, buena evolución',
            say: 'El manejo conservador, con régimen cero y antibióticos, es la excepción. Solo cabe en perforaciones pequeñas, contenidas y con buena evolución. En el examen, si el paciente está séptico, la respuesta es cirugía. Fíjate en la lógica común con la úlcera perforada: agujero, imagen para confirmarlo, y pabellón para cerrarlo.' },
        ] },
      ],
    },

    {
      type: 'points',
      kicker: 'Ingesta de cáustico',
      title: 'Soda cáustica: qué se hace y qué se prohíbe',
      cards: [
        { title: 'Clínica', tag: 'Del labio al epigastrio', kind: 'key', items: [
          { t: 'Dolor y edema, sialorrea, disfagia', d: 'Desde los labios hasta el epigastrio',
            say: 'Tercer cuadro, la ingesta de cáustico, típicamente soda cáustica. El cáustico quema todo lo que toca, así que el dolor y el edema van desde los labios hasta el epigastrio, con sialorrea y disfagia. El niño que babea y llora al tragar es el enunciado clásico.' },
          { t: 'Hemorragia o perforación', d: 'Peritonitis o mediastinitis',
            say: 'En los casos graves puede haber hemorragia digestiva, o perforación, con peritonitis o mediastinitis.' },
        ] },
        { title: 'Primera medida', tag: 'Endoscopía precoz', kind: 'criteria', items: [
          { t: 'EDA en las primeras 12–24 h', d: 'Gradúa el daño y decide la conducta',
            say: 'La primera medida es la endoscopía digestiva alta precoz, idealmente dentro de las primeras doce a veinticuatro horas. Gradúa el daño, y ese grado decide todo lo que viene después. Fíjate que la pregunta no es si el paciente se quemó, eso ya lo sabemos, sino qué tan profundo llegó la quemadura, y eso solo lo muestra el endoscopio.' },
        ] },
        { title: 'Contraindicado', tag: 'Nunca', kind: 'alert', items: [
          { t: 'Carbón activado y lavado gástrico', d: 'El daño es inmediato e irreversible',
            say: 'Y lo que está prohibido. El carbón activado y el lavado gástrico están contraindicados. El daño es inmediato e irreversible, así que no hay nada que rescatar, y ambos lo agravan: el lavado vuelve a exponer el esófago al cáustico y puede perforarlo.' },
          { t: 'Ni neutralizar ni provocar el vómito', d: 'Nada de leche ni vinagre',
            say: 'Tampoco se dan neutralizantes, como leche o vinagre, ni se provoca el vómito. Si vomita, el cáustico vuelve a pasar por el esófago y lo quema por segunda vez.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Ingesta de cáustico',
      title: 'La endoscopía decide la conducta',
      nodes: [
        { id: 'eda', col: 0, row: 2, k: 'start', t: 'Endoscopía precoz', s: '¿Qué tan profundo es el daño?' },
        { id: 'nor', col: 1, row: 0, k: 'good', t: 'Normal o eritema leve', s: 'Daño superficial' },
        { id: 'nor2', col: 2, row: 0, k: 'good', t: 'Observación', s: 'Realimentación oral progresiva' },
        { id: 'ulc', col: 1, row: 2, k: 'risk', t: 'Úlceras o inflamación', s: 'Daño significativo' },
        { id: 'ulc2', col: 2, row: 2, k: 'mech', t: 'Régimen cero + NPT', s: 'Y endoscopía de control' },
        { id: 'nec', col: 1, row: 4, k: 'alert', t: 'Necrosis o perforación', s: 'Daño extenso' },
        { id: 'nec2', col: 2, row: 4, k: 'alert', t: 'Cirugía de urgencia', s: 'Más régimen cero + NPT' },
        { id: 'est', col: 3, row: 2, k: 'risk', t: 'Estenosis cicatricial', s: 'Dilataciones o reconstrucción' },
        { id: 'esc', col: 4, row: 2, k: 'risk', t: 'Carcinoma escamoso', s: 'Riesgo a largo plazo' },
      ],
      edges: [
        { from: 'eda', to: 'nor' }, { from: 'nor', to: 'nor2' },
        { from: 'eda', to: 'ulc' }, { from: 'ulc', to: 'ulc2' },
        { from: 'eda', to: 'nec' }, { from: 'nec', to: 'nec2' },
        { from: 'ulc2', to: 'est', label: 'secuela' }, { from: 'est', to: 'esc', label: 'años' },
      ],
      steps: [
        { show: ['eda'], note: 'Tres escenarios según el hallazgo',
          say: '¿Y qué hacemos con lo que muestra la endoscopía? Hay tres escenarios, y van de menor a mayor daño.' },
        { show: ['nor', 'nor2'], note: 'Daño superficial: vuelve a comer',
          say: 'Si la mucosa está normal o con eritema leve, el daño es superficial. Se observa y se realimenta por boca de forma progresiva.' },
        { show: ['ulc', 'ulc2'], note: 'Úlceras: se deja descansar el esófago',
          say: 'Si hay úlceras o inflamación significativa, se deja descansar el esófago: régimen cero, nutrición parenteral y una endoscopía de control.' },
        { show: ['nec', 'nec2'], note: 'Necrosis o perforación: al pabellón',
          say: 'Y si hay necrosis extensa o perforación, se suma la cirugía de urgencia, además del régimen cero y la nutrición parenteral. Fíjate que aquí volvemos a la regla de la perforación: se opera.' },
        { show: ['est'], note: 'La cicatriz estrecha el esófago',
          say: 'Pero el cuadro no termina en la urgencia. La secuela tardía es la estenosis esofágica cicatricial, que se maneja con dilataciones, o con una reconstrucción usando estómago o colon.' },
        { show: ['esc'], note: 'Conecta con la disfagia lógica',
          say: 'Y a largo plazo aumenta el riesgo de carcinoma escamoso. Conéctalo con la clase de disfagia: un paciente con ingesta de cáustico antigua que empieza con disfagia lógica necesita endoscopía con biopsia.' },
      ],
    },

    {
      type: 'pathway',
      intro: 'Ahora pongamos las tres urgencias en un solo árbol: el contexto clínico decide el examen.',
    },

    {
      type: 'table',
      kicker: 'Trampas EUNACOM',
      title: 'Examen inicial y lo que está prohibido',
      head: ['Cuadro', 'Examen inicial', 'Conducta · contraindicado'],
      rows: [
        { cells: ['Úlcera perforada', 'Rx tórax de pie (neumoperitoneo)', 'Cirugía de urgencia · NO endoscopía'],
          say: 'Repasemos en una tabla. Úlcera perforada: radiografía de tórax de pie buscando neumoperitoneo, y cirugía de urgencia. Nunca endoscopía.' },
        { cells: ['Perforación esofágica (Boerhaave)', 'Rx tórax → TAC tórax (neumomediastino)', 'Cirugía de urgencia · NO endoscopía'],
          say: 'Perforación esofágica: radiografía de tórax, y si es negativa, TAC, buscando neumomediastino. Cirugía de urgencia, y tampoco endoscopía.' },
        { cells: ['Ingesta de cáustico', 'EDA precoz (gradúa el daño)', 'Según EDA · NO carbón, lavado ni vómito'],
          say: 'Ingesta de cáustico: aquí la endoscopía precoz es lo primero, y la conducta depende de lo que muestre. Prohibidos el carbón activado, el lavado gástrico y provocar el vómito.' },
        { cells: ['Mallory-Weiss', 'EDA', 'Suele ceder solo · hemostasia si sangra'],
          say: 'Y Mallory-Weiss: endoscopía, que suele mostrar un desgarro que cede solo, con hemostasia endoscópica si sigue sangrando.' },
      ],
    },

    {
      type: 'quiz',
      kicker: 'Caso clínico',
      title: 'Caso clínico',
      stem: 'Hombre de 58 años con epigastralgia de meses consulta por dolor epigástrico súbito, "como una puñalada", que en 1 hora se extendió a todo el abdomen. Está pálido y taquicárdico, con abdomen rígido, doloroso en forma difusa y sin ruidos hidroaéreos. La radiografía de tórax de pie muestra aire bajo el hemidiafragma derecho.',
      question: '¿Cuál es la conducta más adecuada?',
      options: [
        { letter: 'A', text: 'Endoscopía digestiva alta urgente' },
        { letter: 'B', text: 'Suero, IBP endovenoso y antibióticos, y observar' },
        { letter: 'C', text: 'Cirugía de urgencia' },
        { letter: 'D', text: 'TAC de abdomen con contraste' },
        { letter: 'E', text: 'Sonda nasogástrica y régimen cero por 48 horas' },
      ],
      correct: 'C',
      explanation: 'Síndrome ulceroso + dolor en puñalada que se generaliza + abdomen en tabla + neumoperitoneo = úlcera perforada. El tratamiento es la cirugía de urgencia (sutura + parche de epiplón). Suero, IBP y antibióticos acompañan pero no reemplazan la cirugía; la endoscopía está contraindicada.',
      say: {
        stem: 'Vamos al caso. Hombre de cincuenta y ocho años, con epigastralgia de meses, que consulta por un dolor epigástrico súbito, como una puñalada, que en una hora se extendió a todo el abdomen. Está pálido, taquicárdico, con el abdomen rígido y sin ruidos hidroaéreos. La radiografía de tórax de pie muestra aire bajo el hemidiafragma derecho.',
        question: '¿Cuál es la conducta más adecuada?',
        options: 'Las alternativas: endoscopía urgente, suero con IBP y antibióticos y observar, cirugía de urgencia, TAC de abdomen, o sonda nasogástrica con régimen cero. Piénsalo.',
        answer: 'Es la C, cirugía de urgencia. Tienes todo: síndrome ulceroso, dolor en puñalada, abdomen en tabla y neumoperitoneo. La alternativa tentadora es la B, porque suero, IBP y antibióticos sí se indican. Pero son complementos: solo la cirugía cierra el agujero. Y la endoscopía, ya lo sabes, está contraindicada.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2019 · Pregunta 162',
      stem: 'Un paciente de 43 años presenta dolor epigástrico urente, de un mes de evolución. Hace 24 horas deja de eliminar gases y el dolor se vuelve difuso y persistente, agregándose distensión abdominal. Al examen tiene frecuencia cardíaca de 110 por minuto, presión arterial de 110/70, abdomen doloroso y distendido, con pérdida de la matidez hepática y ruidos hidroaéreos abolidos.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Obstrucción intestinal' },
        { letter: 'B', text: 'Pancreatitis aguda' },
        { letter: 'C', text: 'Perforación de úlcera péptica' },
        { letter: 'D', text: 'Plastrón vesicular' },
        { letter: 'E', text: 'Cáncer de vesícula' },
      ],
      correct: 'C',
      explanation: 'Toda la clínica es de úlcera perforada: epigastralgia urente previa (síndrome ulceroso), y luego dolor intenso y difuso con íleo paralítico por la peritonitis (distensión, ruidos hidroaéreos abolidos) más el signo de neumoperitoneo, la pérdida de la matidez hepática, porque el aire libre se interpone entre el hígado y la pared.',
      say: {
        stem: 'Vamos con una pregunta real, de julio de dos mil diecinueve. Paciente de cuarenta y tres años con dolor epigástrico urente de un mes. Hace veinticuatro horas dejó de eliminar gases y el dolor se volvió difuso y persistente, con distensión abdominal. Al examen tiene taquicardia, el abdomen doloroso y distendido, pérdida de la matidez hepática, y los ruidos hidroaéreos están abolidos.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las alternativas: obstrucción intestinal, pancreatitis aguda, perforación de úlcera péptica, plastrón vesicular, o cáncer de vesícula. Piénsalo.',
        answer: 'Es la C, perforación de úlcera péptica. Tienes el síndrome ulceroso previo, la epigastralgia urente, y luego el dolor se generaliza con un íleo paralítico por la peritonitis. Y la pista fina es la pérdida de la matidez hepática: es el aire libre que se mete entre el hígado y la pared, el mismo neumoperitoneo que buscamos en la radiografía.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2013 · Pregunta 154',
      stem: 'Paciente de 43 años, con epigastralgia desde hace 3 semanas, a quien se le realiza endoscopía digestiva alta por sospecha de úlcera, que muestra gastritis erosiva con test de ureasa positivo, por lo que se indica tratamiento erradicador del Helicobacter pylori. Tres horas después del procedimiento, evoluciona con dolor torácico irradiado a hombro derecho y sensación febril.',
      question: '¿Cuál es el examen de elección para confirmar el diagnóstico en este caso?',
      options: [
        { letter: 'A', text: 'Radiografía de tórax' },
        { letter: 'B', text: 'Repetir la endoscopía' },
        { letter: 'C', text: 'Tomografía axial computada de tórax' },
        { letter: 'D', text: 'Radiografía baritada de esófago-estómago-duodeno' },
        { letter: 'E', text: 'Electrocardiograma' },
      ],
      correct: 'C',
      explanation: 'Dolor torácico y fiebre pocas horas después de una endoscopía es una perforación esofágica iatrogénica, la causa más frecuente de este cuadro, con sospecha de mediastinitis secundaria. El TAC de tórax es el examen que mejor confirma el neumomediastino y la extensión del daño; la radiografía simple puede no mostrarlo si el cuadro es muy reciente.',
      say: {
        stem: 'Otra pregunta real, de julio de dos mil trece. Paciente de cuarenta y tres años con epigastralgia de tres semanas, a quien una endoscopía por sospecha de úlcera le muestra una gastritis erosiva con test de ureasa positivo, y se le indica tratamiento erradicador del Helicobacter pylori. Tres horas después del procedimiento, aparece dolor torácico irradiado al hombro derecho y sensación febril.',
        question: '¿Cuál es el examen de elección para confirmar el diagnóstico?',
        options: 'Las alternativas: radiografía de tórax, repetir la endoscopía, tomografía computada de tórax, radiografía baritada, o electrocardiograma. Piénsalo.',
        answer: 'Es la C, el TAC de tórax. Dolor torácico y fiebre horas después de una endoscopía son la causa más frecuente de perforación esofágica: la propia endoscopía. La radiografía simple es el primer examen que se pide, pero aquí, con la sospecha alta y el cuadro tan reciente, el TAC es el que mejor confirma el neumomediastino y guía la conducta.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2019 · Pregunta 156',
      stem: 'Un paciente de 45 años, luego de una transgresión alcohólica y alimentaria, presenta múltiples episodios de vómitos alimentarios, seguidos de hematemesis en una oportunidad. Su hemograma muestra hemoglobina de 9 gramos por decilitro.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Várices esofágicas' },
        { letter: 'B', text: 'Gastropatía erosiva' },
        { letter: 'C', text: 'Úlcera péptica activa' },
        { letter: 'D', text: 'Síndrome de Mallory-Weiss' },
        { letter: 'E', text: 'Gastritis isquémica' },
      ],
      correct: 'D',
      explanation: 'Vómitos alimentarios intensos seguidos de hematemesis, sin enfisema ni sepsis, es el síndrome de Mallory-Weiss: un desgarro de la mucosa esofágica por el esfuerzo del vómito. No lo confundas con el síndrome de Boerhaave, que es una perforación transmural con mediastinitis.',
      say: {
        stem: 'Una pregunta real más, de julio de dos mil diecinueve. Paciente de cuarenta y cinco años que, después de una transgresión con alcohol y comida, presenta varios vómitos alimentarios, y en una ocasión hematemesis. Su hemoglobina está en nueve.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las alternativas: várices esofágicas, gastropatía erosiva, úlcera péptica activa, síndrome de Mallory-Weiss, o gastritis isquémica. Piénsalo.',
        answer: 'Es la D, síndrome de Mallory-Weiss. Vómitos intensos que terminan en hematemesis, sin fiebre ni enfisema, es el patrón clásico: un desgarro de la mucosa por el esfuerzo del vómito. No lo confundas con Boerhaave, que rompe toda la pared y da mediastinitis, no solo sangrado.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2016 · Pregunta 95',
      stem: 'Una niña de 5 años ingiere accidentalmente soda cáustica hace 45 minutos. Evoluciona con sialorrea y dolor abdominal y torácico.',
      question: '¿Cuál es la conducta más adecuada?',
      options: [
        { letter: 'A', text: 'Administrar carbón activado' },
        { letter: 'B', text: 'Solicitar endoscopía digestiva alta' },
        { letter: 'C', text: 'Administrar un agente alcalinizante' },
        { letter: 'D', text: 'Instalar una sonda nasogástrica y aspirar el contenido' },
        { letter: 'E', text: 'Inducir el vómito' },
      ],
      correct: 'B',
      explanation: 'La ingesta de cáustico se estudia con endoscopía digestiva alta precoz: gradúa el daño y decide la conducta. Carbón activado, neutralizantes, sonda para aspirar y provocar el vómito no tienen utilidad o están contraindicados, porque el daño ya ocurrió y esas maniobras lo agravan o reexponen el esófago al cáustico.',
      say: {
        stem: 'Y la última pregunta real de esta clase, de julio de dos mil dieciséis. Niña de cinco años que hace cuarenta y cinco minutos ingirió soda cáustica por accidente, y evoluciona con sialorrea y dolor abdominal y torácico.',
        question: '¿Cuál es la conducta más adecuada?',
        options: 'Las alternativas: carbón activado, endoscopía digestiva alta, un agente alcalinizante, sonda nasogástrica para aspirar, o inducir el vómito. Piénsalo.',
        answer: 'Es la B, endoscopía digestiva alta. Es exactamente la regla que vimos: el daño ya ocurrió, así que carbón activado, neutralizantes, sonda para aspirar o provocar el vómito no ayudan y algunos lo empeoran. Lo único que sirve es graduar el daño con la endoscopía precoz, y de ahí decidir si se observa, se deja en régimen cero, o se opera.',
      },
    },

    {
      type: 'points',
      kicker: 'Cierre',
      title: 'Reglas de oro para el examen',
      cards: [
        { title: 'Perforaciones', tag: 'Sin endoscopía', kind: 'alert', items: [
          { t: 'Úlcera perforada', d: 'Rx tórax de pie → cirugía urgente',
            say: 'Cerremos con las reglas de oro. Úlcera perforada: dolor en puñalada y abdomen en tabla, radiografía de tórax de pie y cirugía de urgencia.' },
          { t: 'Boerhaave', d: 'Rx tórax o TAC → cirugía urgente',
            say: 'Boerhaave: vómitos, dolor torácico y enfisema, radiografía o TAC de tórax, y cirugía de urgencia.' },
          { t: 'Mallory-Weiss ≠ Boerhaave', d: 'Vómitos → sangre vs vómitos → aire',
            say: 'Vómitos seguidos de sangre es Mallory-Weiss; vómitos seguidos de aire y dolor es Boerhaave.' },
        ] },
        { title: 'Cáustico', tag: 'Endoscopía primero', kind: 'key', items: [
          { t: 'EDA precoz decide la conducta', d: 'Observar, régimen cero o cirugía',
            say: 'Ingesta de cáustico: endoscopía precoz, y según el daño se observa, se deja en régimen cero o se opera.' },
          { t: 'Nunca carbón, lavado ni vómito', d: 'Ni neutralizantes',
            say: 'Y nunca carbón activado, lavado gástrico, neutralizantes ni vómito provocado.' },
        ] },
        { title: 'La trampa final', tag: 'Perforación', kind: 'pharma', items: [
          { t: 'Suero + ATB + IBP + cirugía', d: 'La respuesta es la cirugía',
            say: 'Si en una perforación te ofrecen suero, antibióticos, IBP y cirugía, la respuesta es la cirugía. Si te llevas una sola idea de hoy: donde hay un agujero, la endoscopía se prohíbe y se opera; donde hay una quemadura, la endoscopía es lo primero. Nos vemos en la próxima clase.' },
        ] },
      ],
    },
  ],

  pathway: {
    title: 'Urgencias del tubo digestivo alto',
    root: N('start', 'Urgencia digestiva alta', 'Perforación o ingesta de cáustico',
      'Tres urgencias del tubo digestivo alto que el examen mezcla a propósito. La clave es el contexto clínico.',
      ['', N('q', '¿Cuál es el contexto?', 'El antecedente define el examen',
        '¿Qué antecedente tiene el paciente? Eso define el examen y si la endoscopía se permite o se prohíbe.',
        ['Úlcera + puñalada', N('do', 'Rx de tórax de pie', 'Neumoperitoneo subdiafragmático',
          'Síndrome ulceroso con dolor brusco en puñalada y abdomen en tabla: úlcera perforada. Pedimos radiografía de tórax de pie buscando neumoperitoneo.',
          ['', N('alert', 'Cirugía de urgencia', 'Endoscopía contraindicada',
            'El tratamiento es cirugía de urgencia, con sutura y parche de epiplón. Suero, IBP y antibióticos son complementos, y la endoscopía está contraindicada.')])],
        ['Vómitos + enfisema', N('do', 'Rx de tórax → TAC', 'Neumomediastino (Boerhaave)',
          'Vómitos intensos seguidos de dolor torácico y enfisema subcutáneo: perforación esofágica, síndrome de Boerhaave. Radiografía de tórax y, si es negativa con sospecha alta, TAC.',
          ['', N('alert', 'Cirugía de urgencia', 'Riesgo de mediastinitis',
            'Se opera de urgencia por el riesgo de mediastinitis. No lo confundas con Mallory-Weiss, donde los vómitos terminan en hematemesis y sí se endoscopia.')])],
        ['Cáustico', N('do', 'EDA precoz (12–24 h)', 'Nunca carbón, lavado ni vómito',
          'Ingesta de cáustico: endoscopía precoz, idealmente en las primeras doce a veinticuatro horas, para graduar el daño. Carbón activado, lavado gástrico y provocar el vómito están contraindicados.',
          ['', N('q', '¿Necrosis o perforación?', 'Según el hallazgo endoscópico',
            '¿La endoscopía muestra necrosis extensa o perforación?',
            ['SÍ', N('alert', 'Régimen cero + cirugía', 'Nutrición parenteral',
              'Si hay necrosis o perforación: régimen cero, nutrición parenteral y cirugía de urgencia.')],
            ['NO', N('ok', 'Observar o régimen cero', 'Según el grado de daño',
              'Mucosa normal o eritema leve: observar y realimentar. Úlceras o inflamación significativa: régimen cero, nutrición parenteral y endoscopía de control.')])])])]),
  },
};
