// Clase 8.6 — guion docente escrito a mano (ver gastro-01.cjs para el formato).
// Fuente clínica: books/scripts/dataset_hematologia.cjs (hem-06).

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  id: 'hem-06',
  tier: 3,
  slides: [
    {
      type: 'cover',
      subtitle: 'Un ADN que no se duplica, una médula que no se mielina y un folato que nunca va solo',
      say: 'Bienvenidos. En la clase anterior vimos una pancitopenia con la médula vacía. Hoy vemos otra pancitopenia, pero con una médula llena de células que no logran madurar: la anemia megaloblástica. Es uno de los temas más preguntados del bloque, y casi todo se resuelve separando dos vitaminas: la B doce, que daña los nervios, y el ácido fólico, que no. Y hay un error que el examen castiga siempre: dar ácido fólico solo.',
    },

    {
      type: 'flow',
      kicker: 'Fisiopatología',
      title: 'Un ADN que no se duplica',
      nodes: [
        { id: 'def', col: 0, row: 1, k: 'cause', t: 'Déficit de B12 o folato', s: 'Cofactores del timidilato' },
        { id: 'adn', col: 1, row: 1, k: 'mech', t: 'Falla la síntesis de ADN', s: 'El ARN y las proteínas siguen' },
        { id: 'asi', col: 2, row: 1, k: 'mech', t: 'Asincronía núcleo-citoplasma', s: 'Núcleo inmaduro, citoplasma grande' },
        { id: 'meg', col: 3, row: 0, k: 'effect', t: 'Megaloblastos', s: 'Macroovalocitos y neutrófilos hipersegmentados' },
        { id: 'ine', col: 3, row: 2, k: 'risk', t: 'Eritropoyesis ineficaz', s: 'Mueren dentro de la médula' },
        { id: 'lab', col: 4, row: 2, k: 'effect', t: 'LDH y bilirrubina indirecta altas', s: 'Hemólisis intramedular' },
      ],
      edges: [
        { from: 'def', to: 'adn' }, { from: 'adn', to: 'asi' },
        { from: 'asi', to: 'meg' }, { from: 'asi', to: 'ine' }, { from: 'ine', to: 'lab' },
      ],
      steps: [
        { show: ['def'], note: 'Las dos vitaminas hacen lo mismo en el ADN',
          say: 'Partamos por el mecanismo común. La vitamina B doce y el ácido fólico son cofactores indispensables para fabricar timidilato, una de las piezas del ADN. Si falta cualquiera de las dos, la célula no puede duplicar su ADN.' },
        { show: ['adn'], note: 'Solo falla el ADN; el resto de la célula sigue creciendo',
          say: 'Pero fíjate en el detalle: lo que falla es solo el ADN. La síntesis de ARN y de proteínas del citoplasma sigue normal. La célula sigue creciendo, pero no logra dividirse.' },
        { show: ['asi'], note: 'El citoplasma madura, el núcleo se queda atrás',
          say: 'Eso produce la asincronía de maduración núcleo-citoplasmática: un núcleo inmaduro dentro de un citoplasma grande y cargado de hemoglobina.' },
        { show: ['meg'], note: 'Macrocitosis y pleocariocitos',
          say: 'Esas células son los megaloblastos. A la sangre salen glóbulos rojos grandes y ovalados, los macroovalocitos, y neutrófilos con más de cinco lóbulos, los pleocariocitos. Y como el defecto es del ADN, afecta a todas las series: por eso puede haber pancitopenia, igual que en la aplasia de la clase anterior, pero con una médula llena.' },
        { show: ['ine', 'lab'], note: 'Por eso la megaloblástica imita una hemólisis',
          say: 'Muchos de estos precursores mueren dentro de la médula antes de salir. Es la eritropoyesis ineficaz, una verdadera hemólisis intramedular, y por eso suben la LDH y la bilirrubina indirecta, a veces de forma desproporcionada. Guarda esto, porque es la trampa de varias preguntas reales: parece una hemólisis, pero los reticulocitos están bajos.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'Absorción',
      title: 'El largo viaje de la B12 y el corto del folato',
      nodes: [
        { id: 'ani', col: 0, row: 0, k: 'start', t: 'B12: solo origen animal', s: 'Carnes, lácteos, huevos' },
        { id: 'est', col: 1, row: 0, k: 'mech', t: 'Estómago: ácido y factor intrínseco', s: 'Células parietales de fondo y cuerpo' },
        { id: 'ile', col: 2, row: 0, k: 'mech', t: 'Íleon terminal', s: 'Últimos 60 cm, receptor cubilina' },
        { id: 'res', col: 3, row: 0, k: 'good', t: 'Reservas de 3 a 5 años', s: '3.000 a 5.000 µg en el hígado' },
        { id: 'veg', col: 0, row: 2, k: 'start', t: 'Folato: vegetales y frutas', s: 'Verdes crudos, legumbres' },
        { id: 'yey', col: 1, row: 2, k: 'mech', t: 'Yeyuno proximal', s: 'Absorción rápida' },
        { id: 'fres', col: 3, row: 2, k: 'risk', t: 'Reservas de 3 a 4 meses', s: 'Solo 5 a 10 mg' },
      ],
      edges: [
        { from: 'ani', to: 'est' }, { from: 'est', to: 'ile', label: 'complejo B12-FI' }, { from: 'ile', to: 'res' },
        { from: 'veg', to: 'yey' }, { from: 'yey', to: 'fres' },
      ],
      steps: [
        { show: ['ani'], note: 'El vegano estricto no recibe B12',
          say: 'Para entender las causas, sigamos el viaje de cada vitamina. La B doce viene exclusivamente de alimentos de origen animal: carnes, lácteos y huevos. Por eso el vegano estricto, con los años, se queda sin B doce.' },
        { show: ['est'], note: 'Sin estómago sano no hay factor intrínseco',
          say: 'En el estómago, el ácido clorhídrico y la pepsina la liberan de las proteínas, y se une al factor intrínseco, una glicoproteína que fabrican las células parietales del fondo y del cuerpo gástrico. Sin esas células, no hay factor intrínseco.' },
        { show: ['ile'], note: 'Sin íleon terminal tampoco se absorbe',
          say: 'El complejo de B doce con factor intrínseco recorre todo el intestino delgado y se absorbe recién en los últimos sesenta centímetros del íleon terminal, a través del receptor cubilina. Así que hay dos lugares donde el viaje se puede cortar: el estómago y el íleon.' },
        { show: ['res'], note: 'La clínica aparece años después',
          say: 'Y un dato clave: el hígado guarda entre tres mil y cinco mil microgramos de B doce. Por eso, aunque el aporte se corte del todo, la deficiencia tarda tres a cinco años en aparecer. El gastrectomizado de hoy es el paciente con anemia de dentro de algunos años.' },
        { show: ['veg', 'yey'], note: 'El folato no necesita factor intrínseco',
          say: 'El folato es distinto. Viene de vegetales verdes crudos, legumbres y frutas, y se absorbe rápido en el yeyuno proximal, sin necesidad de factor intrínseco.' },
        { show: ['fres'], note: 'Se agota en meses: alcohol, desnutrición, embarazo',
          say: 'Pero sus reservas son muy pequeñas, de cinco a diez miligramos, y se agotan en solo tres a cuatro meses. Por eso el déficit de folato aparece rápido en la desnutrición, en el alcoholismo o en el embarazo, cuando la demanda sube. Años para la B doce, meses para el folato: esa diferencia se pregunta.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'La diferencia que más se pregunta',
      title: 'Por qué solo la B12 daña los nervios',
      nodes: [
        { id: 'b12', col: 0, row: 1, k: 'cause', t: 'Déficit de B12', s: 'Cofactor de dos enzimas' },
        { id: 'ms', col: 1, row: 0, k: 'mech', t: 'Metionina sintasa bloqueada', s: 'Sube la homocisteína' },
        { id: 'mm', col: 1, row: 2, k: 'mech', t: 'Metilmalonil-CoA mutasa bloqueada', s: 'Sube el ácido metilmalónico' },
        { id: 'mie', col: 2, row: 2, k: 'effect', t: 'Mielina anómala', s: 'Desmielinización progresiva' },
        { id: 'dcs', col: 3, row: 2, k: 'alert', t: 'Degeneración combinada subaguda', s: 'Cordones posteriores y laterales' },
        { id: 'fol', col: 3, row: 0, k: 'good', t: 'Déficit de folato', s: 'Homocisteína alta, AMM normal, sin daño neurológico' },
      ],
      edges: [
        { from: 'b12', to: 'ms' }, { from: 'b12', to: 'mm' },
        { from: 'mm', to: 'mie' }, { from: 'mie', to: 'dcs' },
        { from: 'ms', to: 'fol', label: 'comparte vía' },
      ],
      steps: [
        { show: ['b12'], note: 'La B12 trabaja en dos enzimas; el folato, en una',
          say: 'Ahora, lo que más se pregunta: ¿por qué la B doce daña el sistema nervioso y el folato no? La respuesta está en que la B doce es cofactor de dos enzimas distintas.' },
        { show: ['ms'], note: 'Vía compartida con el folato',
          say: 'La primera es la metionina sintasa, que convierte homocisteína en metionina, y que está acoplada al metabolismo del folato. Si falla, sube la homocisteína. Y como esa vía es compartida, la homocisteína sube en los dos déficits.' },
        { show: ['mm'], note: 'Vía exclusiva de la B12',
          say: 'La segunda es la metilmalonil coenzima A mutasa, en la mitocondria. Esta vía es exclusiva de la B doce. Si falla, se acumula ácido metilmalónico.' },
        { show: ['mie', 'dcs'], note: 'El ácido metilmalónico daña la mielina',
          say: 'Ese ácido metilmalónico, junto con ácidos grasos anómalos, se incorpora a las vainas de mielina y produce una desmielinización progresiva: la degeneración combinada subaguda de la médula espinal. Combinada, porque toma los cordones posteriores y los laterales a la vez.' },
        { show: ['fol'], note: 'Sin ácido metilmalónico, no hay daño medular',
          say: 'El déficit de folato solo toca la primera vía. Sube la homocisteína, pero el ácido metilmalónico queda normal, y no hay degeneración combinada subaguda. Esa es la regla del tema: neurología y ácido metilmalónico alto, B doce; sin neurología y metilmalónico normal, folato.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Clínica neurológica',
      title: 'Qué encuentras al examinar al paciente con déficit de B12',
      cards: [
        { title: 'Médula espinal', tag: 'Degeneración combinada subaguda', kind: 'alert', items: [
          { t: 'Cordones posteriores', d: 'Sin vibración ni posición, Romberg +, ataxia',
            say: 'Veamos cómo se ve esto al examen. Los cordones posteriores llevan la sensibilidad vibratoria y la posicional. Al perderse, el paciente camina con ataxia sensitiva, tiene Romberg positivo y, típicamente, le cuesta caminar en la oscuridad, porque ya no puede corregir con la vista.' },
          { t: 'Vía piramidal', d: 'Hiperreflexia, clonus, Babinski bilateral',
            say: 'Los cordones laterales llevan la vía piramidal. Su daño da espasticidad, hiperreflexia, clonus y Babinski bilateral. Un paciente con Romberg positivo y Babinski bilateral a la vez te tiene que hacer pensar en B doce.' },
        ] },
        { title: 'Nervio y cerebro', tag: 'Más allá de la médula', kind: 'key', items: [
          { t: 'Parestesias en guante y calcetín', d: 'Neuropatía periférica distal',
            say: 'Además hay neuropatía periférica: parestesias en guante y calcetín, ardor en los pies e hipoestesia distal. Es la que mejor revierte con la reposición precoz.' },
          { t: 'Locura megaloblástica', d: 'Apatía, depresión, pérdida de memoria',
            say: 'Y en el cerebro, apatía, depresión, pérdida de memoria, hasta la llamada locura megaloblástica. En el adulto mayor con deterioro cognitivo y VCM alto, siempre se mide la B doce, porque es una demencia reversible.' },
        ] },
        { title: 'Mucosa y pronóstico', tag: 'Reversibilidad', kind: 'normal', items: [
          { t: 'Glositis de Hunter', d: 'Lengua lisa, depapilada, roja',
            say: 'Fuera del sistema nervioso, la glositis de Hunter: una lengua lisa, depapilada y dolorosa, que resuelve en pocos días de tratamiento.' },
          { t: 'Neurología < 6 a 12 meses: revierte', d: 'Si hay pérdida axonal, puede quedar',
            say: 'Y el pronóstico neurológico depende del tiempo. Si el daño lleva menos de seis a doce meses, revierte. Si ya hay pérdida axonal, puede quedar para siempre. Por eso esto es una urgencia relativa, no un hallazgo para el próximo control.' },
        ] },
      ],
    },

    {
      type: 'points',
      kicker: 'Etiología',
      title: 'Quién se queda sin B12 y quién sin folato',
      cards: [
        { title: 'Anemia perniciosa', tag: 'Causa más común de B12', kind: 'key', items: [
          { t: 'Gastritis atrófica autoinmune tipo A', d: 'Sin células parietales: sin FI ni ácido',
            say: 'La causa más común de déficit grave de B doce en el adulto mayor es la anemia perniciosa. Es una gastritis atrófica autoinmune, tipo A, en que linfocitos T destruyen las células parietales. Resultado: aclorhidria y cero factor intrínseco.' },
          { t: 'Anti-FI específicos, anti-parietales sensibles', d: 'Anti-FI 95 % específicos; anti-parietales 90 % sensibles',
            say: 'Se asocia a dos anticuerpos. Los anti factor intrínseco son muy específicos, noventa y cinco por ciento; los anti células parietales son muy sensibles, noventa por ciento.' },
          { t: 'Hashimoto, vitíligo, DM1', d: 'Riesgo x3 de cáncer gástrico y carcinoide',
            say: 'Y viaja con otras autoinmunidades: tiroiditis de Hashimoto, vitíligo y diabetes tipo uno. Además triplica el riesgo de adenocarcinoma gástrico y de tumores carcinoides.' },
        ] },
        { title: 'Otras causas de B12', tag: 'Estómago e íleon', kind: 'alert', items: [
          { t: 'Gastrectomía, manga, bypass en Y de Roux', d: 'Se pierde el factor intrínseco',
            say: 'Las otras causas siguen el viaje que vimos. En el estómago: gastrectomía total o en manga, y bypass gástrico en Y de Roux.' },
          { t: 'Crohn ileal, resección ileal, páncreas', d: 'Se pierde el sitio de absorción',
            say: 'En el intestino: enfermedad de Crohn del íleon, resección ileal e insuficiencia pancreática exocrina.' },
          { t: 'Metformina o IBP por más de 3 a 5 años', d: 'Fármacos de uso masivo',
            say: 'Y dos fármacos que se usan muchísimo: la metformina y los inhibidores de la bomba de protones, usados por más de tres a cinco años.' },
        ] },
        { title: 'Déficit de folato', tag: 'Meses, no años', kind: 'pharma', items: [
          { t: 'Alcohol, desnutrición, hepatopatía, embarazo', d: 'También hemólisis crónica',
            say: 'El déficit de folato tiene otro perfil: alcoholismo crónico, que bloquea la absorción y desnutre; hepatopatía avanzada; embarazo sin suplementación; y anemia hemolítica crónica, que consume folato.' },
          { t: 'Metotrexato, trimetoprima, pirimetamina', d: 'Fenitoína, fenobarbital, carbamazepina',
            say: 'Y fármacos: los que bloquean la dihidrofolato reductasa, como el metotrexato, la trimetoprima y la pirimetamina, y los que aceleran su degradación, como la fenitoína, el fenobarbital y la carbamazepina.' },
        ] },
      ],
    },

    {
      type: 'points',
      kicker: 'Diagnóstico',
      title: 'Hemograma, niveles y ácido metilmalónico',
      cards: [
        { title: 'Hemograma', tag: 'Macrocitosis llamativa', kind: 'key', items: [
          { t: 'VCM típico 110 a 130 fL', d: 'Puede haber pancitopenia',
            say: 'El hemograma muestra una macrocitosis llamativa, con VCM típicamente entre ciento diez y ciento treinta. Y puede acompañarse de leucopenia y trombocitopenia, por la eritropoyesis ineficaz.' },
          { t: 'LDH y bilirrubina indirecta altas', d: 'Reticulocitos bajos',
            say: 'La LDH y la bilirrubina indirecta suben por la hemólisis intramedular, pero los reticulocitos están bajos. Esa es la clave para no confundirla con la anemia hemolítica que vemos en la próxima clase: en la hemólisis la médula responde, aquí no puede.' },
          { t: 'Ferritina normal o alta', d: 'Por la lisis intramedular',
            say: 'Y la ferritina y el hierro sérico suelen estar normales o altos, por la misma lisis de precursores.' },
        ] },
        { title: 'Confirmación', tag: 'Niveles vitamínicos', kind: 'criteria', items: [
          { t: 'B12 < 200 pg/mL', d: 'Déficit confirmado',
            say: 'El déficit se confirma midiendo las vitaminas. Una B doce bajo doscientos picogramos por mililitro confirma el déficit.' },
          { t: 'Folato intraeritrocitario < 150 ng/mL', d: 'Déficit de folato',
            say: 'Y un folato intraeritrocitario bajo ciento cincuenta confirma el de folato. Se piden las dos, siempre juntas.' },
          { t: 'B12 límite 200 a 350: ácido metilmalónico', d: '> 0,4 µmol/L sella el déficit',
            say: 'El problema es la zona gris, con una B doce entre doscientos y trescientos cincuenta. Ahí se mide el ácido metilmalónico: si está sobre cero coma cuatro micromoles por litro, confirma el déficit celular de B doce.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Alerta EUNACOM',
      title: 'La trampa mortal: ácido fólico solo',
      nodes: [
        { id: 'mac', col: 0, row: 1, k: 'start', t: 'Anemia macrocítica', s: 'B12 no medida o no reconocida' },
        { id: 'fol', col: 1, row: 1, k: 'trap', t: 'Ácido fólico solo', s: 'Sin B12 asociada' },
        { id: 'hem', col: 2, row: 0, k: 'effect', t: 'La anemia mejora', s: 'Se corrige el VCM' },
        { id: 'neu', col: 2, row: 2, k: 'alert', t: 'La neurología avanza', s: 'Sin B12 para la mielina' },
        { id: 'par', col: 3, row: 2, k: 'alert', t: 'Paraplejía y ataxia irreversibles', s: 'Degeneración combinada fulminante' },
        { id: 'ok', col: 3, row: 0, k: 'good', t: 'Regla', s: 'B12 primero o junto al folato' },
      ],
      edges: [
        { from: 'mac', to: 'fol' }, { from: 'fol', to: 'hem', label: 'enmascara' },
        { from: 'fol', to: 'neu' }, { from: 'neu', to: 'par' }, { from: 'hem', to: 'ok', label: 'nunca' },
      ],
      steps: [
        { show: ['mac', 'fol'], note: 'El error parece inocente',
          say: 'Ahora la trampa que el libro llama mortal. Tienes un paciente con anemia macrocítica, no mediste la B doce, y le indicas ácido fólico solo. Parece inofensivo: es una vitamina.' },
        { show: ['hem'], note: 'El folato salta el bloqueo del ADN',
          say: 'Y al principio parece que funcionó. El folato vence el bloqueo en la síntesis de timidilato, así que la anemia y el VCM se corrigen.' },
        { show: ['neu', 'par'], note: 'Se trata el hemograma y se abandona la médula espinal',
          say: 'Pero la vía de la mielina sigue sin B doce, y el folato además agota la poca cobalamina que quedaba. La degeneración combinada subaguda progresa de forma rápida e irreversible, hasta una paraplejía con ataxia. Mejoraste el hemograma y dejaste avanzar la lesión medular.' },
        { show: ['ok'], note: 'Nunca folato sin descartar o asociar B12',
          say: 'Por eso la regla es absoluta: nunca se da ácido fólico sin haber descartado el déficit de B doce, o sin darla junto a él. En el examen, la alternativa de ácido fólico en un paciente con neurología es siempre la trampa.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Tratamiento',
      title: 'Cómo se repone cada vitamina',
      cards: [
        { title: 'B12 por malabsorción', tag: 'Intramuscular', kind: 'pharma', items: [
          { t: '1.000 µg IM diario por 7 días', d: 'Cianocobalamina o hidroxocobalamina',
            say: 'Vamos al tratamiento. En el déficit de B doce por malabsorción, es decir, anemia perniciosa, gastrectomía o resección ileal, la vía obligada es intramuscular. ¿Por qué? Porque por boca no hay factor intrínseco ni íleon que la absorba. Se parte con mil microgramos diarios por siete días, de cianocobalamina o hidroxocobalamina.' },
          { t: 'Luego semanal por 4 semanas', d: 'Y mensual de por vida',
            say: 'Luego mil microgramos semanales por cuatro semanas, y después mil microgramos al mes de por vida. Esto último se pregunta: la causa no se corrige, así que el tratamiento no se suspende nunca.' },
        ] },
        { title: 'Folato', tag: 'Oral', kind: 'normal', items: [
          { t: 'Ácido fólico 1 a 5 mg/día oral', d: 'Por 3 a 4 meses',
            say: 'El déficit de folato se trata con ácido fólico oral, uno a cinco miligramos al día, por tres a cuatro meses, que es justamente lo que tarda en rellenar sus reservas.' },
          { t: 'Siempre después de asegurar la B12', d: 'B12 sérica antes de indicarlo',
            say: 'Y siempre después de medir la B doce o de asegurar su dosis. La trampa de la diapositiva anterior aplica también aquí.' },
        ] },
        { title: 'Prevención', tag: 'Profilaxis indefinida', kind: 'alert', items: [
          { t: 'Gastrectomía o bypass gástrico', d: 'B12 profiláctica de por vida',
            say: 'Y en el paciente gastrectomizado o con bypass gástrico no se espera a que aparezca la anemia: la suplementación de B doce es profiláctica e indefinida.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Seguimiento',
      title: 'Qué esperar después de la primera dosis',
      nodes: [
        { id: 'ini', col: 0, row: 1, k: 'start', t: 'Inicio de B12', s: 'Reactivación mitótica masiva' },
        { id: 'k', col: 1, row: 0, k: 'alert', t: 'Hipokalemia a las 48–72 h', s: 'Riesgo de arritmias' },
        { id: 'ret', col: 2, row: 1, k: 'good', t: 'Crisis reticulocitaria', s: 'Día 5 a 7' },
        { id: 'hb', col: 3, row: 1, k: 'good', t: 'Hb normal en 4 a 6 semanas', s: 'Glositis resuelve en días' },
        { id: 'neu', col: 3, row: 2, k: 'risk', t: 'Neurología', s: 'Revierte si < 6 a 12 meses' },
      ],
      edges: [
        { from: 'ini', to: 'k', label: 'primero' }, { from: 'ini', to: 'ret' },
        { from: 'ret', to: 'hb' }, { from: 'ini', to: 'neu' },
      ],
      steps: [
        { show: ['ini'], note: 'La médula despierta de golpe',
          say: 'Veamos qué pasa cuando le das la primera dosis. La médula, que estaba frenada, se reactiva de golpe: miles de millones de eritroblastos empiezan a dividirse al mismo tiempo.' },
        { show: ['k'], note: 'Controlar el potasio a las 48 horas',
          say: 'Y esas células nuevas meten potasio dentro de ellas. En las primeras cuarenta y ocho a setenta y dos horas puede aparecer una hipokalemia grave, con riesgo de arritmias. Por eso se controla el potasio a las cuarenta y ocho horas y se suplementa si hace falta. Es un detalle fino, pero se pregunta.' },
        { show: ['ret'], note: 'La prueba de que el diagnóstico era correcto',
          say: 'A los cinco a siete días aparece una intensa crisis reticulocitaria. Conecta con la primera clase del bloque: los reticulocitos son el marcador de que la médula está respondiendo.' },
        { show: ['hb'], note: 'El hemograma se normaliza en semanas',
          say: 'La hemoglobina se normaliza en cuatro a seis semanas, y la glositis resuelve en pocos días.' },
        { show: ['neu'], note: 'La neurología es la parte que puede quedar',
          say: 'Y la neurología es lo más lento y lo único que puede quedar. Revierte si llevaba menos de seis a doce meses; si no, puede dejar secuelas.' },
      ],
    },

    {
      type: 'pathway',
      intro: 'Juntemos todo en un árbol de decisión, partiendo de una anemia macrocítica.',
    },

    {
      type: 'table',
      kicker: 'Trampas EUNACOM',
      title: 'B12 vs folato: las diferencias que se preguntan',
      head: ['Característica', 'Déficit de B12', 'Déficit de folato'],
      rows: [
        { cells: ['Fuente', 'Solo origen animal', 'Vegetales verdes, legumbres, frutas'],
          say: 'Comparemos las dos vitaminas. La fuente: la B doce solo viene de alimentos animales; el folato, de vegetales, legumbres y frutas.' },
        { cells: ['Absorción', 'Íleon terminal, con factor intrínseco', 'Yeyuno proximal'],
          say: 'La absorción: la B doce en el íleon terminal y con factor intrínseco; el folato en el yeyuno, sin necesitarlo.' },
        { cells: ['Agotamiento', '3 a 5 años', '3 a 4 meses'],
          say: 'El tiempo de agotamiento: años para la B doce, meses para el folato.' },
        { cells: ['Neurología', 'Degeneración combinada subaguda', 'Ausente'],
          say: 'La neurología: presente en la B doce, ausente en el folato. Esta es la fila que decide la mayoría de las preguntas.' },
        { cells: ['Ácido metilmalónico', 'Elevado', 'Normal'],
          say: 'El ácido metilmalónico: alto en la B doce, normal en el folato.' },
        { cells: ['Homocisteína', 'Elevada', 'Elevada'],
          say: 'Y ojo con esta: la homocisteína sube en las dos, así que no sirve para separarlas.' },
        { cells: ['Causa principal', 'Anemia perniciosa, gastrectomía, bypass, íleon', 'Alcohol, desnutrición, metotrexato, embarazo'],
          say: 'Las causas: anemia perniciosa y cirugía gástrica o ileal para la B doce; alcohol, desnutrición, metotrexato y embarazo para el folato.' },
        { cells: ['Tratamiento', '1.000 µg IM; de por vida si hay malabsorción', 'Ácido fólico 1 a 5 mg/día oral, 3 a 4 meses'],
          say: 'Y el tratamiento: B doce intramuscular, de por vida si la causa es malabsorción; folato oral por tres a cuatro meses, nunca solo si no has descartado la B doce.' },
      ],
    },

    {
      type: 'quiz',
      kicker: 'Caso clínico',
      title: 'Caso clínico',
      stem: 'Mujer de 74 años con hipotiroidismo y vitíligo consulta por astenia, parestesias en ambos pies y dificultad para caminar en la oscuridad de 5 meses. Palidez con tinte ictérico leve, lengua lisa y depapilada, marcha atáxica con Romberg positivo, reflejos rotulianos exaltados y Babinski bilateral. Hb 7,1 g/dL, VCM 118 fL, plaquetas 110.000/µL, leucocitos 3.200/µL, reticulocitos 0,4 %, LDH 1.200 UI/L, bilirrubina indirecta 2,3 mg/dL.',
      question: '¿Cuál es la conducta más adecuada?',
      options: [
        { letter: 'A', text: 'Ácido fólico 5 mg/día oral y control en un mes' },
        { letter: 'B', text: 'Prednisona 1 mg/kg por anemia hemolítica autoinmune' },
        { letter: 'C', text: 'Medir B12 y folato, e iniciar hidroxocobalamina 1.000 µg IM diaria con control de potasio' },
        { letter: 'D', text: 'Biopsia de médula ósea antes de cualquier tratamiento' },
        { letter: 'E', text: 'Vitamina B12 oral 1.000 µg/día' },
      ],
      correct: 'C',
      explanation: 'Pancitopenia macrocítica con eritropoyesis ineficaz (LDH y bilirrubina indirecta altas, reticulocitos bajos) y degeneración combinada subaguda, en una paciente con autoinmunidad: anemia perniciosa. Se miden B12 y folato, se piden anticuerpos anti-FI y anti-parietales, y se inicia B12 IM de inmediato vigilando la kalemia. El ácido fólico solo está contraindicado; la vía oral no sirve sin factor intrínseco.',
      say: {
        stem: 'Vamos con un caso. Mujer de setenta y cuatro años, con hipotiroidismo y vitíligo, que consulta por astenia, parestesias en los pies y dificultad para caminar en la oscuridad desde hace cinco meses. Está pálida con un leve tinte ictérico, tiene la lengua lisa, Romberg positivo, reflejos exaltados y Babinski bilateral. Hemoglobina siete coma uno, VCM ciento dieciocho, leucocitos y plaquetas bajos, reticulocitos cero coma cuatro por ciento, y LDH y bilirrubina indirecta altas.',
        question: '¿Cuál es la conducta más adecuada?',
        options: 'Las opciones: ácido fólico oral, prednisona por una hemólisis autoinmune, medir B doce y folato e iniciar hidroxocobalamina intramuscular con control de potasio, biopsia de médula antes de tratar, o B doce oral. Piénsalo.',
        answer: 'Es la C. Es una anemia perniciosa de libro: autoinmunidad, pancitopenia macrocítica y degeneración combinada subaguda. Se miden las vitaminas y se inicia B doce intramuscular sin esperar, vigilando el potasio. El distractor más peligroso es la A, el ácido fólico solo, que empeoraría la médula espinal. Y la hemólisis autoinmune cae por los reticulocitos bajos: la LDH alta aquí viene de la médula, no de la sangre.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2018 · Pregunta 117',
      stem: 'Un paciente de 73 años presenta astenia y disnea de esfuerzos importante, asociada a gran palidez de piel y mucosas. Refiere, también, parestesias en las 4 extremidades. Se solicita hemograma que muestra hemoglobina: 6 mg/dl, VCM: 126 fl, glóbulos blancos: 3.100 por mm3, plaquetas: 105.000 por mm3 y 2 eritroblastos / 100 leucocitos. Se solicitan, además, LDH: 1.800 UI/L y bilirrubina: 5 mg/dl, de predominio indirecto.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Mielodisplasia' },
        { letter: 'B', text: 'Aplasia medular' },
        { letter: 'C', text: 'Anemia por déficit de vitamina B12' },
        { letter: 'D', text: 'Síndrome leucoeritroblástico' },
        { letter: 'E', text: 'Anemia hemolítica autoinmune' },
      ],
      correct: 'C',
      explanation: 'Pancitopenia con VCM 126 fL, LDH y bilirrubina indirecta muy altas (eritropoyesis ineficaz) y parestesias en las cuatro extremidades: déficit de B12, probablemente por anemia perniciosa. La aplasia no da macrocitosis tan marcada ni neurología, y la hemólisis autoinmune no explica la leucopenia ni la trombocitopenia ni las parestesias.',
      say: {
        stem: 'Ahora preguntas reales. La primera, del EUNACOM de diciembre de dos mil dieciocho. Hombre de setenta y tres años con astenia, disnea, gran palidez y parestesias en las cuatro extremidades. Hemoglobina de seis, VCM ciento veintiséis, leucocitos y plaquetas bajos, y LDH de mil ochocientos con bilirrubina de cinco, de predominio indirecto.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones: mielodisplasia, aplasia medular, déficit de vitamina B doce, síndrome leucoeritroblástico, o anemia hemolítica autoinmune. Piénsalo.',
        answer: 'Es la C, déficit de B doce. Pancitopenia con un VCM de ciento veintiséis y parestesias: la neurología es la firma de la B doce. El distractor tentador es la hemólisis autoinmune, por la LDH y la bilirrubina, pero eso es la hemólisis dentro de la médula que vimos al inicio, y la hemólisis no baja los leucocitos ni da parestesias. Y la aplasia, de la clase anterior, no da glóbulos gigantes.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2025 · Pregunta 133',
      stem: 'Un paciente de 71 años consulta por malestar general y disnea progresiva, que actualmente es de pequeños esfuerzos. Al examen físico se observa pálido, con examen cardiopulmonar que muestra ritmo regular en dos tiempos, sin soplos, con frecuencia cardíaca 120 latidos por minuto; y examen pulmonar que constata murmullo pulmonar simétrico sin otros ruidos. Se solicita hemograma que se informa con hematocrito: 16%, hemoglobina: 5,2 g/dL, VCM: 118 fL, CHCM: 40 g/dL, reticulocitos: 0,8%, plaquetas: 60.000/mm³ y glóbulos blancos: 3.300/mm³. Además, se solicita GOT: 52 U/L, bilirrubina total: 3,5 mg/dL y bilirrubina directa: 0,2 mg/dL.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Anemia megaloblástica' },
        { letter: 'B', text: 'Anemia aplásica' },
        { letter: 'C', text: 'Anemia hemolítica' },
        { letter: 'D', text: 'Mielodisplasia' },
        { letter: 'E', text: 'Mieloptisis' },
      ],
      correct: 'A',
      explanation: 'VCM 118 fL con pancitopenia y bilirrubina indirecta alta, pero reticulocitos bajos: eritropoyesis ineficaz por déficit de B12, no hemólisis periférica. Con Hb bajo 7 g/dL puede requerir transfusión, además de B12 intramuscular.',
      say: {
        stem: 'La segunda, del EUNACOM de diciembre de dos mil veinticinco. Hombre de setenta y un años con disnea de pequeños esfuerzos, pálido y taquicárdico. Hemoglobina cinco coma dos, VCM ciento dieciocho, reticulocitos cero coma ocho por ciento, plaquetas sesenta mil y leucocitos tres mil trescientos. La bilirrubina total es tres coma cinco, con la directa en cero coma dos, es decir, casi toda indirecta.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones: anemia megaloblástica, anemia aplásica, anemia hemolítica, mielodisplasia, o mieloptisis. Piénsalo.',
        answer: 'Es la A, anemia megaloblástica. Esta pregunta enseña algo distinto: la bilirrubina indirecta alta te empuja hacia la hemólisis, pero los reticulocitos están bajos, y una anemia hemolítica siempre regenera. Con un VCM de ciento dieciocho y pancitopenia, es la hemólisis intramedular de la megaloblástica. Con esta hemoglobina, probablemente además necesite una transfusión.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2019 · Pregunta 141',
      stem: 'Un paciente de 36 años, desde hace 4 años sigue dieta vegana estricta. Consulta por astenia, adinamia y palidez, a lo que se ha agregado disnea de grandes esfuerzos, que ha aumentado. Al examen físico tiene palidez de piel y mucosas, FC: 92x’, PA: 100/70 mmHg, sin alteraciones del examen segmentario. Se solicita hemograma que muestra plaquetas: 200.000 por mm3, glóbulos blancos: 6.500 por mm3, hematocrito: 27%, hemoglobina: 9 g/dl, VCM: 115 fl, HCM: 35 pg y reticulocitos 0,5%, con LDH: 450 UI/L.',
      question: 'El examen más adecuado para proseguir el estudio es:',
      options: [
        { letter: 'A', text: 'Nivel de vitamina B12' },
        { letter: 'B', text: 'Mielograma' },
        { letter: 'C', text: 'Biopsia de médula ósea' },
        { letter: 'D', text: 'Perfil de fierro' },
        { letter: 'E', text: 'Prueba de Coombs' },
      ],
      correct: 'A',
      explanation: 'Dieta vegana estricta por 4 años (la B12 solo viene de alimentos animales y las reservas duran 3 a 5 años) con anemia macrocítica arregenerativa y VCM 115 fL: el siguiente paso es medir la vitamina B12. La médula ósea no es necesaria para el diagnóstico.',
      say: {
        stem: 'La tercera, del EUNACOM de diciembre de dos mil diecinueve. Hombre de treinta y seis años, vegano estricto desde hace cuatro años, con astenia, palidez y disnea progresiva. Tiene hemoglobina nueve, VCM ciento quince, reticulocitos bajos, y leucocitos y plaquetas normales.',
        question: '¿Cuál es el examen más adecuado para proseguir el estudio?',
        options: 'Las opciones: nivel de vitamina B doce, mielograma, biopsia de médula ósea, perfil de fierro, o prueba de Coombs. Piénsalo.',
        answer: 'Es la A, medir la B doce. Recuerda el viaje: la B doce solo viene de alimentos animales, y las reservas duran tres a cinco años. Cuatro años de dieta vegana calzan perfecto. El distractor es la médula ósea: la anemia megaloblástica no se diagnostica con una biopsia, sino midiendo las vitaminas.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2015 · Pregunta 10',
      stem: 'Un paciente de 60 años, gastrectomizado, presenta un cuadro de astenia, adinamia, asociada a disminución de la sensibilidad distal de las extremidades y debilidad. Además ha presentado algún grado de disminución de la capacidad cognitiva. Al examen físico se aprecia disminución de los reflejos osteotendíneos, palidez y disminución de la sensibilidad de las Extremidades inferiores. Se solicitan exámenes, entre los que destaca un hemograma con Hemoglobina de 6,3 g/dl, VCM: 110 fl, plaquetas: 200.000 por mm3, blancos: 3.200 por mm3.',
      question: 'La indicación más adecuada es:',
      options: [
        { letter: 'A', text: 'Ácido fólico' },
        { letter: 'B', text: 'Vitamina B12' },
        { letter: 'C', text: 'Fierro' },
        { letter: 'D', text: 'Biopsia de médula ósea' },
        { letter: 'E', text: 'Endoscopía digestiva alta' },
      ],
      correct: 'B',
      explanation: 'Gastrectomía: sin factor intrínseco no se absorbe la B12. Tiene anemia macrocítica, neuropatía y compromiso cognitivo, todo explicado por el déficit de B12. El ácido fólico solo sería el error más grave.',
      say: {
        stem: 'Y la última, del EUNACOM de julio de dos mil quince. Hombre de sesenta años, gastrectomizado, con astenia, menor sensibilidad distal, debilidad y cierto deterioro cognitivo. Tiene hemoglobina seis coma tres, VCM ciento diez y leucocitos bajos.',
        question: '¿Cuál es la indicación más adecuada?',
        options: 'Las opciones: ácido fólico, vitamina B doce, fierro, biopsia de médula ósea, o endoscopía. Piénsalo.',
        answer: 'Es la B, vitamina B doce. Sin estómago no hay factor intrínseco, y el paciente tiene la tríada completa: anemia macrocítica, neuropatía y deterioro cognitivo. Y aquí está la trampa mortal en versión examen: el ácido fólico está en la alternativa A. Con neurología, el folato solo es el error más grave que podrías cometer.',
      },
    },

    {
      type: 'points',
      kicker: 'Cierre',
      title: 'Reglas de oro para el examen',
      cards: [
        { title: 'Reconocer', tag: 'Megaloblástica', kind: 'key', items: [
          { t: 'VCM > 110, LDH alta, reticulocitos bajos', d: 'Hemólisis intramedular, no periférica',
            say: 'Cerremos con las reglas de oro. VCM sobre ciento diez, LDH y bilirrubina indirecta altas, pero reticulocitos bajos: es una megaloblástica, no una hemólisis.' },
          { t: 'Neurología = B12', d: 'Ácido metilmalónico alto; el folato no daña nervios',
            say: 'Si hay neurología, es B doce. El ácido metilmalónico alto también es B doce. El folato no daña los nervios.' },
        ] },
        { title: 'Causas', tag: 'Seguir el viaje', kind: 'criteria', items: [
          { t: 'Perniciosa, gastrectomía, bypass, íleon, vegano', d: 'Metformina e IBP crónicos',
            say: 'La B doce falta en la anemia perniciosa, en la cirugía gástrica o ileal, en el vegano estricto y con metformina o IBP crónicos.' },
          { t: 'Folato: alcohol, embarazo, metotrexato', d: 'Se agota en meses',
            say: 'El folato falta en el alcohólico, en el embarazo y con metotrexato, y se agota en meses.' },
        ] },
        { title: 'Tratar', tag: 'Sin trampas', kind: 'alert', items: [
          { t: 'Nunca ácido fólico solo', d: 'Enmascara la anemia, progresa la médula',
            say: 'Nunca ácido fólico solo sin descartar la B doce.' },
          { t: 'B12 IM de por vida si hay malabsorción', d: 'Vigilar potasio a las 48 horas',
            say: 'La B doce va intramuscular, de por vida si hay malabsorción, vigilando el potasio al inicio. En la próxima clase vemos las anemias en que los reticulocitos sí suben: las hemolíticas autoinmunes. Si te llevas una sola idea de hoy: macrocitosis con neurología es B doce, y el ácido fólico nunca va solo. Nos vemos en la próxima clase.' },
        ] },
      ],
    },
  ],

  pathway: {
    title: 'Anemia macrocítica: B12, folato y la trampa del ácido fólico',
    root: N('start', 'Anemia macrocítica', 'VCM > 100, típicamente 110 a 130',
      'Tienes una anemia con glóbulos grandes. Lo primero es mirar los reticulocitos, para separar la médula que responde de la que no puede.',
      ['', N('q', '¿Reticulocitos?', 'Separar hemólisis de megaloblástica',
        '¿Los reticulocitos están altos o bajos?',
        ['Altos', N('refer', 'Pensar en hemólisis', 'Próxima clase',
          'Si están altos, la médula está respondiendo a una pérdida o una destrucción: piensa en hemólisis, que vemos en la próxima clase.')],
        ['Bajos', N('do', 'Medir B12 y folato', 'LDH y bilirrubina indirecta altas',
          'Si están bajos, con LDH y bilirrubina indirecta altas, es una eritropoyesis ineficaz. Mide la B doce y el folato, siempre juntos.',
          ['', N('q', '¿Neurología o AMM alto?', 'Romberg, Babinski, parestesias',
            'La pregunta que decide: ¿hay neurología, o el ácido metilmalónico está alto?',
            ['Sí', N('alert', 'Déficit de B12', 'B12 IM + control de potasio',
              'Si la hay, es déficit de B doce. Se inicia B doce intramuscular de inmediato, se vigila el potasio, y nunca se da ácido fólico solo. Luego se busca la causa: anemia perniciosa, cirugía gástrica o ileal, dieta vegana o fármacos.',
              ['Malabsorción', N('ok', 'B12 IM de por vida', 'Perniciosa, gastrectomía, bypass',
                'Si la causa es malabsorción, la B doce es intramuscular y de por vida.')])],
            ['No', N('ok', 'Déficit de folato', 'Ácido fólico oral 3 a 4 meses',
              'Sin neurología, con ácido metilmalónico normal y folato bajo, es déficit de folato: ácido fólico oral por tres a cuatro meses, una vez descartada la B doce.')])])])]),
  },
};
