// Clase 1.4 — guion docente escrito a mano (ver gastro-01.cjs para el formato).
// Fuente clínica: books/scripts/dataset_infectologia.cjs (inf-04).

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  id: 'infecto-04',
  tier: 3,
  slides: [
    {
      type: 'cover',
      subtitle: 'El dolor que no calza con la piel, el pabellón que no espera y la vía aérea primero',
      say: 'Bienvenidos. Cerramos el bloque de urgencias con dos emergencias quirúrgicas de altísima letalidad: la fascitis necrotizante y la angina de Ludwig. Aquí el examen evalúa dos ideas. La primera, reconocer temprano un dolor que no calza con lo que ves en la piel. La segunda, que la conducta es el pabellón, sin perder tiempo en imágenes. Y en la angina de Ludwig, antes que todo, la vía aérea. Partamos.',
    },

    {
      type: 'flow',
      kicker: 'Fisiopatología',
      title: 'Fascitis necrotizante: dos tipos, un mismo daño',
      nodes: [
        { id: 't1', col: 0, row: 0, k: 'cause', t: 'Tipo I · polimicrobiana · 80 %', s: 'Anaerobios + enterobacterias + estreptococos' },
        { id: 'fou', col: 1, row: 0, k: 'risk', t: 'Diabéticos o cirugía perineal', s: 'Gangrena de Fournier' },
        { id: 't2', col: 0, row: 2, k: 'cause', t: 'Tipo II · monomicrobiana · 20 %', s: 'Streptococcus pyogenes' },
        { id: 'jov', col: 1, row: 2, k: 'risk', t: 'Jóvenes', s: 'Trauma menor o varicela' },
        { id: 'fas', col: 2, row: 1, k: 'mech', t: 'Fascia profunda y subcutáneo', s: 'Infección rápidamente destructiva' },
        { id: 'tro', col: 3, row: 1, k: 'mech', t: 'Trombosis microvascular', s: 'El tejido se queda sin sangre' },
        { id: 'nec', col: 4, row: 1, k: 'effect', t: 'Necrosis que avanza', s: 'Bajo una piel que parece sana' },
      ],
      edges: [
        { from: 't1', to: 'fou' },
        { from: 't2', to: 'jov' },
        { from: 'fou', to: 'fas' },
        { from: 'jov', to: 'fas' },
        { from: 'fas', to: 'tro' },
        { from: 'tro', to: 'nec' },
      ],
      steps: [
        { show: ['fas'], note: 'Lo que se infecta es la fascia, no la piel',
          say: 'Partamos por entender qué es. La fascitis necrotizante es una infección rápidamente destructiva de la fascia profunda y del tejido subcutáneo. Fíjate en la profundidad: la infección no está en la piel, está debajo. Esa sola idea explica por qué engaña tanto al examen físico.' },
        { show: ['t1', 'fou'], note: 'Tipo I: la más frecuente, en el diabético',
          say: 'Se clasifica en dos tipos. El tipo uno, que es el ochenta por ciento, es polimicrobiano: una mezcla de anaerobios como Bacteroides, enterobacterias y estreptococos. Aparece en el diabético o después de una cirugía perineal, y cuando compromete el periné recibe un nombre propio: gangrena de Fournier.' },
        { show: ['t2', 'jov'], note: 'Tipo II: estreptococo en el joven',
          say: 'El tipo dos, el veinte por ciento restante, es monomicrobiano, por Streptococcus pyogenes. Y el paciente es otro: un joven sano que tuvo un traumatismo menor o una varicela. Entonces, no porque el paciente sea joven y sin enfermedades descartas el cuadro.' },
        { show: ['tro'], note: 'La trombosis corta la irrigación',
          say: 'Lo que hace destructiva a esta infección es que trombosa los vasos pequeños. Sin irrigación, el tejido muere, y además los antibióticos no llegan bien al lugar. Retén esto, porque es la razón de fondo de por qué el tratamiento es quirúrgico.' },
        { show: ['nec'], note: 'La necrosis avanza por debajo',
          say: 'El resultado es una necrosis que avanza por debajo de una piel que al principio parece casi normal. Y de ahí sale el signo más importante de toda la clase, que vemos ahora.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Clínica',
      title: '¿Cómo reconocerla a tiempo?',
      cards: [
        { title: 'El signo precoz', tag: 'Sospecha', kind: 'key', items: [
          { t: 'Dolor desproporcionado', d: 'Intolerable frente a una piel solo eritematosa',
            say: 'El signo más precoz es el dolor desproporcionado. La piel se ve solo enrojecida, como una celulitis cualquiera, pero el paciente tiene un dolor intolerable. El dolor no calza con lo que ves, porque lo que duele es la fascia que se está muriendo por debajo.' },
          { t: 'Sobrepasa los bordes visibles', d: 'Duele más allá del eritema',
            say: 'Y ese dolor sobrepasa los márgenes del eritema. Duele más allá de donde está roja la piel. Esa es la frase que tienes que asociar a la sospecha.' },
        ] },
        { title: 'Signos duros de necrosis', tag: 'Confirman', kind: 'alert', items: [
          { t: 'Flictenas serohemáticas', d: 'Bulas con contenido sanguinolento',
            say: 'Después, cuando la necrosis avanza, aparecen los signos duros. El primero, las flictenas con contenido serohemático: ampollas con líquido sanguinolento. En las preguntas reales se describen como bulas sobre una piel violácea.' },
          { t: 'Crepitación', d: 'Gas tisular por anaerobios',
            say: 'El segundo es la crepitación a la palpación. Es gas en el tejido, producido por los anaerobios. Por eso la crepitación se asocia sobre todo al tipo uno.' },
          { t: 'Anestesia cutánea focal', d: 'Necrosis de los nervios dérmicos',
            say: 'El tercero es la anestesia cutánea focal. Y fíjate en la paradoja: al principio duele muchísimo, pero cuando se necrosan los nervios de la dermis, la zona queda insensible. Una zona que antes dolía y ahora no se siente es mala noticia, no mejoría.' },
          { t: 'Shock séptico fulminante', d: 'Acidosis y lactato elevado',
            say: 'Y el cuarto es sistémico: un shock séptico fulminante, con acidosis y lactato elevado. Es el mismo shock séptico que vimos en la primera clase del bloque, con un foco que solo se controla con cirugía.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Conducta',
      title: 'Fascitis necrotizante: el tratamiento es el pabellón',
      nodes: [
        { id: 'sos', col: 0, row: 1, k: 'start', t: 'Sospecha', s: 'Dolor desproporcionado · signos duros' },
        { id: 'pab', col: 1, row: 1, k: 'good', t: 'Pabellón inmediato', s: 'Aseo quirúrgico, fasciotomía, desbridamiento' },
        { id: 'atb', col: 2, row: 0, k: 'good', t: 'Meropenem + vancomicina + clindamicina', s: 'EV, de amplio espectro' },
        { id: 'rea', col: 2, row: 2, k: 'good', t: 'Reanimación', s: 'Manejo del shock séptico' },
        { id: 'sob', col: 3, row: 1, k: 'effect', t: 'Define la sobrevida', s: 'Cada hora de demora cuenta' },
        { id: 'tra', col: 1, row: 3, k: 'trap', t: 'Pedir TAC o RMN', s: 'O punción, o solo antibióticos' },
      ],
      edges: [
        { from: 'sos', to: 'pab' },
        { from: 'pab', to: 'atb', label: 'junto con' },
        { from: 'pab', to: 'rea', label: 'junto con' },
        { from: 'pab', to: 'sob' },
        { from: 'sos', to: 'tra', label: 'error' },
      ],
      steps: [
        { show: ['sos'], note: 'La sospecha clínica basta',
          say: 'Ahora la conducta, que es lo que decide el examen. Si tienes un paciente con dolor desproporcionado y signos duros de necrosis, el diagnóstico es clínico. No necesitas nada más para actuar.' },
        { show: ['pab'], note: 'Aseo quirúrgico y fasciotomía urgente',
          say: 'La conducta es el traslado inmediato a pabellón, para exploración quirúrgica, fasciotomía y desbridamiento amplio de todo el tejido necrótico. ¿Te acuerdas de la trombosis? Como el tejido muerto no recibe sangre, el antibiótico no llega. Solo sacándolo controlas el foco.' },
        { show: ['sob'], note: 'La cirugía define la sobrevida',
          say: 'Por eso la exploración quirúrgica es la medida que define la sobrevida. La mortalidad aumenta con cada hora de demora antes del pabellón.' },
        { show: ['atb', 'rea'], note: 'Antibióticos y reanimación, en paralelo',
          say: 'En paralelo, y sin que retrase la cirugía, se reanima al paciente como un shock séptico y se inicia terapia endovenosa con tres fármacos: meropenem, vancomicina y clindamicina. Enseguida vemos por qué esos tres.' },
        { show: ['tra'], note: 'Trampa: estudiar antes de operar',
          say: 'Y la trampa clásica. La alternativa que dice pedir una resonancia o una TAC para ver la profundidad suena muy razonable, pero es incorrecta si retrasa el pabellón. Lo mismo la punción aspirativa para cultivo, o dejar solo antibióticos y reevaluar. En la fascitis necrotizante no se difiere la cirugía por imágenes.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Tratamiento',
      title: 'Los antibióticos y el papel de la clindamicina',
      cards: [
        { title: 'Fascitis necrotizante', tag: 'Tres fármacos EV', kind: 'pharma', items: [
          { t: 'Meropenem', d: 'Cubre enterobacterias y anaerobios del tipo I',
            say: 'Veamos el esquema. El meropenem da un espectro amplio, que cubre las enterobacterias y los anaerobios de la forma polimicrobiana.' },
          { t: 'Vancomicina', d: 'Se suma al esquema empírico',
            say: 'La vancomicina completa la cobertura de los grampositivos en el esquema empírico.' },
          { t: 'Clindamicina', d: 'Bloquea la síntesis de toxinas',
            say: 'Y la clindamicina es la que más se pregunta, porque cumple un papel distinto. No está solo para matar la bacteria: bloquea la producción de las toxinas estreptocócicas, que son las que provocan el shock. Si te preguntan por qué va la clindamicina, la respuesta es las toxinas.' },
        ] },
        { title: 'Infección simple', tag: 'Sin signos duros', kind: 'normal', items: [
          { t: 'Cefazolina o cloxacilina EV', d: 'Celulitis sin necrosis ni shock',
            say: 'Compáralo con la celulitis simple, sin signos duros ni compromiso sistémico. Ahí basta cefazolina o cloxacilina endovenosa.' },
          { t: 'Marcar el borde del eritema', d: 'Reevaluar en 12 a 24 horas',
            say: 'Y se delimita el borde del eritema con un marcador, para reevaluar a las doce o veinticuatro horas. Si el eritema sobrepasa la marca o aparece algún signo duro, cambia todo: ya no es una celulitis y va al pabellón.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Angina de Ludwig',
      title: 'Angina de Ludwig: el riesgo es la asfixia',
      nodes: [
        { id: 'mol', col: 0, row: 1, k: 'cause', t: '2.º o 3.er molar inferior', s: 'Origen dental en el 80 %' },
        { id: 'cel', col: 1, row: 1, k: 'mech', t: 'Celulitis gangrenosa bilateral', s: 'Espacios submandibular y sublingual' },
        { id: 'pis', col: 2, row: 0, k: 'effect', t: 'Piso de boca elevado', s: 'Lengua protruida, trismus' },
        { id: 'est', col: 2, row: 2, k: 'risk', t: 'Estridor', s: 'La vía aérea se cierra' },
        { id: 'via', col: 3, row: 1, k: 'alert', t: 'Asegurar la vía aérea', s: 'Intubación con fibra óptica o traqueostomía' },
        { id: 'qx', col: 4, row: 1, k: 'good', t: 'Luego aseo quirúrgico', s: '+ antibióticos EV' },
      ],
      edges: [
        { from: 'mol', to: 'cel' },
        { from: 'cel', to: 'pis' },
        { from: 'cel', to: 'est' },
        { from: 'pis', to: 'via' },
        { from: 'est', to: 'via' },
        { from: 'via', to: 'qx', label: 'primero' },
      ],
      steps: [
        { show: ['mol'], note: 'El origen es un diente',
          say: 'Pasemos a la angina de Ludwig. En el ochenta por ciento de los casos el origen es dental: una infección del segundo o del tercer molar inferior. Por eso en el enunciado casi siempre vas a leer una extracción o un dolor de muela reciente.' },
        { show: ['cel'], note: 'Bilateral: submandibular y sublingual',
          say: 'Desde ahí se produce una celulitis gangrenosa bilateral de los espacios submandibular y sublingual. Retén la palabra bilateral: el cuello completo, bajo la mandíbula, está tomado.' },
        { show: ['pis'], note: 'El piso de la boca empuja la lengua',
          say: 'Como el piso de la boca se llena de edema e infección, empuja la lengua hacia arriba y hacia afuera. El paciente tiene la lengua protruida, trismus, y la voz cambia.' },
        { show: ['est'], note: 'Estridor: la vía aérea está en riesgo',
          say: 'Y cuando aparece el estridor, la vía aérea se está cerrando. El riesgo inminente de este paciente no es la sepsis: es la asfixia.' },
        { show: ['via'], note: 'Lo primero es la vía aérea',
          say: 'Por eso la prioridad número uno es asegurar la vía aérea, mediante intubación guiada con fibra óptica o traqueostomía. Antes de la TAC, antes del drenaje y antes de cualquier otra cosa.' },
        { show: ['qx'], note: 'Después, el mismo manejo de fondo',
          say: 'Con la vía aérea segura, el manejo sigue los mismos pilares que la fascitis: aseo quirúrgico urgente y antibióticos endovenosos.' },
      ],
    },

    {
      type: 'pathway',
      intro: 'Juntemos todo en un árbol de decisión: una infección de partes blandas y qué mirar para saber si es simple, necrotizante o una amenaza para la vía aérea.',
    },

    {
      type: 'table',
      kicker: 'Trampas EUNACOM',
      title: 'Celulitis simple o infección necrotizante',
      head: ['Característica', 'Celulitis o erisipela', 'Fascitis necrotizante'],
      rows: [
        { cells: ['Dolor', 'Proporcional al eritema visible', 'Severo, desproporcionado al examen'],
          say: 'Comparemos, porque el examen pone la celulitis como alternativa de la fascitis. En la celulitis el dolor es proporcional a lo que ves. En la fascitis es severo y desproporcionado al examen.' },
        { cells: ['Signos locales', 'Calor, rubor, edema con fóvea', 'Flictenas hemorrágicas, crepitación, anestesia focal'],
          say: 'En lo local, la celulitis tiene calor, rubor y edema. La fascitis tiene los signos duros: flictenas hemorrágicas, crepitación y anestesia focal.' },
        { cells: ['Compromiso sistémico', 'Fiebre moderada, hemodinamia estable', 'Shock séptico, lactato elevado'],
          say: 'La celulitis da fiebre moderada con el paciente estable. La fascitis da shock séptico, lactato elevado y falla multiorgánica. Un paciente hipotenso con una lesión de piel ya no es una celulitis.' },
        { cells: ['Antibiótico', 'Cefazolina o cloxacilina EV', 'Meropenem + vancomicina + clindamicina'],
          say: 'En los antibióticos, cefazolina o cloxacilina para la celulitis, y el esquema de tres fármacos con clindamicina para la fascitis.' },
        { cells: ['Conducta', 'Antibióticos en sala, reevaluar el borde', 'Pabellón urgente, sin esperar imágenes'],
          say: 'Y la conducta: la celulitis se trata con antibióticos en sala y se reevalúa el borde. La fascitis va a pabellón urgente para desbridamiento amplio, sin esperar ninguna imagen.' },
      ],
    },

    {
      type: 'quiz',
      kicker: 'Caso clínico',
      title: 'Caso clínico',
      stem: 'Hombre de 38 años con 48 horas de aumento de volumen doloroso cervical anterior y submandibular bilateral, iniciado tras la extracción del tercer molar inferior izquierdo. Al examen: piso de boca elevado que empuja la lengua contra el paladar, trismus moderado, voz engolada y estridor inspiratorio intermitente. T° 38,9 °C.',
      question: '¿Cuál es la prioridad inmediata?',
      options: [
        { letter: 'A', text: 'Asegurar la vía aérea mediante intubación con fibra óptica o traqueostomía' },
        { letter: 'B', text: 'Solicitar TAC de cuello con contraste para planificar el drenaje' },
        { letter: 'C', text: 'Iniciar amoxicilina con ácido clavulánico oral y analgesia' },
        { letter: 'D', text: 'Iniciar meropenem, vancomicina y clindamicina EV y observar en sala' },
        { letter: 'E', text: 'Nebulizar con adrenalina y controlar en 12 horas' },
      ],
      correct: 'A',
      explanation: 'Celulitis bilateral submandibular y sublingual de origen dental con estridor y lengua protruida: angina de Ludwig con riesgo inminente de asfixia. Lo primero es asegurar la vía aérea (fibra óptica o traqueostomía); después, aseo quirúrgico y antibióticos EV.',
      say: {
        stem: 'Vamos con un caso. Hombre de treinta y ocho años con dos días de aumento de volumen doloroso bajo la mandíbula, a ambos lados, que empezó después de que le sacaron el tercer molar inferior izquierdo. Tiene el piso de la boca elevado que empuja la lengua contra el paladar, trismus, voz engolada y estridor inspiratorio intermitente.',
        question: '¿Cuál es la prioridad inmediata?',
        options: 'Las opciones son: asegurar la vía aérea; pedir una TAC de cuello; amoxicilina con ácido clavulánico oral; tres antibióticos endovenosos y observar en sala; o nebulizar con adrenalina. Piénsalo.',
        answer: 'La respuesta es la A. Origen dental, compromiso bilateral del piso de la boca y estridor: es una angina de Ludwig, y el estridor te dice que la vía aérea se está cerrando. La TAC es el distractor más tentador, porque sirve para planificar el drenaje, pero sacar a este paciente a una imagen sin vía aérea segura es arriesgar una asfixia. Y los antibióticos son necesarios, pero no son lo primero.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Agosto 2021 · Pregunta 172',
      stem: 'Un paciente de 53 años, diabético mal controlado, presenta una lesión en la pierna derecha, desde hace 2 días, que se ha extendido hasta alcanzar un gran tamaño y se ha asociado a malestar general y fiebre. Al examen físico tiene T°: 39,0°C, FC: 115x’, PA: 90/60 mmHg. Además, se aprecia la lesión eritematosa de 20 cm, con zonas violáceas y bulas en su superficie.',
      question: 'El diagnóstico más probable es:',
      options: [
        { letter: 'A', text: 'Erisipela' },
        { letter: 'B', text: 'Herpes zóster' },
        { letter: 'C', text: 'Pioderma gangrenoso' },
        { letter: 'D', text: 'Fasceítis necrotizante' },
        { letter: 'E', text: 'Celulitis bacteriana' },
      ],
      correct: 'D',
      explanation: 'Diabético con lesión extensa, zonas violáceas y bulas, más taquicardia e hipotensión: signos de necrosis con compromiso sistémico. Es una fascitis necrotizante, no una celulitis ni una erisipela.',
      say: {
        stem: 'Ahora las preguntas reales. La primera es del EUNACOM de agosto de dos mil veintiuno, y casi la misma salió en diciembre de dos mil diecinueve. Paciente de cincuenta y tres años, diabético mal controlado, con una lesión en la pierna que creció mucho en dos días, con fiebre. Tiene treinta y nueve grados, pulso de ciento quince y presión de noventa con sesenta. La lesión es eritematosa, de veinte centímetros, con zonas violáceas y bulas.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones son: erisipela, herpes zóster, pioderma gangrenoso, fascitis necrotizante, o celulitis bacteriana. Piénsalo.',
        answer: 'Es la D, fascitis necrotizante. Es un diabético, el paciente clásico del tipo uno, y tiene dos cosas que la celulitis no da: las zonas violáceas con bulas, que son los signos duros de necrosis, y la hipotensión con taquicardia, que es el shock. La celulitis es el distractor: el inicio se parece, pero una celulitis no deja a un paciente hipotenso ni forma bulas sobre piel violácea.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2015 · Pregunta 28',
      stem: 'Un paciente alcohólico, de 50 años, en situación de calle, consulta por dolor en el antebrazo derecho, muy intenso. Al examen físico se aprecia una lesión grande en el antebrazo derecho, con áreas violáceas, que crepita a la palpación. Su frecuencia cardiaca es de 108x`, con PA: 90/60 mmHg y su hemograma muestra leucocitosis de 17.000.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Loxocelismo cutáneo' },
        { letter: 'B', text: 'Celulitis' },
        { letter: 'C', text: 'Úlcera por presión' },
        { letter: 'D', text: 'Fascitis necrosante' },
        { letter: 'E', text: 'Miositis necrosante' },
      ],
      correct: 'D',
      explanation: 'Dolor muy intenso, áreas violáceas y crepitación (gas tisular), con taquicardia, hipotensión y leucocitosis: fascitis necrotizante.',
      say: {
        stem: 'La siguiente es del EUNACOM de julio de dos mil quince. Paciente alcohólico de cincuenta años, en situación de calle, con un dolor muy intenso en el antebrazo derecho. Tiene una lesión grande con áreas violáceas que crepita a la palpación, pulso de ciento ocho, presión de noventa con sesenta y leucocitosis de diecisiete mil.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones son: loxocelismo cutáneo, celulitis, úlcera por presión, fascitis necrosante, o miositis necrosante. Piénsalo.',
        answer: 'Es la D. Aquí la pista es otra: la crepitación, que es gas en el tejido, sumada al dolor muy intenso, las áreas violáceas y el shock. Fíjate además que el paciente no es diabético: no esperes siempre al diabético para sospecharla. La miositis necrosante es el distractor, pero el cuadro que se describe con estos signos y que el examen espera es la fascitis. Y el loxocelismo da una lesión violácea, pero no crepita.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2025 · Pregunta 48',
      stem: 'Hombre de 20 años con odinofagia severa, fiebre 39°C, dificultad para abrir la boca (trismus) y desviación de la úvula hacia el lado contrario.',
      question: '¿Cuál es el diagnóstico más probable?',
      options: [
        { letter: 'A', text: 'Angina de Ludwig' },
        { letter: 'B', text: 'Faringitis estreptocócica' },
        { letter: 'C', text: 'Absceso periamigdalino' },
        { letter: 'D', text: 'Mononucleosis infecciosa' },
        { letter: 'E', text: 'Epiglotitis' },
      ],
      correct: 'C',
      explanation: 'Odinofagia severa, trismus y úvula desviada al lado contrario: absceso periamigdalino, un proceso unilateral de la faringe. La angina de Ludwig es bilateral, del piso de la boca, de origen dental, con lengua protruida.',
      say: {
        stem: 'Y la última, del EUNACOM de julio de dos mil veinticinco, que usa la angina de Ludwig como distractor. Hombre de veinte años con odinofagia severa, fiebre de treinta y nueve grados, trismus y la úvula desviada hacia el lado contrario.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones son: angina de Ludwig, faringitis estreptocócica, absceso periamigdalino, mononucleosis infecciosa, o epiglotitis. Piénsalo.',
        answer: 'Es la C, absceso periamigdalino. El trismus aparece en los dos cuadros, por eso la angina de Ludwig tienta. Pero la úvula desviada te habla de una colección unilateral al lado de la amígdala. La angina de Ludwig es otra cosa: bilateral, del piso de la boca, de origen dental, con la lengua empujada hacia arriba y estridor.',
      },
    },

    {
      type: 'points',
      kicker: 'Cierre',
      title: 'Reglas de oro para el examen',
      cards: [
        { title: 'Fascitis necrotizante', tag: 'Sospecha precoz', kind: 'key', items: [
          { t: 'Dolor desproporcionado', d: 'El signo más precoz',
            say: 'Cerremos con las reglas de oro. El signo más precoz de la fascitis necrotizante es el dolor desproporcionado a lo que se ve en la piel.' },
          { t: 'Bulas, crepitación, anestesia, shock', d: 'Signos duros de necrosis',
            say: 'Las flictenas hemorrágicas, la crepitación, la anestesia focal y el shock son los signos duros que confirman la necrosis.' },
        ] },
        { title: 'Conducta', tag: 'Sin esperar', kind: 'alert', items: [
          { t: 'Pabellón inmediato', d: 'Nunca diferir por TAC o RMN',
            say: 'La conducta es el pabellón inmediato para desbridamiento. Nunca se difiere por una TAC ni por una resonancia.' },
          { t: 'Meropenem + vancomicina + clindamicina', d: 'Clindamicina bloquea las toxinas',
            say: 'Junto con reanimación y meropenem, vancomicina y clindamicina, que está ahí por las toxinas.' },
        ] },
        { title: 'Angina de Ludwig', tag: 'Vía aérea', kind: 'pharma', items: [
          { t: 'Origen dental, bilateral', d: 'Submandibular y sublingual',
            say: 'La angina de Ludwig es una celulitis bilateral del piso de la boca, de origen dental.' },
          { t: 'Primero la vía aérea', d: 'Fibra óptica o traqueostomía',
            say: 'Y la prioridad es la vía aérea. Si te llevas una sola idea de hoy: un dolor que no calza con la piel es fascitis hasta demostrar lo contrario, y su tratamiento es el pabellón, no la imagen. La próxima clase abrimos el bloque de salud pública con el manejo de contactos y los accidentes cortopunzantes. Nos vemos en la próxima clase.' },
        ] },
      ],
    },
  ],

  pathway: {
    title: 'Infección de partes blandas: simple, necrotizante o vía aérea',
    root: N('start', 'Infección de partes blandas', 'Eritema, dolor, fiebre',
      'Paciente con una infección de partes blandas. Lo primero es decidir si es una infección simple o una emergencia quirúrgica.',
      ['', N('q', '¿Compromete el piso de la boca?', 'Bilateral, estridor, lengua protruida',
        'Si la infección está en el cuello, pregúntate si compromete el piso de la boca a ambos lados, con estridor o lengua protruida.',
        ['SÍ', N('alert', 'Angina de Ludwig', 'Asegurar vía aérea primero',
          'Si es así, es una angina de Ludwig, y lo primero es asegurar la vía aérea con fibra óptica o traqueostomía.',
          ['', N('do', 'Aseo quirúrgico + antibióticos EV', 'Con la vía aérea segura',
            'Con la vía aérea segura, siguen el aseo quirúrgico urgente y los antibióticos endovenosos.')])],
        ['NO', N('q', '¿Signos duros de necrosis?', 'Dolor desproporcionado, bulas, crepitación, shock',
          'Si no, busca los signos duros: dolor desproporcionado, flictenas, crepitación, anestesia focal o shock.',
          ['SÍ', N('alert', 'Pabellón inmediato', 'Meropenem + vancomicina + clindamicina',
            'Si hay alguno, es una fascitis necrotizante: pabellón inmediato para desbridamiento, sin esperar imágenes, y en paralelo reanimación con meropenem, vancomicina y clindamicina.')],
          ['NO', N('ok', 'Celulitis simple', 'Cefazolina o cloxacilina EV · reevaluar en 12 a 24 h',
            'Si no hay ninguno, es una celulitis simple: cefazolina o cloxacilina endovenosa. Marcas el borde del eritema y reevalúas a las doce o veinticuatro horas; si avanza o aparece un signo duro, vuelves a pensar en fascitis.')])])]),
  },
};
