// Clase 2.2 — guion docente escrito a mano (ver gastro-01.cjs para el formato).
// Fuente clínica: books/scripts/dataset_infectologia.cjs (inf-06).

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  id: 'infecto-06',
  tier: 2,
  slides: [
    {
      type: 'cover',
      subtitle: 'Qué animal mordió, qué herida es y cuántas dosis tiene: las tres preguntas que deciden',
      say: 'Bienvenidos. En la clase anterior vimos profilaxis después de un contacto. Hoy seguimos con profilaxis, pero después de una herida: rabia y tétanos. Las dos son enfermedades neurotrópicas, prevenibles con vacuna, y con una letalidad cercana al cien por ciento una vez que aparecen los síntomas. Por eso el examen no pregunta cómo curarlas, pregunta cómo evitarlas: qué animal mordió, qué tipo de herida es, y cuántas dosis de vacuna tiene el paciente. Partamos.',
    },

    {
      type: 'flow',
      kicker: 'Rabia · patogenia',
      title: '¿Cómo llega el virus rábico al cerebro?',
      nodes: [
        { id: 'sal', col: 0, row: 1, k: 'cause', t: 'Saliva de mamífero infectado', s: 'Mordedura o contacto con mucosas' },
        { id: 'mio', col: 1, row: 1, k: 'mech', t: 'Replicación local', s: 'En el músculo de la herida' },
        { id: 'axo', col: 2, row: 1, k: 'mech', t: 'Transporte axonal retrógrado', s: 'Por los nervios periféricos' },
        { id: 'enc', col: 3, row: 1, k: 'risk', t: 'Encefalomielitis letal', s: 'Médula y encéfalo' },
        { id: 'cli', col: 3, row: 3, k: 'effect', t: 'Hidrofobia, espasmo laríngeo', s: 'Paro cardiorrespiratorio' },
        { id: 'pre', col: 1, row: 3, k: 'good', t: 'Ventana para prevenir', s: 'Antes de que llegue al sistema nervioso' },
      ],
      edges: [
        { from: 'sal', to: 'mio' },
        { from: 'mio', to: 'axo' },
        { from: 'axo', to: 'enc' },
        { from: 'enc', to: 'cli' },
        { from: 'mio', to: 'pre', label: 'aquí se actúa' },
      ],
      steps: [
        { show: ['sal'], note: 'Un virus que viaja en la saliva',
          say: 'Partamos por la rabia. El virus rábico es un virus ARN neurotrópico, que se transmite por la saliva de un mamífero infectado, a través de una mordedura o del contacto con mucosas.' },
        { show: ['mio'], note: 'Primero se replica en la herida',
          say: 'Después de la inoculación, el virus no va directo al cerebro. Primero se replica en el músculo, en el sitio de la herida.' },
        { show: ['axo'], note: 'Sube por los nervios',
          say: 'Luego sube por dentro de los nervios periféricos, por transporte axonal retrógrado, hacia la médula y el encéfalo. Es el mismo mecanismo que vimos en la encefalitis herpética, y lo vamos a volver a ver en el tétanos.' },
        { show: ['enc', 'cli'], note: 'Una vez en el cerebro, es letal',
          say: 'Cuando llega, produce una encefalomielitis letal, con hidrofobia, espasmos laríngeos y finalmente paro cardiorrespiratorio. Una vez que aparecen los síntomas, la letalidad es cercana al cien por ciento.' },
        { show: ['pre'], note: 'La profilaxis actúa antes',
          say: 'Y aquí está la lógica de toda la profilaxis. Mientras el virus se replica en la herida y viaja por el nervio, hay una ventana. La vacuna y la inmunoglobulina actúan en esa ventana, antes de que el virus llegue al sistema nervioso.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'Rabia · norma MINSAL',
      title: 'Profilaxis antirrábica: ¿qué animal fue?',
      nodes: [
        { id: 'mor', col: 0, row: 2, k: 'start', t: 'Mordedura o contacto', s: '¿Qué animal fue?' },
        { id: 'ubi', col: 1, row: 0, k: 'q', t: 'Perro o gato ubicable', s: 'Doméstico y conocido' },
        { id: 'obs', col: 2, row: 0, k: 'mech', t: 'Observación veterinaria 10 días', s: '¿Sigue sano?' },
        { id: 'nov', col: 3, row: 0, k: 'good', t: 'Sano al día 10', s: 'No se vacuna' },
        { id: 'enf', col: 3, row: 1, k: 'refer', t: 'Enferma, muere o desaparece', s: 'Vacunación inmediata' },
        { id: 'des', col: 1, row: 2, k: 'q', t: 'Desconocido o vagabundo', s: 'No se puede observar' },
        { id: 'vac', col: 2, row: 2, k: 'refer', t: 'Vacuna inmediata', s: '5 dosis: días 0, 3, 7, 14 y 28' },
        { id: 'mur', col: 1, row: 4, k: 'alert', t: 'Murciélago', s: 'Cualquier contacto = exposición grave' },
        { id: 'ig', col: 2, row: 4, k: 'alert', t: 'Vacuna + inmunoglobulina', s: 'Antirrábica humana, siempre' },
      ],
      edges: [
        { from: 'mor', to: 'ubi' },
        { from: 'mor', to: 'des' },
        { from: 'mor', to: 'mur' },
        { from: 'ubi', to: 'obs' },
        { from: 'obs', to: 'nov', label: 'sí' },
        { from: 'obs', to: 'enf', label: 'no' },
        { from: 'des', to: 'vac' },
        { from: 'mur', to: 'ig' },
      ],
      steps: [
        { show: ['mor'], note: 'La pregunta es el animal',
          say: 'Ahora la conducta, según la norma del Ministerio de Salud. Frente a una mordedura, la pregunta que decide todo es qué animal fue.' },
        { show: ['ubi', 'obs'], note: 'Animal ubicable: se observa',
          say: 'Si es un perro o un gato doméstico, conocido y ubicable, no se vacuna de inmediato al paciente. Se mantiene al animal en observación veterinaria estricta por diez días.' },
        { show: ['nov'], note: 'Si sigue sano, no se vacuna',
          say: 'Si el animal sigue sano al día diez, no se vacuna al paciente. Esa es la regla que más se pregunta. Fíjate que se observa al animal, no al paciente.' },
        { show: ['enf'], note: 'Si enferma, muere o desaparece: vacunar',
          say: 'Pero si el animal enferma, muere o desaparece durante la observación, se inicia la vacunación de inmediato.' },
        { show: ['des', 'vac'], note: 'Si no se puede observar: vacunar',
          say: 'Si el animal es desconocido o vagabundo, no hay a quién observar, así que se vacuna de inmediato. El esquema es de cinco dosis, los días cero, tres, siete, catorce y veintiocho.' },
        { show: ['mur'], note: 'El murciélago es el reservorio en Chile',
          say: 'Y el caso especial. En Chile, el reservorio silvestre de la rabia es el murciélago. Todo contacto con murciélago es una exposición grave: una mordedura, tomarlo con la mano desnuda, o incluso despertar en una habitación donde hay un murciélago, porque su mordedura puede pasar inadvertida.' },
        { show: ['ig'], note: 'Vacuna completa + inmunoglobulina',
          say: 'Por eso, ante el murciélago, siempre vacunación antirrábica completa inmediata más inmunoglobulina antirrábica humana. No se espera nada, y no importa si no hay herida visible.' },
      ],
    },

    {
      type: 'flow',
      kicker: 'Tétanos · mecanismo',
      title: 'Tétanos: una toxina que quita el freno',
      nodes: [
        { id: 'esp', col: 0, row: 1, k: 'cause', t: 'Esporas de Clostridium tetani', s: 'Suelo y heces de animales' },
        { id: 'her', col: 1, row: 1, k: 'risk', t: 'Herida desvitalizada', s: 'Punzante, quemadura, fractura expuesta' },
        { id: 'tox', col: 2, row: 1, k: 'mech', t: 'Tetanoespasmina', s: 'Sube por transporte axonal retrógrado' },
        { id: 'int', col: 3, row: 1, k: 'mech', t: 'Interneuronas inhibitorias', s: 'Bloquea la liberación de GABA y glicina' },
        { id: 'con', col: 3, row: 3, k: 'effect', t: 'Contracción tónica sostenida', s: 'Más espasmos paroxísticos dolorosos' },
      ],
      edges: [
        { from: 'esp', to: 'her' },
        { from: 'her', to: 'tox' },
        { from: 'tox', to: 'int' },
        { from: 'int', to: 'con' },
      ],
      steps: [
        { show: ['esp'], note: 'Un anaerobio que vive en la tierra',
          say: 'Pasemos al tétanos. Clostridium tetani es un bacilo grampositivo, anaerobio estricto, que forma esporas. Esas esporas están en todas partes: en el suelo y en las heces de animales.' },
        { show: ['her'], note: 'Germina donde falta oxígeno',
          say: 'Como es anaerobio, las esporas germinan donde falta oxígeno: en un tejido desvitalizado o sucio. Por eso las heridas de riesgo son las punzantes, las quemaduras y las fracturas expuestas. Esto va a ser clave para la profilaxis.' },
        { show: ['tox'], note: 'La toxina viaja por el nervio',
          say: 'Ahí produce la tetanoespasmina, una neurotoxina que sube por los nervios, otra vez por transporte axonal retrógrado, hasta la médula espinal.' },
        { show: ['int'], note: 'Bloquea la inhibición',
          say: 'En la médula llega a las interneuronas inhibitorias. Degrada la sinaptobrevina, una proteína necesaria para liberar neurotransmisores, y así bloquea la liberación de GABA y glicina, que son los frenos del músculo.' },
        { show: ['con'], note: 'Sin freno, el músculo se contrae',
          say: 'Sin frenos, la neurona motora queda desinhibida: contracción muscular tónica sostenida y espasmos paroxísticos muy dolorosos. El mecanismo te explica la clínica.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Tétanos · clínica y manejo',
      title: 'Cómo se ve y qué se hace',
      cards: [
        { title: 'Clínica', tag: 'Mente lúcida', kind: 'key', items: [
          { t: 'Trismus y risa sardónica', d: 'Espasmo del masetero y de la cara',
            say: 'Veamos la clínica. Lo primero suele ser el trismus, el espasmo del masetero que impide abrir la boca, y la risa sardónica, una mueca fija de la cara.' },
          { t: 'Opistótonos', d: 'Arco dorsal rígido',
            say: 'Luego el opistótonos, el arco rígido de la espalda por la contracción de los músculos extensores.' },
          { t: 'Espasmos por luz o ruido', d: 'Con la conciencia conservada',
            say: 'Los espasmos se desencadenan con estímulos luminosos o sonoros, y lo más dramático: la mente permanece lúcida. El paciente está consciente durante los espasmos.' },
          { t: 'Muerte por paro respiratorio', d: 'Espasmo laríngeo o diafragmático',
            say: 'La causa de muerte es el paro respiratorio, por espasmo de la laringe o del diafragma.' },
        ] },
        { title: 'Tétanos establecido', tag: 'UCI', kind: 'pharma', items: [
          { t: 'UCI en box oscuro y silencioso', d: 'Sedación y relajantes musculares',
            say: 'El tétanos establecido se maneja en la unidad de cuidados intensivos, en un box oscuro y silencioso, para no gatillar espasmos, con sedación y relajantes musculares.' },
          { t: 'Metronidazol EV o penicilina', d: 'Contra la bacteria',
            say: 'Se da metronidazol endovenoso, o penicilina, contra la bacteria.' },
          { t: 'IGH-T 3.000 a 6.000 UI', d: 'Neutraliza la toxina libre',
            say: 'Y la inmunoglobulina antitetánica humana, tres mil a seis mil unidades. Fíjate en la diferencia con la profilaxis, que usa solo doscientas cincuenta.' },
        ] },
      ],
    },

    {
      type: 'points',
      kicker: 'Profilaxis antitetánica',
      title: 'Dos preguntas ante cualquier herida',
      cards: [
        { title: '¿Qué herida es?', tag: 'Pregunta 1', kind: 'criteria', items: [
          { t: 'Limpia y superficial', d: 'Refuerzo dT si pasaron > 10 años',
            say: 'Ahora la profilaxis, que es lo que se pregunta. Ante cualquier herida haces dos preguntas. La primera: qué herida es. Si es limpia y superficial, el refuerzo con vacuna dT se da solo si pasaron más de diez años desde la última dosis.' },
          { t: 'Sucia o tetanígena', d: 'Refuerzo dT si pasaron > 5 años',
            say: 'Si es sucia o tetanígena, es decir, contaminada con tierra, heces o saliva, punzante profunda, una mordedura o con tejido desvitalizado, el corte baja: refuerzo si pasaron más de cinco años.' },
        ] },
        { title: '¿Cuántas dosis tiene?', tag: 'Pregunta 2', kind: 'alert', items: [
          { t: 'Menos de 3 dosis o desconocido', d: 'Herida sucia: dT + IGH-T 250 UI IM',
            say: 'La segunda pregunta: cuántas dosis de toxoide ha recibido en la vida. Si tiene menos de tres, o no lo sabe, y la herida es sucia, va vacuna dT más inmunoglobulina antitetánica, doscientas cincuenta unidades intramuscular.' },
          { t: 'En sitios anatómicos separados', d: 'Para que no se neutralicen',
            say: 'Y se ponen en sitios separados, para que la inmunoglobulina no neutralice la vacuna.' },
          { t: 'IGH-T solo con las dos condiciones', d: 'Herida sucia + esquema incompleto',
            say: 'La trampa es dar inmunoglobulina de más. Solo va cuando se juntan las dos condiciones: herida sucia y esquema incompleto o desconocido. Con tres dosis o más, nunca se da inmunoglobulina.' },
        ] },
      ],
    },

    {
      type: 'pathway',
      intro: 'Juntemos todo en un árbol de decisión: un paciente con una herida, y las dos profilaxis que tienes que pensar.',
    },

    {
      type: 'table',
      kicker: 'Trampas EUNACOM',
      title: 'Matriz de profilaxis antitetánica',
      head: ['Vacunación previa', 'Herida limpia y superficial', 'Herida sucia o punzante'],
      rows: [
        { cells: ['Menos de 3 dosis o desconocida', 'dT, 3 dosis · sin IGH-T', 'dT, 3 dosis + IGH-T 250 UI'],
          say: 'Pongamos todo en la matriz. Con menos de tres dosis o antecedente desconocido, se completa la vacunación con tres dosis de dT, y si la herida es sucia, se agrega inmunoglobulina. Es la única fila que la lleva.' },
        { cells: ['≥ 3 dosis · última hace < 5 años', 'Nada', 'Nada'],
          say: 'Con tres dosis o más y la última hace menos de cinco años, no se da nada, ni siquiera con una herida sucia. Solo el aseo de la herida.' },
        { cells: ['≥ 3 dosis · última hace 5 a 10 años', 'Nada', 'Refuerzo dT · sin IGH-T'],
          say: 'Si la última dosis fue hace cinco a diez años, la herida limpia no necesita nada, y la sucia, solo un refuerzo de dT.' },
        { cells: ['≥ 3 dosis · última hace > 10 años', 'Refuerzo dT', 'Refuerzo dT · sin IGH-T'],
          say: 'Y si pasaron más de diez años, cualquier herida lleva un refuerzo de dT, pero sin inmunoglobulina, porque el paciente tiene su esquema completo.' },
      ],
    },

    {
      type: 'quiz',
      kicker: 'Caso clínico',
      title: 'Caso clínico',
      stem: 'Hombre de 32 años, campesino, sufre una herida punzante profunda en la planta del pie derecho con un clavo oxidado en un establo. Recibió sus vacunas en la infancia, pero no recuerda ningún refuerzo en los últimos 15 años. Examen: herida puntiforme de 1 cm, márgenes desvitalizados y restos de barro.',
      question: 'Además del aseo de la herida, ¿cuál es la conducta antitetánica más adecuada?',
      options: [
        { letter: 'A', text: 'Refuerzo con vacuna dT, sin inmunoglobulina' },
        { letter: 'B', text: 'Vacuna dT + inmunoglobulina antitetánica 250 UI' },
        { letter: 'C', text: 'Solo inmunoglobulina antitetánica 250 UI' },
        { letter: 'D', text: 'No requiere profilaxis por su vacunación infantil' },
        { letter: 'E', text: 'Inmunoglobulina antitetánica 3.000 UI y metronidazol EV' },
      ],
      correct: 'A',
      explanation: 'Herida tetanígena (punzante, con barro y tejido desvitalizado) en un paciente con esquema completo en la infancia (≥ 3 dosis) y último refuerzo hace más de 10 años: refuerzo con dT. La IGH-T se reserva para herida sucia con esquema incompleto o desconocido.',
      say: {
        stem: 'Vamos con un caso. Hombre de treinta y dos años, campesino, que se clava un clavo oxidado en la planta del pie en un establo. Recibió sus vacunas de niño, pero no recuerda ningún refuerzo en los últimos quince años. La herida es puntiforme, con bordes desvitalizados y restos de barro.',
        question: 'Además del aseo, ¿cuál es la conducta antitetánica más adecuada?',
        options: 'Las opciones son: refuerzo de dT sin inmunoglobulina; dT más inmunoglobulina; solo inmunoglobulina; nada, por su vacunación infantil; o inmunoglobulina en dosis alta con metronidazol. Piénsalo.',
        answer: 'La respuesta es la A. Haz las dos preguntas. ¿Qué herida es? Sucia, punzante y con barro. ¿Cuántas dosis tiene? Un esquema completo en la infancia, con la última hace más de diez años. Entonces, refuerzo de dT. La B es el distractor más tentador, porque la herida asusta, pero la inmunoglobulina es solo para el esquema incompleto. Y la E es el tratamiento del tétanos ya establecido, no la profilaxis.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Diciembre 2017 · Pregunta 93',
      stem: 'Un niño de 7 años es mordido por un perro callejero en el brazo derecho.',
      question: 'Además del manejo de la herida, ¿cuál es la conducta más adecuada respecto a la profilaxis de la rabia?',
      options: [
        { letter: 'A', text: 'Observar al niño por 10 días' },
        { letter: 'B', text: 'Vacunar al niño solo si el perro presenta síntomas' },
        { letter: 'C', text: 'Administrar la vacuna antirrábica al niño' },
        { letter: 'D', text: 'Vacunar al niño solo si el perro muere' },
        { letter: 'E', text: 'Administrar inmunoglobulina antirrábica al niño' },
      ],
      correct: 'C',
      explanation: 'Perro callejero: no es ubicable ni se puede observar, así que se vacuna al niño de inmediato (esquema de 5 dosis). La inmunoglobulina se reserva para la exposición grave, como el contacto con murciélago.',
      say: {
        stem: 'Ahora una pregunta real, del EUNACOM de diciembre de dos mil diecisiete. Un niño de siete años es mordido en el brazo por un perro callejero.',
        question: 'Además del manejo de la herida, ¿cuál es la conducta respecto a la rabia?',
        options: 'Las opciones son: observar al niño por diez días; vacunar solo si el perro presenta síntomas; vacunar al niño; vacunar solo si el perro muere; o dar inmunoglobulina antirrábica. Piénsalo.',
        answer: 'Es la C, vacunar. La pregunta clave es si el animal es ubicable, y un perro callejero no lo es: no hay a quién observar. Las alternativas B y D serían correctas para un perro conocido en observación. Y la A tiene la trampa clásica: los diez días de observación son para el animal, no para el niño.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta del banco EUNACOM',
      title: 'Banco EUNACOM · Caso representativo',
      stem: 'Un hombre de 28 años despierta en una cabaña de veraneo y encuentra un murciélago vivo volando en su habitación. No presenta heridas evidentes ni recuerda haber sido mordido.',
      question: '¿Cuál es la conducta inmediata recomendada?',
      options: [
        { letter: 'A', text: 'Observar al paciente de forma ambulatoria y consultar solo si presenta fiebre o cefalea' },
        { letter: 'B', text: 'Iniciar vacunación antirrábica completa e inmunoglobulina antirrábica de inmediato' },
        { letter: 'C', text: 'Capturar al murciélago para observarlo vivo durante 10 días' },
        { letter: 'D', text: 'Administrar profilaxis con amoxicilina y citar a curaciones diarias' },
        { letter: 'E', text: 'Descartar el riesgo de rabia dado que no existen lesiones cortantes visibles' },
      ],
      correct: 'B',
      explanation: 'En Chile el murciélago es el reservorio de la rabia y su mordedura puede pasar inadvertida. Despertar con un murciélago en la habitación es exposición grave: vacunación completa inmediata más inmunoglobulina antirrábica.',
      say: {
        stem: 'Y ahora dos casos representativos del banco, porque el murciélago y la profilaxis antitetánica no tienen preguntas reales fechadas. El primero: un hombre de veintiocho años despierta en una cabaña y encuentra un murciélago vivo volando en su pieza. No tiene heridas y no recuerda haber sido mordido.',
        question: '¿Cuál es la conducta inmediata?',
        options: 'Las opciones son: observar y consultar si tiene fiebre; vacuna completa más inmunoglobulina de inmediato; capturar al murciélago y observarlo diez días; amoxicilina y curaciones; o descartar el riesgo porque no hay heridas. Piénsalo.',
        answer: 'Es la B. Despertar con un murciélago en la habitación es una exposición grave, porque la mordedura puede ser indolora e imperceptible. La E es el distractor más tentador: no ver una herida no descarta nada. Y la C aplica la regla del perro ubicable a un animal donde no corresponde.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta del banco EUNACOM',
      title: 'Banco EUNACOM · Caso representativo',
      stem: 'Una mujer de 45 años consulta tras cortarse la mano con una lata oxidada en su patio. Su esquema de vacunación contra el tétanos está al día, habiendo recibido su última dosis de refuerzo hace 3 años.',
      question: '¿Cuál es la indicación correcta?',
      options: [
        { letter: 'A', text: 'Aseo quirúrgico local de la herida sin necesidad de vacuna ni inmunoglobulina' },
        { letter: 'B', text: 'Administrar refuerzo con toxoide tetánico (dT)' },
        { letter: 'C', text: 'Administrar inmunoglobulina antitetánica (IGH-T) en dosis de 250 UI' },
        { letter: 'D', text: 'Administrar vacuna dT + inmunoglobulina antitetánica' },
        { letter: 'E', text: 'Iniciar profilaxis antibiótica con ciprofloxacino por 10 días' },
      ],
      correct: 'A',
      explanation: 'Esquema completo con última dosis hace menos de 5 años: la protección es suficiente incluso ante una herida sucia. Solo se requiere aseo prolijo de la herida.',
      say: {
        stem: 'El segundo: una mujer de cuarenta y cinco años se corta la mano con una lata oxidada en su patio. Tiene su esquema antitetánico al día, con el último refuerzo hace tres años.',
        question: '¿Cuál es la indicación correcta?',
        options: 'Las opciones son: solo aseo de la herida; refuerzo de dT; inmunoglobulina; dT más inmunoglobulina; o ciprofloxacino. Piénsalo.',
        answer: 'Es la A, solo el aseo. La herida es sucia, pero el esquema está completo y la última dosis fue hace menos de cinco años, así que su protección es suficiente. La B es el distractor: la lata oxidada invita a vacunar, pero el refuerzo en herida sucia se da solo si pasaron más de cinco años.',
      },
    },

    {
      type: 'points',
      kicker: 'Cierre',
      title: 'Reglas de oro para el examen',
      cards: [
        { title: 'Rabia', tag: '¿Qué animal?', kind: 'key', items: [
          { t: 'Perro o gato ubicable: observar 10 días', d: 'Si sigue sano, no se vacuna',
            say: 'Cerremos con las reglas de oro. En la rabia, perro o gato ubicable: se observa al animal diez días, y si sigue sano, no se vacuna al paciente.' },
          { t: 'Desconocido o vagabundo: vacunar', d: '5 dosis: días 0, 3, 7, 14 y 28',
            say: 'Animal desconocido o vagabundo: vacuna de inmediato, cinco dosis.' },
          { t: 'Murciélago: vacuna + inmunoglobulina', d: 'Siempre, aunque no haya herida',
            say: 'Murciélago: vacuna más inmunoglobulina, siempre, aunque no haya herida visible.' },
        ] },
        { title: 'Tétanos', tag: '¿Qué herida y cuántas dosis?', kind: 'alert', items: [
          { t: 'Limpia: > 10 años · sucia: > 5 años', d: 'Plazos para el refuerzo dT',
            say: 'En el tétanos, el refuerzo de dT se da si pasaron más de diez años en la herida limpia, o más de cinco en la sucia.' },
          { t: 'IGH-T: herida sucia + < 3 dosis', d: 'O esquema desconocido',
            say: 'Y la inmunoglobulina solo va con herida sucia y esquema incompleto o desconocido. Si te llevas una sola idea de hoy: en la rabia se pregunta por el animal, y en el tétanos por la herida y las dosis. La próxima clase vemos las infecciones asociadas a la atención de salud y las precauciones de aislamiento. Nos vemos en la próxima clase.' },
        ] },
      ],
    },
  ],

  pathway: {
    title: 'Paciente con una herida: rabia y tétanos',
    root: N('start', 'Paciente con una herida', 'Mordedura, corte o punción',
      'Llega un paciente con una herida. Tienes que pensar en dos profilaxis distintas: la antirrábica, si hubo un mamífero, y la antitetánica, siempre.',
      ['Mamífero', N('q', '¿Qué animal fue?', 'Ubicable · desconocido · murciélago',
        'Si hubo una mordedura o contacto con un mamífero, la pregunta es qué animal fue.',
        ['Perro o gato ubicable', N('ok', 'Observar al animal 10 días', 'Sano: no se vacuna',
          'Si es un perro o gato ubicable, se observa al animal por diez días; si sigue sano, no se vacuna. Si enferma, muere o desaparece, se vacuna.')],
        ['Desconocido o vagabundo', N('do', 'Vacuna antirrábica inmediata', '5 dosis: días 0, 3, 7, 14 y 28',
          'Si es desconocido o vagabundo, vacuna antirrábica inmediata, cinco dosis.')],
        ['Murciélago', N('alert', 'Vacuna + inmunoglobulina', 'Exposición grave siempre',
          'Si es un murciélago, cualquier contacto es exposición grave: vacuna completa más inmunoglobulina antirrábica.')])],
      ['Siempre', N('q', '¿Herida limpia o sucia?', 'Tierra, heces, saliva, punzante',
        'Y en toda herida evalúas el tétanos. Primero, si la herida es limpia o sucia.',
        ['Limpia', N('ok', 'dT si pasaron > 10 años', 'Sin inmunoglobulina',
          'Si es limpia y el esquema está completo, refuerzo de dT solo si pasaron más de diez años.')],
        ['Sucia', N('q', '¿Tiene 3 dosis o más?', 'Esquema completo',
          'Si es sucia, la pregunta es si tiene tres dosis o más.',
          ['SÍ', N('do', 'dT si pasaron > 5 años', 'Sin inmunoglobulina',
            'Con esquema completo, refuerzo de dT si pasaron más de cinco años, sin inmunoglobulina.')],
          ['NO o no sabe', N('alert', 'dT + IGH-T 250 UI', 'En sitios separados',
            'Con menos de tres dosis o antecedente desconocido, vacuna dT más inmunoglobulina antitetánica, doscientas cincuenta unidades, en sitios separados.')])])]),
  },
};
