// Clase 10.21 — guion docente escrito a mano (ver gastro-01.cjs para el formato).
// Fuente clínica: books/scripts/dataset_neurologia.cjs (neuro-21).
// Preguntas reales: banco real (classes/scripts/class_questions.cjs neuro-21 y --search).

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  id: 'neuro-21',
  tier: 3,
  slides: [
    {
      type: 'cover',
      subtitle: 'La inatención lo diagnostica, la causa se busca siempre y el fármaco es la excepción',
      say: 'Bienvenidos. Con esta clase entramos al bloque de geriatría, y partimos con el síndrome más preguntado de todos: el síndrome confusional agudo, o delirium. En el EUNACOM aparece casi en cada examen, y se responde con tres ideas: reconocerlo por la inatención, buscar siempre la causa que lo gatilló, y tratarlo primero sin fármacos. Partamos.',
    },

    {
      type: 'flow',
      kicker: 'Fisiopatología',
      title: '¿Por qué un adulto mayor se confunde?',
      nodes: [
        { id: 'neu', col: 0, row: 0, k: 'mech', t: 'Menos acetilcolina, más dopamina', s: 'Falla la neurotransmisión' },
        { id: 'inf', col: 0, row: 2, k: 'mech', t: 'Citoquinas inflamatorias', s: 'Infección, sepsis o cirugía' },
        { id: 'bhe', col: 1, row: 2, k: 'mech', t: 'Barrera hematoencefálica permeable', s: 'Neuroinflamación' },
        { id: 'pre', col: 2, row: 0, k: 'risk', t: 'Factores predisponentes', s: 'Edad > 75, demencia, fragilidad' },
        { id: 'pci', col: 2, row: 3, k: 'cause', t: 'Factor precipitante', s: 'Noxa aguda' },
        { id: 'del', col: 3, row: 1, k: 'alert', t: 'Delirium', s: 'Disfunción cerebral aguda y difusa' },
        { id: 'mor', col: 4, row: 1, k: 'risk', t: 'Duplica la mortalidad', s: 'Marcador de mal pronóstico' },
      ],
      edges: [
        { from: 'inf', to: 'bhe' }, { from: 'bhe', to: 'neu', label: 'altera' },
        { from: 'neu', to: 'del' }, { from: 'pre', to: 'del', label: 'vulnerabilidad' },
        { from: 'pci', to: 'del', label: 'gatilla' }, { from: 'del', to: 'mor' },
      ],
      steps: [
        { show: ['neu'], note: 'Hipoactividad colinérgica e hiperactividad dopaminérgica',
          say: 'Partamos por el mecanismo. El delirium es una claudicación aguda de la neurotransmisión cerebral. El modelo aceptado es una caída de la actividad colinérgica junto con un exceso de dopamina. Guarda este dato, porque explica por qué los fármacos anticolinérgicos lo desencadenan y por qué los antipsicóticos calman la agitación.' },
        { show: ['inf', 'bhe'], note: 'La inflamación sistémica llega al cerebro',
          say: 'En paralelo, una infección, una sepsis o una cirugía mayor liberan citoquinas inflamatorias. Estas citoquinas abren la barrera hematoencefálica, activan la microglía y producen neuroinflamación. Por eso una neumonía, que es un problema del pulmón, termina confundiendo al paciente.' },
        { show: ['pre'], note: 'Cerebro vulnerable: edad, demencia, fragilidad, polifarmacia',
          say: 'Ahora, la idea clínica clave: el modelo de vulnerabilidad. Hay factores predisponentes de base, como tener más de setenta y cinco años, una demencia previa, fragilidad, polifarmacia, un déficit auditivo o visual no corregido, o dependencia funcional.' },
        { show: ['pci', 'del'], note: 'A más vulnerabilidad, menos estímulo se necesita',
          say: 'Y sobre ese terreno actúa un factor precipitante agudo. Mientras más vulnerable es el cerebro, menos estímulo se necesita. En un paciente con demencia avanzada, basta un cambio de habitación, un fecaloma o una retención urinaria. En un adulto mayor sano y robusto, en cambio, se necesita algo grande, como un shock séptico o una hipoxia crítica.' },
        { show: ['mor'], note: 'No es psiquiátrico: es una descompensación sistémica',
          say: 'Por eso el delirium no es una enfermedad psiquiátrica. Es un síntoma de que algo sistémico se descompensó, y es un marcador de mal pronóstico: duplica la mortalidad intrahospitalaria. Afecta hasta a la mitad de los adultos mayores hospitalizados. Es una urgencia médica.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Diagnóstico',
      title: 'Criterios CAM: el diagnóstico es clínico',
      cards: [
        { title: 'Obligatorios', tag: 'Siempre los dos', kind: 'criteria', items: [
          { t: '1. Inicio agudo y fluctuante', d: 'Horas o días; peor en la noche',
            say: 'El diagnóstico del delirium es estrictamente clínico: no depende de exámenes ni de imágenes. Se hace con el Confusion Assessment Method, el CAM. El primer criterio es el inicio agudo y el curso fluctuante: un cambio brusco respecto de su estado basal, en horas o días, que empeora en la tarde y en la noche. Eso es el sundowning.' },
          { t: '2. Inatención', d: 'MUNDO al revés, meses en orden inverso',
            say: 'El segundo criterio es el eje de todo: la inatención. El paciente no logra fijar ni mantener la atención. Se pesquisa pidiéndole deletrear MUNDO al revés, decir los meses del año desde diciembre hacia enero, o contar de veinte a uno. Ojo, porque esto es lo que lo diferencia de la demencia.' },
        ] },
        { title: 'Más uno de estos', tag: '3 o 4', kind: 'key', items: [
          { t: '3. Pensamiento desorganizado', d: 'Incoherente, ideas ilógicas',
            say: 'A esos dos criterios obligatorios se suma al menos uno de los otros dos. El tercero es el pensamiento desorganizado: conversación incoherente, que salta de un tema a otro, con respuestas ilógicas.' },
          { t: '4. Conciencia alterada', d: 'De hipervigilante a letárgico',
            say: 'El cuarto es la alteración del nivel de conciencia: cualquier cosa que no sea la alerta normal, desde la hipervigilancia hasta la letargia o el estupor. La fórmula que tienes que memorizar es criterio uno, más criterio dos, más el tres o el cuatro.' },
        ] },
        { title: 'Subtipos motores', tag: 'Ojo en el examen', kind: 'alert', items: [
          { t: 'Hipoactivo: 50 %', d: 'El más frecuente y el más grave',
            say: 'Según la actividad motora hay tres subtipos. El hipoactivo es la mitad de los casos: el paciente está somnoliento, lento, callado. Es el más frecuente, el que más se pasa por alto, porque se confunde con depresión, y el de mayor mortalidad, por la inmovilidad, las aspiraciones y las úlceras por presión.' },
          { t: 'Hiperactivo y mixto: 25 % cada uno', d: 'Agitación y alucinaciones visuales',
            say: 'El hiperactivo, un cuarto de los casos, es el que todos reconocen: agitación, alucinaciones visuales, hostilidad. Y el mixto, el otro cuarto, alterna entre ambos. No asumas que un delirium siempre es un paciente agitado.' },
        ] },
      ],
    },

    {
      type: 'table',
      kicker: 'Diagnóstico diferencial',
      title: 'Delirium, demencia o depresión',
      head: ['Parámetro', 'Delirium', 'Demencia', 'Depresión'],
      rows: [
        { cells: ['Inicio', 'Agudo, fechable', 'Insidioso, meses a años', 'Subagudo, semanas'],
          say: 'Esta comparación es de las competencias más evaluadas. Empieza por el inicio: el delirium es agudo, la familia te dice el día exacto. La demencia es insidiosa, de meses a años. Y la depresión es subaguda, de semanas, muchas veces tras un duelo.' },
        { cells: ['Curso', 'Fluctuante, peor de noche', 'Estable, progresivo', 'Constante, peor en la mañana'],
          say: 'El curso: el delirium fluctúa y empeora de noche. La demencia es estable y lentamente progresiva. La depresión es constante, y suele ser peor en la mañana al despertar.' },
        { cells: ['Atención', 'Alterada desde el inicio', 'Conservada hasta fases avanzadas', 'Conservada; poco esfuerzo'],
          say: 'La atención es la clave. En el delirium está alterada desde el comienzo. En la demencia se conserva hasta fases avanzadas. Y en la depresión también se conserva, aunque el paciente parece no esforzarse.' },
        { cells: ['Conciencia', 'Alterada', 'Lúcida', 'Alerta, enlentecido'],
          say: 'El nivel de conciencia está alterado solo en el delirium. El paciente con demencia está lúcido, y el deprimido está alerta, aunque lento.' },
        { cells: ['Memoria', 'Falla por inatención', 'Olvido reciente, confabula', '"No sé"; mejora si se insiste'],
          say: 'En la memoria, el deprimido responde "no sé" y abandona rápido, pero mejora si insistes. Por eso se habla de pseudodemencia depresiva.' },
        { cells: ['Percepción', 'Alucinaciones visuales vívidas', 'Ausentes al inicio (salvo Lewy)', 'Raras; ideas de culpa o ruina'],
          say: 'Las alucinaciones visuales vívidas son típicas del delirium. En la demencia no aparecen al inicio, salvo en la demencia por cuerpos de Lewy.' },
        { cells: ['Pronóstico', 'Reversible si se corrige la causa', 'Irreversible, progresiva', 'Reversible con tratamiento'],
          say: 'Y el pronóstico: el delirium es reversible si corriges la causa a tiempo. Pero recuerda que la demencia es el principal factor predisponente, así que el delirium sobre una demencia es muy frecuente.' },
      ],
    },

    {
      type: 'points',
      kicker: 'Etiología',
      title: 'I WATCH DEATH: ningún delirium es idiopático',
      cards: [
        { title: 'Lo más frecuente', tag: 'Buscar primero', kind: 'key', items: [
          { t: 'Infección', d: 'Urinaria y neumonía, los dos focos clásicos',
            say: 'Una vez que el CAM es positivo, el objetivo urgente es encontrar y corregir el gatillante. Ningún delirium es idiopático. La mnemotecnia es I WATCH DEATH. La I es infección, y los dos focos más comunes son la infección urinaria y la neumonía.' },
          { t: 'Metabólico y abstinencia', d: 'Hipoglicemia, sodio, calcio, uremia; alcohol',
            say: 'La W es la abstinencia de alcohol, benzodiacepinas u opioides. La A son las alteraciones metabólicas: hipoglicemia, deshidratación, hiponatremia o hipernatremia, hipercalcemia, uremia o falla hepática.' },
          { t: 'Hipoxia, SNC y trauma', d: 'IAM silente, ACV, hematoma subdural',
            say: 'Después vienen la hipoxia o la hipercapnia, por insuficiencia cardíaca, EPOC o un infarto silente; las causas intracraneales, como el ACV, la meningitis o un estado epiléptico no convulsivo; y el trauma, como una fractura no pesquisada o un hematoma subdural tras una caída menor.' },
          { t: 'Déficit y endocrino', d: 'Tiamina, B12, tiroides, suprarrenal',
            say: 'También las deficiencias vitamínicas, como la de tiamina, que produce la encefalopatía de Wernicke, o la de vitamina B doce; y las endocrinopatías, como la tormenta tiroidea, el coma mixedematoso o la insuficiencia suprarrenal.' },
        ] },
        { title: 'Fármacos', tag: 'La causa más prevenible', kind: 'pharma', items: [
          { t: 'Anticolinérgicos', d: 'Clorfenamina, tricíclicos, pargeverina',
            say: 'La otra A son los fármacos, la causa iatrogénica más prevenible. Recuerda el mecanismo: si falta acetilcolina, los anticolinérgicos empeoran todo. Por eso ojo con la clorfenamina, los antidepresivos tricíclicos y antiespasmódicos como la pargeverina.' },
          { t: 'Benzodiacepinas y opioides', d: 'También corticoides, digoxina, anticonvulsivantes',
            say: 'Y también las benzodiacepinas, los opioides, los corticoides sistémicos, la digoxina y los anticonvulsivantes. Siempre revisa la lista de medicamentos.' },
        ] },
        { title: 'Causas mecánicas', tag: 'Regla de oro', kind: 'alert', items: [
          { t: 'Globo vesical', d: 'Sonda Foley: se resuelve en minutos',
            say: 'Y la regla de oro del examen: la última H es heces y orina. Hay dos causas no infecciosas muy frecuentes que se pasan por alto. La primera es el globo vesical, la retención aguda de orina. Una sonda Foley descompresiva resuelve el delirium de inmediato, sin ningún psicofármaco.' },
          { t: 'Fecaloma', d: 'Tacto rectal y evacuación',
            say: 'La segunda es el fecaloma. Por eso, en todo adulto mayor confuso, palpa el hipogastrio y haz un tacto rectal antes de pensar en fármacos.' },
        ] },
      ],
    },

    {
      type: 'points',
      kicker: 'Tratamiento',
      title: 'Primera línea: medidas no farmacológicas',
      cards: [
        { title: 'Modelo HELP', tag: 'Siempre, en todos', kind: 'normal', items: [
          { t: 'Reorientar y acompañar', d: 'Reloj, calendario, familia en la sala',
            say: 'El tratamiento tiene dos ejes, y el primero es obligatorio: las medidas no farmacológicas multicomponente, del modelo HELP. Es la única intervención con evidencia sólida de reducir la duración y la gravedad del delirium. Parte por reorientar con calma, con relojes, calendarios, luz natural, y la familia acompañando en la sala.' },
          { t: 'Lentes y audífonos', d: 'Devolver la aferencia sensorial',
            say: 'Después, devolverle sus lentes y sus audífonos. Un paciente que no ve ni oye bien pierde las referencias y se desorienta más.' },
          { t: 'Proteger el sueño', d: 'Luz de día, oscuridad y silencio de noche',
            say: 'Luego, cuidar el sueño: luz y actividad de día, y de noche apagar las luces, reducir el ruido y evitar controles de signos vitales innecesarios.' },
          { t: 'Hidratar, movilizar, retirar sondas', d: 'Movilización precoz fuera de la cama',
            say: 'Y finalmente, hidratación oral, sacarlo de la cama lo antes posible, y retirar las sondas y vías venosas que no sean necesarias.' },
        ] },
        { title: 'Sujeción mecánica', tag: 'Proscrita', kind: 'alert', items: [
          { t: 'No previene caídas', d: 'Agrava la agitación y perpetúa el cuadro',
            say: 'Y una prohibición que se pregunta: las sujeciones mecánicas. Parecen prudentes, pero no previenen caídas ni retiros de tubos. Al contrario, aumentan la agitación y perpetúan el delirium.' },
          { t: 'Complicaciones graves', d: 'Isquemia, asfixia, rabdomiolisis',
            say: 'Además producen isquemia de extremidades, asfixia posicional y rabdomiolisis. Si una alternativa dice contención física, desconfía.' },
        ] },
      ],
    },

    {
      type: 'flow',
      kicker: 'Farmacoterapia de rescate',
      title: '¿Cuándo y con qué se seda?',
      nodes: [
        { id: 'agi', col: 0, row: 2, k: 'q', t: '¿Agitación con riesgo?', s: 'Para sí, terceros o soporte vital' },
        { id: 'no', col: 1, row: 0, k: 'good', t: 'Sin fármacos', s: 'Solo causa + medidas HELP' },
        { id: 'hal', col: 2, row: 1, k: 'good', t: 'Haloperidol 0,5–1 mg', s: 'VO o IM; máx. 2–3 mg/día' },
        { id: 'qtc', col: 3, row: 1, k: 'risk', t: 'Controlar QTc', s: 'Riesgo de torsades de pointes' },
        { id: 'par', col: 2, row: 3, k: 'refer', t: 'Parkinson o Lewy', s: 'Quetiapina 12,5–25 mg' },
        { id: 'dt', col: 3, row: 4, k: 'alert', t: 'Delirium tremens', s: 'Benzodiacepinas: única excepción' },
        { id: 'bzd', col: 4, row: 2, k: 'trap', t: 'Benzodiacepinas en delirium común', s: 'Contraindicadas' },
      ],
      edges: [
        { from: 'agi', to: 'no', label: 'no' }, { from: 'agi', to: 'hal', label: 'sí' },
        { from: 'hal', to: 'qtc' }, { from: 'agi', to: 'par', label: 'sí + parkinsonismo' },
        { from: 'agi', to: 'dt', label: 'abstinencia' }, { from: 'hal', to: 'bzd', label: 'nunca' },
      ],
      steps: [
        { show: ['agi'], note: 'Los antipsicóticos no previenen ni curan el delirium',
          say: 'El segundo eje es el fármaco de rescate, y aquí el mensaje es restrictivo. Los antipsicóticos no previenen ni curan el delirium, ni bajan la mortalidad. Se usan solo si hay agitación grave que pone en riesgo al paciente o a otros, o que impide un tratamiento vital, como cuando intenta sacarse el tubo.' },
        { show: ['no'], note: 'Sin agitación peligrosa: no se medica',
          say: 'Si no hay agitación peligrosa, no se medica: se trata la causa y se aplican las medidas no farmacológicas.' },
        { show: ['hal'], note: 'Dosis mínima, por el menor tiempo',
          say: 'Si hay que sedar, el fármaco de elección es el haloperidol. En el adulto mayor se parte con medio a un miligramo, oral o intramuscular, cada ocho a doce horas, con un máximo de dos a tres miligramos al día. Casi no tiene efecto anticolinérgico, y no deprime la respiración.' },
        { show: ['qtc'], note: 'Electrocardiograma basal',
          say: 'Pero prolonga el intervalo QT corregido, así que pide un electrocardiograma basal, por el riesgo de torsades de pointes. Como alternativas atípicas están la quetiapina, la risperidona y la olanzapina, en dosis bajas.' },
        { show: ['par'], note: 'Haloperidol contraindicado en Parkinson y Lewy',
          say: 'Regla de oro: en la enfermedad de Parkinson y en la demencia por cuerpos de Lewy, el haloperidol está contraindicado, porque desencadena parkinsonismo grave y síndrome neuroléptico maligno. Ahí el fármaco de elección es la quetiapina, de doce coma cinco a veinticinco miligramos, o la clozapina.' },
        { show: ['bzd'], note: 'Sedan, deprimen y perpetúan el cuadro',
          say: 'Y la trampa clásica: las benzodiacepinas. En el delirium geriátrico común están contraindicadas, porque sedan de más, deprimen la respiración, pueden desinhibir de forma paradójica y perpetúan la confusión.' },
        { show: ['dt'], note: 'Abstinencia de alcohol o sedantes',
          say: 'La única excepción es el delirium tremens, o la abstinencia de benzodiacepinas. Ahí son el tratamiento de primera línea, porque compensan la hiperexcitabilidad de rebote: diazepam de cinco a diez miligramos endovenoso lento, o lorazepam de uno a dos miligramos.' },
      ],
    },

    {
      type: 'pathway',
      intro: 'Juntemos todo en un árbol de decisión, tal como lo razonas frente al paciente confuso.',
    },

    {
      type: 'table',
      kicker: 'Trampas EUNACOM',
      title: 'Las decisiones que más se preguntan',
      head: ['Escenario', 'Conducta correcta', 'Error frecuente'],
      rows: [
        { cells: ['Anciano hospitalizado, agitado de noche y tranquilo de día', 'Delirium', 'Demencia o psicosis'],
          say: 'Repasemos las trampas. El adulto mayor hospitalizado que se agita en la noche y amanece tranquilo tiene un delirium. El error es rotularlo como demencia o como un cuadro psicótico.' },
        { cells: ['Alucinaciones o ideas delirantes de inicio agudo', 'Delirium', 'Esquizofrenia o trastorno delirante'],
          say: 'Si hay alucinaciones o ideas delirantes de inicio agudo, sigue siendo un delirium. La esquizofrenia y el trastorno delirante son cuadros crónicos.' },
        { cells: ['Delirium con masa hipogástrica mate', 'Sonda Foley', 'Antipsicótico o contención'],
          say: 'Delirium con una masa hipogástrica mate a la percusión: es un globo vesical, y la conducta es la sonda Foley. Medicar o contener sin vaciar la vejiga es mala práctica.' },
        { cells: ['Agitación grave con riesgo', 'Haloperidol en dosis baja', 'Benzodiacepinas'],
          say: 'Agitación grave con riesgo en un delirium común: haloperidol en dosis baja. La benzodiacepina es el distractor más tentador, y está contraindicada.' },
        { cells: ['Delirium en Parkinson o Lewy', 'Quetiapina', 'Haloperidol'],
          say: 'Si el paciente tiene Parkinson o demencia por cuerpos de Lewy, quetiapina. El haloperidol, aquí, es el error.' },
        { cells: ['Abstinencia alcohólica con alucinaciones', 'Benzodiacepinas + tiamina', 'Haloperidol solo'],
          say: 'Y en la abstinencia alcohólica con temblor y alucinaciones, el delirium tremens, se usan benzodiacepinas. Es la única vez que las eliges.' },
      ],
    },

    {
      type: 'quiz',
      kicker: 'Caso clínico',
      title: 'Caso clínico',
      stem: 'Hombre de 79 años, autovalente, en su 2.º día postoperatorio de artroplastia de cadera. En la madrugada inicia bruscamente inquietud extrema, dice que "hay animales debajo de la cama", intenta retirarse la vía venosa y no reconoce a su hija. PA 145/85, FC 98, afebril, SatO₂ 95 %. No logra deletrear MUNDO al revés. Se palpa una masa hipogástrica dolorosa, mate a la percusión. Herida limpia.',
      question: '¿Cuál es la conducta inmediata más adecuada?',
      options: [
        { letter: 'A', text: 'Haloperidol 1 mg intramuscular' },
        { letter: 'B', text: 'Lorazepam 1 mg endovenoso' },
        { letter: 'C', text: 'Instalar sonda Foley descompresiva' },
        { letter: 'D', text: 'Sujeción mecánica de las cuatro extremidades' },
        { letter: 'E', text: 'Solicitar TAC de cerebro urgente' },
      ],
      correct: 'C',
      explanation: 'Delirium hiperactivo (CAM positivo) gatillado por una retención aguda de orina, frecuente tras anestesia neuroaxial y opioides. La sonda Foley revierte la agitación en minutos, junto con medidas no farmacológicas. Medicar o contener sin drenar el globo vesical es mala práctica; las benzodiacepinas están contraindicadas.',
      say: {
        stem: 'Vamos al caso. Hombre de setenta y nueve años, autovalente, en el segundo día después de una artroplastia de cadera. En la madrugada se pone muy inquieto, dice que hay animales debajo de la cama, intenta sacarse la vía venosa y no reconoce a su hija. Está afebril y saturando bien. No logra deletrear MUNDO al revés. Y en el hipogastrio se palpa una masa dolorosa, mate a la percusión.',
        question: '¿Cuál es la conducta inmediata más adecuada?',
        options: 'Las opciones son: haloperidol intramuscular, lorazepam endovenoso, instalar una sonda Foley, sujeción de las cuatro extremidades, o un TAC de cerebro urgente. Piénsalo.',
        answer: 'La respuesta es la C. Primero, esto es un delirium: inicio agudo, inatención, alucinaciones. Y la masa hipogástrica mate es un globo vesical, muy frecuente después de una anestesia raquídea y de los opioides. La sonda Foley resuelve la agitación en minutos. El distractor tentador es el haloperidol: sería el fármaco correcto si hubiera que sedar, pero no antes de corregir la causa. El lorazepam y la sujeción están proscritos.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2013 · Pregunta 68',
      stem: 'Un paciente de 80 años, autovalente, inicia cuadro de compromiso del estado general, tos y expectoración mucopurulenta, se realiza radiografía de tórax en donde se comprueba diagnóstico de neumonía basal derecha por lo que se hospitaliza para el tratamiento. Durante la hospitalización en la noche el paciente se agita, se saca sonda foley y vías venosas, durante la mañana está tranquilo.',
      question: 'El diagnóstico más probable es:',
      options: [
        { letter: 'A', text: 'Síndrome confusional agudo' },
        { letter: 'B', text: 'Delirio' },
        { letter: 'C', text: 'Alzheimer' },
        { letter: 'D', text: 'Meningitis bacteriana' },
        { letter: 'E', text: 'Demencia frontotemporal' },
      ],
      correct: 'A',
      explanation: 'Inicio agudo en contexto de una neumonía, agitación nocturna y lucidez en la mañana: curso fluctuante típico del síndrome confusional agudo (delirium). "Delirio" en Chile designa la pérdida del juicio de realidad de los cuadros psicóticos, no el delirium.',
      say: {
        stem: 'Ahora preguntas reales. La primera es del EUNACOM de julio de dos mil trece. Paciente de ochenta años, autovalente, hospitalizado por una neumonía basal derecha. En la noche se agita, se saca la sonda Foley y las vías venosas, y en la mañana está tranquilo.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones son: síndrome confusional agudo, delirio, Alzheimer, meningitis bacteriana, o demencia frontotemporal. Piénsalo.',
        answer: 'Es la A, síndrome confusional agudo. Tiene todo: un adulto mayor, un gatillante infeccioso, y un curso fluctuante que empeora de noche. Y fíjate en la trampa de palabras: delirio no es lo mismo que delirium. En Chile, delirio se usa para la pérdida del juicio de realidad de los cuadros psicóticos. El delirium es el síndrome confusional agudo.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2019 · Pregunta 139',
      stem: 'Un paciente de 84 años presenta desgarro mucopurulento, desde hace 4 días, por lo que se hospitaliza y se inicia tratamiento antibiótico. Evoluciona con dificultades para reconocer a sus hijos y esposa, a quienes confunde con su mamá y hermanos ya fallecidos. Se molesta cuando lo contrarían e incluso llegó a agredir físicamente a uno de sus hijos.',
      question: 'El diagnóstico más probable es:',
      options: [
        { letter: 'A', text: 'Enfermedad de Alzheimer' },
        { letter: 'B', text: 'Trastorno delirante' },
        { letter: 'C', text: 'Depresión psicótica' },
        { letter: 'D', text: 'Esquizofrenia' },
        { letter: 'E', text: 'Delírium' },
      ],
      correct: 'E',
      explanation: 'Desorientación y compromiso de conciencia de inicio agudo, secundario a una infección bacteriana: delirium. Las alucinaciones y las ideas delirantes son frecuentes en el delirium; la esquizofrenia y el trastorno delirante son cuadros crónicos.',
      say: {
        stem: 'Segunda pregunta, del EUNACOM de julio de dos mil diecinueve. Paciente de ochenta y cuatro años hospitalizado por una infección respiratoria, con antibióticos. Evoluciona sin reconocer a su familia, confunde a sus hijos con sus padres y hermanos fallecidos, se irrita y llega a agredir a uno de sus hijos.',
        question: '¿Cuál es el diagnóstico más probable?',
        options: 'Las opciones son: Alzheimer, trastorno delirante, depresión psicótica, esquizofrenia, o delírium. Piénsalo.',
        answer: 'Es la E, delírium, secundario a la infección. Aquí la trampa es que el paciente tiene síntomas que suenan psicóticos. Pero las alucinaciones y las ideas delirantes son frecuentes en el delirium. La esquizofrenia empieza en la adolescencia y es crónica, y el trastorno delirante tiene un delirio sistematizado de más de un mes. Lo agudo, en un anciano con infección, es delirium.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2024 · Pregunta 168',
      stem: 'Una paciente de 78 años con diagnóstico de enfermedad de Alzheimer es hospitalizada tras desorientarse y agredir a sus cuidadores. En el examen mental se encuentra desorientada en tiempo y espacio, no puede decir los días de la semana en orden inverso y no es capaz de recordar tres palabras que se le dicen en voz alta. Dice ver a su padre en la habitación y, tras el ingreso al hospital, comienza a gritar, exigiendo que la suelten y que se quiere ir del hospital.',
      question: '¿Cuál es el fármaco de elección para su manejo inicial?',
      options: [
        { letter: 'A', text: 'Clonazepam' },
        { letter: 'B', text: 'Carbamazepina' },
        { letter: 'C', text: 'Haloperidol' },
        { letter: 'D', text: 'Mirtazapina' },
        { letter: 'E', text: 'Diazepam' },
      ],
      correct: 'C',
      explanation: 'Delirium sobreimpuesto a demencia (inatención: no dice los días en orden inverso; alucinaciones visuales; agitación). Además de tratar la causa, la agitación grave se maneja con haloperidol en dosis bajas (0,5–1 mg VO o IM). Las benzodiacepinas están contraindicadas.',
      say: {
        stem: 'Tercera pregunta, del EUNACOM de julio de dos mil veinticuatro. Mujer de setenta y ocho años con Alzheimer, hospitalizada tras desorientarse y agredir a sus cuidadores. No puede decir los días de la semana en orden inverso, dice ver a su padre en la habitación, y ya hospitalizada grita que la suelten y que se quiere ir.',
        question: '¿Cuál es el fármaco de elección para su manejo inicial?',
        options: 'Las opciones son: clonazepam, carbamazepina, haloperidol, mirtazapina o diazepam. Piénsalo.',
        answer: 'Es la C, haloperidol. Es un delirium sobre una demencia: fíjate en la inatención, que es no poder decir los días al revés, y en la alucinación visual. La agitación es grave, así que corresponde haloperidol en dosis baja, además de buscar la causa. El distractor tentador son las benzodiacepinas, el clonazepam o el diazepam, que están contraindicadas porque empeoran la confusión.',
      },
    },

    {
      type: 'quiz',
      kicker: 'Pregunta real EUNACOM',
      title: 'EUNACOM Julio 2025 · Pregunta 103',
      stem: 'Paciente de 55 años alcohólico crónico, 48 horas después de dejar de beber presenta agitación severa, alucinaciones visuales de insectos, temblor generalizado, taquicardia 120 lpm, sudoración y fiebre 38°C.',
      question: '¿Cuál es el diagnóstico y tratamiento?',
      options: [
        { letter: 'A', text: 'Delirium tremens: diazepam EV + tiamina + corrección hidrolectrolítica' },
        { letter: 'B', text: 'Psicosis alcohólica: haloperidol' },
        { letter: 'C', text: 'Meningoencefalitis: antibióticos EV' },
        { letter: 'D', text: 'Hipoglicemia: glucosa EV en bolo' },
        { letter: 'E', text: 'ACV isquémico: tPA' },
      ],
      correct: 'A',
      explanation: 'Abstinencia alcohólica grave a las 48–72 horas del cese, con hiperactividad autonómica y alucinaciones: delirium tremens. Es la única indicación de benzodiacepinas en el delirium (diazepam o lorazepam), junto con tiamina y corrección hidroelectrolítica.',
      say: {
        stem: 'Y la última, del EUNACOM de julio de dos mil veinticinco. Hombre de cincuenta y cinco años, alcohólico crónico. Cuarenta y ocho horas después de dejar de beber presenta agitación grave, alucinaciones visuales de insectos, temblor, taquicardia de ciento veinte, sudoración y fiebre de treinta y ocho grados.',
        question: '¿Cuál es el diagnóstico y el tratamiento?',
        options: 'Las opciones son: delirium tremens con diazepam, tiamina y corrección hidroelectrolítica; psicosis alcohólica con haloperidol; meningoencefalitis con antibióticos; hipoglicemia con glucosa; o ACV con trombolisis. Piénsalo.',
        answer: 'Es la A, delirium tremens. Es la excepción que te pedí recordar: aquí las benzodiacepinas son el tratamiento de elección, porque compensan la hiperexcitabilidad de rebote. Se suma la tiamina, para prevenir la encefalopatía de Wernicke. El distractor es el haloperidol: sirve en el delirium común, pero en la abstinencia no trata la causa.',
      },
    },

    {
      type: 'points',
      kicker: 'Cierre',
      title: 'Reglas de oro para el examen',
      cards: [
        { title: 'Diagnóstico', tag: 'CAM', kind: 'criteria', items: [
          { t: 'Agudo + inatención + 3 o 4', d: 'Clínico, sin exámenes',
            say: 'Cerremos con las reglas de oro. El delirium se diagnostica en la cama del paciente con el CAM: inicio agudo y fluctuante, inatención, y pensamiento desorganizado o conciencia alterada.' },
          { t: 'El hipoactivo es el más frecuente', d: 'Y el de mayor mortalidad',
            say: 'El subtipo hipoactivo es el más frecuente y el más grave, y es el que se pasa por alto.' },
        ] },
        { title: 'Causa', tag: 'Siempre se busca', kind: 'key', items: [
          { t: 'I WATCH DEATH', d: 'Infección urinaria y neumonía primero',
            say: 'Siempre hay una causa. Busca primero infección urinaria y neumonía, y revisa los fármacos, sobre todo los anticolinérgicos.' },
          { t: 'Globo vesical y fecaloma', d: 'Antes de cualquier fármaco',
            say: 'Y antes de indicar cualquier psicofármaco, descarta el globo vesical y el fecaloma.' },
        ] },
        { title: 'Tratamiento', tag: 'Primero sin fármacos', kind: 'pharma', items: [
          { t: 'Medidas HELP, sin sujeción', d: 'Reorientar, lentes, audífonos, familia',
            say: 'El tratamiento de base son las medidas no farmacológicas, y la sujeción mecánica está proscrita.' },
          { t: 'Haloperidol solo si hay riesgo', d: 'Quetiapina en Parkinson; BZD solo en abstinencia',
            say: 'El haloperidol en dosis baja queda para la agitación con riesgo; en Parkinson y Lewy, quetiapina; y las benzodiacepinas, solo en la abstinencia. Si te llevas una sola idea de hoy: el delirium es un síntoma, y lo que lo cura es encontrar la causa. En la próxima clase seguimos con la fragilidad y la valoración geriátrica integral. Nos vemos en la próxima clase.' },
        ] },
      ],
    },
  ],

  pathway: {
    title: 'Adulto mayor con confusión aguda',
    root: N('start', 'Confusión aguda en adulto mayor', 'Cambio brusco del estado mental',
      'Adulto mayor que cambia bruscamente su estado mental. Lo primero es confirmar si es un delirium, y para eso usas el CAM.',
      ['', N('q', '¿CAM positivo?', 'Agudo + inatención + 3 o 4',
        '¿Hay inicio agudo y fluctuante, inatención, y además pensamiento desorganizado o conciencia alterada?',
        ['NO', N('refer', 'Otra causa', 'Demencia o depresión',
          'Si la atención está conservada y el curso es lento, piensa en demencia o en depresión, y evalúalas por su lado.')],
        ['SÍ', N('do', 'Buscar la causa', 'I WATCH DEATH',
          'Si el CAM es positivo, es un delirium, y la prioridad es buscar la causa con I WATCH DEATH: infección, metabólico, hipoxia, fármacos y el resto.',
          ['', N('q', '¿Globo vesical o fecaloma?', 'Palpar hipogastrio y tacto rectal',
            'Antes que nada, palpa el hipogastrio y haz un tacto rectal.',
            ['SÍ', N('ok', 'Sonda Foley o evacuación', 'Resuelve en minutos',
              'Si hay globo vesical, sonda Foley; si hay fecaloma, evacuación rectal. El delirium suele resolverse en minutos.')],
            ['NO', N('do', 'Tratar la causa + HELP', 'Sin sujeción mecánica',
              'Si no, tratas la causa que encontraste y aplicas las medidas no farmacológicas en todos los pacientes, sin sujeción.',
              ['', N('q', '¿Agitación con riesgo?', 'Para sí, terceros o soporte vital',
                '¿La agitación pone en peligro al paciente, a otros, o un tratamiento vital?',
                ['NO', N('ok', 'Sin fármacos', 'Mantener medidas',
                  'Si no, no se medica. Sigues con las medidas y el tratamiento de la causa.')],
                ['SÍ', N('alert', 'Haloperidol dosis baja', 'Quetiapina en Parkinson o Lewy',
                  'Si hay riesgo, haloperidol en dosis baja, con control del QT. En Parkinson o demencia por cuerpos de Lewy, quetiapina.')],
                ['Abstinencia', N('alert', 'Benzodiacepinas', 'Delirium tremens + tiamina',
                  'Y si es una abstinencia alcohólica, el delirium tremens, la excepción: benzodiacepinas y tiamina.')])])])])])]),
  },
};
