// Árboles de decisión clínica de Gastroenterología, derivados de books/scripts/dataset_gastroenterologia.cjs.
// Nodo: k = start | q (pregunta) | do (examen/acción) | ok (manejo resolutivo) | refer (derivar/especialista) | alert (urgencia)
// t = etiqueta corta, s = detalle de una línea, say = explicación hablada (también se muestra como razonamiento).
// kids = [[etiquetaDeFlecha, nodo], ...]; una sola hija sin etiqueta usa ['', nodo].

const N = (k, t, s, say, ...kids) => ({ k, t, s, say, kids });

module.exports = {
  'gastro-01': {
    title: 'ERGE y Esófago de Barrett: ¿cuándo endoscopiar?',
    root: N('start', 'Pirosis y regurgitación', 'Sospecha de reflujo gastroesofágico',
      'Partimos del paciente que consulta por pirosis y regurgitación ácida. Antes de indicar cualquier fármaco, la primera pregunta del examen es siempre la misma.',
      ['', N('q', '¿Signos de alarma?', 'Disfagia · baja de peso · anemia · HDA · ≥ 50 años · pirosis > 5 años',
        '¿Tiene signos de alarma? Disfagia, odinofagia, baja de peso, anemia, hemorragia, síntomas que lo despiertan, inicio después de los cincuenta años o pirosis de más de cinco años. Cualquiera de ellos cambia la conducta.',
        ['SÍ', N('alert', 'Endoscopía digestiva alta', 'Con biopsias, sin subir el IBP a ciegas',
          'Si hay alarma, la conducta es endoscopía digestiva alta con biopsias. La trampa del examen es duplicar el omeprazol sin estudiar: eso retrasa el diagnóstico de un cáncer.',
          ['', N('q', 'Barrett: ¿hay displasia?', 'Barrett = metaplasia intestinal en la biopsia',
            'Si la biopsia muestra metaplasia intestinal, es esófago de Barrett. Lo que decide la conducta no es la metaplasia, sino la displasia.',
            ['NO', N('ok', 'IBP + vigilancia endoscópica', 'La cirugía NO está indicada',
              'Barrett sin displasia: inhibidor de la bomba de protones continuo y endoscopía de vigilancia. Operar solo por la metaplasia es una respuesta incorrecta clásica.')],
            ['SÍ', N('refer', 'Tratamiento endoscópico', 'Bajo grado: ablación · Alto grado: resección',
              'Con displasia de bajo grado se indica ablación endoscópica; con displasia de alto grado, resección endoscópica o esofagectomía. Se deriva al especialista.')])])],
        ['NO', N('q', '¿Clínica típica?', 'Pirosis + regurgitación en < 50 años',
          'Sin alarma, miramos la presentación. ¿Es típica, con pirosis y regurgitación en un paciente joven, o atípica, con tos crónica, disfonía o dolor torácico?',
          ['SÍ', N('ok', 'Prueba con IBP 4–8 semanas', 'Omeprazol en ayunas, 30–60 min antes del desayuno',
            'Cuadro típico sin alarma: el diagnóstico es clínico. Indicamos omeprazol en ayunas, treinta a sesenta minutos antes del desayuno, por cuatro a ocho semanas, más medidas generales. La respuesta confirma el diagnóstico.')],
          ['NO', N('do', 'pH-metría de 24 horas', 'Clínica atípica o duda diagnóstica',
            'Si la clínica es atípica o hay duda diagnóstica, el patrón de referencia es la pH-metría esofágica de veinticuatro horas. También se usa antes de una cirugía antirreflujo.')])])]),
  },

  'gastro-02': {
    title: 'Dispepsia y úlcera péptica: estudio y erradicación',
    root: N('start', 'Dispepsia / epigastralgia', 'Urente, alivia con la comida',
      'Paciente con epigastralgia urente que alivia con la comida. Ojo: la misma clínica la dan la úlcera, el cáncer gástrico y la dispepsia funcional.',
      ['', N('q', '¿Alarma o edad ≥ 40 años?', 'Baja de peso · anemia · vómitos · HDA',
        '¿Tiene signos de alarma o cuarenta años o más? Esa es la puerta de entrada a la endoscopía.',
        ['SÍ', N('alert', 'EDA con biopsias', 'Confirma la úlcera y descarta cáncer',
          'Se solicita endoscopía digestiva alta con biopsias: confirma la úlcera y descarta un cáncer gástrico. En la biopsia además buscamos Helicobacter pylori con test de ureasa.',
          ['', N('q', '¿Úlcera duodenal o gástrica?', 'Define a quién se erradica y cómo se controla',
            'Ahora la pregunta clave: ¿la úlcera es duodenal o gástrica? De eso depende cómo erradicamos y cómo controlamos.',
            ['Duodenal', N('ok', 'Erradicar H. pylori siempre', 'Control: antígeno fecal o test del aliento',
              'Toda úlcera duodenal se erradica, aunque el test salga negativo, porque los falsos negativos son frecuentes. Primera línea: IBP más amoxicilina y claritromicina por catorce días. Control a las cuatro semanas con antígeno fecal o test del aliento.')],
            ['Gástrica', N('refer', 'Erradicar si H. pylori (+)', 'Biopsia del borde + EDA de control',
              'En la úlcera gástrica se erradica si el Helicobacter es positivo, y siempre se controla con una nueva endoscopía para verificar cicatrización y descartar cáncer.')])])],
        ['NO', N('ok', 'Buscar H. pylori y AINE', 'Dispepsia funcional exige EDA normal',
          'Sin alarma y bajo los cuarenta, buscamos las dos causas: Helicobacter pylori y los antiinflamatorios. Recuerda que la dispepsia funcional es un diagnóstico de exclusión que requiere una endoscopía normal.')])]),
  },

  'gastro-03': {
    title: 'Disfagia: ¿obstrucción o trastorno motor?',
    root: N('start', 'Disfagia', 'Dificultad para tragar',
      'Paciente con disfagia. Con dos preguntas clínicas ya sabes qué examen pedir.',
      ['', N('q', '¿Disfagia alta + halitosis?', 'Regurgitación de comida no digerida',
        'Primero: ¿la disfagia es alta, con halitosis marcada y regurgitación de comida sin digerir?',
        ['SÍ', N('refer', 'Esofagograma con bario', 'Divertículo de Zenker → cirugía',
          'Eso es un divertículo de Zenker. El examen es el esofagograma con bario, no la endoscopía ni la manometría, y el tratamiento es quirúrgico.')],
        ['NO', N('q', '¿Sólidos → líquidos, progresiva?', 'Lógica vs ilógica',
          'Si no, preguntamos el patrón. ¿Empezó con sólidos y progresó a líquidos? Eso es disfagia lógica. ¿Afecta a los líquidos desde el inicio y fluctúa? Eso es ilógica.',
          ['Lógica', N('alert', 'EDA + biopsia', 'Descartar cáncer de esófago',
            'Disfagia lógica significa obstrucción mecánica que crece. Hay que descartar cáncer de esófago, sobre todo con baja de peso: endoscopía digestiva alta con biopsia.')],
          ['Ilógica', N('do', 'Manometría esofágica', 'Trastorno motor',
            'Disfagia ilógica es un problema del músculo, no un tumor. El examen de elección es la manometría esofágica.',
            ['', N('q', '¿Pirosis intensa + Raynaud?', 'Calcinosis, telangiectasias',
              '¿Se acompaña de pirosis intensa, fenómeno de Raynaud o calcinosis?',
              ['SÍ', N('refer', 'Esclerodermia (CREST)', 'Anti-Scl-70 · anticentrómero',
                'Eso es esclerodermia: trastorno motor con reflujo ácido grave. Se piden anticuerpos anti Scl-70 y anticentrómero.')],
              ['NO', N('refer', 'Acalasia', 'Miotomía del EEI de elección',
                'Sin reflujo, con regurgitación no ácida y neumonías aspirativas: acalasia. El esfínter no relaja. El tratamiento de elección es la miotomía del esfínter esofágico inferior.')])])])])]),
  },

  'gastro-04': {
    title: 'Urgencias del tubo digestivo alto',
    root: N('start', 'Urgencia digestiva alta', 'Perforación o ingesta de cáustico',
      'Tres urgencias del tubo digestivo alto que el examen mezcla a propósito. La clave es el contexto clínico.',
      ['', N('q', '¿Cuál es el contexto?', 'El antecedente define el examen',
        '¿Qué antecedente tiene el paciente?',
        ['Úlcera + puñalada', N('do', 'Rx de tórax de pie', 'Neumoperitoneo subdiafragmático',
          'Síndrome ulceroso con dolor brusco en puñalada y abdomen en tabla: úlcera perforada. Pedimos radiografía de tórax de pie buscando neumoperitoneo.',
          ['', N('alert', 'Cirugía de urgencia', 'Endoscopía contraindicada',
            'El tratamiento es cirugía de urgencia. Suero, IBP y antibióticos son complementos, y la endoscopía está contraindicada.')])],
        ['Vómitos + enfisema', N('do', 'Rx de tórax → TAC', 'Neumomediastino (Boerhaave)',
          'Vómitos intensos seguidos de dolor torácico y enfisema subcutáneo: perforación esofágica, síndrome de Boerhaave. Radiografía de tórax y, si es negativa, TAC.',
          ['', N('alert', 'Cirugía de urgencia', 'Riesgo de mediastinitis',
            'Se opera de urgencia por el riesgo de mediastinitis. No lo confundas con Mallory-Weiss, donde los vómitos terminan en hematemesis.')])],
        ['Cáustico', N('do', 'EDA precoz (12–24 h)', 'Nunca carbón, lavado ni vómito',
          'Ingesta de cáustico: endoscopía precoz en las primeras doce a veinticuatro horas para graduar el daño. Carbón activado, lavado gástrico y provocar el vómito están contraindicados.',
          ['', N('q', '¿Necrosis o perforación?', 'Según el hallazgo endoscópico',
            '¿La endoscopía muestra necrosis extensa o perforación?',
            ['SÍ', N('alert', 'Régimen cero + cirugía', 'Nutrición parenteral',
              'Si hay necrosis o perforación: régimen cero, nutrición parenteral y cirugía de urgencia.')],
            ['NO', N('ok', 'Observar o régimen cero', 'Según el grado de daño',
              'Mucosa normal: observar y realimentar. Úlceras: régimen cero, nutrición parenteral y control endoscópico.')])])])]),
  },

  'gastro-05': {
    title: 'Cáncer digestivo alto: del síntoma al examen',
    root: N('start', 'Síntoma digestivo alto', 'Baja de peso · anemia · anorexia',
      'Paciente con baja de peso, anemia o anorexia. El síntoma que predomina nos dice qué cáncer buscar y con qué examen.',
      ['', N('q', '¿Qué predomina?', 'El síntoma guía el examen',
        '¿Qué predomina en el cuadro?',
        ['Disfagia lógica', N('alert', 'EDA + biopsia', 'Cáncer de esófago',
          'Disfagia lógica progresiva con baja de peso: cáncer de esófago hasta demostrar lo contrario. Endoscopía con biopsia.',
          ['', N('refer', 'TAC + endosonografía', 'Mide la invasión de la pared',
            'Se etapifica con TAC y endosonografía, porque el principal factor pronóstico es la invasión transmural. El tratamiento curativo es la cirugía, con rol importante de la radioterapia.')])],
        ['Epigastralgia ≥ 40', N('alert', 'EDA + biopsias', 'Cáncer gástrico (GES)',
          'Epigastralgia en mayor de cuarenta, o vómitos de retención en aumento: cáncer gástrico. Endoscopía con biopsias, garantía GES.',
          ['', N('q', '¿Invade la muscular propia?', 'Incipiente vs avanzado',
            '¿El tumor invade la muscular propia?',
            ['NO', N('ok', 'Incipiente: resección', 'Endoscópica o gastrectomía',
              'Si está limitado a mucosa y submucosa es incipiente, con buen pronóstico: resección endoscópica o gastrectomía.')],
            ['SÍ', N('refer', 'Gastrectomía + D2 + QT', 'Cáncer avanzado',
              'Si compromete la muscular propia es avanzado: gastrectomía con linfadenectomía D2 y quimioterapia perioperatoria.')])])],
        ['Ictericia', N('do', 'TAC de abdomen con contraste', 'Sospecha de cáncer de páncreas',
          'Si a la baja de peso y la epigastralgia se suma ictericia, la sospecha cambia a cáncer de páncreas. Ahí el examen es TAC de abdomen con contraste, no endoscopía.')])]),
  },

  'gastro-06': {
    title: 'Hiato, diafragma y mediastino: ¿observar u operar?',
    root: N('start', 'Hallazgo torácico o hiatal', 'Imagen o endoscopía',
      'Aquí la pregunta del examen es casi siempre la misma: ¿esto se observa o se opera?',
      ['', N('q', '¿Qué tipo de lesión?', 'Hernia hiatal, diafragmática o masa',
        '¿Frente a qué lesión estamos?',
        ['Hernia hiatal', N('q', '¿Tipo I, por deslizamiento?', 'Más del 95 % de los casos',
          '¿Es tipo uno, por deslizamiento, donde sube la unión gastroesofágica?',
          ['SÍ', N('ok', 'Observar', 'Tratar el reflujo solo si hay síntomas',
            'La hernia por deslizamiento es casi una variante normal. Se observa, y solo se trata el reflujo si existe.')],
          ['NO', N('refer', 'Cirugía electiva', 'Paraesofágica: riesgo de vólvulo',
            'La hernia paraesofágica es una hernia real, con riesgo de vólvulo y estrangulación: cirugía electiva, y urgente si se complica.')])],
        ['Diafragmática traumática', N('alert', 'Siempre se opera', 'Aguda: urgencia · Crónica: electiva',
          'La hernia diafragmática traumática nunca se observa. Si es aguda o complicada, cirugía de urgencia; si es un hallazgo crónico, cirugía electiva.')],
        ['Masa mediastínica', N('do', 'TAC de tórax con contraste', 'Anterior: las 4 T',
          'Toda masa mediastínica se estudia con TAC de tórax con contraste. En el mediastino anterior piensa en las cuatro T: timoma, linfoma, teratoma y tiroides. Timoma con miastenia gravis: timectomía.')])]),
  },

  'gastro-07': {
    title: 'Síndrome de intestino irritable: diagnóstico positivo',
    root: N('start', 'Dolor abdominal crónico recurrente', 'Con cambios en las deposiciones',
      'Paciente con dolor abdominal recurrente y cambios en las deposiciones. Lo primero no es pedir exámenes, sino buscar signos de alarma.',
      ['', N('q', '¿Signos de alarma?', 'ABCDEFH',
        'Recuerda la regla A B C D E F H: anemia, baja de peso, cambio reciente del hábito, disfagia, edad de inicio sobre cincuenta años, familiar con cáncer digestivo y hemorragia o síntomas nocturnos.',
        ['SÍ', N('alert', 'EDA o colonoscopía', 'Se abandona la hipótesis funcional',
          'Con cualquier signo de alarma se abandona la hipótesis funcional y se estudia con endoscopía o colonoscopía según el síntoma.')],
        ['NO', N('ok', 'SII por criterios de Roma IV', 'Educación + estrés + dieta baja en FODMAP',
          'Sin alarma y con criterios de Roma cuatro, el diagnóstico es clínico y positivo, no de descarte. Base del tratamiento: educar, manejar el estrés y dieta baja en FODMAP.',
          ['', N('q', '¿Síntoma predominante?', 'Fármaco dirigido al síntoma',
            'Los fármacos se eligen según el síntoma que predomina.',
            ['Dolor', N('ok', 'Antiespasmódicos', 'Trimebutino · pinaverio',
              'Si predomina el dolor: antiespasmódicos como trimebutino o bromuro de pinaverio.')],
            ['Diarrea', N('ok', 'Amitriptilina dosis baja', 'Antidepresivo tricíclico',
              'Si predomina la diarrea: amitriptilina en dosis baja.')],
            ['Constipación', N('ok', 'Polietilenglicol', 'Laxante osmótico',
              'Si predomina la constipación: laxante osmótico, polietilenglicol.')])])])]),
  },

  'gastro-08': {
    title: 'Diarrea del adulto: el tiempo define el estudio',
    root: N('start', 'Diarrea', 'Más de 3 deposiciones al día',
      'Diarrea es más de tres deposiciones al día de menor consistencia. La primera pregunta es cuánto tiempo lleva.',
      ['', N('q', '¿Cuánto tiempo lleva?', 'Aguda · prolongada · crónica',
        '¿Menos de dos semanas, entre dos y cuatro, o cuatro semanas o más?',
        ['< 2 semanas', N('do', 'Hidratar: Plan A, B o C', 'Sin antidiarreicos',
          'La diarrea aguda es casi siempre viral. El manejo es la hidratación según el plan A, B o C. La loperamida está contraindicada.',
          ['', N('q', '¿Disentería, viajero o sepsis?', 'O fiebre persistente > 2–3 días',
            '¿Hay sangre en las deposiciones, es diarrea del viajero, fiebre persistente o sepsis?',
            ['SÍ', N('alert', 'Ciprofloxacino', 'Ceftriaxona si es grave',
              'Solo entonces se indica antibiótico: ciprofloxacino oral, o ceftriaxona endovenosa si es grave.')],
            ['NO', N('ok', 'Manejo sintomático', 'Antieméticos si vomita',
              'Si no, manejo sintomático: se pueden usar antieméticos y antiespasmódicos.')])])],
        ['2–4 semanas', N('do', 'Coprocultivo + parasitológico', 'Post-antibiótico → C. difficile',
          'En la diarrea prolongada se busca el agente: coprocultivo y parasitológico seriado. Si usó antibióticos el último mes, sospecha Clostridioides difficile y pide PCR de toxina.')],
        ['≥ 4 semanas', N('alert', 'Colonoscopía si hay alarma', 'SII · malabsorción · EII · cáncer',
          'La diarrea crónica se orienta según la clínica: funcional, malabsorción, enfermedad inflamatoria o cáncer. Con signos de alarma, colonoscopía.')])]),
  },

  'gastro-09': {
    title: 'Malabsorción: dónde está el problema',
    root: N('start', 'Diarrea crónica + baja de peso', 'Con ingesta conservada',
      'Diarrea crónica con baja de peso a pesar de comer bien. Hay que confirmar la malabsorción y luego localizarla.',
      ['', N('q', '¿Esteatorrea?', 'Deposiciones brillantes que flotan',
        '¿Las deposiciones son brillantes, flotan y huelen mal?',
        ['NO', N('ok', 'Intolerancia a la lactosa', 'Test de hidrógeno espirado',
          'Diarrea osmótica tras los lácteos, sin esteatorrea: intolerancia a la lactosa. Se confirma con test de hidrógeno espirado y se reduce la lactosa.')],
        ['SÍ', N('do', 'Test de Sudán + D-xilosa', 'Sudán confirma · D-xilosa localiza',
          'El test de Sudán confirma la esteatorrea. El test de D-xilosa nos dice dónde está el problema.',
          ['', N('q', '¿D-xilosa alterada?', 'Pared vs páncreas',
            '¿La D-xilosa está alterada?',
            ['SÍ', N('do', 'Anti-transglutaminasa IgA', 'Con IgA total, consumiendo gluten',
              'Alterada significa problema de la pared: pensamos en celíaca. Pedimos anti-transglutaminasa IgA junto con IgA total, con el paciente comiendo gluten.',
              ['', N('ok', 'Biopsia duodenal → sin gluten', 'Dieta estricta de por vida',
                'Se confirma con biopsia duodenal, y el único tratamiento es la dieta sin gluten estricta y de por vida.')])],
            ['NO', N('refer', 'Origen pancreático', 'Pancreatitis crónica · fibrosis quística',
              'Normal significa que la pared absorbe bien: el problema es enzimático, pancreático, como la pancreatitis crónica o la fibrosis quística.')])])])]),
  },

  'gastro-10': {
    title: 'Enfermedad inflamatoria intestinal: CU vs Crohn',
    root: N('start', 'Joven con diarrea disentérica', 'Crónica, con fiebre y baja de peso',
      'Adulto joven con diarrea crónica con sangre, fiebre y baja de peso. Pensamos en enfermedad inflamatoria intestinal.',
      ['', N('do', 'Colonoscopía + ileoscopía', 'Con biopsias escalonadas',
        'La conducta inicial es siempre colonoscopía total con ileoscopía y biopsias. La calprotectina fecal apoya el origen inflamatorio.',
        ['', N('q', '¿Alguna característica de Crohn?', 'Íleon · parches · recto respetado · fístula · perianal',
          'La regla de oro: ¿tiene al menos una característica de Crohn? Compromiso del íleon, lesiones en parches, recto respetado, afectación transmural, fístula o enfermedad perianal.',
          ['SÍ', N('refer', 'Enfermedad de Crohn', 'Cirugía segmentaria: nunca cura',
            'Basta una para llamarla Crohn. Puede afectar de la boca al ano, así que la cirugía solo reseca el segmento complicado y nunca cura.')],
          ['NO', N('refer', 'Colitis ulcerosa', 'Colectomía = curativa',
            'Si es solo colónica, continua y desde el recto, es colitis ulcerosa. Como se limita al colon, la colectomía es curativa. Vigila megacolon tóxico y cáncer colorrectal tras ocho a diez años.')])])]),
  },

  'gastro-11': {
    title: 'Cáncer colorrectal: diagnóstico vs tamizaje',
    root: N('start', 'Evaluación de colon', 'Síntomas o tamizaje',
      'Para el cáncer de colon hay dos caminos distintos: el paciente con síntomas y el asintomático que se tamiza.',
      ['', N('q', '¿Síntomas o signos de alarma?', 'Anemia · cambio del hábito · rectorragia',
        '¿Tiene síntomas o signos de alarma, como anemia ferropénica, cambio del hábito o rectorragia?',
        ['SÍ', N('alert', 'Colonoscopía total + biopsia', 'No test de sangre oculta',
          'Al paciente sintomático se le hace colonoscopía directamente. El test de sangre oculta es solo para asintomáticos.',
          ['', N('refer', 'TAC de tórax, abdomen y pelvis', 'Recto: + RM de pelvis',
            'Se etapifica con TAC de tórax, abdomen y pelvis; en el recto se agrega resonancia de pelvis. El CEA solo sirve para el seguimiento posoperatorio.')])],
        ['NO', N('ok', 'Tamizaje desde los 50 años', 'Test inmunoquímico o colonoscopía c/10 años',
          'En el asintomático de riesgo promedio desde los cincuenta años: test de sangre oculta inmunoquímico y, si es positivo, colonoscopía.',
          ['', N('q', '¿Qué pólipo se encontró?', 'Define el riesgo',
            'Si la colonoscopía encuentra un pólipo, el tipo define la conducta.',
            ['Hiperplásico', N('ok', 'Observar', 'No es premaligno',
              'El pólipo hiperplásico no es premaligno: se observa.')],
            ['Adenomatoso', N('refer', 'Polipectomía + control', 'Colonoscopía en 1–3 años',
              'El adenomatoso es el precursor del cáncer: polipectomía y colonoscopía de control en uno a tres años.')])])])]),
  },

  'gastro-12': {
    title: 'Patología perianal: clínica y conducta',
    root: N('start', 'Dolor o sangrado anal', 'Inspección siempre',
      'Dolor o sangrado anal. Cada entidad tiene una clínica tan característica que el diagnóstico se hace mirando.',
      ['', N('q', '¿Qué predomina?', 'La clínica define la conducta',
        '¿Qué es lo que predomina?',
        ['Dolor al defecar', N('ok', 'Fisura: baños de asiento', 'Crónica: esfinterotomía interna',
          'Dolor intenso con la defecación y sangre al papel: fisura anal. Baños de asiento y tratar la constipación. Si es crónica, esfinterotomía del esfínter interno, nunca el externo.')],
        ['Sangrado sin dolor', N('ok', 'Hemorroide interno: ligadura', 'Descartar otras causas',
          'Hematoquecia sin dolor: hemorroide interno. Ligadura elástica, pero siempre descartando cáncer o diverticulosis.')],
        ['Nódulo violáceo', N('ok', 'Trombosado: baños de asiento', 'Trombectomía si < 72 h',
          'Dolor agudo con nódulo violáceo: hemorroide externo trombosado. Baños de asiento, y trombectomía solo si consulta antes de setenta y dos horas.')],
        ['Masa fluctuante', N('alert', 'Absceso: drenaje en pabellón', 'Antibióticos solos no bastan',
          'Dolor que aumenta progresivamente con masa fluctuante: absceso perianal. Drenaje quirúrgico en pabellón.',
          ['', N('refer', 'Fístula → cirugía', 'Orificio que supura crónicamente',
            'Si después queda un orificio que supura de forma crónica, es una fístula, y su manejo es quirúrgico. Fisura y fístula se escriben parecido y se manejan al revés.')])])]),
  },

  'gastro-13': {
    title: 'Ictericia: dos preguntas de laboratorio',
    root: N('start', 'Ictericia', 'Visible sobre 2,5–3 mg/dL',
      'Paciente ictérico. Con dos preguntas de laboratorio ordenamos todas las causas.',
      ['', N('q', '¿Bilirrubina directa o indirecta?', 'Paso 1',
        'Paso uno: ¿predomina la bilirrubina indirecta o la directa?',
        ['Indirecta', N('ok', 'Gilbert o hemólisis', 'Anemia + LDH alta = hemólisis',
          'Indirecta con el resto normal en un joven: síndrome de Gilbert, se observa. Si hay anemia y LDH alta, es hemólisis y se trata la causa.')],
        ['Directa', N('q', '¿Transaminasas o FA/GGT?', 'Paso 2',
          'Paso dos, en la directa: ¿suben las transaminasas o las fosfatasas alcalinas y la GGT?',
          ['Transaminasas', N('refer', 'Hepatitis', 'Lesión del hepatocito',
            'Transaminasas altas indican hepatitis, lesión del hepatocito.')],
          ['FA / GGT', N('do', 'Ecografía abdominal', 'Siempre el primer examen',
            'Fosfatasas y GGT altas indican colestasia. El primer examen es siempre la ecografía abdominal.',
            ['', N('q', '¿Dolor? ¿Fiebre?', 'Orienta la causa',
              '¿Hay dolor? ¿Hay fiebre?',
              ['Dolor', N('refer', 'Coledocolitiasis', 'Colangio-RM → CPRE',
                'Colestasia con dolor: coledocolitiasis. Colangiorresonancia y luego CPRE.')],
              ['Dolor + fiebre', N('alert', 'Colangitis: CPRE urgente', 'Tríada de Charcot',
                'Dolor, ictericia y fiebre: tríada de Charcot, colangitis. CPRE urgente más antibióticos.')],
              ['Sin dolor', N('alert', 'Sospecha de cáncer', 'Colangio-RM o TAC si páncreas',
                'Ictericia silente en el adulto mayor con baja de peso: cáncer, sobre todo de páncreas. Colangiorresonancia, o TAC si se sospecha masa pancreática.')])])])])]),
  },

  'gastro-14': {
    title: 'Hepatitis: aguda vs crónica',
    root: N('start', 'Transaminasas elevadas', 'Inflamación del hepatocito',
      'Transaminasas elevadas. El eje que ordena toda la clase es si la hepatitis es aguda o crónica.',
      ['', N('q', '¿Menos de 6 meses?', 'Aguda vs crónica',
        '¿Lleva menos de seis meses de evolución?',
        ['Aguda', N('do', 'IgM anti-VHA · AgHBs · IgM anti-HBc', 'Buscar la causa',
          'En la hepatitis aguda pedimos IgM anti hepatitis A, antígeno de superficie e IgM anti core de hepatitis B, y buscamos alcohol y fármacos.',
          ['', N('q', '¿Encefalopatía o INR alterado?', 'El marcador es el tiempo de protrombina',
            'El riesgo es la hepatitis fulminante. ¿Hay encefalopatía, o el tiempo de protrombina está alterado?',
            ['SÍ', N('alert', 'Fulminante: derivar a trasplante', 'No se mide con la bilirrubina',
              'Si hay encefalopatía o protrombina alterada: hepatitis fulminante, derivación a centro de trasplante.')],
            ['NO', N('ok', 'Soporte + tratar la causa', 'Fármaco: suspender · Paracetamol: NAC',
              'Si no, soporte y tratar la causa: suspender el fármaco sospechoso, y en el paracetamol dar N-acetilcisteína.')])])],
        ['Crónica', N('refer', 'Estudio de causa + GES', 'VHB · VHC · NASH · autoinmune',
          'La hepatitis crónica mata por cirrosis. Buscamos virus B y C, esteatohepatitis y autoinmunes. Las hepatitis B y C crónicas tienen garantía GES: derivar para carga viral, elastografía y antivirales.')])]),
  },

  'gastro-15': {
    title: 'Cirrótico descompensado: conducta por complicación',
    root: N('start', 'Cirrótico descompensado', 'Hipertensión portal',
      'Llega un paciente cirrótico descompensado. La conducta depende de la complicación.',
      ['', N('q', '¿Qué complicación?', 'Cada una tiene su tratamiento',
        '¿Qué complicación presenta?',
        ['Hemorragia variceal', N('alert', 'Terlipresina + ATB + ligadura', 'Volumen · tiamina si alcohol',
          'Hemorragia variceal activa: volumen, terlipresina, antibióticos como ceftriaxona y ligadura endoscópica en las primeras doce horas. Tiamina si es alcohólico. No omitas los antibióticos.')],
        ['Ascitis', N('do', 'Paracentesis diagnóstica', 'Siempre primero',
          'Todo cirrótico con ascitis que consulta: paracentesis diagnóstica antes que nada, para descartar peritonitis bacteriana espontánea.',
          ['', N('q', '¿PMN ≥ 250/mm³?', 'Peritonitis bacteriana espontánea',
            '¿El líquido tiene doscientos cincuenta polimorfonucleares o más?',
            ['SÍ', N('alert', 'Cefotaxima + albúmina', 'Albúmina días 1 y 3',
              'Eso es peritonitis bacteriana espontánea: cefotaxima endovenosa más albúmina los días uno y tres, para prevenir el síndrome hepatorrenal.')],
            ['NO', N('ok', 'Sodio + espironolactona', 'A tensión: evacuadora + albúmina',
              'Si no: restricción de sodio y espironolactona, con furosemida si hace falta. Ascitis a tensión: paracentesis evacuadora con albúmina.')])])],
        ['Asterixis', N('alert', 'Lactulosa + tratar precipitante', 'TIPS contraindicado',
          'Desorientación con asterixis: encefalopatía hepática. Buscar el precipitante, casi siempre una infección, y lactulosa hasta dos a tres deposiciones blandas.')])]),
  },

  'gastro-16': {
    title: 'Lesión hepática en la ecografía',
    root: N('start', 'Lesión hepática', 'Hallazgo ecográfico',
      'Una lesión hepática en la ecografía. Su aspecto y el contexto del paciente orientan el diagnóstico.',
      ['', N('q', '¿Cómo se ve la lesión?', 'Aspecto ecográfico + contexto',
        '¿Es quística, sólida homogénea o heterogénea en un hígado cirrótico?',
        ['Quística', N('q', '¿Tabiques o membrana?', 'Contexto rural, perros',
          '¿Tiene tabiques, membrana o vesículas hijas?',
          ['NO', N('ok', 'Quiste simple: observar', 'Anecogénico, pared fina',
            'Anecogénico de pared fina, sin tabiques: quiste simple, se observa.')],
          ['SÍ', N('refer', 'Hidatídico: albendazol + cirugía', 'Evitar la punción libre',
            'Con tabiques o membrana en contexto rural: quiste hidatídico. Albendazol y cirugía; nunca punción libre por riesgo de anafilaxia.')])],
        ['Sólida homogénea', N('q', '¿Hiperecogénica?', 'Benignas',
          '¿Es hiperecogénica o hipoecogénica?',
          ['SÍ', N('ok', 'Hemangioma: observar', 'La benigna más frecuente',
            'Hiperecogénica homogénea: hemangioma, la lesión benigna más frecuente. Se observa.')],
          ['NO', N('refer', 'Adenoma: suspender estrógenos', 'Resecar si > 5 cm',
            'Hipoecogénica única en mujer que usa anticonceptivos: adenoma. Suspender estrógenos y resecar si mide más de cinco centímetros.')])],
        ['Heterogénea + cirrosis', N('alert', 'Hepatocarcinoma', 'TAC/RM trifásico · AFP alta',
          'Heterogénea e irregular en un cirrótico con alfafetoproteína alta: hepatocarcinoma. Se confirma con TAC o resonancia trifásica.')])]),
  },

  'gastro-17': {
    title: 'Patología biliar: qué acompaña al dolor',
    root: N('start', 'Dolor en hipocondrio derecho', 'Paciente con colelitiasis',
      'Paciente con cálculos en la vesícula y dolor en el hipocondrio derecho. Lo que acompaña al dolor define la entidad.',
      ['', N('q', '¿Qué acompaña al dolor?', 'Fiebre · ictericia · ambas',
        '¿El dolor viene solo, con fiebre, con ictericia o con ambas?',
        ['Solo dolor', N('ok', 'Cólico biliar', 'Analgesia + colecistectomía electiva',
          'Solo dolor que cede en menos de seis horas: cólico biliar. Analgesia, y colecistectomía laparoscópica electiva porque toda colelitiasis se opera en Chile.')],
        ['Fiebre', N('alert', 'Colecistitis aguda', 'ATB + colecistectomía < 72 h',
          'Dolor persistente con fiebre y Murphy positivo: colecistitis aguda. Antibióticos y colecistectomía precoz, en menos de setenta y dos horas.')],
        ['Ictericia', N('do', 'Coledocolitiasis', 'Eco → colangio-RM → CPRE',
          'Dolor con ictericia sin fiebre: coledocolitiasis. Ecografía, colangiorresonancia y CPRE para extraer el cálculo; después, colecistectomía electiva.')],
        ['Ictericia + fiebre', N('alert', 'Colangitis aguda', 'Volumen + ATB + CPRE urgente',
          'Dolor, ictericia y fiebre: tríada de Charcot. Colangitis aguda: volumen, antibióticos y drenaje biliar urgente por CPRE.')])]),
  },

  'gastro-18': {
    title: 'Pancreatitis aguda: diagnóstico y primeras 48 horas',
    root: N('start', 'Dolor epigástrico en faja', 'Irradiado al dorso',
      'Dolor epigástrico intenso, transfixiante, irradiado en faja al dorso.',
      ['', N('q', '¿Cumple 2 de 3 criterios?', 'Dolor típico · lipasa > 3× · imagen',
        '¿Cumple dos de tres criterios? Dolor típico, lipasa o amilasa sobre tres veces lo normal, o imagen compatible. Con los dos primeros no se necesita TAC.',
        ['NO', N('do', 'Buscar diferencial', 'Úlcera perforada · IAM inferior · isquemia',
          'Si no los cumple, piensa en los imitadores: úlcera perforada, infarto de cara inferior o isquemia mesentérica.')],
        ['SÍ', N('alert', 'Volumen agresivo: Ringer lactato', 'Analgesia · sin ATB profilácticos',
          'Pancreatitis aguda. Lo que más reduce la mortalidad es el volumen precoz con Ringer lactato, ajustado a diuresis. Analgesia, realimentación precoz y nada de antibióticos profilácticos.',
          ['', N('do', 'Ecografía en 24–48 h', 'Buscar litiasis · lípidos · calcio',
            'A todos se les pide ecografía en las primeras veinticuatro a cuarenta y ocho horas para buscar cálculos, más perfil lipídico y calcemia.',
            ['', N('q', '¿Colangitis asociada?', 'U obstrucción biliar persistente',
              '¿Hay colangitis asociada u obstrucción biliar persistente?',
              ['SÍ', N('alert', 'CPRE urgente < 24 h', 'Solo con colangitis',
                'Solo en ese caso se hace CPRE urgente, en menos de veinticuatro horas.')],
              ['NO', N('ok', 'Colecistectomía en el ingreso', 'Pancreatitis biliar leve',
                'En la pancreatitis biliar leve, colecistectomía en el mismo ingreso para evitar la recurrencia.')])])])])]),
  },

  'gastro-19': {
    title: 'Abdomen agudo: apendicitis y diverticulitis',
    root: N('start', 'Dolor abdominal agudo', 'Diagnóstico clínico',
      'Abdomen agudo. Es un diagnóstico clínico, y no todos son quirúrgicos.',
      ['', N('do', 'Mujer fértil: test de embarazo', 'Y evaluación ginecológica',
        'Primera regla: en toda mujer en edad fértil con dolor abdominal bajo, test de embarazo y evaluación ginecológica antes que nada.',
        ['', N('q', '¿Dónde está el dolor?', 'Fosa ilíaca derecha o izquierda',
          '¿El dolor está en la fosa ilíaca derecha o en la izquierda?',
          ['Derecha', N('q', '¿Masa de varios días?', 'Plastrón apendicular',
            'Dolor que migró del ombligo a la fosa ilíaca derecha. ¿Se palpa una masa con varios días de evolución?',
            ['NO', N('alert', 'Apendicectomía', 'Laparoscópica',
              'Sin masa: apendicitis aguda, apendicectomía laparoscópica.')],
            ['SÍ', N('refer', 'Plastrón: antibióticos', 'Apendicectomía diferida 6–8 sem',
              'Con masa de varios días: plastrón apendicular. Primero antibióticos y apendicectomía diferida a las seis a ocho semanas.')])],
          ['Izquierda', N('do', 'TAC de abdomen y pelvis', 'Colonoscopía contraindicada en agudo',
            'Dolor en fosa ilíaca izquierda con fiebre en mayor de cincuenta: diverticulitis. TAC de abdomen y pelvis; la colonoscopía se hace después, nunca en el episodio agudo.',
            ['', N('q', '¿Hinchey?', 'Absceso vs peritonitis',
              '¿La TAC muestra absceso o peritonitis?',
              ['I–II', N('ok', 'Antibióticos ± drenaje', 'Drenaje percutáneo si absceso',
                'Hinchey uno o dos, con absceso: antibióticos y drenaje percutáneo si es necesario.')],
              ['III–IV', N('alert', 'Operación de Hartmann', 'Cirugía de urgencia',
                'Hinchey tres o cuatro, con peritonitis purulenta o fecal: cirugía de urgencia, operación de Hartmann.')])])])])]),
  },

  'gastro-20': {
    title: 'Abdomen agudo vascular',
    root: N('start', 'Dolor abdominal desproporcionado', 'Al examen físico',
      'Dolor abdominal intensísimo con un examen físico que no lo explica. Piensa en isquemia.',
      ['', N('q', '¿Cuál es el contexto?', 'Define la entidad',
        '¿Cuál es el contexto del paciente?',
        ['Fibrilación auricular', N('alert', 'Embolia: heparina + angio-TAC', 'Abdomen blando al inicio',
          'Fibrilación auricular con dolor súbito y abdomen blando: embolia de la mesentérica superior. Heparina de inmediato ante la sospecha y angio-TAC.',
          ['', N('refer', 'Revascularización', '± resección del intestino necrótico',
            'Luego revascularización con embolectomía o trombólisis, y resección del intestino necrótico.')])],
        ['Hipercoagulable', N('do', 'TAC con contraste', 'Dolor de días',
          'Paciente hipercoagulable o cirrótico con dolor de días: trombosis venosa mesentérica. TAC con contraste.',
          ['', N('ok', 'Anticoagulación', 'Cirugía si necrosis',
            'El tratamiento es anticoagular; cirugía solo si hay necrosis o perforación.')])],
        ['Adulto mayor + hematoquecia', N('do', 'TAC de abdomen', 'Engrosamiento segmentario',
          'Adulto mayor ateroesclerótico con dolor izquierdo y hematoquecia: colitis isquémica. TAC de abdomen.',
          ['', N('ok', 'Manejo médico', 'Reposo intestinal + hidratación + ATB',
            'La mayoría se resuelve con manejo médico: reposo intestinal, hidratación y antibióticos.')])])]),
  },

  'gastro-21': {
    title: 'Hemorragia digestiva: estabilizar y localizar',
    root: N('start', 'Hemorragia digestiva', 'Hematemesis · melena · hematoquecia',
      'Paciente con hemorragia digestiva. Antes de pensar en la causa, lo estabilizamos.',
      ['', N('alert', '2 vías gruesas + cristaloides', 'La gravedad es la hemodinamia',
        'Dos vías venosas gruesas y cristaloides. La gravedad se mide por la hemodinamia, taquicardia, ortostatismo, hipotensión, no por el hematocrito. La transfusión no es el primer paso.',
        ['', N('q', '¿Alta o baja?', 'Proximal o distal al ángulo de Treitz',
          '¿Es alta, con hematemesis o melena, o baja, con hematoquecia?',
          ['Alta', N('q', '¿Cirrótico?', 'Várices vs úlcera',
            '¿Es un paciente cirrótico?',
            ['SÍ', N('alert', 'Várices: terlipresina + ATB', 'Ligadura · tiamina',
              'En el cirrótico pensamos en várices: terlipresina, antibióticos, tiamina y ligadura endoscópica.')],
            ['NO', N('ok', 'Úlcera: IBP EV + EDA', 'Erradicar H. pylori',
              'Si no, lo más probable es una úlcera: IBP endovenoso en dosis alta, endoscopía terapéutica y erradicación de Helicobacter.')])],
          ['Baja', N('q', '¿Masiva e inestable?', 'Define la urgencia',
            '¿Es masiva, con el paciente inestable?',
            ['NO', N('ok', 'Colonoscopía en 24 h', 'Con preparación',
              'Si está estable: preparación de colon y colonoscopía en veinticuatro horas.')],
            ['SÍ', N('alert', 'Colonoscopía urgente → EDA', '→ angio-TAC si no se localiza',
              'Si es masiva: colonoscopía urgente; si no localiza, endoscopía alta, porque uno de cada diez es en realidad alto; luego angio-TAC.')])])])]),
  },

  'gastro-22': {
    title: 'Cuerpo extraño digestivo: ¿retirar u observar?',
    root: N('start', 'Ingesta de cuerpo extraño', 'Sospecha clínica',
      'Sospecha de ingesta de un cuerpo extraño.',
      ['', N('do', 'Rx de cuello, tórax y abdomen', 'Localizar el objeto',
        'Primero lo localizamos con radiografía de cuello, tórax y abdomen.',
        ['', N('q', '¿Dónde está?', 'Esófago vs más allá',
          '¿Está en el esófago o ya pasó más allá?',
          ['Esófago', N('q', '¿Pila, afilado u obstrucción?', 'O más de 24 h impactado',
            '¿Es una pila, un objeto afilado, hay obstrucción completa o lleva más de veinticuatro horas?',
            ['SÍ', N('alert', 'EDA urgente', 'Pila de botón = emergencia',
              'Entonces endoscopía urgente. La pila de botón en el esófago es una emergencia: quema la mucosa en horas.')],
            ['NO', N('refer', 'EDA para retirarlo', 'En el esófago siempre se retira',
              'Aun sin urgencia, en el esófago siempre se retira por endoscopía.')])],
          ['Más allá', N('q', '¿Pila, imanes, afilado o > 5 cm?', 'O bolitas absorbentes',
            '¿Es una pila, dos o más imanes, un objeto afilado, mayor de cinco centímetros o bolitas absorbentes?',
            ['SÍ', N('alert', 'Retirar siempre', 'En cualquier ubicación',
              'Esos se retiran siempre, estén donde estén.')],
            ['NO', N('ok', 'Observar + Rx cada 1–2 semanas', 'Romo, pequeño, asintomático',
              'Objeto romo y pequeño en paciente asintomático: se observa con radiografía cada una a dos semanas.')])])])]),
  },

  'gastro-23': {
    title: 'Diarrea en el niño: hidratar según el grado',
    root: N('start', 'Niño con diarrea', 'Mayoritariamente viral',
      'Niño con diarrea. Primero definimos si es aguda o crónica.',
      ['', N('q', '¿Aguda o crónica?', 'Menos o más de 4 semanas',
        '¿Es aguda o crónica?',
        ['Aguda', N('q', '¿Grado de deshidratación?', 'Sin antidiarreicos',
          'En la aguda, el pilar es hidratar según el grado de deshidratación. Los antidiarreicos están contraindicados en pediatría.',
          ['Sin', N('ok', 'Plan A: SRO en casa', '100–200 mL tras cada deposición',
            'Sin deshidratación: plan A, sales de rehidratación oral cien a doscientos mililitros tras cada deposición, en casa.')],
          ['5–10 %', N('ok', 'Plan B: SRO 50–100 mL/kg', 'En 4–6 horas',
            'Deshidratación moderada: plan B, sales de rehidratación cincuenta a cien mililitros por kilo en cuatro a seis horas.')],
          ['> 10 % / shock', N('alert', 'Plan C: SF 20 mL/kg en bolo', 'Intraósea si no hay acceso',
            'Deshidratación grave o shock: plan C, suero fisiológico veinte mililitros por kilo en bolo, por vía intraósea si no hay acceso venoso.')])],
        ['Crónica', N('ok', 'Niño sano: suspender jugos', 'Descartar Giardia antes de celíaca',
          'La diarrea crónica más frecuente es la inespecífica por jugos: el niño crece bien, se suspenden los jugos. Siempre descarta Giardia antes de diagnosticar celíaca.')])]),
  },

  'gastro-24': {
    title: 'Lactante que vomita: fisiológico, patológico o píloro',
    root: N('start', 'Lactante que regurgita', 'O vomita',
      'Lactante que regurgita o vomita. Hay que separar lo fisiológico de lo patológico y no perder una estenosis del píloro.',
      ['', N('q', '¿Vómitos explosivos 2.ª–6.ª semana?', 'Lactante ávido por comer',
        '¿Son vómitos explosivos y proyectivos que empezaron entre la segunda y la sexta semana, en un lactante ávido por comer?',
        ['SÍ', N('alert', 'Estenosis del píloro: ecografía', 'Alcalosis hipoclorémica',
          'Eso es estenosis hipertrófica del píloro, con alcalosis hipoclorémica. Ecografía, corregir hidratación y electrolitos, y luego pilorotomía de Ramstedt.')],
        ['NO', N('q', '¿Crece bien y está feliz?', 'Examen normal',
          '¿Es un lactante feliz que crece bien y tiene el examen normal?',
          ['SÍ', N('ok', 'RGE fisiológico', 'Educar y tranquilizar',
            'Reflujo fisiológico: educar, tranquilizar, medidas posturales y fraccionar la alimentación. Sin fármacos.')],
          ['NO', N('refer', 'RGE patológico: omeprazol', 'Mal incremento · respiratorio · sangre',
            'Si tiene mal incremento de peso, síntomas respiratorios o sangre: reflujo patológico. Se estudia y el omeprazol es la primera línea.')])])]),
  },

  'gastro-25': {
    title: 'Cirugía pediátrica digestiva: la clave de cada cuadro',
    root: N('start', 'Urgencia digestiva en el niño', 'La edad orienta',
      'Urgencia digestiva en un niño. La edad y un signo clave te dan el diagnóstico.',
      ['', N('q', '¿Edad y signo clave?', 'Un dato define cada cuadro',
        '¿Qué edad tiene y cuál es el signo clave?',
        ['Prematuro', N('do', 'Rx: neumatosis intestinal', 'Distensión + hematoquecia',
          'Prematuro con retención gástrica, distensión y hematoquecia. La radiografía muestra neumatosis intestinal.',
          ['', N('ok', 'Enterocolitis: régimen cero', 'NPT + ATB · cirugía si perfora',
            'Enterocolitis necrotizante: régimen cero, nutrición parenteral y antibióticos; cirugía solo si perfora.')])],
        ['Lactante 6–12 m', N('do', 'Eco: signo de la dona', 'Mermelada de grosella',
          'Lactante de seis a doce meses con crisis de llanto y deposiciones en mermelada de grosella: ecografía con signo de la dona.',
          ['', N('ok', 'Reducción neumática', 'Cirugía si falla',
            'Invaginación intestinal: reducción neumática guiada por imagen; cirugía solo si falla.')])],
        ['HDB indolora', N('do', 'Cintigrafía Tc-99m', 'Mucosa gástrica ectópica',
          'Niño pequeño con sangrado rectal abundante e indoloro: divertículo de Meckel. Cintigrafía con tecnecio 99.',
          ['', N('refer', 'Resección del divertículo', 'Regla de los 2',
            'Se reseca. Recuerda la regla de los dos: dos por ciento de la población, dos pies de la válvula, alrededor de los dos años.')])],
        ['Meconio > 48 h', N('do', 'Biopsia rectal', 'Ausencia de células ganglionares',
          'Recién nacido que no elimina meconio en cuarenta y ocho horas: enfermedad de Hirschsprung. Se confirma con biopsia rectal.',
          ['', N('refer', 'Resección agangliónica', 'Cirugía',
            'El tratamiento es resecar el segmento agangliónico.')])])]),
  },

  'gastro-26': {
    title: 'Trauma abdominal: conducta según el mecanismo',
    root: N('start', 'Trauma abdominal', 'ABC primero',
      'Paciente con trauma abdominal. La conducta la define el mecanismo.',
      ['', N('q', '¿Cuál fue el mecanismo?', 'Cerrado · arma blanca · arma de fuego',
        '¿Fue un trauma cerrado, por arma blanca o por arma de fuego?',
        ['Cerrado', N('do', 'Clínica + eco-FAST', 'Lavado peritoneal obsoleto',
          'En el trauma cerrado: clínica más eco FAST buscando líquido libre. El lavado peritoneal está obsoleto.',
          ['', N('q', '¿Inestable o líquido libre?', 'O signos peritoneales',
            '¿Está inestable, tiene signos peritoneales o líquido libre?',
            ['SÍ', N('alert', 'Laparotomía', 'Cirugía de urgencia',
              'Entonces laparotomía.')],
            ['NO', N('ok', 'Observación', '± TAC si alta energía',
              'Estable con FAST negativa: observación, con TAC si el mecanismo fue de alta energía.')])])],
        ['Arma blanca', N('q', '¿Penetra el peritoneo?', 'Exploración de la herida',
          'En la herida por arma blanca, la pregunta es si penetra el peritoneo.',
          ['SÍ', N('alert', 'Exploración quirúrgica', 'También si inestable o evisceración',
            'Si penetra, o hay inestabilidad, peritonitis o evisceración: exploración quirúrgica.')],
          ['NO', N('ok', 'Observación', 'Herida superficial',
            'Si no penetra, observación.')])],
        ['Arma de fuego', N('alert', 'Exploración quirúrgica siempre', 'Salvo herida tangencial demostrada',
          'El trauma abdominal por arma de fuego se explora quirúrgicamente siempre.')])]),
  },
};
